### ISSUE TITLE
Claiming namespace master 

### ISSUE THREAD

**Issue by gejqim-bipciw-5Tonri** [EclipseFdn/open-vsx.org#1001]
@eclipse 
  [Master ](https://open-vsx.org/) 

- [x] @eclipsewebmaster 

Briefly explain what makes you a legitimate owner of the namespace mentioned in
the issue title.

1. Please ensure that you have logged in to https://open-vsx.org at least once,

otherwise we cannot process your request.
-->

**Comment by mbarbero** [comment]
Looks like spam
