### ISSUE TITLE
remove mistakenly published extension

### ISSUE THREAD

**Issue by lonhutt** [EclipseFdn/open-vsx.org#1006]
I accidentally published from the wrong local directory to the open-vsx registry. Can I please ask that 

https://open-vsx.org/extension/LonHutt/sfdx-vscode-internal-dev-pack

be deleted? 

Thanks!

**Comment by lonhutt** [comment]
there are currently 0 downloads and no dependencies on this extension pack.

**Comment by kineticsquid** [comment]
@lonhutt Done!

**Comment by lonhutt** [comment]
thanks!
