### ISSUE TITLE
Claiming namespace obliviousharmony

### ISSUE THREAD

**Issue by ObliviousHarmony** [EclipseFdn/open-vsx.org#1009]
Greetings,

[An issue was opened in the repository for my VS Code PHPCS extension](https://github.com/ObliviousHarmony/vscode-php-codesniffer/issues/43) requesting that I publish it on [open-vsx.org](https://open-vsx.org). I would like to publish the extension in the same namespace that it is published there. I have used the online alias "obliviousharmony" for roughly fifteen years and own that name virtually everywhere that a name can be owned. I don't think it would be inappropriate for me to own that here as well.

Thanks!

**Comment by kineticsquid** [comment]
@ObliviousHarmony granted! I suppose that's better than `ObviousDiscord`.

**Comment by ObliviousHarmony** [comment]
Given that I adopted it when I was fifteen, I'm lucky I didn't choose an online alias to manifest teenage angst. Thanks, @kineticsquid!
