### ISSUE TITLE
Claiming namespace silopolis

### ISSUE THREAD

**Issue by silopolis** [EclipseFdn/open-vsx.org#1013]
Hello,

Starting dev of VSCodium extensions I plan to publish, I'd like to claim the 'silopolis' namespace as that id identifies me also on Github and everywhere on the Net for all my IT activities.

Thanks in advance

TY
Jérémie

**Comment by kineticsquid** [comment]
@silopolis Sorry, I forgot to let you know this was granted and close the issue. Thanks for your contribution!

**Comment by silopolis** [comment]
No problem
Thank you and have a nice we
