### ISSUE TITLE
Claiming namespace [21zz]

### ISSUE THREAD

**Issue by 21zz** [EclipseFdn/open-vsx.org#1015]
I've forked and modified a Discord Rich Presence extension specifically for VSCodium.
Here's the project: https://github.com/21zz/vscord-vscodium
and published here: https://open-vsx.org/extension/21zz/vscord

21zz identifies me on GitHub, so I thought it would be a fitting namespace.

Thanks.

**Comment by kineticsquid** [comment]
Thanks for your contribution @21zz!
