### ISSUE TITLE
Claiming namespace [houkanshan]

### ISSUE THREAD

**Issue by houkanshan** [EclipseFdn/open-vsx.org#1017]
Hi I'm the developer of https://github.com/houkanshan/vscode-markdown-footnote and I [published it](https://open-vsx.org/extension/houkanshan/vscode-markdown-footnote) under the namespace `houkanshan`.

My username is houkanshan as well, so I think it's easy to verify.

Thank you!

**Comment by kineticsquid** [comment]
Thanks @houkanshan, glad to have your contribution!
