### ISSUE TITLE
Claiming namespace hall

### ISSUE THREAD

**Issue by hall** [EclipseFdn/open-vsx.org#1019]
`hall` is my GitHub & GitLab username as well as my VS Marketplace publisher name :shrug:

**Comment by hall** [comment]
For what it's worth, I've published this extension: https://open-vsx.org/extension/hall/draw

**Comment by kineticsquid** [comment]
Thanks @hall, glad to have you!

**Comment by hall** [comment]
Thanks, @kineticsquid!

The linked extension still shows as unverified and I don't see the namespace in my account. Let me know if there's something more I need to do on my end.

![image](https://user-images.githubusercontent.com/32495955/171849045-219c4448-4ef5-45ee-9187-c5f4210ff6a1.png)

**Comment by hall** [comment]
_bump_

This namespace still shows as unverified. Not sure if I need to open a new issue.

**Comment by kineticsquid** [comment]
@hall My bad... I thought I'd assigned this. I think we're good now. Thanks for following up.
