### ISSUE TITLE
Claiming namespace EkangDev and StoneC0der

### ISSUE THREAD

**Issue by stoneC0der** [EclipseFdn/open-vsx.org#1020]
I would like to claim the namespace StoneC0der, It's the name of my github profile as well my vscode marketplace publisher name and basically my name as a developer.

**Comment by kineticsquid** [comment]
@stoneC0der I see both name spaces, `StoneC0der` and `EkangDev`. Which is/are you looking to claim?

**Comment by stoneC0der** [comment]
@kineticsquid I created the publisher under then name StoneC0der and then created a namespace using EkangDev.
If I can claim both that will be great else I will go for StoneC0der since I have already pulish a theme with it.

**Comment by kineticsquid** [comment]
@stoneC0der, done!
