### ISSUE TITLE
Claiming namespace ZixuanWang

### ISSUE THREAD

**Issue by TheNetAdmin** [EclipseFdn/open-vsx.org#1023]
I'm using `TheNetAdmin` as profile name, but publish extensions under `ZixuanWang` namespace. So I'd like to claim this namespace.

BTW I created this `ZixuanWang` namespace using `ovsx` following the instructions: 

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#2-create-the-namespace

In this case do I still need to claim this namespace?

**Comment by kineticsquid** [comment]
Thanks @TheNetAdmin , good to have your contribution!
