### ISSUE TITLE
Claiming namespace `iterative`

### ISSUE THREAD

**Issue by shcheklein** [EclipseFdn/open-vsx.org#1024]
I'm a publisher of [this](https://marketplace.visualstudio.com/items?itemName=Iterative.dvc) extension and co-founder / CTO at [Iterative](Iterative.ai).

**Comment by shcheklein** [comment]
Here is the DVC extension that got published - https://open-vsx.org/extension/iterative/dvc

**Comment by kineticsquid** [comment]
Granted @shcheklein , glad to have your contribution!

**Comment by shcheklein** [comment]
@kineticsquid thanks!
