### ISSUE TITLE
Claiming namespace wesleyegberto

### ISSUE THREAD

**Issue by wesleyegberto** [EclipseFdn/open-vsx.org#1026]
I want to claim the namespace `wesleyegberto` to publish my extension, I received an issue on my Github requesting it.

Here is the extension repo and link to Microsoft marketplace:

https://github.com/wesleyegberto/vscode-java-tests

https://marketplace.visualstudio.com/items?itemName=wesleyegberto.vscode-java-tests

**Comment by kineticsquid** [comment]
@wesleyegberto I've created the namespace and made you owner.

**Comment by wesleyegberto** [comment]
Thank you
