### ISSUE TITLE
Claiming namespace evidence

### ISSUE THREAD

**Issue by hughess** [EclipseFdn/open-vsx.org#1027]
I’ve published an extension using the name “evidence” in the VS Code marketplace and have published the same extension to Open VSX.

[VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Evidence.evidence-vscode)

[Open VSX](https://open-vsx.org/extension/Evidence/evidence-vscode)

**Comment by kineticsquid** [comment]
Thanks @hughess, granted!
