### ISSUE TITLE
Claiming namespace andrewmcodes

### ISSUE THREAD

**Issue by andrewmcodes** [EclipseFdn/open-vsx.org#1028]
I have logged in to Open VSX 👍 

I created a namespace to match my username. You can find me on Twitter at [@andrewmcodes](https://twitter.com/andrewmcodes) and my website is [andrewm.codes](https://andrewm.codes). 

My VS Code Marketplace username is also [andrewmcodes](https://marketplace.visualstudio.com/publishers/andrewmcodes)

**Comment by kineticsquid** [comment]
Thanks @andrewmcodes, good to have your contribution!
