### ISSUE TITLE
Claiming namespace josefpihrt-vscode

### ISSUE THREAD

**Issue by JosefPihrt** [EclipseFdn/open-vsx.org#1029]
Hi,

I would like to claim the ownership of the namespace "josefpihrt-vscode" that I've just created.

I would like to publish the extension "Roslynator" which is already published at VS Marketplace.

https://marketplace.visualstudio.com/items?itemName=josefpihrt-vscode.Roslynator.

Thanks,
Josef

**Comment by kineticsquid** [comment]
Thanks @JosefPihrt, granted!

**Comment by JosefPihrt** [comment]
👍
