### ISSUE TITLE
Error 500 (Website and VSCode)

### ISSUE THREAD

**Issue by HeavenVolkoff** [EclipseFdn/open-vsx.org#1038]
Hello,

I am receiving error 500 when interacting with both the website and on VSCode Extensions tab

The homepage does load successfully (https://open-vsx.org/), but any dynamic interaction such as seem below results in Error 500
 - Loading more extensions than the ones pre-baked in the page
![image](https://user-images.githubusercontent.com/9082460/171031891-5d10c669-9146-4191-86e0-62cd8c3740dc.png)
 - Opening an extension page
![image](https://user-images.githubusercontent.com/9082460/171031986-6354c351-6ac2-45dd-8e09-f2871f0dc3e7.png)
 - Doing any kind of search
![image](https://user-images.githubusercontent.com/9082460/171032030-2e4eaea6-163f-4070-85ed-2d9270708f94.png)

In the `Network Tab` all calls to the open-vsx API return the following body:
```json
{
  "timestamp": "2022-05-30T16:30:05.225+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "message": "",
  "path": "/api/-/search"
}
```

Accessing the API directly leads me to a `Whitelabel Error Page`
https://open-vsx.org/api/-/search?query=python&size=10&sortBy=relevance&sortOrder=desc
![image](https://user-images.githubusercontent.com/9082460/171031605-0caef64d-35ab-4213-8dd9-dd733e28971d.png)

The Extensions tab in VSCode doesn't seem to work at all, always returns error 500 
![image](https://user-images.githubusercontent.com/9082460/171032087-7ae6e856-3450-43a8-a18c-cfef1255748a.png)

**Comment by mbarbero** [comment]
There has been a quirk while deploying last changes https://github.com/EclipseFdn/open-vsx.org/pull/1036. It's being fixed

**Comment by mbarbero** [comment]
Rollout has been rolled back.

**Comment by vince-fugnitto** [comment]
@mbarbero it looks as though it is down again.

![image](https://user-images.githubusercontent.com/40359487/172187192-8a4bf7d5-99e1-48b3-83b4-80f518bfa07d.png)

**Comment by vince-fugnitto** [comment]
> @mbarbero it looks as though it is down again (https://open-vsx.org/).

Fixed thanks to https://github.com/EclipseFdn/open-vsx.org/issues/1047#issuecomment-1147605096.
