### ISSUE TITLE
Claiming namespace t-codespaces

### ISSUE THREAD

**Issue by godkite** [EclipseFdn/open-vsx.org#1039]
Namespace "t-codespaces" was created by me, "godkite" is my github username, it is also used on marketplace for publishing extension.

https://open-vsx.org/extension/t-codespaces/install-extensions
https://open-vsx.org/extension/t-codespaces/ide-code-status

thanks

**Comment by kineticsquid** [comment]
Thanks, @godkite, good to have you!
