### ISSUE TITLE
Claiming namespace solidjs-community

### ISSUE THREAD

**Issue by thetarnav** [EclipseFdn/open-vsx.org#1040]
Hello!
Recently I've created a VSCode extension with code snippets for SolidJS under a [solidjs-community](https://github.com/solidjs-community), and got a request to publish it on open-vsx too.
Don't know if it makes me a "legitimate owner", but it would be nice if the warning went away :)
Here is the project: https://github.com/solidjs-community/solid-snippets
And the published extension: https://open-vsx.org/extension/solidjs-community/solid-snippets

**Comment by kineticsquid** [comment]
And poof, the warnings are gone!
