### ISSUE TITLE
Unpublish request for `sumneko.lua` @ `v3.2.0`

### ISSUE THREAD

**Issue by sumneko** [EclipseFdn/open-vsx.org#1045]
2.5.3 is the last generic version.

Starting with 2.6.0, I will release different versions for different platforms, but since OVSX did not support this feature at that time, I did not continue to publish on OVSX.

Version 3.2.0 was a failed attempt that resulted in the release of a version that could only run on the macOS platform.

**Comment by kineticsquid** [comment]
Done!
