### ISSUE TITLE
Claiming namespace Snickerdoodle

### ISSUE THREAD

**Issue by TtheBC01** [EclipseFdn/open-vsx.org#1046]
I'm the [CTO](https://toddchapman.io) of [Snickerdoodle Labs](https://snickerdoodlelabs.io) and our engineering team would like to be able to publish VSX extensions under the Snickerdoodle namespace. I recently published a [color theme package](https://github.com/SnickerdoodleLabs/Snickerdoodle-Theme-Light) to [VSX](https://open-vsx.org/extension/Snickerdoodle/snickerdoodle-light).

**Comment by kineticsquid** [comment]
Always good to have an important food group covered.
