### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/open-vsx.org#1047]
After opening the website, got an error immediately:
![image](https://user-images.githubusercontent.com/43075439/172188754-70103948-0baf-4fa3-bdac-78abf6fd9fba.png)

After close it and scroll down, will get another error (and it seems it's doing API call infinitely):
![image](https://user-images.githubusercontent.com/43075439/172188978-a44b8ae1-0cd2-40ec-a8e9-5dbc7496621f.png)

When I click the login icon/button on the top right corner, I will see an error page like this:
![image](https://user-images.githubusercontent.com/43075439/172189061-772d904c-2748-407a-8759-c2d5912102dd.png)

Thanks!

**Comment by eclipsewebmaster** [comment]
The core pods seem to be running, but we've restarted them just in case.

**Comment by linkfang** [comment]
Now it works fine on my end, thanks @eclipsewebmaster !

Closing the issue.

**Comment by xaberus** [comment]
The service is down again. I am seeing the same messages as the OP. Is this the correct way to report it? Should I open a new issue?
