### ISSUE TITLE
Claiming namespace fortran-lang

### ISSUE THREAD

**Issue by gnikit** [EclipseFdn/open-vsx.org#1050]
I am the main dev and owner of the [`fortran-lang`](https://marketplace.visualstudio.com/publishers/fortran-lang) publisher, previously known as `krvajalm`. We have migrated our [Modern Fortran extension](https://github.com/fortran-lang/vscode-fortran-support) to a GitHub organisation and a different publisher.

**Comment by kineticsquid** [comment]
Thanks @gnikit good to have you with us!
