### ISSUE TITLE
Implement website visit and API use tracking

### ISSUE THREAD

**Issue by kineticsquid** [EclipseFdn/open-vsx.org#1054]
We'd like to better understand who's visiting open-vsx.org from a browser (eyeballs on the site) and who's accessing content through the API. Total visits, unique visitors, where they're coming from. This may not be exactly the same thing so I'm mentioning it separately, download stats, in aggregate and by extension. If the implementation of these is different, I'd prioritize as follows:
1. Browser visitors
2. Download stats
3. API Traffic.

**Comment by kineticsquid** [comment]
@chrisguindon Looks like #220 is complete. Independent of this request, https://gitlab.eclipse.org/eclipsefdn/infrazilla/-/issues/334, can you enable GA now?

**Comment by chrisguindon** [comment]
@kineticsquid From what I can see, the production branch is  [9 commits ahead](https://github.com/EclipseFdn/open-vsx.org/compare/main...production), [4 commits behind](https://github.com/EclipseFdn/open-vsx.org/compare/production...main) main: https://github.com/EclipseFdn/open-vsx.org/compare/production...main

The change that Zhou did is still not in production: 


![Screenshot 2022-07-12 083725](https://user-images.githubusercontent.com/893942/178491469-3167d9dd-28b6-4301-8e54-7474e86b7b2b.png)


@mbarbero are we still experiencing issues with open-vsx? Is it safe for us to publish the latest commits on main to production?

**Comment by MatthewKhouzam** [comment]
A thought, please check out  [https://matomo.org/](https://matomo.org/). It is an open source privacy centered tracker.

**Comment by chrisguindon** [comment]
@MatthewKhouzam This is definitely something that we are considering. I made a proposal a few months ago via our internal bug tracking systems recommending that we switch from GA to motomo. 

I think this is where we would like to go in the future.

**Comment by kineticsquid** [comment]
@chrisguindon Are you able to enable browser stats now?

**Comment by chrisguindon** [comment]
@kineticsquid I granted you access to the Google Analytics property. Let me know if you have any questions.

**Comment by kineticsquid** [comment]
Yep, @chrisguindon thanks, I can see the stats. If I recall, this is visits to the site and not API activity?

**Comment by chrisguindon** [comment]
> Yep, @chrisguindon thanks, I can see the stats. If I recall, this is visits to the site and not API activity?

Correct, these are users visiting the site with a browser. 

API calls would need to be monitored/tracked by another service.
