### ISSUE TITLE
Claiming namespace Mineiros

### ISSUE THREAD

**Issue by mariux** [EclipseFdn/open-vsx.org#1055]
Hi,

I am the co-founder of Mineiros GmbH and we own mineiros.io and gihub.com/mineiros-io where we also publish https://github.com/mineiros-io/vscode-terramate/ as https://open-vsx.org/extension/Mineiros/terramate (published by our awesome go guy @i4ki)

Our github also shows the verified domain.

What else do i need to provide to claim the namespace?

Thanks, all the best, marius

**Comment by kineticsquid** [comment]
@mariux I only see @i4ki in the name space currently. Can I get confirmation from them that you can own the namespace?

**Comment by kineticsquid** [comment]
Thanks @i4ki. I've added @mariux and made them the owner.

**Comment by i4ki** [comment]
Thank you @kineticsquid
