### ISSUE TITLE
Claiming namespace xdebug

### ISSUE THREAD

**Issue by zobo** [EclipseFdn/open-vsx.org#1058]
I maintain VSC MP extensions `xdebug.php-debug` and `xdebug.php-pack`. Would like to publish them too, seems namespace is already taken.

**Comment by kineticsquid** [comment]
@zobo I can see the `xdebug` namespace was added to `extensions.json` in https://github.com/open-vsx/publish-extensions/pull/565. Specifically, https://github.com/open-vsx/publish-extensions/pull/565/commits/e4d2abcb9cfae0694a1fb4db87e3354b42d338fa. There are currently no extensions published under the `xdebug` namespace. Did you ever have either of these extensions auto-published?

**Comment by zobo** [comment]
I did not. But felixfbecker got renamed to xdebug, so maybe that is the reason.

**Comment by zobo** [comment]
I also want to note, that on VS Marketplace the old ID redirects to the new one: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug -> https://marketplace.visualstudio.com/items?itemName=xdebug.php-debug

Same happens inside vscode for existing extension installations.

Let me know if I can do more to get this resolved.

**Comment by spoenemann** [comment]
Yes :+1:

**Comment by filiptronicek** [comment]
> remove this namespace from extensions.json

@kineticsquid https://github.com/open-vsx/publish-extensions/commit/e69f9730e7f392cd764d9db73d190d5168ef640a ✅

**Comment by zobo** [comment]
Thanks!

**Comment by kineticsquid** [comment]
@zobo Thanks! You're good now.

**Comment by zobo** [comment]
I have been able to claim the namespace and it shows up under my settings. But when I try to publish an existing vsix I get an Internal Server Error...

```
ovsx publish xdebug.php-debug-1.27.0.vsix --pat ...
❌  Internal Server Error
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

Any idea how I can get more info what's going on?

**Comment by spoenemann** [comment]
It's probably best to request support from [Help Desk](https://gitlab.eclipse.org/eclipsefdn/helpdesk) to look into the server logs. @zobo could you provide a timestamp of your publishing attempt?

**Comment by zobo** [comment]
I tried an upload just now 15:06 CEST
`ovsx publish xdebug.php-debug-1.27.0.vsix`

**Comment by zobo** [comment]
Found a ticket and added info. Could be related... https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1330#note_1008525
