### ISSUE TITLE
Claiming namespace elves

### ISSUE THREAD

**Issue by xiaq** [EclipseFdn/open-vsx.org#1065]
This namespace will be used to publish extensions related to the Elvish shell project (https://elv.sh), which uses the organization name `elves` on GitHub, and you can see I'm its sole member and owner: https://github.com/orgs/elves/people.

I have already claimed the VS Code publisher ID `elves` too, which you can see on https://marketplace.visualstudio.com/items?itemName=elves.elvish.

**Comment by kineticsquid** [comment]
Thanks @xiaq, granted!
