### ISSUE TITLE
Claiming namespace wdhongtw

### ISSUE THREAD

**Issue by wdhongtw** [EclipseFdn/open-vsx.org#1066]
`wdhongtw` is the namespace which is identical to my GitHub username (and many other identities such as Eclipse username). :D

Here are some extension published under this namespace:

- <https://open-vsx.org/extension/wdhongtw/gpg-indicator>
- <https://open-vsx.org/extension/wdhongtw/otp-toolbox>

These are extension of which the source repositories are published under `wdhongtw` GitHub user. :D

**Comment by kineticsquid** [comment]
Thanks @wdhongtw, good to have you!
