### ISSUE TITLE
Claiming namespace LearnPack (id learn-pack)

### ISSUE THREAD

**Issue by tommygonzaleza** [EclipseFdn/open-vsx.org#1078]
I'm the CTO of the company that created this plugin, my partner and I are the developers who wrote the code of this extension. You can check more information about us on our webpage: https://www.learnpack.co/

**Comment by kineticsquid** [comment]
@tommygonzaleza Following up on the comment above.

**Comment by kineticsquid** [comment]
@tommygonzaleza following up one more time. If we don't hear from you, I'll need to close this

**Comment by tommygonzaleza** [comment]
Hello! Let me talk with Alejandro so he can confirm it here, thanks!

**Comment by kineticsquid** [comment]
@tommygonzaleza Any news on this?

**Comment by alesanchezr** [comment]
Hello! Yes please add tomas as a contributor to this same namespace

**Comment by kineticsquid** [comment]
@tommygonzaleza @alesanchezr Good to have you all!
