### ISSUE TITLE
Claiming namespace bscan

### ISSUE THREAD

**Issue by bscan** [EclipseFdn/open-vsx.org#1082]
I have published https://open-vsx.org/extension/bscan/perlnavigator under the namespace bscan. I also have published this to the Microsoft marketplace as https://marketplace.visualstudio.com/items?itemName=bscan.perlnavigator and would like to have the same namespace on Open VSX. I also plan on publishing the Raku extension: https://marketplace.visualstudio.com/items?itemName=bscan.raku-navigator . Thanks!

**Comment by kineticsquid** [comment]
@bscan, thanks good to have you!
