### ISSUE TITLE
Update old version of publishing API to support platform-specific releases

### ISSUE THREAD

**Issue by radeksimko** [EclipseFdn/open-vsx.org#1084]
The latest published version of ovsx (v0.5.0) supports platform-specific releases via `ovsx` `--target` flag.

However, the Registry running at open-vsx.org does not seem to support this.

The issue was discussed initially here:
 - https://github.com/eclipse/openvsx/issues/450#issuecomment-1135966458
 - https://github.com/eclipse/openvsx/issues/450#issuecomment-1141948684
 - https://github.com/eclipse/openvsx/issues/450#issuecomment-1142063626
 - https://github.com/eclipse/openvsx/issues/461

At this point we are still blocked from publishing our extension to open-vsx.org unfortunately. The situation is worse in that I managed to publish a platform-specific extension which appears to be universal, hence appears broken for all users except for users of that single platform.

Could we get the API updated, please? 🙏🏻

**Comment by radeksimko** [comment]
@kineticsquid If you could unpublish all versions above `2.20.0` (i.e. make 2.20.0 the latest available version) that would be amazing! 🙏🏻  `2.20.0` is the last version which was universal, before we started publishing platform-specific ones.

https://open-vsx.org/extension/hashicorp/terraform

> I should know this but don't, what version are we running at open-vsx.org?

Perhaps not related to this particular issue, but would it be useful to expose the version somewhere in footer, so that everyone can know?

**Comment by kineticsquid** [comment]
@radeksimko Done!

@spoenemann Thoughts on this enhancement request?

**Comment by spoenemann** [comment]
I'm not deep enough into that topic. @amvanbaren @jeanp413 @filiptronicek WDYT?

**Comment by amvanbaren** [comment]
https://github.com/eclipse/openvsx/issues/21

**Comment by radeksimko** [comment]
@amvanbaren am I right the production version was now updated as part of https://github.com/EclipseFdn/open-vsx.org/pull/1094 , so publishing platform-specific extensions is now possible, or are there some other changes tracked anywhere that need to happen?

**Comment by amvanbaren** [comment]
@radeksimko Yes, publishing platform-specific extensions is now possible.

**Comment by radeksimko** [comment]
I'm assuming this was rolled back as part of the Friday outage? https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1483

**Comment by filiptronicek** [comment]
@radeksimko yes indeed, this is not possible right now again :(

**Comment by lnicola** [comment]
> Yes, publishing platform-specific extensions is now possible.

We (in `rust-analyzer`) have a CI action that tries to publish the extension each night, and it never worked https://github.com/rust-lang/rust-analyzer/actions/workflows/release.yaml. So maybe there are multiple issues at play.

**Comment by radeksimko** [comment]
Is there any updated plan on rolling out the new version? It looks like a number of extensions are essentially blocked by this

 - https://github.com/wgsl-analyzer/wgsl-analyzer/issues/28
 - https://github.com/muhammadsammy/free-omnisharp-vscode/issues/39
 - https://github.com/johnsoncodehk/volar/pull/1255
 - https://github.com/hashicorp/vscode-terraform/pull/1064

**Comment by amvanbaren** [comment]
@radeksimko open-vsx.org now does support target specific extensions, but timeouts have been reported when publishing.
Improvements are on the way. I'm blocked by helpdesk issue [#2104](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2104). I've added your comment and bumped the priority to high.

**Comment by lnicola** [comment]
> but timeouts have been reported when publishing

Note that on our side it reverted to returning 500.

**Comment by pm4rcin** [comment]
@amvanbaren how's it going because the issue you mentioned on Eclipse's gitlab was closed?

**Comment by amvanbaren** [comment]
Hi @pm4rcin, the API supports platform-specific releases for a while now. I think the issue can be closed. @radeksimko Please re-open this issue if platform specific releases still don't work for you.
