### ISSUE TITLE
Claiming namespace sourcegraph

### ISSUE THREAD

**Issue by abeatrix** [EclipseFdn/open-vsx.org#1088]
Hi there,

I am an engineer on a team that builds extensions for [Sourcegraph](https://sourcegraph.com/search). 

We have recently published our [extension](https://open-vsx.org/extension/sourcegraph/sourcegraph) via @ryankscott 's open-vsx token, and would like to claim the `sourcegraph` namespace and add me and @ryankscott @sourcegraph-bot as the owner of the namespace, please. 

List of users to be added as owners:
@abeatrix 
@ryankscott
@sourcegraph-bot 

ref: https://github.com/sourcegraph/sourcegraph/issues/36477

Please let us know if additional info is required.

Thanks!

**Comment by kineticsquid** [comment]
@abeatrix Since `@ryankscott` published the extension that is there, I need confirmation from them before I grant this request.

**Comment by ryankscott** [comment]
Hi @kineticsquid, I can confirm that both @abeatrix and @sourcegraph-bot should be owners of the `sourcegraph` namespace.

**Comment by kineticsquid** [comment]
I've added @abeatrix and @ryankscott as owners. I'm not seeing `@sourcegraph-bot` as a user.

**Comment by abeatrix** [comment]
@kineticsquid I will consult with the account owner of @sourcegraph-bot account and add them to the namespace manually.  

Thank you so much for the help @kineticsquid !
