### ISSUE TITLE
Claiming namespace RustedTurnip

### ISSUE THREAD

**Issue by RustedTurnip** [EclipseFdn/open-vsx.org#1089]
I created the namespace in my own Github name and am the only one to have published to it, hence the want to own the namespace.

I am unsure how else to prove ownership other than sending this from the same account used to publish the extensions, but let me know and I will happily oblige.

Many thanks,
RustedTurnip

**Comment by kineticsquid** [comment]
@RustedTurnip Granted! We can always use more vegetables, even oxidized ones.
