### ISSUE TITLE
Claiming namespace takkaO

### ISSUE THREAD

**Issue by takkaO** [EclipseFdn/open-vsx.org#1090]
I'm using namespace for all my OSS project:
https://github.com/takkaO?tab=repositories
https://qiita.com/takkaO

I already published extension ```open-window-tab-context``` to [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=takkaO.open-window-tab-context) and I want to publish to [OpenVSX](https://open-vsx.org/extension/takkaO/open-window-tab-context) too.

Thank you.

**Comment by kineticsquid** [comment]
Thanks @takkaO good to have you.
