### ISSUE TITLE
Claiming namespace rust-lang

### ISSUE THREAD

**Issue by pietroalbini** [EclipseFdn/open-vsx.org#1091]
Hello! I'm Pietro, lead of the [Rust infrastructure team](https://www.rust-lang.org/governance/teams/infra). I'd like to claim the `rust-lang` namespace on behalf of the Rust project, to be able to publish our extensions on Open VSX.

You can verify I'm the lead of the Rust infrastructure team on the [Rust project governance page](https://www.rust-lang.org/governance/teams/infra), or by emailing `infra@rust-lang.org`.

**Comment by kineticsquid** [comment]
Grazie @pietroalbini!
