### ISSUE TITLE
Claiming namespace [name]

### ISSUE THREAD

**Issue by michael-andreuzza** [EclipseFdn/open-vsx.org#1099]
Hey, I just wanted to request about this space 
https://open-vsx.org/extension/wicked-labs/sinequanone-sunset

And this is to prove is mine.
https://marketplace.visualstudio.com/items?itemName=wicked-labs.sinequanone-sunset

**Comment by kineticsquid** [comment]
@michael-andreuzza Confirming that this request is for namespace `wicked-labs`. If so, this is a dup of #1100

**Comment by michael-andreuzza** [comment]
I confirm this is a request for wicked-labs. Also misunderstood.

Thank you.
