### ISSUE TITLE
Claiming namespace [name]

### ISSUE THREAD

**Issue by michael-andreuzza** [EclipseFdn/open-vsx.org#1100]
Hey, I just wanted to request about this space 
https://open-vsx.org/extension/wicked-labs/sequoia
And this is to prove is mine.
- https://marketplace.visualstudio.com/items?itemName=wicked-labs.sequoia
- sequoiatheme.com

Thank you

/Mike

**Comment by kineticsquid** [comment]
@michael-andreuzza Looks like you're already the owner of `wicked-labs`. Is that the namespace you're looking to claim?

**Comment by michael-andreuzza** [comment]
Yeah, that's the one. 
I misunderstood, it seemed that I had to claim the name for every extension I pushed...

Thank you.

**Comment by kineticsquid** [comment]
No worries, thanks for your contributions!

**Comment by michael-andreuzza** [comment]
You are very welcome, more coming up soon!
