### ISSUE TITLE
Claiming namespace jburz2001

### ISSUE THREAD

**Issue by jburz2001** [EclipseFdn/open-vsx.org#1102]
Hello. I want to claim the jburz2001 namespace.

Here is a graph showing that I contributed to the project in this namespace: [https://github.com/jburz2001/vnv-vscode-snippets-extension/graphs/contributors](https://github.com/jburz2001/vnv-vscode-snippets-extension/graphs/contributors)

Here is an issue from a related Github repo that shows my task of publishing this to the Open VSX Registry: [https://github.com/vnvlabs/vnv/issues/6](https://github.com/vnvlabs/vnv/issues/6)

**Comment by kineticsquid** [comment]
@jburz2001 good to have your contribution!
