### ISSUE TITLE
Unpublish request for `vscjava.vscode-java-test` and `vscjava.vscode-maven`

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#1105]
Please unpublish the latest versions of `vscjava.vscode-java-test` and `vscjava.vscode-maven`.

This is `v0.36.0` for `vscjava.vscode-maven` & `v0.35.1` for `vscjava.vscode-java-test`.

See https://github.com/eclipse/openvsx/issues/481 for why this is. A fix is already in place and ready to publish a fixed version for both extensions.

**Comment by kineticsquid** [comment]
@filiptronicek Done.
