### ISSUE TITLE
Claiming namespace 1Password

### ISSUE THREAD

**Issue by jodyheavener** [EclipseFdn/open-vsx.org#1106]
I'd like to claim ownership of the namespace "1Password" on Open VSX. I work for 1Password and look after [op-vscode](https://github.com/1Password/op-vscode), or 1Password for VS Code, ([listing](https://open-vsx.org/extension/1Password/op-vscode)) and am [setting up a workflow](https://github.com/1Password/op-vscode/pull/34) to start automatically publishing releases to the registry.

Thanks!

**Comment by kineticsquid** [comment]
Thanks @jodyheavener, glad to have you!
