### ISSUE TITLE
Claiming namespace byCedric

### ISSUE THREAD

**Issue by byCedric** [EclipseFdn/open-vsx.org#1107]
It's my GitHub and Dutch company name.

You can find the dutch registration in the chambers of commerce website here: https://www.kvk.nl/orderstraat/product-kiezen/?kvknummer=777814810000
> Because it's written in dutch, you can use [Google Translate to translate the website](https://translate.google.com/?sl=nl&tl=en&op=websites)

---

- [Currently implementing the publish of vscode-expo in the Open VSX registry](https://github.com/expo/vscode-expo/pull/112)
- [Namespace is currently set as publisher too](https://github.com/expo/vscode-expo/blob/main/package.json#L16)
- [VSCode marketplace has this extension as well](https://marketplace.visualstudio.com/items?itemName=byCedric.vscode-expo)

**Comment by kineticsquid** [comment]
Thanks @byCedric, granted!
