### ISSUE TITLE
Claiming namespace mark-wiemer

### ISSUE THREAD

**Issue by mark-wiemer** [EclipseFdn/open-vsx.org#1114]
I just registered it, it matches my GitHub username, and it also matches the namespace under which I've published my Visual Studio Marketplace extension [AutoHotkey Plus Plus](https://marketplace.visualstudio.com/items?itemName=mark-wiemer.vscode-autohotkey-plus-plus)

**Comment by kineticsquid** [comment]
@mark-wiemer Good to have you, granted!
