### ISSUE TITLE
Claiming namespace dsrkafuu

### ISSUE THREAD

**Issue by dsrkafuu** [EclipseFdn/open-vsx.org#1118]
I created the namespace: `dsrkafuu` for published my theme "Aofuji Light":

- Theme: https://open-vsx.org/extension/dsrkafuu/vscode-theme-aofuji
- VS Marketplace Version: https://marketplace.visualstudio.com/items?itemName=dsrkafuu.vscode-theme-aofuji
- Source: https://github.com/dsrkafuu/vscode-theme-aofuji

Thanks.

**Comment by kineticsquid** [comment]
@dsrkafuu Thanks for your contribution!
