### ISSUE TITLE
Claiming namespace jock

### ISSUE THREAD

**Issue by lishu** [EclipseFdn/open-vsx.org#1128]

**Comment by kineticsquid** [comment]
@lishu Looks like one of your extensions is already published at this namespace by others. @KokaKiwi and @appelgriebsch, letting you know that we're assigning this namespace to @lishu. Thanks for all your contributions!

**Comment by lishu** [comment]
This maybe has some issues, my vscode `publisher` is `jock`, not ~~lishu~~.

**Comment by lishu** [comment]
https://github.com/lishu/vscode-svg2/blob/fb2af1a03b0f9efc4bfd60ad7f0ba20f5bf00302/package.json#L6

For now:  
```
> ovsx create-namespace jock
❌  Namespace already exists: jock
> ovsx publish
❌  Insufficient access rights for publisher: jock
```

**Comment by kineticsquid** [comment]
This is what I see when searching for publisher `jock`:
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/681707/187246860-efa21ab4-ee24-45ea-bf71-35f984b85d8f.png">

**Comment by kineticsquid** [comment]
@lishu RIght, there is already an extension in that namespace.

**Comment by lishu** [comment]
My Extension `jock.svg` is publish by `open-vsx`, so i cannot use `jock` as namespace (package.json publisher) republish.
I'm not sure what I can do

**Comment by lishu** [comment]
Current My Open VSX Account is `lishu`

**Comment by filiptronicek** [comment]
@lishu I have removed the jock.svg extension from automatic publishing (https://github.com/open-vsx/publish-extensions/commit/c6e68801d18c88705a461c7d8d8435c2ce66dd8d). Thanks for taking it over, it has been failing to build for quite a while and sadly didn't have the time to try to fix the build.

**Comment by filiptronicek** [comment]
@kineticsquid I think what just needs to happen is for the `jock` namespace to be assigned to the `lishu` account. Could you try it? 🙏

**Comment by kineticsquid** [comment]
@filiptronicek Done! 

@lishu Can you confirm?

**Comment by lishu** [comment]
Yes, It works now.

Thanks to @kineticsquid and @filiptronicek 

🚀  Published jock.svg v1.4.22
