### ISSUE TITLE
Renaming Namespace: RedVanWorkshop => PeterSchmalfeldt

### ISSUE THREAD

**Issue by manifestinteractive** [EclipseFdn/open-vsx.org#1135]
My github account is @manifestinteractive and I initially created Open VSX Extensions under my work name, but would also like to publish extensions on your platform for non work related extensions.

I tried creating another account to do this, but it uses my GitHub username and tells me another account is already using it.

So, I either need to delete my `RedVanWorkshop` Namespace ( it's fine if that extension gets deleted too ) so I can reuse my `manifestinteractive` GitHub username, or rename that `RedVanWorkshop` Namespace to my real name `PeterSchmalfeldt` so it's less confusing when I publish packages.

I only picked that work name since the extension I was making at the time was tied to that line of work, but it was still an open source personal project I did on my own time on my own devices and 100% OK to just move it to my name since I manage all that stuff.

It does not appear I can even delete my own account or remove a package, so this seems to be the only resort I have left ( submitting a namespace ticket ).

Thanks for making the extensions easy to publish !!!

**Comment by kineticsquid** [comment]
@manifestinteractive We're working on an admin capability to enable this: https://github.com/eclipse/openvsx/issues/427. Stay tuned!

**Comment by manifestinteractive** [comment]
I've got a pending update I need to get out for this software that requires I change the name first, can I just delete my current account then and start over?  I am just stuck currently as I cannot publish this new package under the incorrect name and would like to get this out under the correct name.  So just deleting `RedVanWorkshop` would be fine, then I could create a new account and reupload this and send people the new link.

Just kind of stuck with not being able to get a release out under the correct name, and also having an invalid extension still listed that I cannot seem to delete or unpublish.

If there is an alpha or beta access to test out this admin, I am more than willing to test this out, I just have some time restraints on getting this renamed.

**Comment by kineticsquid** [comment]
@manifestinteractive I've renamed `RedVanWorkshop` to `PeterSchmalfeldt`.
