### ISSUE TITLE
Loading the main page results in an error popup

### ISSUE THREAD

**Issue by eclipsewebmaster** [EclipseFdn/open-vsx.org#1137]
Some hours after rolling our a new version people are starting to see a popup with the message "Request failed: GET https://open-vsx.org/user (Service Unavailable)" when loading the main page.
Restarting the underlying service clears the error (presumably temporarily), but something isn't quite right.

**Comment by amvanbaren** [comment]
@eclipsewebmaster Any exceptions or stack traces on the server side?

**Comment by 0x199x** [comment]
![image](https://user-images.githubusercontent.com/89231731/181393985-f1bd6243-83e0-47dd-bcb9-2a00af532a24.png)

![image](https://user-images.githubusercontent.com/89231731/181393931-3260e670-3734-4096-8d4c-e342e2960153.png)

![image](https://user-images.githubusercontent.com/89231731/181393972-2f6f4554-0d19-479e-9a56-21d01ef9fcc4.png)

**Comment by fredg02** [comment]
Should be better now.
