### ISSUE TITLE
Claiming namespace tomtung

### ISSUE THREAD

**Issue by tomtung** [EclipseFdn/open-vsx.org#1140]
I own the same namespace on VS Code Marketplace: https://marketplace.visualstudio.com/publishers/tomtung (the page links to my GitHub account).

**Comment by kineticsquid** [comment]
@tomtung What is the publisher ID you want associated with this namespace?

**Comment by tomtung** [comment]
Sorry not sure if I understand the difference between the two... can I use the same string `tomtung` for both?

**Comment by kineticsquid** [comment]
The publisher ID is the GitHub ID that does the publishing. I checked and I don't see `tomtung` at Github.

**Comment by tomtung** [comment]
Sorry isn't `tomtung` my GitHub ID? https://github.com/tomtung

Also I'm sure my extension was uploaded to https://open-vsx.org/extension/tomtung/vscode-markdown-linkify but seems like it's gone for some reason?

**Comment by kineticsquid** [comment]
@tomtung Weird, when I went to add you yesterday, I didn't see `tomtung` listed in ope-vsx as a registered publisher. But I see it now. You are the owner or the `tomtung` namespace. Thanks!
