### ISSUE TITLE
openvsx is unresponsive and not stable

### ISSUE THREAD

**Issue by akosyakov** [EclipseFdn/open-vsx.org#1141]
On our side we see that requests are taking very long time with many internal errors.

<img width="863" alt="Screenshot 2022-07-22 at 08 54 06" src="https://user-images.githubusercontent.com/3082655/180381350-72c376a4-507b-4db2-80dc-755afe4ab10c.png">
<img width="894" alt="Screenshot 2022-07-22 at 08 54 08" src="https://user-images.githubusercontent.com/3082655/180381343-d4c9b80f-51af-45ca-96b6-ee7d9a80b494.png">

**Comment by akosyakov** [comment]
Users cannot search and install extensions:
<img width="347" alt="Screenshot 2022-07-22 at 09 02 40" src="https://user-images.githubusercontent.com/3082655/180382678-94d74240-48ee-47f0-a46f-bb6006685e99.png">

**Comment by akosyakov** [comment]
cc @eclipsewebmaster Could someone start an incident on Eclipse side?

**Comment by logithack** [comment]
Presumably related: https://github.com/eclipse/openvsx/issues/497

**Comment by fredg02** [comment]
> cc @eclipsewebmaster Could someone start an incident on Eclipse side?

=> https://www.eclipsestatus.io/incidents/rwq9sc8j8vsf

**Comment by geropl** [comment]
@fredg02 Are there any updates to share on this topic? What's your approach in general? E.g. have you discussed and dismissed a rollback? :thinking: 
Just trying to get a feel where we are, and how long this might take. :lotus_position:

**Comment by fredg02** [comment]
AFAIK the rollback was done yesterday already (see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1483#note_916312), but the 502s appeared after that.

**Comment by geropl** [comment]
Just wanted to share that starting at ~14:30 CEST (UTC+2) things started to look differently: Instead of getting 502s + high latency, we now get a lot of 503s instead.
![image](https://user-images.githubusercontent.com/32448529/180463932-b6786b46-499e-45d7-8451-42ded8690aab.png)

**Comment by fredg02** [comment]
We are still working on it.

**Comment by geropl** [comment]
> We are still working on it.

Awesome, thank you! :pray:

**Comment by filiptronicek** [comment]
https://open-vsx.org seems to be up for me now 🥳

**Comment by benz0li** [comment]
Seems to be resolved now.

Someone from @eclipsewebmaster please confirm.

**Comment by daenney** [comment]
According to https://www.eclipsestatus.io/ it's still ongoing, but unfortunately the status page hasn't provided meaningful updates throughout this. It's very possible it's out of date. Things do appear to be in working order.

**Comment by geropl** [comment]
Can confirm. From our end (gitpod.io) things look fine again:
![image](https://user-images.githubusercontent.com/32448529/180600307-7e9fa422-9ecc-4c4e-807e-be534c695ffb.png)

**Comment by fredg02** [comment]
Yes, service is restored but had to be rolled back to an older, working state.
