### ISSUE TITLE
Claiming namespace Cloud-pipelines

### ISSUE THREAD

**Issue by Ark-kun** [EclipseFdn/open-vsx.org#1142]
I'm the owner of the https://github.com/Cloud-Pipelines repo, https://cloud-pipelines.net domain (verified by MS) and the [Cloud-pipelines.pipeline-editor-vscode](https://marketplace.visualstudio.com/items?itemName=Cloud-pipelines.pipeline-editor-vscode) extension.

**Comment by kineticsquid** [comment]
Granted, good to have you @Ark-kun!
