### ISSUE TITLE
Claiming namespace radiolevity

### ISSUE THREAD

**Issue by finnsjames** [EclipseFdn/open-vsx.org#1145]
I use the name radiolevity for all of my publishing work, such as vscode extensions. You can see that radiolevity.com redirects to my personal website.

Edit: also, [it looks like](https://github.com/EclipseFdn/open-vsx.org/issues/66) I was approved for this namespace a while back. I suppose something has changed?

**Comment by kineticsquid** [comment]
@finnsjames Yes, you currently own this namespace. Anything else you need?

**Comment by finnsjames** [comment]
It appears that the issue is with my eclipse account. No, I think I can figure it out from here. Thanks!
