### ISSUE TITLE
Claiming namespace [Oracle]

### ISSUE THREAD

**Issue by christianshay** [EclipseFdn/open-vsx.org#1146]
We are getting ready to publish an extension and so I would like to claim namespace ownership for "Oracle"  on behalf of Oracle Corporation.

I don't want my name to be listed as the owner, it should be "Oracle Corporation", but I am not sure exactly how to accomplish this. There's some mention of a "service account" but I am not sure what that is, or who might control it.

**Comment by kineticsquid** [comment]
@christianshay I've created the namespace but have not yet assigned it. The assignment is to the GH id that does the publishing. One example of how to accomplish this is how Red Hat does it: https://open-vsx.org/extension/redhat/vscode-yaml. They publish from a GH id, `rhdevelopers-ci` and clarify in the name of the extension its source. Hope this helps.

**Comment by christianshay** [comment]
> @christianshay I've created the namespace but have not yet assigned it. The assignment is to the GH id that does the publishing. One example of how to accomplish this is how Red Hat does it: https://open-vsx.org/extension/redhat/vscode-yaml. They publish from a GH id, `rhdevelopers-ci` and clarify in the name of the extension its source. Hope this helps.

Hi, so to confirm I have to use a GitHub ID to publish whatever GitHub ID I used to publish will show up on openvsx marketplace? Some of the documentation references something called a service account which seem to be talking about corporate accounts.  Do you know what they are referring to when they talk about service accounts?

**Comment by kineticsquid** [comment]
@christianshay You're asking about this reference in the Open-VSX FAQ: https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-9.

>Can I sign the Publisher Agreement on behalf of a Service Account?

>Yes, the Publisher Agreement accounts for this. If you are able to sign the Publisher Agreement based on a service account and related service GitHub ID, coupled with the ability to enter into the Publisher Agreement (necessary rights to do so based on the terms of the Publisher Agreement), then you may do so.

>Please note if you wish to publish as an individual at a later time, you will need to create an individual account against a personal GitHub ID and sign the Publisher Agreement with that ID as an individual.

@amvanbaren @spoenemann @mbarbero Does this service account refer to a [GitHub organization account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#organization-accounts) or a user account set up by an individual (different from their own) for the sole purpose of publishing?

**Comment by amvanbaren** [comment]
@filiptronicek Is the @open-vsx account a [GitHub organization account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#organization-accounts) or a user account set up by an individual (different from their own) for the sole purpose of publishing?

**Comment by filiptronicek** [comment]
> @filiptronicek Is the @open-vsx account a [GitHub organization account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#organization-accounts) or a user account set up by an individual (different from their own) for the sole purpose of publishing?

@amvanbaren this account has been setup by Eclipse for the two following reasons:
1. To host https://github.com/open-vsx/publish-extensions
2. To publish extensions from the aforementioned repo

There could be something else to it, but it's a simple personal account setup for publishing extensions.

**Comment by amvanbaren** [comment]
> it's a simple personal account setup for publishing extensions.

Thanks @filiptronicek!

**Comment by kineticsquid** [comment]
@amvanbaren @filiptronicek Sorry, I meant to ask a different question. @christianshay at Oracle wants to publish an extension from an account that's not his individually.

>We are getting ready to publish an extension and so I would like to claim namespace ownership for "Oracle" on behalf of Oracle Corporation.

>I don't want my name to be listed as the owner, it should be "Oracle Corporation", but I am not sure exactly how to accomplish this. There's some mention of a "service account" but I am not sure what that is, or who might control it.

He's looking at the FAQ we've posted and we refer to a 'service' account. The question I meant to ask is in order to accomplish his goal, should @christianshay use a GH organization account or use a user account, but one that's different from his own?

**Comment by kineticsquid** [comment]
@amvanbaren @filiptronicek @spoenemann Thoughts on the above question?

**Comment by filiptronicek** [comment]
I think one cannot publish on behalf of an organisation, since you cannot sign in to Open VSX as an org. I would suggest making a new GitHub user account to do publishing from, similar to the one we use at Gitpod - https://github.com/gitpod-openvsx.

RedHat does it similarly in that they have an account for all their CI needs (including publishing to Open VSX): https://github.com/rhdevelopers-ci

cc @christianshay @kineticsquid

**Comment by spoenemann** [comment]
The owner of an open-vsx.org namespace is not visible to the public, only the publisher of an extension is visible. The publisher can be a service account. This requires two things:
 - A GitHub account (no exposure of personal details, so it can be a "bot" / service account)
 - An eclipse.org account connected to the GitHub account (this requires personal details of a person responsible for the published content)

As initialization step, it is necessary to log in to open-vsx.org with the GitHub service account, connect it to the eclipse.org account in the Settings page, sign the Publisher Agreement, and finally create an access token.

**Comment by Oracle-openvsx** [comment]
Thank you all! 

@kineticsquid I have created this github ID to do the publishing (Oracle-openvsx). Can you please assign ownership of the Oracle namespace to gh id Oracle-openvsx. Thank you!

**Comment by christianshay** [comment]
I can confirm that Oracle-openvsx is me :)

**Comment by kineticsquid** [comment]
@Oracle-openvsx You are good to go, glad to have you!

**Comment by spoenemann** [comment]
To clarify, from the Guidelines Wiki:

> Namespace ownership should not be granted to bots / service accounts, but only to accounts associated with real persons. They will have the opportunity to add more accounts to the namespace by themselves

https://github.com/EclipseFdn/open-vsx.org/wiki/Guidelines-on-Namespaces#checking-ownership-requests

But I'm ok to keep it like requested here to avoid further hassle.
