### ISSUE TITLE
Claiming namespace [devsense]

### ISSUE THREAD

**Issue by jakubmisek** [EclipseFdn/open-vsx.org#1149]
`"devsense"` is our publisher name on vscode marketplace, our legal domain name - "devsense.com", and our legal entity name "DEVSENSE s.r.o."

Thank you for processing this request.

**Comment by kineticsquid** [comment]
@jakubmisek It's yours! Thanks for your contribution.

**Comment by jakubmisek** [comment]
thank you @kineticsquid!
