### ISSUE TITLE
openvsx is unresponsive and not stable

### ISSUE THREAD

**Issue by jeanp413** [EclipseFdn/open-vsx.org#1151]
Again same as https://github.com/EclipseFdn/open-vsx.org/issues/1141

![image](https://user-images.githubusercontent.com/25115070/181381762-b0947a30-8557-4bb1-8b51-71a90d516679.png)

cc @eclipsewebmaster Could someone start an incident on Eclipse side?

**Comment by akosyakov** [comment]
@eclipsewebmaster @mbarbero Could you please have a look into it? It breaks our development cycles and affects customers.

**Comment by fredg02** [comment]
=> https://www.eclipsestatus.io/incidents/d62bsgwg0vj2

**Comment by fredg02** [comment]
Probably related to https://github.com/eclipse/openvsx/issues/501

**Comment by fredg02** [comment]
openvsx is responsive again.
