### ISSUE TITLE
Remove obsolete versions

### ISSUE THREAD

**Issue by h-cwc** [EclipseFdn/open-vsx.org#1159]
[https://open-vsx.org/extension/hc/wallace-corporation](https://open-vsx.org/extension/hc/wallace-corporation)
Hi, I would like to remove all previous versions aside from the latest version (0.2.3). Previous versions are obsolete and don't exclude node modules from the .vscodeignore file, making the file size too big.

**Comment by kineticsquid** [comment]
@eclipsewebmaster Could check the logs, would have been about 00:30 GMT on Monday, Aug 8. I tried to remove these versions and after spinning a while I received a network error. Happened a couple of times. Thanks

**Comment by kineticsquid** [comment]
Weird, I checked today and all versions save 0.2.3 have been removed. I'm wondering if my request was eventually processed despite the error message.
