### ISSUE TITLE
Claiming namespace weaveworks

### ISSUE THREAD

**Issue by kingdonb** [EclipseFdn/open-vsx.org#1161]
Hello, I have published GitOps Tools and I am the maintainer at [weaveworks/vscode-gitops-tools](/weaveworks/vscode-gitops-tools)

You can find our extension here:
* https://marketplace.visualstudio.com/items?itemName=Weaveworks.vscode-gitops-tools
* https://open-vsx.org/extension/weaveworks/vscode-gitops-tools

I have added the extension in the Open-VSX marketplace as of this morning, and I'd like to resolve the big mustardy warning about verified publishers 👍 
<img width="619" alt="Screen Shot 2022-08-04 at 9 40 29 AM" src="https://user-images.githubusercontent.com/3286998/182861827-8dca7c25-95aa-4759-a76b-4c11d5f50db6.png">

Can I be given ownership of this namespace please? I've reviewed the docs at [here](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) and if I have understood correctly, opening an issue is the only step. (Thanks!)

**Comment by kineticsquid** [comment]
@kingdonb, thanks for your contribution!
