### ISSUE TITLE
Claiming namespace `filiptronicek`

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#1163]
Hello hello! 

figured after advising so many devs to verify their namespace on https://open-vsx.org, I should get my own one verified 😆.

I publish the `Open in Gitpod` extension from https://github.com/filiptronicek/open-in-gitpod to the [Microsoft Marketplace](https://marketplace.visualstudio.com/items?itemName=filiptronicek.open-in-gitpod) and [Open VSX](https://open-vsx.org/extension/filiptronicek/open-in-gitpod).

**Comment by kineticsquid** [comment]
Thanks @filiptronicek, glad to have you!
