### ISSUE TITLE
Claiming namespace ost-fh

### ISSUE THREAD

**Issue by misto** [EclipseFdn/open-vsx.org#1166]
Hi, I've just released a new extension to both the VS Marketplace and the Open VSX Registry:

https://marketplace.visualstudio.com/items?itemName=ost-fh.visual-oo-debugger
https://open-vsx.org/extension/ost-fh/visual-oo-debugger

It would be great to get rid of that yellow warning :-) Cheers, Mirko

**Comment by kineticsquid** [comment]
Granted @misto !
