### ISSUE TITLE
Claiming namespace avast-threatlabs-yara

### ISSUE THREAD

**Issue by MatejKastak** [EclipseFdn/open-vsx.org#1171]
Hi :wave:, I have just created a new namespace `avast-threatlabs-yara` dedicated to publishing extensions related to our [open-source projects](https://github.com/avast).

> Briefly explain what makes you a legitimate owner of the namespace mentioned in the issue title.
- I created that namespace and there are no other packages published from the past (appart from the one that I published)
- I am contributor and a part of the Avast open-source Github organization https://github.com/avast
- We are in the process of open-sourcing new [YARA](https://github.com/virusTotal/yara) related [project](https://github.com/avast/yls/tree/master/editors/vscode) which will be published in this namespace
- [X] Please ensure that you have logged in to https://open-vsx.org at least once, otherwise we cannot process your request.

**Comment by kineticsquid** [comment]
@MatejKastak Thanks for your contribution!
