### ISSUE TITLE
Claiming namespace NomicFoundation

### ISSUE THREAD

**Issue by kanej** [EclipseFdn/open-vsx.org#1173]
I am a programmer at the [Nomic Foundation](https://nomic.foundation/) and work on the [Hardhat for Visual Studio Code](https://github.com/NomicFoundation/hardhat-vscode) extension.

As evidence you can check [my contribution history to the extension](https://github.com/NomicFoundation/hardhat-vscode/graphs/contributors) and my current membership of the [Nomic Foundation github organization](https://github.com/orgs/NomicFoundation/people).

Nomic Foundation publishes the [Hardhat for Visual Studio Code](https://github.com/NomicFoundation/hardhat-vscode) extension to the [Microsoft marketplace](https://marketplace.visualstudio.com/items?itemName=NomicFoundation.hardhat-solidity) under the `NomicFoundation` publisher, and we want to do the same for open-vsx.

Microsoft Marketplace: https://marketplace.visualstudio.com/items?itemName=NomicFoundation.hardhat-solidity
Nomic Foundation Organization: https://github.com/orgs/NomicFoundation/people
Hardhat for Visual Studio Code repo: https://github.com/NomicFoundation/hardhat-vscode

* [x] Please ensure that you have logged in to https://open-vsx.org at least once

**Comment by kineticsquid** [comment]
@kanej Thanks, good to have you!
