### ISSUE TITLE
Unpublish request for Axway.vscode-titanium

### ISSUE THREAD

**Issue by ewanharris** [EclipseFdn/open-vsx.org#1174]
The [Axway.vscode-titanium](https://open-vsx.org/extension/Axway/vscode-titanium) has been replaced by a new extension after the handover of the Titanium project to the community. This extension has been removed from the VS Code Marketplace and we would also like to remove it from open-vsx.

Once removed we will then publish the new extension

**Comment by kineticsquid** [comment]
@ewanharris Just to confirm, you want me to remove this entirely, all 11 versions, 0.9.0 - 0.14.0?

**Comment by ewanharris** [comment]
@kineticsquid yes please. The extension will then be republished under a new name/namespace

**Comment by ewanharris** [comment]
Thank you!
