### ISSUE TITLE
Claiming namespace TiDev

### ISSUE THREAD

**Issue by ewanharris** [EclipseFdn/open-vsx.org#1175]
Hi, I'm a maintainer on [vscode-titanium](https://github.com/tidev/vscode-titanium) which has now been transferred into [TiDev](https://github.com/tidev) ownership. We would like to claim the TiDev namespace on open-vsx.

Thanks!

**Comment by kineticsquid** [comment]
@ewanharris Granted!

**Comment by ewanharris** [comment]
Thanks again!
