### ISSUE TITLE
Claiming namespace [chrisbibby]

### ISSUE THREAD

**Issue by ChrisBibby** [EclipseFdn/open-vsx.org#1177]
The namespace I'm using is my actual name.  

I currently use the namespace on the VSCode Marketplace - links below to my Github account and an extension I've published

https://github.com/ChrisBibby
https://marketplace.visualstudio.com/items?itemName=chrisbibby.hide-node-modules

**Comment by kineticsquid** [comment]
@ChrisBibby You're good to go!
