### ISSUE TITLE
Claiming namespace `wgsl-analyzer`

### ISSUE THREAD

**Issue by jakobhellermann** [EclipseFdn/open-vsx.org#1178]
I maintain the vscode extension [wgsl-analyzer](https://marketplace.visualstudio.com/items?itemName=wgsl-analyzer.wgsl-analyzer) which I have published under the `wgsl-analyzer` namespace there.
The extension is inspired by `rust-analyzer` and provides language support for the WGSL shading language.

Recently people suggested also publishing the extension in the open-vsx marketplace, so that it can be used with `VSCodium` as well https://github.com/wgsl-analyzer/wgsl-analyzer/issues/28, so I'd like to have the same namespace available for publishing the extension.

**Comment by kineticsquid** [comment]
@jakobhellermann You are now the proud owner of `wgsl-analyzer`!
