### ISSUE TITLE
Claiming namespace NicolasVuillamy

### ISSUE THREAD

**Issue by nvuillam** [EclipseFdn/open-vsx.org#1180]
My name is Nicolas Vuillamy and I claim the namespace NicolasVuillamy :)

I used it to publish [VsCode Groovy Lint](https://open-vsx.org/extension/NicolasVuillamy/vscode-groovy-lint) on OpenVSX after users requested it

Thanks & best regards :)

**Comment by kineticsquid** [comment]
@nvuillam Thanks for your contribution!
