### ISSUE TITLE
Claiming namespace MateuszDrewniak

### ISSUE THREAD

**Issue by Verseth** [EclipseFdn/open-vsx.org#1181]
I'm the author of extensions like [Ruby Test Runner](https://gitlab.com/mateuszdrewniak/ruby-test-runner) and I would like to claim this namespace in OpenVSX to publish my extensions to this registry.

**Comment by filiptronicek** [comment]
Linking an issue in the repo for publishing: [#2](https://gitlab.com/mateuszdrewniak/ruby-test-runner/-/issues/2).

**Comment by kineticsquid** [comment]
@Verseth Granted!
