### ISSUE TITLE
Claiming namespace Catppuccin

### ISSUE THREAD

**Issue by nekowinston** [EclipseFdn/open-vsx.org#1185]
Hi there 👋 
I'm one of the three main maintainers for @catppuccin, and I'd like to update our Open VSX release as well.

Refs:
- Open VSX request: https://github.com/catppuccin/vscode/issues/35
- VSCode Marketplace: https://github.com/catppuccin/vscode/issues/32

**Comment by kineticsquid** [comment]
@nekowinston It looks like this namespace is currently owned by `VictorTennekes`. If you'll document their approval for you to also be an owner in this issue, I can add you.

**Comment by VictorTennekes** [comment]
@kineticsquid all clear to add @nekowinston as an owner 😄

**Comment by kineticsquid** [comment]
@VictorTennekes Thanks. @nekowinston You're good to go. Good to have you all!
