### ISSUE TITLE
Claiming namespace chalet-org

### ISSUE THREAD

**Issue by rewrking** [EclipseFdn/open-vsx.org#1194]
Hello! I'm the maintainer of a new application called [Chalet](https://github.com/chalet-org). I'd like to claim ownership of the `chalet-org` namespace in order to publish a VSCode extension to the VSCodium extension marketplace. I've created a user on open-vsx.org, an access token, and called `ovsx create-namespace chalet-org` already.

Extension: https://github.com/chalet-org/vscode-chalet

**Comment by kineticsquid** [comment]
Thanks @rewrking, glad to have you!
