### ISSUE TITLE
The fields in the More Info panel return invalid date

### ISSUE THREAD

**Issue by rainbyte** [EclipseFdn/open-vsx.org#1198]
## Description

In the Website it can be seen the current version of an extension, publication date and fields.

In vscode extension details the dates are shown as invalid:

![image](https://user-images.githubusercontent.com/749068/186270430-afef977f-d621-4f93-8ae8-8b78b52d9dba.png)

There is a PR in openvsx repo which implemented a fix: https://github.com/eclipse/openvsx/pull/434

## Steps to reproduce

1. Open vscode
2. Click on **Extensions** icon on the left
3. Select any extension from the list
4. Look into the **More Info** panel
5. Dates are `Invalid Date` :scream: 

## Expected result

- Website endpoints should return valid dates
- Dates can be shown in the editor extension details

**Comment by kineticsquid** [comment]
@rainbyte I was also able to reproduce this.  At the risk of asking an unanswerable question, do you recall the last time you observed this working?

**Comment by rainbyte** [comment]
> @rainbyte I was also able to reproduce this. @amvanbaren is the PR above in the deployment queue?

I don't know if it was working before. I think it has been like this since I started using Code-OSS build on Arch Linux (I was using emacs before)

**Comment by amvanbaren** [comment]
@kineticsquid Yes, the deployment that is about to be released contains a fix for this issue. It was adressed in PR https://github.com/eclipse/openvsx/pull/434

**Comment by rainbyte** [comment]
Hello @amvanbaren , any update about this? I'm still seeing "invalid date" in my editor :(

**Comment by amvanbaren** [comment]
Hi @rainbyte, you can follow helpdesk issues [#1698](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1698) or [#1483](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1483) for updates.

**Comment by kineticsquid** [comment]
This appears to be fixed now. @rainbyte?

**Comment by kineticsquid** [comment]
@rainbyte ^^^^

**Comment by rainbyte** [comment]
It seems to be working now. Thanks!
