### ISSUE TITLE
Claiming namespace ShishirSingh

### ISSUE THREAD

**Issue by shi2rsingh** [EclipseFdn/open-vsx.org#1200]
I am the developer who wrote the code of this extension and I myself published this to the VSX Marketplace. 

I want ownership of this namespace. Kindly verify the same or comment in case of any queries.

Here are some reference
VSX Market Place:  https://open-vsx.org/extension/ShishirSingh/easy-react-snippet
MS Marketplace:  https://marketplace.visualstudio.com/items?itemName=ShishirSingh.easy-react-snippet ( Verified)
GitHub repo: https://github.com/shi2rsingh/easy-react-snippet
My Website: https://www.shishirsingh.com/

**Comment by kineticsquid** [comment]
@shi2rsingh Thanks for your contribution!

**Comment by shi2rsingh** [comment]
@kineticsquid Thank You
