### ISSUE TITLE
Problem with two different publications of the same extension

### ISSUE THREAD

**Issue by alesanchezr** [EclipseFdn/open-vsx.org#1201]
Hello! I have a problem with two versions of the same extension that are published on the openvsx marketplace:
![two versions of learnpack](https://user-images.githubusercontent.com/426452/187007112-f3c8a763-de29-4279-97c1-c37e898509f7.gif)

I would like to keep only `learn-pack` and remove `learnpack`

**Comment by kineticsquid** [comment]
This is puzzling. When I examine the `learnpack` namespace, I see this:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/681707/187212812-879b1e29-890b-40a6-bd5c-b3bf334056d5.png">

But when I attempt to access the `LearnPack` extension in that namespace from the admin panel, I see this:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/681707/187213035-6a42a06a-ab5b-4312-861e-e967584e7265.png">

Same thing happens with `learn-pack`. @amvanbaren @eclipsewebmaster, am I missing something?

**Comment by amvanbaren** [comment]
The extension name is `learnpack-vscode`
https://open-vsx.org/api/learnpack

The webui shows the extension display name. 
Maybe we can add a tooltip or code block to show the extension name?
Or allow searching by extension display name in the admin panel?

**Comment by kineticsquid** [comment]
@amvanbaren thanks for the pointer. What you suggest could be helpful, but not necessary right now. I can use a url of the form 'https://open-vsx.org/api/{namespace}' to get the names of the extensions.

**Comment by kineticsquid** [comment]
@alesanchezr, I just removed `0.0.1` - `0.0.7` of `learnpack.learnpack-vscode`.

**Comment by kineticsquid** [comment]
@amvanbaren Is there a way to remove a namespace? Assuming there is, @alesanchezr do you want me to remove the `learnpack` namespace?

**Comment by kineticsquid** [comment]
@amvanbaren ^^^^

**Comment by kineticsquid** [comment]
@amvanbaren Thoughts on this?

**Comment by amvanbaren** [comment]
There's a OrphanNamespaceMigration. It cleans up namespaces without extensions.
https://github.com/eclipse/openvsx/blob/8bf1d23af572aebe2321f304ea605ceb6b8f0923/server/src/main/java/org/eclipse/openvsx/migration/OrphanNamespaceMigration.java#L44-L47

**Comment by kineticsquid** [comment]
Does it run automatically?  `learnpack` namespace is there with no extensions.

**Comment by amvanbaren** [comment]
It runs on server startup. An orphaned namespace is a namespace without any members.
https://github.com/eclipse/openvsx/blob/8bf1d23af572aebe2321f304ea605ceb6b8f0923/server/src/main/java/org/eclipse/openvsx/repositories/NamespaceRepository.java#L25-L26

I don't know 100% if this is possible, but you might be able to delete all namespace members in the admin panel.

**Comment by kineticsquid** [comment]
I did, I just deleted the two members listed. Now there are none.

**Comment by amvanbaren** [comment]
learnpack has been deleted: https://open-vsx.org/api/learnpack

**Comment by kineticsquid** [comment]
Thanks @amvanbaren!
