### ISSUE TITLE
Claiming namespace google

### ISSUE THREAD

**Issue by ogiekako** [EclipseFdn/open-vsx.org#1205]
I'm a maintainer of CrOS IDE VSCode extension, as can be seen by the commit history in that repo.
Repository: https://chromium.git.corp.google.com/chromiumos/chromite/+/refs/heads/main/ide_tooling/cros-ide/
History: https://chromium.git.corp.google.com/chromiumos/chromite/+log/refs/heads/main/ide_tooling/cros-ide
The extension is developed by a team in Google, and has the name "google.cros-ide".

**Comment by kineticsquid** [comment]
@ogiekako Granted! Good to have you!
