### ISSUE TITLE
OpenVSX is down Comment

### ISSUE THREAD

**Issue by mustard-mh** [EclipseFdn/open-vsx.org#1210]
Looks like https://open-vsx.org is down at the time of this issue. @mbarbero @eclipsewebmaster
Could you check please and update https://www.eclipsestatus.io/ accordingly? Thank you!

![image](https://user-images.githubusercontent.com/20944364/187845697-9da8cd0a-8063-4e6f-934f-20dab65582b2.png)

**Comment by benz0li** [comment]
Maybe not down, but incredibly slowly.

**Comment by akosyakov** [comment]
We observed both slowness and elevated error rates:
<img width="873" alt="Screenshot 2022-09-01 at 08 30 55" src="https://user-images.githubusercontent.com/3082655/187847180-7e33c3b5-fe86-4372-986f-342ab2341bd4.png">
<img width="925" alt="Screenshot 2022-09-01 at 08 30 44" src="https://user-images.githubusercontent.com/3082655/187847183-452bdca8-158e-4e92-a52f-db0c10534910.png">

**Comment by fredg02** [comment]
Incident has been created: https://www.eclipsestatus.io/incidents/xhzx390y4wx9

**Comment by benz0li** [comment]
Performance is much better by now.

**Comment by fredg02** [comment]
The pod count has been increased from 2 to 4.

**Comment by filiptronicek** [comment]
@fredg02 could you update here 🙏? I think this can be closed.
