### ISSUE TITLE
Claiming namespace posit

### ISSUE THREAD

**Issue by jcheng5** [EclipseFdn/open-vsx.org#1215]
Hi, I work for a company that has been known as [RStudio](https://www.rstudio.com) and is in the middle of rebranding to [Posit](https://posit.co). I have an extension that I'd like to publish, it's located at this repo: https://github.com/rstudio/pyshiny-vscode

Thanks!

**Comment by kineticsquid** [comment]
@jcheng5 Thanks for your contribution!
