### ISSUE TITLE
Claiming namespace fernandoescolar

### ISSUE THREAD

**Issue by fernandoescolar** [EclipseFdn/open-vsx.org#1217]
I'm trying to publish my extension (vscode-solution-explorer) in open vsx and I can't:
- I can't create the namespace "fernandoescolar" because it already exists
- I can't publish because I have insufficient access rights

related: https://github.com/fernandoescolar/vscode-solution-explorer/issues/132

**Comment by kineticsquid** [comment]
@fernandoescolar Thanks, granted!
