### ISSUE TITLE
Claiming namespace claui

### ISSUE THREAD

**Issue by claui** [EclipseFdn/open-vsx.org#1221]
Dear Open VSX Registry team,

I’d like to claim the `claui` namespace because that’s my GitHub username.
Besides, I also have the same publisher ID at Microsoft’s Visual Studio marketplace.

Thanks and kind regards!  
Claudia

**Comment by kineticsquid** [comment]
@claui Thanks, good to have you!

**Comment by claui** [comment]
Warning banners have re-appeared in all my extensions ([example](https://open-vsx.org/extension/claui/packaging)).

![image](https://user-images.githubusercontent.com/1239874/211093251-e3d649b8-f397-424b-872a-23db00a116f5.png)

@kineticsquid What do I need to do for these warnings to go away?

**Comment by kineticsquid** [comment]
@claui I re-opened this because while I marked your namespace request as granted, you are still not showing up as owner. Probably a mistake on my end. You should be good now as owner. Would you confirm and then I'll close this? Thanks and sorry for the churn.

**Comment by claui** [comment]
Thank you so much @kineticsquid, works like a charm now!
