### ISSUE TITLE
Claiming namespace ArmantGoldswain

### ISSUE THREAD

**Issue by ArmantG** [EclipseFdn/open-vsx.org#1222]
This is my Full name and surname and can be verified using Github: 
https://github.com/ArmantG/ArmantG/blob/cfa6eef3b9d72d77808733a52bb8e8e2196b0af7/README.md

I also have this extension published here:
https://marketplace.visualstudio.com/items?itemName=ArmantGoldswain.seesharp-theme

**Comment by kineticsquid** [comment]
@ArmantG Thanks, good to have your contribution!
