### ISSUE TITLE
Claiming namespace [Discloud]

### ISSUE THREAD

**Issue by pedroricardo** [EclipseFdn/open-vsx.org#1224]
I would like to request ownership of the Discloud namespace.
I created an extension for my hosting company and I would like to publish it on your page.

and for you to have full control over the extension I'm claiming the name space

my company websites https://discloudbot.com/

the same extension is already in the vscode store https://marketplace.visualstudio.com/items?itemName=discloud.discloud

**Comment by kineticsquid** [comment]
@pedroricardo Good to have you!
