### ISSUE TITLE
Claiming namespace apjanke

### ISSUE THREAD

**Issue by apjanke** [EclipseFdn/open-vsx.org#1225]
I would like to claim the Open VSX namespace "apjanke".

I use the handle "apjanke" for publishing software and as a public handle in various places. "apjanke" is my username at [GitHub](https://github.com/apjanke), Eclipse Foundation (accounts.eclipse.org), [Twitter](https://twitter.com/apjanke), and so on. I own the domain [apjanke.net](https://apjanke.net) and use it as my main personal presence on the web. It is also the publisher name I use on the Visual Studio Code Marketplace (e.g., for my [Octave Hacking VS Code extension](https://marketplace.visualstudio.com/items?itemName=apjanke.octave-hacking) which I wouldlike to also publish on Open VSX).

I was able to create the namespace apjanke on Open VSX earlier today.

**Comment by kineticsquid** [comment]
Thanks @apjanke!
