### ISSUE TITLE
Claiming namespace root16

### ISSUE THREAD

**Issue by plohm12** [EclipseFdn/open-vsx.org#1227]
Hello, I'd like to claim ownership of the root16 namespace on Open VSX. I'm an employee of Root16 and contributing member to [their github](https://github.com/Root16). Thank you!

**Comment by plohm12** [comment]
[This PR](https://github.com/Root16/bamboo/pull/46) allows Root16 to publish releases of our Bamboo extension to [Open VSX](https://open-vsx.org/extension/root16/bamboo-pa-vscode) as well as [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=root16.bamboo-pa-vscode)

**Comment by kineticsquid** [comment]
Thanks @plohm12 , granted!
