### ISSUE TITLE
Claiming namespace dongfg

### ISSUE THREAD

**Issue by dongfg** [EclipseFdn/open-vsx.org#1228]
> Extension on open-vsx
https://open-vsx.org/extension/dongfg/vscode-beancount-formatter

> Extension on visualstudio marketplace
https://marketplace.visualstudio.com/items?itemName=dongfg.vscode-beancount-formatter

> Source code repo
https://github.com/dongfg/vscode-beancount-formatter

**Comment by kineticsquid** [comment]
@dongfg Good to have you!
