### ISSUE TITLE
Claiming namespace lkrms

### ISSUE THREAD

**Issue by lkrms** [EclipseFdn/open-vsx.org#1232]
1. My GitHub identity is lkrms :)
2. I own the domain lkrms.org (and also lkr.ms)
3. I have a [verified `lkrms.*` VSCode extension](https://marketplace.visualstudio.com/items?itemName=lkrms.inifmt) in the Visual Studio Marketplace.

Hopefully that's enough :)

Thank you!

**Comment by kineticsquid** [comment]
Good to have you @lkrms!
