### ISSUE TITLE
Claiming namespace trallard

### ISSUE THREAD

**Issue by trallard** [EclipseFdn/open-vsx.org#1239]
I created this namespace to match my GitHub username https://github.com/trallard which also happens to be a shortened version of my own name (Tania Allard) and I usually use this for all open-source-related tasks.

I am also the maintainer and publisher of the VSCode extension pitaya smoothie under the trallard namespace in OSVX https://marketplace.visualstudio.com/items?itemName=trallard.pitaya-smoothie

**Comment by kineticsquid** [comment]
@trallard thanks for your contribution, sounds tasty!
