### ISSUE TITLE
website: improve information from search result 

### ISSUE THREAD

**Issue by vince-fugnitto** [EclipseFdn/open-vsx.org#1240]
**Description**

The search result for https://open-vsx.org is not very informative for newcomers, and would be better to provide details on what the site is about (no mention of extensions, vscode, open-source):

![Screen Shot 2022-09-21 at 2 39 17 PM](https://user-images.githubusercontent.com/40359487/191584574-8f6b78cd-712a-4c99-bbe8-7ea94a15d380.png)

**Additional Information**
- [Google - No Page Information](https://support.google.com/webmasters/answer/7489871?hl=en)

**Comment by chrisguindon** [comment]
@kineticsquid I wound't replace the google meta tags but I would simply add the new one that you have in your comment.

**Comment by chrisguindon** [comment]
@kineticsquid I missed that you said you were going to submit a PR. 

I already made one: https://github.com/EclipseFdn/open-vsx.org/pull/1256

Feel free to close it and if you were planning to make more changes.

**Comment by kineticsquid** [comment]
Thanks @chrisguindon, I approved and merged the PR

**Comment by kineticsquid** [comment]
@vince-fugnitto It will be in the next deploy after this one that's currently underway: https://github.com/EclipseFdn/open-vsx.org/issues/1293.

**Comment by kineticsquid** [comment]
I can see the meta data updates after this recent deploy, but the search results remain unchanged. Is there a mechanism to tell the bots to update?

**Comment by chrisguindon** [comment]
@kineticsquid Looks like there is an issue with the robots.txt file:
https://open-vsx.org/robots.txt

> Disallow: /

This is stopping the site from being indexed. 

![Screenshot 2022-11-01 085225](https://user-images.githubusercontent.com/893942/199236498-7e9a6c40-81b3-40d2-a810-985212dcdd23.png)

**Comment by chrisguindon** [comment]
I have access and it reports that the page is blocked by our robots.txt file. Here's an updated screenshot where the tools says that the page is blocked. This is true for all pages on the site not just the homepage.

![Screenshot 2022-11-01 113835](https://user-images.githubusercontent.com/893942/199274181-eabb4d11-5100-41b4-914f-0651b4c1350d.png)

**Comment by kineticsquid** [comment]
@chrisguindon Right, sorry, my point was that if this line, `Disallow: /` is blocking pages on open-vsx.org from being crawled, why is the same line in `eclipse.org/robots.txt` not having the same effect?

**Comment by chrisguindon** [comment]
> @chrisguindon Right, sorry, my point was that if this line, `Disallow: /` is blocking pages on open-vsx.org from being crawled, why is the same line in `eclipse.org/robots.txt` not having the same effect?

I was wondering the same thing and did a bit of research this morning and found the explanation:

> The instructions (entries) in robots.txt always consist of two parts. In the first part, you define which robots (user-agents) the following instruction apply for. The second part contains the instruction (disallow or allow). "user-agent: Google-Bot" and the instruction "disallow: /clients/" mean that Google bot is not allowed to search the directory /clients/.

If we look at https://www.eclipse.org/robots.txt we quickly notice that we have 2 blocks. The first one instructs all user-agent to disallow the forums and a few other sections such as search and download.php. The second block instructs a few different user-agents such as  but not limited to QuepasaCreep, TurnitinBot to not index the full site (Disallow: /).


Now, if we look at https://open-vsx.org/robots.txt, we notice that we only have 1 disallow instructions which includes User-agent: *  and the full-list of crawler. They are not separated into 2 blocks of instructions like the one on eclipse.org.

**Comment by chrisguindon** [comment]
I did some testing with a different tool: https://technicalseo.com/tools/robots-txt/

That site reports that `Crawl-delay: 2` rule is ignored by googlebots. Maybe that's the reason why the robots.txt is not working as we expect. The instruction in the first block is ignored so it's putting all the user-agent in the same group.

**Comment by kineticsquid** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/681707/200075406-2f158272-dabb-4f93-8060-6757af7b08c2.png">

**Comment by chrisguindon** [comment]
![Screenshot 2022-11-07 080820](https://user-images.githubusercontent.com/893942/200318392-31acc91f-310c-49f2-8642-4e39d347188f.png)

Now with some extensions, I think we can close this issue. However, I would recommend that the application is upgraded to include a different description per page.

As you can see in my screenshot, the same description "Open VSX is an Eclipse open-source project and alternative to ...
" is used for each page and that's not ideal.

**Comment by chrisguindon** [comment]
For those following this thread, the indexing issue was addressed here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2190

**Comment by kineticsquid** [comment]
@chrisguindon Good observation. You mean, e.g. with this page https://open-vsx.org/extension/ms-toolsai/jupyter, we'd generate different text for the meta tags (presumably based on the plug-in information):
```
<meta name="description" content="Open VSX is an Eclipse open-source project and alternative to the Visual Studio Marketplace. It is deployed by the Eclipse Foundation at open-vsx.org.">
```

**Comment by chrisguindon** [comment]
> @chrisguindon Good observation. You mean, e.g. with this page https://open-vsx.org/extension/ms-toolsai/jupyter, we'd generate different text for the meta tags (presumably based on the plug-in information):

+1

**Comment by amvanbaren** [comment]
Google is starting to show the extension description (Prisma, Astro):
![open-vsx_meta](https://user-images.githubusercontent.com/14129099/222666778-d8fbbd98-0378-42db-bedc-a284bf8fa15c.png)

Server side webui rendering (https://github.com/eclipse/openvsx/issues/8) can still be beneficial to rank higher in search results because it improves the page indexing speed.
![astro-search-results](https://user-images.githubusercontent.com/14129099/222669663-9a509fc8-a44e-4f12-abea-8c064226b5ca.png)

**Comment by chrisguindon** [comment]
This is awesome @amvanbaren. I am sure this is going to help users find the open-vsx website!

**Comment by chrisguindon** [comment]
+1

**Comment by kineticsquid** [comment]
Ditto to @chrisguindon's comments, this is really nice work!
