### ISSUE TITLE
Claiming namespace abhatt-rh

### ISSUE THREAD

**Issue by abhatt-rh** [EclipseFdn/open-vsx.org#1242]
This namespace is associated with my GitHub account and I am it's owner.

**Comment by kineticsquid** [comment]
@abhatt-rh What namespace?

**Comment by abhatt-rh** [comment]
> @abhatt-rh What namespace?

Sorry about that - `abhatt-rh` namespace

**Comment by kineticsquid** [comment]
@abhatt-rh No worries, granted!
