### ISSUE TITLE
Claiming namespace hugo-vrijswijk

### ISSUE THREAD

**Issue by hugo-vrijswijk** [EclipseFdn/open-vsx.org#1247]
Hi, I would like to cross-publish my VS Code plugin to open-vsx. The plugin is https://marketplace.visualstudio.com/items?itemName=hugo-vrijswijk.vscode-lit-xml under the publisher name hugo-vrijswijk. I would like to claim the same namespace in open-vsx. The namespace is the same as my username.

**Comment by kineticsquid** [comment]
@hugo-vrijswijk Good to have you!
