### ISSUE TITLE
Claiming namespace [dotenv]

### ISSUE THREAD

**Issue by motdotla** [EclipseFdn/open-vsx.org#1250]
Hello 👋 Open-VSX,

Wonderful open service you are providing here.

I would like to claim the namespace dotenv.

I'm the creator of https://github.com/motdotla/dotenv and https://github.com/dotenv-org/dotenv-vscode

I've claimed the namespace on Microsoft's extension marketplace: https://marketplace.visualstudio.com/items?itemName=dotenv.dotenv-vscode

It would be great to claim it here as well. Thank you!

Then we plan to publish the extension to your open marketplace immediately following that.

**Comment by kineticsquid** [comment]
@motdotla And it's yours, welcome!

**Comment by motdotla** [comment]
Thank you!

**Comment by motdotla** [comment]
Hi @kineticsquid I am trying to publish to open-vsx but receiving a 500 error on login. Could someone on your team fix up?

https://github.com/eclipse/openvsx/issues/532

This occurred after attempting to agree to the agreement on open-vsx. I already finished submitting the agreement at eclipse.org.

**Comment by kineticsquid** [comment]
@motdotla We had a bit of a hiccup last night that you may have experienced. Things are stable now. Can you try again?
