### ISSUE TITLE
OpenVSX is down

### ISSUE THREAD

**Issue by AlexTugarev** [EclipseFdn/open-vsx.org#1252]
Looks like https://open-vsx.org is down at the time of this issue. Search for extension doesn't work.

cc. @mbarbero @eclipsewebmaster
Could you check please and update https://www.eclipsestatus.io/ accordingly? Thank you!

**Comment by fredg02** [comment]
https://open-vsx.org works again after a restart and increasing the number of production pods to 4.

**Comment by AlexTugarev** [comment]
@fredg02, thanks for taking action swiftly! 
🙏🏻

**Comment by kineticsquid** [comment]
Do we have an issue to track the root cause?

**Comment by ArthurSens** [comment]
Hey 👋 -- Just letting you know that since around 50mins ago we're seeing errors again and it is still on going.

**Comment by ArthurSens** [comment]
Friendly pinging @mbarbero @eclipsewebmaster just to make sure you know 🙂

**Comment by fredg02** [comment]
Pods have been restarted.

**Comment by ArthurSens** [comment]
Hey 👋 -- Just letting you know that since around 10 mins ago we started seeing failures again 😬

**Comment by fredg02** [comment]
Closing.
