### ISSUE TITLE
System down on open-vsx.org

### ISSUE THREAD

**Issue by h3knix** [EclipseFdn/open-vsx.org#1258]
503 errors for searches and "Application is not available" going on with  https://open-vsx.org/

it looks like others are having similar issues as well and reporting them on the other repo
https://github.com/eclipse/openvsx/issues/539

**Comment by h3knix** [comment]
additionally https://www.eclipsestatus.io/ reports no issues/green for open-vsx.org (even though it has been down for multiple hours now)

![Screen Shot 2022-09-29 at 6 07 04 PM](https://user-images.githubusercontent.com/18606366/193162962-0efbd23f-5500-4458-bbd7-6b715faeca0d.png)

**Comment by jeanp413** [comment]
cc @eclipsewebmaster

**Comment by inkinworld** [comment]
it's still down now.

**Comment by amvanbaren** [comment]
You can follow helpdesk issue [#2017](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2017) for updates.

**Comment by heurtematte** [comment]
Service up!

**Comment by akosyakov** [comment]
@heurtematte it seems to be down again.

**Comment by svenefftinge** [comment]
It is still down

**Comment by fredg02** [comment]
Pods were restarted yesterday.
