### ISSUE TITLE
Removing Extension `gitduck.code-streaming`

### ISSUE THREAD

**Issue by kineticsquid** [EclipseFdn/open-vsx.org#1266]
The repo link for extension https://open-vsx.org/extension/gitduck/code-streaming is no longer valid, also resulting in no license for the extension. This is a violation of the publisher's agreement. I am removing the extension, all versions, but leaving the namespace.

**Comment by kineticsquid** [comment]
Confirmed all versions of the extension are removed.
@waynebeaton @mbarbero FYI

**Comment by waynebeaton** [comment]
Will you communicate this with the reporter, or do you want me to?

**Comment by kineticsquid** [comment]
I think it makes sense for you to since you had the initial dialog with the reporter.

**Comment by waynebeaton** [comment]
Done.
