### ISSUE TITLE
Claiming namespace danbmky

### ISSUE THREAD

**Issue by danBamikiya** [EclipseFdn/open-vsx.org#1267]
Hello, I created a open-vsx.org account to publish [Agoric Extension](https://github.com/danBamikiya/agoric-vscode-extension) so that Gitpod users can be able to use it too. I created the namespace `danbmky` which is the same as my vscode marketplace publishing account: [danbmky](https://marketplace.visualstudio.com/publishers/danbmky).
I'll like to claim ownership to that namespace on open-vsx.org: `danbmky`
Here is the extension repo: https://github.com/danBamikiya/agoric-vscode-extension
The extension on vscode marketplace (currently at 40 installs): https://marketplace.visualstudio.com/items?itemName=danbmky.agoric-vscode

**Comment by kineticsquid** [comment]
@danBamikiya Glad to have you!

**Comment by danBamikiya** [comment]
Thank you! @kineticsquid I just tried to install it on Gitpod for the first time after pushing to open-vsx.org, is this error from the registry or Gitpod specific?
![image](https://user-images.githubusercontent.com/58262528/194110533-97ae2e4e-b67d-42ac-aa3a-ddbbfda19541.png)
