### ISSUE TITLE
OpenVSX is down

### ISSUE THREAD

**Issue by utam0k** [EclipseFdn/open-vsx.org#1270]
Looks like https://open-vsx.org is down at the time of this issue. @mbarbero @eclipsewebmaster
Could you check please and update https://www.eclipsestatus.io/ accordingly? Thank you!

When I tried to open https://open-vsx.org and got the following message.
```
Request failed: GET https://open-vsx.org/api/-/search?size=10&sortBy=relevance&sortOrder=desc (Bad Gateway)
```

**Comment by fredg02** [comment]
Server has been restarted and https://open-vsx.org is working again.

**Comment by fireflystorm** [comment]
It is down once again...
Can you restart it?

**Comment by fredg02** [comment]
Pods have been restarted.

**Comment by utam0k** [comment]
@fredg02 Thanks for your handling :bow:

**Comment by oorzc** [comment]
> 
It is down once again...
Can you restart it?
It is down once again...
Can you restart it?
It is down once again...
Can you restart it?

**Comment by fredg02** [comment]
It's up again.

**Comment by VAISHAKH-GK** [comment]
Looks like its down again
