### ISSUE TITLE
Claiming namespace openpatch

### ISSUE THREAD

**Issue by mikebarkmin** [EclipseFdn/open-vsx.org#1273]
Hi. I am the creator of OpenPatch (https://github.com/openpatch). I am owing the GitHub organisation OpenPatch, the domain [openpatch.org](https://openpatch.org), and the publisher id [openpatch](https://marketplace.visualstudio.com/items?itemName=openpatch.hyperbook-studio) on the visualstudio marketplace.

**Comment by kineticsquid** [comment]
Granted @mikebarkmin!
