### ISSUE TITLE
OpenVSX is down again

### ISSUE THREAD

**Issue by utam0k** [EclipseFdn/open-vsx.org#1274]
Looks like https://open-vsx.org is down at the time of this issue. @mbarbero @eclipsewebmaster
Could you check please and update https://www.eclipsestatus.io/ accordingly? Thank you!

```
Request failed: GET https://open-vsx.org/user (Bad Gateway)
```

**Comment by oorzc** [comment]
I'm speechless and down again

**Comment by fredg02** [comment]
Duplicate of #1270.
