### ISSUE TITLE
Claiming namespace "osohq"

### ISSUE THREAD

**Issue by vrama628** [EclipseFdn/open-vsx.org#1284]
Hi, I would like to claim ownership of the namespace "osohq" on behalf of [Oso](https://www.osohq.com/). I would like for us to begin publishing our VSCode extension ([seen here on the VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=osohq.oso)). To verify the affiliation you can see that I am a contributor to the GitHub repository linked in our VSCode Marketplace listing.

**Comment by kineticsquid** [comment]
And it's yours!
