### ISSUE TITLE
OpenVSX is down

### ISSUE THREAD

**Issue by Siddhant-K-code** [EclipseFdn/open-vsx.org#1296]
Looks like https://open-vsx.org/ is down at the time of this issue. @mbarbero @eclipsewebmaster

Could you check please (restart the deployment) and update [Status Page](https://www.eclipsestatus.io/) accordingly? Thank you!

**Comment by mbarbero** [comment]
It looks like the recent rate limiter that has been deployed is being triggered here. Our monitoring indicates error 503 rather than 502. Also, given the behavior of the homepage, i'm wondering if the app is not self ddos'ing. The homepage indicates an error with changing message:

```
https://open-vsx.org/api/-/search?offset=10&size=10&sortBy=relevance&sortOrder=desc
https://open-vsx.org/api/-/search?offset=20&size=10&sortBy=relevance&sortOrder=desc
https://open-vsx.org/api/-/search?offset=30&size=10&sortBy=relevance&sortOrder=desc
https://open-vsx.org/api/-/search?offset=40&size=10&sortBy=relevance&sortOrder=desc
https://open-vsx.org/api/-/search?offset=50&size=10&sortBy=relevance&sortOrder=desc
...
https://open-vsx.org/api/-/search?offset=3710&size=10&sortBy=relevance&sortOrder=desc
...
```

I'll gather some logs and restart the deployment.

/cc @amvanbaren.

**Comment by kishaningithub** [comment]
vscodium is unable to fetch extensions due to 503 error

## Screenshot
<img width="291" alt="Screenshot 2022-10-14 at 12 29 50 PM" src="https://user-images.githubusercontent.com/763760/195782930-82178a41-7188-4131-b6c9-7e729569b14c.png">

**Comment by mbarbero** [comment]
fixed.

/close

**Comment by mbarbero** [comment]
FWIW, here is what I found in DB logs:

```
2022-10-14 00:11:25.787 EDT [4108452] ERROR:  deadlock detected
2022-10-14 00:11:25.787 EDT [4108452] DETAIL:  Process 4108452 waits for ShareLock on transaction 7405526; blocked by process 4109128.
	Process 4109128 waits for ShareLock on transaction 7405512; blocked by process 4108452.
	Process 4108452: update extension set active=$1, average_rating=$2, download_count=$3, last_updated_date=$4, name=$5, namespace_id=$6, public_id=$7, published_date=$8 where id=$9
	Process 4109128: update extension set active=$1, average_rating=$2, download_count=$3, last_updated_date=$4, name=$5, namespace_id=$6, public_id=$7, published_date=$8 where id=$9
2022-10-14 00:11:25.787 EDT [4108452] HINT:  See server log for query details.
2022-10-14 00:11:25.787 EDT [4108452] CONTEXT:  while updating tuple (11,22) in relation "extension"
2022-10-14 00:11:25.787 EDT [4108452] STATEMENT:  update extension set active=$1, average_rating=$2, download_count=$3, last_updated_date=$4, name=$5, namespace_id=$6, public_id=$7, published_date=$8 where id=$9
```

**Comment by mbarbero** [comment]
> Could you check please (restart the deployment) and update [Status Page](https://www.eclipsestatus.io/) accordingly? Thank you

BTW, we have a new status page dedicated to open-vsx.org: https://status.open-vsx.org
