### ISSUE TITLE
Claiming namespace monosans

### ISSUE THREAD

**Issue by monosans** [EclipseFdn/open-vsx.org#1299]
Hi.

I created an open-vsx.org account to publish [djLint extension](https://github.com/monosans/djlint-vscode) ([VS Marketplace](https://marketplace.visualstudio.com/items?itemName=monosans.djlint)).
I created a namespace `monosans` which is the same as [my VS Marketplace publishing account](https://marketplace.visualstudio.com/publishers/monosans).

**Comment by kineticsquid** [comment]
@monosans Thanks, we need more penguins!
