### ISSUE TITLE
Claiming namespace carlosorozcojimenez

### ISSUE THREAD

**Issue by CarlosOrozco88** [EclipseFdn/open-vsx.org#1309]
Hello Open-VSX!

I am the owner of this extension: 
- https://marketplace.visualstudio.com/items?itemName=carlosorozcojimenez.ui5-tools
- https://github.com/CarlosOrozco88/ui5-tools

I have already published the extension:
- https://open-vsx.org/extension/carlosorozcojimenez/ui5-tools

Thanks!

**Comment by kineticsquid** [comment]
@CarlosOrozco88 Thanks for your contribution!
