### ISSUE TITLE
Claiming namespace mrorz

### ISSUE THREAD

**Issue by MrOrz** [EclipseFdn/open-vsx.org#1310]
I am the owner of repository https://github.com/mrorz/vscode-gettext , previously [published to open-vsx](https://open-vsx.org/extension/mrorz/language-gettext) via https://github.com/open-vsx/publish-extensions/pull/406 . 

As I am now [setting up Github actions](https://github.com/MrOrz/vscode-gettext/pull/27) that co-publish to both open-vsx and VS marketplace, I would like to claim the namespace `mrorz` on open-vsx.

**Comment by kineticsquid** [comment]
@MrOrz Thanks for your contribution!
