### ISSUE TITLE
`open-vsx` is down

### ISSUE THREAD

**Issue by vince-fugnitto** [EclipseFdn/open-vsx.org#1313]
#### Issue

The [registry](https://open-vsx.org/) is down, and the [status page](https://status.open-vsx.org/) is reporting a false positive that "all services are online".

```
Request failed: GET https://open-vsx.org/user (Bad Gateway)
```

I've noticed lately that `open-vsx` is down quite often (which directly affects consumers), is there something we can do to improve the situation? Is it an issue related to metrics not reporting the proper information or in a timely manner?

**Comment by vince-fugnitto** [comment]
It is down again:

![image](https://user-images.githubusercontent.com/40359487/197005690-e0c34ee3-a061-4537-bfe7-5617619e5235.png)

It's happening quite often lately.

**Comment by mbarbero** [comment]
Service has been restored (issue is deadlock in the code https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2104#note_1028562)

**Comment by mbarbero** [comment]
see also https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2091
