### ISSUE TITLE
Claiming namespace HiroSystems

### ISSUE THREAD

**Issue by hugocaillard** [EclipseFdn/open-vsx.org#1314]
I'm a member of the [github.com/HiroSystems](https://github.com/HiroSystems) organization, developing this extensions: [https://open-vsx.org/extension/hirosystems/clarity-lsp](https://open-vsx.org/extension/hirosystems/clarity-lsp).

I'd like to claim the ownership of this namespace so that we can publish updates.

Can there be multiple owners?
What's the best to handle namespaces ownership as a company?

**Comment by kineticsquid** [comment]
@hugocaillard good to have you!
