### ISSUE TITLE
Claiming namespace StevenConaway

### ISSUE THREAD

**Issue by SConaway** [EclipseFdn/open-vsx.org#1315]
I want to claim this namespace (StevenConaway) because I have just created it to publish into. I am the owner of the GitHub namespace/account SConaway and use StevenConaway on VSCode Marketplace.

**Comment by kineticsquid** [comment]
Good to have you @SConaway!

**Comment by SConaway** [comment]
Not sure if it's related, but I know am unable to access my extensions or account page...
