### ISSUE TITLE
Claiming namespace onnovalkering

### ISSUE THREAD

**Issue by onnovalkering** [EclipseFdn/open-vsx.org#1316]
I want to claim the 'onnovalkering' namespace. 

It's my own name, GitHub username, and I've published on the VS marketplace under the same namespace.

https://github.com/onnovalkering/vscode-singularity
https://marketplace.visualstudio.com/items?itemName=onnovalkering.vscode-singularity
https://open-vsx.org/extension/onnovalkering/vscode-singularity

**Comment by kineticsquid** [comment]
Thanks for your contribution @onnovalkering!
