### ISSUE TITLE
Failed to install `Spring Boot Dashboard` extension

### ISSUE THREAD

**Issue by zWingz** [EclipseFdn/open-vsx.org#1323]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/13031838/197167972-ec8babd4-2db3-4da3-9c42-cf0a10a6416c.png">

**Comment by kineticsquid** [comment]
@zWingz Is this still an issue for you? I just tried this with VS Codium 1.68.0 and was able to install Spring Boot Dashboard 0.7.1.

**Comment by zWingz** [comment]
I think it is a bug for vscode 
When install `Spring boot dashboard`, It will install the dependencies.
But I have installed all the dependencies, It still in `installling` status.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/13031838/197445647-816aa937-5720-4e13-8cbe-a89af71c84ca.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/13031838/197445631-4e171bc8-dcf2-44c8-a3a9-c7f06668427a.png">

After reload the page, it change to `installed`

<img width="344" alt="image" src="https://user-images.githubusercontent.com/13031838/197445699-04f6e903-2d76-4d80-9970-ec845f4e3710.png">
