### ISSUE TITLE
Claiming namespace auiworks

### ISSUE THREAD

**Issue by alisonatwork** [EclipseFdn/open-vsx.org#1366]
[amVim](https://github.com/aioutecism/amVim-for-VSCode) is an alternative Vim-style plugin for VS Code. It was created in 2015 by @aioutecism and was actively maintained by him until 2018, after which he stepped back and allowed community members to maintain the project (including reviewing and merging pull requests).

Releasing to the Visual Studio marketplace has always been done by him, up to and including the current version 1.34.0, released May 2021. We agreed from the date forward that I would manage the publishing of future releases to the VS marketplace because due to his work he is not able to respond quickly to Github activity. Since that date there have been no new features released, so no requirement to publish anything, but I plan to release 1.35.0 next week with some long-awaited functionality, and thought it would be good to publish to OpenVSX at the same time (another long-requested feature: https://github.com/aioutecism/amVim-for-VSCode/issues/278).

I just pushed 1.34.0 to OpenVSX at https://open-vsx.org/extension/auiworks/amvim

I hope to be able to claim the namespace ownership ahead of the 1.35.0 release so that our OpenVSX users can migrate from the existing fork (https://open-vsx.org/extension/9j/amvim) to the latest version.

Please let me know if you need any more information or evidence.

**Comment by kineticsquid** [comment]
@alisonatwork Good to have you!
