### ISSUE TITLE
Unpublish request for 9j.amvim

### ISSUE THREAD

**Issue by 9j** [EclipseFdn/open-vsx.org#1367]
Hi, The original author(@alisonatwork) directly [publishes the extension](https://github.com/aioutecism/amVim-for-VSCode/issues/278#issuecomment-1296119478) on open vsx and maintains it.
So, 9j.amvim is no longer maintained.

Please unpublish 9j.amvim.
Thanks

**Comment by alisonatwork** [comment]
If there is some way to deprecate the repo or provide a redirect to the canonical repo so people don't need to uninstall and reinstall, that would be great too. Right now the version I published in `auiworks` namespace is a lower version number than the one in `9j` namespace, which is a pre-release, but I can cut a an arbitrary 1.34.2 or something if it would make it easier for users to upgrade. I'll be releasing 1.35.0 with more functionality hopefully sometime next week.

**Comment by kineticsquid** [comment]
@9j I can certainly remove all versions of this extension
<img width="519" alt="image" src="https://user-images.githubusercontent.com/681707/198898936-5b36f006-ea65-47cb-a23b-d22c311e0999.png">

Before I do, @amvanbaren @spoenemann, is there a more elegant approach?

**Comment by spoenemann** [comment]
No, I think it's ok to remove it.
