### ISSUE TITLE
Claiming namespace curlconverter

### ISSUE THREAD

**Issue by verhovsky** [EclipseFdn/open-vsx.org#1368]
You can see that I am a contributor on

https://github.com/curlconverter/curlconverter-vscode

which is published on VS Code as

https://marketplace.visualstudio.com/items?itemName=curlconverter.curlconverter

and also links to that repo.

**Comment by verhovsky** [comment]
Also, I published my extension .vsix file a few minutes ago, it told me `🚀  Published curlconverter.curlconverter v0.0.3` but I don't see anything at
https://open-vsx.org/extension/curlconverter/curlconverter
or in the search.

Did something go wrong? If you just have some approval process for newly published extensions, could you add that to 
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by kineticsquid** [comment]
@verhovsky Glad to have your contribution!
