### ISSUE TITLE
Claiming namespace PierreBelmondo

### ISSUE THREAD

**Issue by PierreBelmondo** [EclipseFdn/open-vsx.org#1374]
Hi,

I published this extension on the Visual Studio Market Place:

- [https://github.com/PierreBelmondo/vscode-wipeout](https://github.com/PierreBelmondo/vscode-wipeout)
- [https://marketplace.visualstudio.com/items?itemName=PierreBelmondo.wipeout](https://marketplace.visualstudio.com/items?itemName=PierreBelmondo.wipeout)

Please create a namespace for me on Open VSX.

Best regards,

**Comment by kineticsquid** [comment]
@PierreBelmondo And it's yours!
