### ISSUE TITLE
Claiming namespace [freeo]

### ISSUE THREAD

**Issue by freeo** [EclipseFdn/open-vsx.org#1376]
I own "freeo" on these accounts:
- github.com/freeo
- open-vsx.org
- accounts.eclipse.org/users/freeo
- https://marketplace.visualstudio.com/publishers/freeo

This makes me the owner for all relevant places in terms of publishing extensions.

Hope this is enough?!

**Comment by kineticsquid** [comment]
Thanks @freeo, good to have you!
