### ISSUE TITLE
Claiming namespace [google-cloud-spanner-ecosystem]

### ISSUE THREAD

**Issue by olavloite** [EclipseFdn/open-vsx.org#1377]
* I'm the publisher of https://marketplace.visualstudio.com/items?itemName=google-cloud-spanner-ecosystem.google-cloud-spanner-driver, which uses this namespace
* I'm one of the maintainers of the https://github.com/cloudspannerecosystem organization

**Comment by kineticsquid** [comment]
@olavloite Thanks for your contribution!
