### ISSUE TITLE
Claiming namespace [wso2]

### ISSUE THREAD

**Issue by kaviththiranga** [EclipseFdn/open-vsx.org#1381]
I am from the team who develop [VS Code extension](https://marketplace.visualstudio.com/items?itemName=WSO2.ballerina) for [Ballerina Language ](https://ballerina.io/)created by [WSO2](https://wso2.com/).

We have received a request to publish the Ballerina VS Code extension to Open VSX via https://github.com/wso2/ballerina-plugin-vscode/issues/196.

Furthermore, we have been using Code Server to host VS Code on browser for [Choreo](https://wso2.com/choreo/). There , we manually install vsix during docker build ATM. But after publishing to Open VSX, we can get rid of that. 

We have published[ current stable version of the plugin](https://open-vsx.org/extension/wso2/ballerina) to Open VSX manually ATM. But we are working on to improve our release pipelines to automatically publish every release to Open VSX. 

Hence, I am requesting to make me the owner of this namespace and then I can add other bot users from pipelines to automate this properly.

Thank you.

**Comment by kineticsquid** [comment]
@kaviththiranga Great to have you!

**Comment by kaviththiranga** [comment]
Thank you @kineticsquid for the quick response.
