### ISSUE TITLE
Open VSX is down with 502 (Bad Gateway)

### ISSUE THREAD

**Issue by kittaakos** [EclipseFdn/open-vsx.org#1388]
Hi there,

Open VSX is down again. Same as #1322

```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
```

<img width="752" alt="Screen Shot 2022-11-03 at 15 58 54" src="https://user-images.githubusercontent.com/1405703/199756182-f6aca27c-48af-4a1f-9e1e-d44d20b78fa3.png">

I checked https://www.eclipsestatus.io/, and it says all is fine, but it does not show Open VSX. Is this the correct status page to check for Open VSX status? Is this the proper issue tracker to report service problems? If not, which channel to use? I do not want to spam your issue tracker. Thank you!

**Comment by fredg02** [comment]
The issue has been fixed.

The correct status page is: https://status.open-vsx.org/

Please report service problems here (after checking that there is no open bug for it already):
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new?issue[title]=Issue%20with%20open-vsx.org
