### ISSUE TITLE
OpenVSX is down

### ISSUE THREAD

**Issue by kylos101** [EclipseFdn/open-vsx.org#1389]
Looks like https://open-vsx.org is down at the time of this issue. @mbarbero @eclipsewebmaster
Could you check please and update https://status.open-vsx.org/ accordingly? Thank you!

When browsing to it, it returns:

502 Bad Gateway
nginx

**Comment by kylos101** [comment]
It's better now, looks like it was returning 502s from 14:15 to 14:37 UTC

**Comment by fredg02** [comment]
Quoting from an internal chat:
> Denis  [4:03 PM]
I just killed a couple of DELETE queries that were blocking the entire site
