### ISSUE TITLE
Claiming namespace `tiffnix`

### ISSUE THREAD

**Issue by tiffany352** [EclipseFdn/open-vsx.org#1394]
I'm looking to publish my VS code theme ([tiffcolors](https://github.com/tiffany352/tiffcolors)) to open-vsx. I'm using the publisher `tiffnix` as it's the same one I used for the Microsoft marketplace, and because I own https://tiffnix.com (various ways to verify this, easiest is to visit it and see that it links back to my github account).

**Comment by kineticsquid** [comment]
@tiffany352 Thanks for your contribution!
