### ISSUE TITLE
Remove extensions from the registry

### ISSUE THREAD

**Issue by robertohuertasm** [EclipseFdn/open-vsx.org#1396]
Hi, I'd like to ask for the removal of:

- robertohuertasm/vscode-open
- robertohuertasm/vscode-open-url

I tried to publish `robertohuertasm/vscode-open` but unfortunately the Microsoft marketplace doesn't allow to use duplicate names (another extension already owns `vscode-open`) so I switched it to `open-vscode` instead. 

Unfortunately, 🤦🏻 I did a mistake and I published with the wrong name (`vscode-open-url`). So there are 3 extensions now in the registry with the same display name.

The valid one should be `open-vscode`.

Thank you very much for your help and apologies for the inconveniences. 🙏🏻

**Comment by kineticsquid** [comment]
Done!
