### ISSUE TITLE
Claiming namespace augustocdias

### ISSUE THREAD

**Issue by augustocdias** [EclipseFdn/open-vsx.org#1400]
I want to publish my extension to open-vsx: https://github.com/augustocdias/vscode-shell-command
https://marketplace.visualstudio.com/items?itemName=augustocdias.tasks-shell-input
https://open-vsx.org/extension/augustocdias/tasks-shell-input

**Comment by kineticsquid** [comment]
Thanks for your contribution @augustocdias!
