### ISSUE TITLE
Claiming namespace ONXGroup

### ISSUE THREAD

**Issue by feamsr00** [EclipseFdn/open-vsx.org#1404]
Hi,
I'm an admin of the org https://github.com/ONXGroup
Please grant ownership of the namespace to the role/bot account that comments below!

**Comment by ONXMaintainer** [comment]
*BOOP*

**Comment by kineticsquid** [comment]
@ONXMaintainer Confirming you want me to grant ownership of namespace `ONXGroup` to publisher `BOOP`? I don't see `BOOP` registered as a publisher.

**Comment by ONXMaintainer** [comment]
Sorry couldn't make an empty comment, so the bot said "boop". Please grant ownership to the "ONXMaintainer" account.

**Comment by kineticsquid** [comment]
Doh... should have seen that :)

Thanks and good to have you!
