### ISSUE TITLE
Claiming namespace [nitrous-cloud]

### ISSUE THREAD

**Issue by scar45** [EclipseFdn/open-vsx.org#1411]
I am requesting to become the legitimate owner of the `nitrous-cloud` namespace on Open VSX, as I have just created it in order to publish my VSCode theme, "[NiTROUS](https://marketplace.visualstudio.com/items?itemName=nitrous-cloud.nitrous-vscode-color-theme
)". `nitrous-cloud` is the same publisher name that I use on VS Marketplace, and under **[Project Details](https://marketplace.visualstudio.com/items?itemName=nitrous-cloud.nitrous-vscode-color-theme)** you can see that the theme package is linked to my GitHub account.

Thank you in advance!

**Comment by kineticsquid** [comment]
Granted @scar45!

**Comment by scar45** [comment]
Yes please @kineticsquid! Pretty sure the next time I upload my extension, it should go into my proper namespace. Appreciate it.

**Comment by kineticsquid** [comment]
@scar45 Done!

**Comment by kineticsquid** [comment]
@scar45 How are you publishing your extension? I forked the repo, changed `package.json` to point to my namespace, and used `npx ovsx publish -p ******` to publish: https://open-vsx.org/?search=kineticsquid&category=&sortBy=relevance&sortOrder=desc. That landed in my namespace.

**Comment by kineticsquid** [comment]
@scar45 OK, I deleted the errant extension in the `undefined` namespace. Still not sure what you were doing wrong :). I tried three different ways of packaging and publishing.
- `npx ovsx publish -p ******`
- `vsce package` then drag and drop the `.vsix` file
- `vsce package` and then selecting the `.vsix` file from the file selector pop up. 

All three seemed to work: 
<img width="826" alt="Screen Shot 2022-11-16 at 12 19 30 PM" src="https://user-images.githubusercontent.com/681707/202249573-bfaf071c-6a2b-4857-abcf-66bbd255068c.png">

That said, there appear to be come caching or CDN issues. E.g. the above is what I see for my namespace from my admin panel. But this is what I see as an end user if I search on my namespace:
<img width="998" alt="Screen Shot 2022-11-16 at 12 19 45 PM" src="https://user-images.githubusercontent.com/681707/202250040-5348dca4-a482-47f0-898e-ce2eacc7dc6f.png">

I also observed this. After publishing `NiTROUS-drag-drop-vsix`. Note the image.
<img width="951" alt="Screen Shot 2022-11-16 at 12 13 10 PM" src="https://user-images.githubusercontent.com/681707/202250172-5b21de1f-6a82-4a3c-bb23-a6d316a55789.png">

After the next publish about two minutes later:
<img width="962" alt="Screen Shot 2022-11-16 at 12 15 52 PM" src="https://user-images.githubusercontent.com/681707/202250591-6c1b2ea9-0471-4642-b742-f7cf481df53e.png">

@amvanbaren @spoenemann Thoughts on this caching question?

**Comment by amvanbaren** [comment]
@scar45 The Web UI tries to automatically create the namespace if it doesn't exist yet. Can you share the vsix package you uploaded?

**Comment by scar45** [comment]
@amvanbaren - Sure, [here is the extension](https://github.com/EclipseFdn/open-vsx.org/files/10033810/nitrous-vscode-color-theme-1.0.0.vsix.zip) (renamed to .zip). In the original first version I was trying to upload (v1.0.0, attached), when looking at the `package.json` included in that `.vsix`, I was missing the `publisher` key. This is my first time building a theme extension, and I am now thinking this is why it got placed in the `undefined` namespace. I was also unaware that (technically) "publisher" == "namespace".

It worked fine in the VS Marketplace for that first version, presumably because I had already created my namespace/publisher in that system, so the uploaded package defaulted to that, even with the `publisher` key missing. Since that worked well, I uploaded the same package to Open VSX, and that's when this issue arose.

I was unclear on the necessity of having `publisher` defined in `package.json` on that first version, though it's been a good learning experience. My subsequent package uploads to Open VSX have landed in the correct namespace, since `publisher` is properly defined in `package.json`.

**Comment by amvanbaren** [comment]
@scar45 Thanks for providing the extension. Open VSX uses the extension.vsixmanifest file for extension info. The Publisher attribute in extension.vsixmanifest is literally `undefined`. I'll add some error handling to the webui publishing process.

**Comment by scar45** [comment]
I see what you mean @amvanbaren:

`<Identity Language="en-US" Id="nitrous-vscode-color-theme" Version="1.0.0" Publisher="undefined" />
`

I'm glad this oversight from my first package built has helped to make the web UI more robust, eliminating this kind of issue for others in the future. Cheers!

**Comment by kineticsquid** [comment]
@scar45 Thanks for the reminder, I've just removed my test instances of your extension.
