### ISSUE TITLE
Claiming namespace rome

### ISSUE THREAD

**Issue by sebmck** [EclipseFdn/open-vsx.org#1423]
We work on https://github.com/rome/tools and publish a LSP extension to VSCode Marketplace under the `rome` namespace at https://marketplace.visualstudio.com/items?itemName=rome.rome We have recently started publishing to Open VSX at https://open-vsx.org/extension/rome/rome and would like to have our namespace verified.

**Comment by kineticsquid** [comment]
@sebmck Good to have your contribution!
