### ISSUE TITLE
Broken publishing to non-latest versions of `redhat.java`

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#1426]
We tried publishing a `linux-x64` version of the `redhat.java` to `v1.12`, but when published, the version does not appear in the UI or the API. Only way we could see that the version was indeed published was to go to https://open-vsx.org/extension/redhat/java/linux-x64/1.12.0 directly.

**Comment by filiptronicek** [comment]
Querying the VS Code API does show the version though:
```
curl 'https://open-vsx.org/vscode/gallery/extensionquery' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0' -H 'Accept: application/json;api-version=3.0-preview.1' -H 'Accept-Language: en-US,en;q=0.5' -H 'Referer: https://gitpodsampl-springpetcl-ze357m30kov.ws-eu74.gitpod.io/' -H 'X-Market-Client-Id: VSCode 1.73.1' -H 'Content-Type: application/json' -H 'Origin: https://gitpodsampl-springpetcl-ze357m30kov.ws-eu74.gitpod.io' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Sec-GPC: 1' -H 'TE: trailers' --data-raw '{"filters":[{"criteria":[{"filterType":7,"value":"redhat.java"},{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":12,"value":"4096"}],"pageNumber":1,"pageSize":1,"sortBy":0,"sortOrder":0}],"assetTypes":[],"flags":439}' | jq .
```

**Comment by jeanp413** [comment]
@filiptronicek close this as we found it was an issue with our mirror

**Comment by filiptronicek** [comment]
Will do, but it was an issue with Open VSX, not happening on our mirror with the version listings. Looks like it just needed time, because now it is present in the API response: https://open-vsx.org/api/redhat/java/1.12.0

**Comment by jeanp413** [comment]
Ah sorry I got mistaken, but yeah it now shows in the UI :thinking:
