### ISSUE TITLE
Mark latest release of `ms-python.black-formatter` as a pre-release 

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#1427]
I have forgot to mark the extension as a pre-release in the packaging step, and when publishing it just got ignored. This version is `2022.7.13061128`.

I'm not sure if it's possible to mark it as a pre-release easily though, maybe worth just removing, and I'll re-publish it correctly.

**Comment by filiptronicek** [comment]
@kineticsquid could you please remove version `2022.7.13061128` of `ms-python.black-formatter` 🙏?

**Comment by kineticsquid** [comment]
@filiptronicek We good to close this?

**Comment by filiptronicek** [comment]
Let's do it, there's still some things I need to do for the pre-release, but I'll create new issues when necessary for further actions.
