### ISSUE TITLE
Claiming namespace [Mindsmiths]

### ISSUE THREAD

**Issue by mjuraj** [EclipseFdn/open-vsx.org#1429]
Hi,

`Mindsmiths` is the name of the company where I'm [Head of Engineering](https://www.linkedin.com/in/juraj-malenica-29705156/). We're building a [platform](https://docs.mindsmiths.com/) and want to allow developers on Theia to have a nicer user experience by using our plugin.

**Comment by kineticsquid** [comment]
@mjuraj Thanks for your contribution!
