### ISSUE TITLE
Claiming namespace SamHarris

### ISSUE THREAD

**Issue by Arkaedan** [EclipseFdn/open-vsx.org#1430]
My name is Sam Harris. I have published an extension on the Visual Studio Marketplace under the publisher `SamHarris` and would like to publish my extension on Open VSX as well. Thanks!

My extension:
- [Open VSX](https://open-vsx.org/extension/SamHarris/eclipse-epsilon-languages)
- [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=SamHarris.eclipse-epsilon-languages)

**Comment by kineticsquid** [comment]
@Arkaedan Glad to have you!
