### ISSUE TITLE
Claiming namespace epsilon.language-epsilon

### ISSUE THREAD

**Issue by agarciadom** [EclipseFdn/open-vsx.org#1432]
I am one of the Eclipse Epsilon committers, as listed here:

https://projects.eclipse.org/projects/modeling.epsilon/who

I recently renamed this Github account from `bluezio` (from my PhD student days!) to `agarciadom`, and since the username in OpenVSX is based on my Github account, it looks like I don't have ownerships right to it anymore. I cannot see any way to update the information of the Epsilon Languages extension I published 9 months ago:

https://open-vsx.org/extension/epsilon/language-epsilon

Could you please reinstate me as owner of the `epsilon.language-epsilon` namespace? Thanks for your help!

**Comment by kineticsquid** [comment]
@agarciadom Done! Do you want me to remove `bluezio` as an owner?

**Comment by kineticsquid** [comment]
@agarciadom ^^^^

**Comment by agarciadom** [comment]
Yes, please do!
