### ISSUE TITLE
Claiming namespace eccelerators

### ISSUE THREAD

**Issue by denisvasilik** [EclipseFdn/open-vsx.org#1433]
Hi,

I am one of the founders of Eccelerators GmbH. We are specializing in Electronic Design Automation (EDA) tools based on XText, Eclipse, VS Code, Theia and so forth. In order to publish our extensions, we would like to claim the eccelerators namespace.

Best Regards,
Denis Vasilik

**Comment by kineticsquid** [comment]
Thanks @denisvasilik, good to have you!
