### ISSUE TITLE
Claiming namespace DanielGavin

### ISSUE THREAD

**Issue by DanielGavin** [EclipseFdn/open-vsx.org#1435]
I want to claim DanielGavin.

I have published under the same namespace on Visual Studio Marketplace.

Extensions:
[Vs Marketplace]( https://marketplace.visualstudio.com/items?itemName=DanielGavin.ols)
[Open VSX]( https://open-vsx.org/extension/DanielGavin/ols)

Thanks!

**Comment by kineticsquid** [comment]
Thanks for your contribution @DanielGavin!
