### ISSUE TITLE
Claiming namespace huff-langauge

### ISSUE THREAD

**Issue by cheethas** [EclipseFdn/open-vsx.org#1438]
I've been maintaining a vscode extension for an Ethereum macro assembler language called Huff (https://github.com/huff-language/vscode-huff). I have been pushing releases to the vscode marketplace and would like to also start publishing to open-vsx! 
I'm claiming ownership of `huff-language` to do this.

Looking forward to hearing from you!

**Comment by kineticsquid** [comment]
Good to have you @cheethas!

**Comment by cheethas** [comment]
Thank you!!
