### ISSUE TITLE
Claiming namespace ngtystr

### ISSUE THREAD

**Issue by nagata-yoshiteru** [EclipseFdn/open-vsx.org#1439]
this is my repository: 
https://github.com/nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode

and this is the above extention in MS Market Place:
https://marketplace.visualstudio.com/items?itemName=ngtystr.ppm-pgm-viewer-for-vscode

**Comment by kineticsquid** [comment]
Good to have you @nagata-yoshiteru!
