### ISSUE TITLE
Claiming namespace charliermarsh

### ISSUE THREAD

**Issue by charliermarsh** [EclipseFdn/open-vsx.org#1445]
I'm the publisher of the Ruff VS Code extension: https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff.

I'd like to publish it to Open VSX, on [request](https://github.com/charliermarsh/vscode-ruff/issues/29) of one of the users.

**Comment by kineticsquid** [comment]
@charliermarsh Thanks for your contribution!
