### ISSUE TITLE
Claiming namespace 'yozz'

### ISSUE THREAD

**Issue by KekOnTheWorld** [EclipseFdn/open-vsx.org#1446]
Hey,

I am currently working on a fullstack HTTP framework called `YOZZ` written in ZIG. 

The source code can be found here:
https://github.com/KekOnTheWorld/yozz, https://github.com/KekOnTheWorld/yozz/yozz-vscode.

**Comment by kineticsquid** [comment]
@KekOnTheWorld Thanks for your contribution!
