### ISSUE TITLE
Claiming namespace 'jripouteau'

### ISSUE THREAD

**Issue by Julien-R44** [EclipseFdn/open-vsx.org#1448]
Hello! I'm looking for ownership on the namespace 'jripouteau'. jripouteau is just a contraction of my first name + last name. 

I have so far mainly published this extension for Adonis and plan to do so for another one 👍 
https://open-vsx.org/extension/jripouteau/adonis-vscode-extension
https://marketplace.visualstudio.com/items?itemName=jripouteau.adonis-vscode-extension&ssr=false#overview

Thanks a lot !

**Comment by kineticsquid** [comment]
Thanks for your contribution @Julien-R44!
