### ISSUE TITLE
Claiming namespace [Codeium]

### ISSUE THREAD

**Issue by codeium-dev** [EclipseFdn/open-vsx.org#1450]
We are the team behind codeium.com and the Codeium code completion extension that we would like to publish under the Codeium namespace.

**Comment by kineticsquid** [comment]
@codeium-dev Good to have you!

**Comment by codeium-dev** [comment]
@kineticsquid thanks for the welcome! we noticed that we were approved for the "Codium" namespace rather than our product name "Codeium" - could we get approval for the "Codeium" namespace as well? that is what we have published our extension under (https://open-vsx.org/extension/Codeium/codeium). thanks in advance!

**Comment by kineticsquid** [comment]
@codeium-dev, Oof, that's embarrassing! I've added you to `Codeium` as owner. And I've removed you as an owner from `Codium`, unless you also have a need for a more marine oriented namespace.
