### ISSUE TITLE
Claiming namespace [Codeium]

### ISSUE THREAD

**Issue by codeium-dev** [EclipseFdn/open-vsx.org#1454]
@kineticsquid we noticed that we were approved for the "Codium" namespace in #1450 rather than our product name "Codeium" - could we get approval for the "Codeium" namespace as well? that is what we have published our extension under (https://open-vsx.org/extension/Codeium/codeium). 

(we commented on the previous issue but were unable to reopen it, so we opened this new issue as well - sorry if you received multiple messages)

**Comment by kineticsquid** [comment]
Resolved in https://github.com/EclipseFdn/open-vsx.org/issues/1450
