### ISSUE TITLE
Claiming namespace jevko

### ISSUE THREAD

**Issue by djedr** [EclipseFdn/open-vsx.org#1459]
I am the creator of Jevko, a minimal general-purpose syntax -- I intend to publish extensions for this project on open-vsx.org.

I have already published on [the Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=jevko.jevkodata-basic-highlighting).

I am the owner of [https://jevko.org/](https://jevko.org/), [the jevko GitHub organization](https://github.com/jevko), and associated social media accounts.

**Comment by kineticsquid** [comment]
@djedr Thanks for your contribution!

**Comment by djedr** [comment]
Perhaps this takes a while to propagate, but in case it doesn't, I'm just checking in to report that so far I don't see any change on my end:
![Screenshot 2022-12-01 at 18-34-56 Open VSX Registry](https://user-images.githubusercontent.com/8414718/205121700-2b3de81f-d851-4637-a7bd-e8fdef41ee41.png)
![Screenshot 2022-12-01 at 18-34-44 Open VSX Registry](https://user-images.githubusercontent.com/8414718/205121709-5600a3c9-648f-4c47-bd65-2ace2634d6f3.png)
Thanks!

**Comment by kineticsquid** [comment]
Oops, thanks for following up! You should be good now.

**Comment by djedr** [comment]
All good now, thanks again.
Have a good day!
