### ISSUE TITLE
Claiming namespace `sugatoray`

### ISSUE THREAD

**Issue by sugatoray** [EclipseFdn/open-vsx.org#1462]
I am the author of the following two VS Code extensions:

- `sugatoray.jinja-extension-pack` [See [extension@vscode-marketplace](https://marketplace.visualstudio.com/items?itemName=sugatoray.jinja-extension-pack)]
- `sugatoray.vscode-markdown-extension-pack` [See [extension@vscode-marketplace](https://marketplace.visualstudio.com/items?itemName=sugatoray.vscode-markdown-extension-pack)]

Since I own the namespace `sugatoray` on VS Code Marketplace, and am the sole author of the above two extensions, I would like to claim ownership of this namespace on open-vsx.org as well.

**Comment by sugatoray** [comment]
cc: @amvanbaren

**Comment by kineticsquid** [comment]
Thanks @sugatoray, good to have your contributions.
