### ISSUE TITLE
Claiming namespace sketchbuch

### ISSUE THREAD

**Issue by sketchbuch** [EclipseFdn/open-vsx.org#1466]
I want to claim ownership of sketchbuch. I think maybe I created an account a long time ago as one of my extensions is already on your marketplace: https://open-vsx.org/extension/sketchbuch/vsc-packages

I created an account on open vsx using github.

Here are my extensions on the VSCode marktplace

https://marketplace.visualstudio.com/publishers/sketchbuch

And this is my repo for the extension that is already on your marketplace:
https://github.com/sketchbuch/vsc-packages

**Comment by kineticsquid** [comment]
Good to have you @sketchbuch!
