### ISSUE TITLE
Claiming namespace `sgryjp`

### ISSUE THREAD

**Issue by sgryjp** [EclipseFdn/open-vsx.org#1470]
Hi. I want to claim a namespace `sgryjp`.

I am the author of couple of VSCode extensions below and willing to publish them on OpenVSX too:

- [Smart Sort](https://marketplace.visualstudio.com/items?itemName=sgryjp.vscode-stable-sort)
- [Japanese Word Handler](https://marketplace.visualstudio.com/items?itemName=sgryjp.japanese-word-handler)

**Comment by kineticsquid** [comment]
Thanks @sgryjp, good to have you!
