### ISSUE TITLE
Claiming namespace ejgallego

### ISSUE THREAD

**Issue by ejgallego** [EclipseFdn/open-vsx.org#1488]
Dear Open VSX team,

I'd like to claim the namespace `ejgallego` so I can safely publish my [coq-lsp](https://github.com/ejgallego/coq-lsp) extension into the marketplace https://open-vsx.org/extension/ejgallego/coq-lsp

**Comment by kineticsquid** [comment]
Thanks for your contribution @ejgallego!

**Comment by ejgallego** [comment]
Thanks to you for the help!
