### ISSUE TITLE
Claiming namespace rdfox

### ISSUE THREAD

**Issue by DianaMarksOST** [EclipseFdn/open-vsx.org#1495]
I work for Oxford Semantic Technologies (creators of the RDFox graph database, hence the namespace name) and we publish under the "rdfox" namespace on the VSCode Marketplace. We would like to publish our extension ["RDFox Syntax Highlighting"](https://marketplace.visualstudio.com/items?itemName=rdfox.rdfox-rdf) on the Open VSX.

**Comment by kineticsquid** [comment]
@DianaMarksOST thanks for your contribution!
