### ISSUE TITLE
Claiming namespace googlecloudtools

### ISSUE THREAD

**Issue by kschaab** [EclipseFdn/open-vsx.org#1497]
We own the googlecloudtools namespace on the VS Code Marketplace for the Cloud Code extension https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.cloudcode.  I and my team owns the attached repo https://github.com/GoogleCloudPlatform/cloud-code-vscode.  Please let me know if additional information is required to be granted ownership of this namespace.

**Comment by kineticsquid** [comment]
@kschaab great to have your contributions!
