### ISSUE TITLE
Claiming namespace timkmecl

### ISSUE THREAD

**Issue by timkmecl** [EclipseFdn/open-vsx.org#1514]
That's the name of my account for Eclipse and also [github](https://github.com/timkmecl). I am publishing[ this extension](https://github.com/timkmecl/chatgpt-vscode), that has previously been published using the same namespace on [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=timkmecl.chatgpt).

**Comment by kineticsquid** [comment]
Thanks for your contribution @timkmecl!
