### ISSUE TITLE
Claiming namespace CodeQue

### ISSUE THREAD

**Issue by jayu** [EclipseFdn/open-vsx.org#1517]
Hey I've create CodeQue VSCode extension. One of the users asked for publishing at open-vsx.org in [this issue](https://github.com/codeque-co/codeque/issues/2)

To legitimate the ownership you can check that 
- The https://github.com/codeque-co/codeque repo and organisation is owned and managed by my user name @jayu
- I've already [published extension to VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=CodeQue.codeque) and verified my account there using project domain [codeque.co]( https://codeque.co)

I hope it's enough for the legitimisation, cheers!

**Comment by kineticsquid** [comment]
Thanks for your contribution @jayu!
