### ISSUE TITLE
Claiming namespace `tomoyukim`

### ISSUE THREAD

**Issue by tomoyukim** [EclipseFdn/open-vsx.org#1521]
Hi I want to claim a namespace: tomoyukim
I'm the author of VSCode extension: [mermaid-editor](https://marketplace.visualstudio.com/items?itemName=tomoyukim.vscode-mermaid-editor) and I want to publish it to open-vsx.org too.

**Comment by kineticsquid** [comment]
@tomoyukim Always good to have more marine life!
