### ISSUE TITLE
Claiming namespace gencay

### ISSUE THREAD

**Issue by gencay** [EclipseFdn/open-vsx.org#1522]
Hi I want to claim a namespace: gencay
I'm the author of VSCode extension: [gencay/vscode-chatgpt](https://open-vsx.org/extension/gencay/vscode-chatgpt)

**Comment by kineticsquid** [comment]
Good to have you @gencay!

**Comment by gencay** [comment]
> Hi I want to claim a namespace: gencay I'm the author of VSCode extension: [gencay/vscode-chatgpt](https://open-vsx.org/extension/gencay/vscode-chatgpt)

Hi @kineticsquid is there a way to deprecate this extension in favor of another one?

I also mistakenly created a namespace while testing things under my account, but it should really be a namespace for another account. Now I can't seem to find a way to remove the namespace from my account and the new authors of the new extension that this extension will deprecate in favor of, cannot publish their extension (Created this issue since I couldn't find a similar post: https://github.com/eclipse/openvsx/issues/709).

**Comment by kineticsquid** [comment]
@gencay Is it the extension or the namespace? Would renaming `gencay` to something else accomplish what you're looking to do?

**Comment by gencay** [comment]
Hi - here's what I am trying to accomplish, maybe you could help me understand the best way to do it:
- I am the author of gencay.vscode-chatgpt
- I would like to deprecate this extension in favor of genieai.chatgpt-vscode ([See vscode marketplace](https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode))
- The new extension will be owned by another account(genieai-info is their account name) under namespace `genieai`

However, while trying to understand our options, I mistakenly created `genieai` namespace under my account(gencay), which I am unable to remove now and the genieai account owners aren't able to create that namespace on their account since it's unique.

In the ideal scenario for the extension to keep its downloads and ratings:
- Replace `gencay.vscode-chatgpt` with the new `genieai.chatgpt-vscode` and move the ownership to the Genie AI team.

I hope this clarifies my goal, let me know what would be the best course of action

**Comment by kineticsquid** [comment]
@gencay I think I have it. My superpowers include:
- renaming namespaces
- adding and removing namespace members and changing ownership
- unpublishing extension versions (including all versions)

The do not include renaming extensions (mostly because the code doesn't support this). Also, if I remove all extensions and members from a namespace, it'll get deleted in a clean up process.

Unfortunately, there is not a way to rename the namespace and extension and keep the downloads and ratings. 

I'm thinking the path forward is the following:
1. I remove all members and extension versions in `gencay`.
2. That namespace will get cleaned up
3. You/the Genie AI team publish `genieai.chatgpt-vscode`.
4. I add the Genie AI team to the `genieai` namespace and make this ID the owner.

Make sense?

@amvanbaren keep me honest

**Comment by gencay** [comment]
Got it. Being able to remove old versions is a great feature that VS Code doesn't have. I didn't know that. In that case I will figure something out without removing the extension from openvsx marketplace without removing the extension and keeping the history.

May I request the following then:
- I want to keep the gencay.vscode-chatgpt without the old versions. Please remove all versions except for the latest (v3.9.8) from gencay.vscode-chatgpt. I will then update the store with the right features. My personal extension will remain in-tact.
- Let's make the Genie AI team the owners of 'genieai' namespace (It's currently under my personal account - gencay). I will ask them to either reply here or create another issue for verification.
- Genie AI team will publish their own versions under `genieai.chatgpt-vscode` after verification.

Thank you @kineticsquid

**Comment by kineticsquid** [comment]
@gencay Yep. Removed all versions of `gencay.vscode-chatgpt` save `v3.9.8`. In https://github.com/EclipseFdn/open-vsx.org/issues/1713 I have given ownership of `genieai` to `genieai-info`. Note, you are still listed as a contributor to that namespace. Does this cover it?

**Comment by gencay** [comment]
This is great, thanks for your help @kineticsquid!
