### ISSUE TITLE
Claiming namespace [Peterson]

### ISSUE THREAD

**Issue by Joao-Peterson** [EclipseFdn/open-vsx.org#1524]
Hi, i want to claim my namespace `Peterson`, thank you!

So far i have only the following extensions on the registry:
**Open VSX:** `https://open-vsx.org/extension/Peterson/super-figure`
**Github:** `https://github.com/Joao-Peterson/super-figure`

**Comment by kineticsquid** [comment]
@Joao-Peterson Thanks for your contribution!
