### ISSUE TITLE
Claiming namespace Tobias-Faller

### ISSUE THREAD

**Issue by TobiasFaller** [EclipseFdn/open-vsx.org#1529]
This namespace `Tobias-Faller` is used by me on the Microsoft's VS Code marketplace for my VT100 / ANSI terminal highlighting plugin and it would make sense to make the plugin available here under the same namespace and id.
Plugin Link: [https://marketplace.visualstudio.com/items?itemName=Tobias-Faller.vt100-syntax-highlighting](https://marketplace.visualstudio.com/items?itemName=Tobias-Faller.vt100-syntax-highlighting)

**Comment by kineticsquid** [comment]
Granted @TobiasFaller!
