### ISSUE TITLE
Claiming namespace toki and tokilabs

### ISSUE THREAD

**Issue by svallory** [EclipseFdn/open-vsx.org#1533]
Hi! I'm the owner of http://github.com/tokilabs and tokilabs.io and would like to claim, if possible, those 2 namespaces. If not, I prefer `toki` since it's shorter

**Comment by kineticsquid** [comment]
@svallory I've granted you ownership of `toki`. You can publish an extension to just one name space. Given that, do you intend to publish some extensions to one namespace and some to the other, `tokilabs`?

**Comment by svallory** [comment]
Thanks @kineticsquid ! Toki Labs is part of Toki Network and in we usually use just `toki` for namespaces, accounts, etc. But I wanted to prevent someone from grabbing that namespace and impersonating Toki Labs (check https://tokilabs.io). 

That would mean nothing right now, but we have plans to release the disl language as open source and publish several other packages that we think may get some traction.

Is there a way to simply block registration to that namespace? If not, please register it for me and I'll make it a mirror of toki

**Comment by kineticsquid** [comment]
@svallory Just made you owner of `tokilabs` too.
