### ISSUE TITLE
Claiming namespace HackMD

### ISSUE THREAD

**Issue by Yukaii** [EclipseFdn/open-vsx.org#1534]
Hi, I would like to claim the namespace of HackMD. I'm the maintainer of [hackmd-vscode](https://marketplace.visualstudio.com/items?itemName=HackMD.vscode-hackmd) VSCode extension, now the open-vsx equivalent also has been published to https://open-vsx.org/extension/HackMD/vscode-hackmd

**Comment by kineticsquid** [comment]
Granted!
