### ISSUE TITLE
Claiming namespace [scinteco]

### ISSUE THREAD

**Issue by robert-boulanger** [EclipseFdn/open-vsx.org#1536]
We at aimit and [scinteco](https://www.scinteco.com) are developing a series of vscode extensions for our product "improve" which is a huge repository for pharmaceutical R&D processes.
Those extensions run in verified and secured environments and are published only via private instances of open-vsx servers and will never appear in the ms-marketplace.

So I would like to claim **scinteco** as namespace

**Comment by kineticsquid** [comment]
@robert-boulanger Confirming you want the `scinteco` namespace and not `scinteco.com`?

**Comment by kineticsquid** [comment]
Minions unite!
