### ISSUE TITLE
Claiming namespace RiversideSoftware

### ISSUE THREAD

**Issue by gquerret** [EclipseFdn/open-vsx.org#1538]
I'm the owner of Riverside Software, and publisher of this [VSCode extension](https://marketplace.visualstudio.com/items?itemName=RiversideSoftware.openedge-abl-lsp). I'd like to publish to open-vsx.org.
Source code is here: https://github.com/vscode-abl/vscode-abl

**Comment by kineticsquid** [comment]
@gquerret Thanks for your contribution!
