### ISSUE TITLE
Claiming namespace [benmcmorran]

### ISSUE THREAD

**Issue by benmcmorran** [EclipseFdn/open-vsx.org#1545]
I'd like to claim ownership of the `benmcmorran` namespace. You can see that this namespace matches my GitHub username, and that I have published extensions to [the official VS Code marketplace under this name](https://marketplace.visualstudio.com/items?itemName=benmcmorran.vscode-api-explorer).

**Comment by kineticsquid** [comment]
Good to have you @benmcmorran!
