### ISSUE TITLE
Claiming namespace [name] FaybrainH1554@bigfoot.spokane.edu

### ISSUE THREAD

**Issue by LionDeLien** [EclipseFdn/open-vsx.org#1556]

**Comment by kineticsquid** [comment]
@LionDeLien Clarifying that you want namespace `FaybrainH1554@bigfoot.spokane.edu`?

**Comment by kineticsquid** [comment]
@LionDeLien ^^^^

**Comment by LionDeLien** [comment]
hi! stranger, Yes want namespace. Is it that I am moving to slow? I don't want any interference. How are you doing?

**Comment by kineticsquid** [comment]
Hi @LionDeLien I should have checked first. Characters in namespace names are limited to letters, numbers, `-`, `+`, `$` and `~`.  

https://github.com/eclipse/openvsx/blob/90606d30d27c5f2c610932c582e0ef7d2ede0fbd/server/src/main/java/org/eclipse/openvsx/ExtensionValidator.java#L48-L61

Can you recommend a new namespace name?

**Comment by kineticsquid** [comment]
@LionDeLien ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
