### ISSUE TITLE
Unpublish request: `somebody1234.hoverlens`

### ISSUE THREAD

**Issue by somebody1234** [EclipseFdn/open-vsx.org#1560]
[Link](https://open-vsx.org/extension/somebody1234/hoverlens)

It was a stopgap solution while waiting for the author (NonSpicyBurrito) to upload [an official package](https://open-vsx.org/extension/NonSpicyBurrito/hoverlens)

**Comment by kineticsquid** [comment]
Needs https://github.com/eclipse/openvsx/issues/664

**Comment by kineticsquid** [comment]
Done!
