### ISSUE TITLE
Update ElasticSearch to 7.11.0

### ISSUE THREAD

**Issue by amvanbaren** [EclipseFdn/open-vsx.org#1561]
https://github.com/eclipse/openvsx/pull/656 uses a case insensitive term query. This feature was introduced in ElasticSearch 7.10.0. Please update ElasticSearch to 7.11.0 for open-vsx.org and staging.open-vsx.org, so that https://github.com/eclipse/openvsx/pull/656 can be tested and deployed.

**Comment by amvanbaren** [comment]
Opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2571

**Comment by kineticsquid** [comment]
@amvanbaren Can we close this one now?

**Comment by amvanbaren** [comment]
Yes, ElasticSearch 7.11.0 is running in production.
