### ISSUE TITLE
Claiming namespace RavenscroftSoftware

### ISSUE THREAD

**Issue by ravenscroftj** [EclipseFdn/open-vsx.org#1566]
Hi there, I have just initialised and created RavenscroftSoftware namespace over on open-vsx.org. This will allow me to publish my VSCode extension published [here](https://marketplace.visualstudio.com/items?itemName=RavenscroftSoftware.md-hypothesis-sync) and source code [here](https://github.com/ravenscroftj/md-hypothesis-sync) in the open marketplace under the same name.

**Comment by kineticsquid** [comment]
@ravenscroftj Thanks for your contribution!
