### ISSUE TITLE
Claiming namespace psioniq

### ISSUE THREAD

**Issue by davidquinn** [EclipseFdn/open-vsx.org#1567]
I am the author of psioniq fileHeader VSC extension which I have uploaded to Open VSX Registry. The extension is published on VSC Marketplace [here](https://marketplace.visualstudio.com/items?itemName=psioniq.psi-header) and the source is published on GitHub [here](https://github.com/davidquinn/psi-header).

**Comment by kineticsquid** [comment]
@davidquinn Granted!
