### ISSUE TITLE
Request to unpublish `lukashass.volar`

### ISSUE THREAD

**Issue by lukashass** [EclipseFdn/open-vsx.org#1568]
I manually published `lukashass.volar` while the official build was not working.
Since I am no longer publishing updates, I think it is best to remove it.

Link to extension: https://open-vsx.org/extension/lukashass/volar

**Comment by kineticsquid** [comment]
Needs https://github.com/eclipse/openvsx/issues/664

**Comment by kineticsquid** [comment]
Done!
