### ISSUE TITLE
Unpublish request:  jsomsanith.kh-explorer

### ISSUE THREAD

**Issue by jsomsanith** [EclipseFdn/open-vsx.org#1573]
Hello open-vsx team 👋

I would like to unpublish my newly published package `jsomsanith.kh-explorer`.
I published a it just for a test before seeing that we cannot unpublish it ourself 😬. Sorry for that.
This extension doesn't even work.
I'll switch to a custom build of the registry plugin.

Thanks in advance for your help.

**Comment by kineticsquid** [comment]
Needs https://github.com/eclipse/openvsx/issues/664

**Comment by jsomsanith** [comment]
Hi @kineticsquid, I don't see why we need this issue.
I saw that to remove a package we needed a manual step from the open-vsx team.

**Comment by czadikem** [comment]
Yes exactly

**Comment by jsomsanith** [comment]
Oh ok that's perfectly clear now :D 
Thanks for the info @kineticsquid I'll be patient

**Comment by kineticsquid** [comment]
Done!

**Comment by jsomsanith** [comment]
Thank you @kineticsquid
