### ISSUE TITLE
Claiming namespace georgejames

### ISSUE THREAD

**Issue by gjsjohnmurray** [EclipseFdn/open-vsx.org#1583]
I am Senior Product Engineer at George James Software, https://georgejames.com

I have set up the 'georgejames' namespace on Open VSX in order to publish extensions that we already publish on Visual Studio Marketplace under the publisher 'georgejames'. An example extension there is https://marketplace.visualstudio.com/items?itemName=georgejames.objectscript-class-view

**Comment by kineticsquid** [comment]
@gjsjohnmurray Thanks for your contribution!
