### ISSUE TITLE
Claiming namespace EdwinKofler and hyperupcall

### ISSUE THREAD

**Issue by hyperupcall** [EclipseFdn/open-vsx.org#1585]
Hello there! I would like to claim ownership of the namespaces `EdwinKofler` and `hyperupcall`.

The former because [my name](https://edwinkofler.com) is EDWIN KOFLER and I publish under `EdwinKofler` on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/search?term=EdwinKofler&target=VSCode&category=All%20categories&sortBy=Relevance)

The latter because my username is `hyperupcall`, on GitHub, Eclipse (and everywhere else).

Thank you for your consideration,
EDWIN KOFLER

**Comment by kineticsquid** [comment]
@hyperupcall Good to have you!
