### ISSUE TITLE
Claiming namespace [rubberduck]

### ISSUE THREAD

**Issue by lgrammel** [EclipseFdn/open-vsx.org#1590]
Publishing the https://github.com/rubberduck-ai/rubberduck-vscode extension on open vsx. Using the same namespace that I use on the VS Code marketplace ( https://marketplace.visualstudio.com/items?itemName=Rubberduck.rubberduck-vscode ).

**Comment by kineticsquid** [comment]
@lgrammel We can always use more bath toys!
