### ISSUE TITLE
Claiming namespace thebearingedge

### ISSUE THREAD

**Issue by thebearingedge** [EclipseFdn/open-vsx.org#1597]
Hi there, I was asked to publish one of my extensions to open-vsx and finally had time to do it.

The extension's GitHub repository is here:
https://github.com/thebearingedge/vscode-sql-lit

The issue requesting publication to open-vsx is here:
https://github.com/thebearingedge/vscode-sql-lit/issues/6

My Visual Studio Marketplace link is here:
https://marketplace.visualstudio.com/items?itemName=thebearingedge.vscode-sql-lit

The open-vsx page is here:
https://open-vsx.org/extension/thebearingedge/vscode-sql-lit

👏 🚀

**Comment by kineticsquid** [comment]
@thebearingedge Great to have you!
