### ISSUE TITLE
Claiming namespace intersystems

### ISSUE THREAD

**Issue by isc-bsaviano** [EclipseFdn/open-vsx.org#1599]
I am the lead developer of the [InterSystems Language Server](https://marketplace.visualstudio.com/items?itemName=intersystems.language-server) VS Code extension and am a Development Manager at InterSystems.

**Comment by gjsjohnmurray** [comment]
I can vouch for the authenticity of this claim. I am owner of the georgejames namespace and I collaborate with @isc-bsaviano on development of extensions for the InterSystems platforms.

**Comment by kineticsquid** [comment]
@isc-bsaviano Good to have you!

**Comment by isc-bsaviano** [comment]
@kineticsquid Thanks!
