### ISSUE TITLE
Unpublish josegonzalez/UnisonSync extension

### ISSUE THREAD

**Issue by josegonzalez** [EclipseFdn/open-vsx.org#1602]
Per https://github.com/eclipse/openvsx/issues/58#issuecomment-607902879, I'd like to have this extension removed. I named it slightly incorrectly in the package.json and would like to not have duplicate (and eventually outdated) content out there.

**Comment by kineticsquid** [comment]
We need to get a fix first for https://github.com/eclipse/openvsx/issues/664 and then I'll be able to unpublish this.

**Comment by kineticsquid** [comment]
Done!
