### ISSUE TITLE
Unpublish PierreBelmondo.wipeout version 0.10.0

### ISSUE THREAD

**Issue by PierreBelmondo** [EclipseFdn/open-vsx.org#1607]
Hi,

I cannot find a way to unpublish a version.

There was an error when bumping 0.0.9. I published 0.10.0 instead of 0.0.10.

Currently 0.0.10 and 0.0.11 have been (re)published but they are masked by 0.10.0.

Thanks in advance.

**Comment by kineticsquid** [comment]
@PierreBelmondo Hi, we need to fix https://github.com/eclipse/openvsx/issues/664 first and then I can unpublish this extension version.

**Comment by kineticsquid** [comment]
Done!
