### ISSUE TITLE
Claiming namespace raiondesu

### ISSUE THREAD

**Issue by Raiondesu** [EclipseFdn/open-vsx.org#1609]
As evident by my github username and email, I go by `raiondesu`. This includes the Visual Studio Marketplace, where I published [this extension](https://marketplace.visualstudio.com/items?itemName=Raiondesu.qwik-city-link-autocomplete). But when [publishing it to open-vsx](https://open-vsx.org/extension/raiondesu/qwik-city-link-autocomplete), I forgot about creating a namespace before publishing, so now the namespace is already created and is unverified, sadly.

**Comment by kineticsquid** [comment]
@Raiondesu Good to have you!
