### ISSUE TITLE
Claiming namespace 1nVitr0

### ISSUE THREAD

**Issue by 1nVitr0** [EclipseFdn/open-vsx.org#1611]
I have been publishing extension on the Visual Studio Marketplace under the same publisher for several years and use the same name across VS Code, OPenVSX and Github. My published extensions in no particular order are:

- `1nVitr0.blocksort` https://github.com/1nVitr0/plugin-vscode-blocksort
- `1nVitr0.valgrind-task-integration` https://github.com/1nVitr0/plugin-vscode-valgrind-task-integration
-  `1nVitr0.censitive` https://github.com/1nVitr0/plugin-vscode-censitive
- `1nVitr0.theme-coral-reef` https://github.com/1nVitr0/coral-reef-theme-vscode
- `1nVitr0.random-sample` https://github.com/1nVitr0/plugin-vscode-random-sample
- `1nVitr0.daily-timelog` https://github.com/1nVitr0/plugin-vscode-daily-timelog
- `1nVitr0.invert-if` https://github.com/1nVitr0/plugin-vscode-invert-if
- `1nVitr0.invert-if-php` https://github.com/1nVitr0/plugin-vscode-invert-if
- `1nVitr0.snippet-clipboard` https://github.com/1nVitr0/plugin-vscode-snippet-clipboard

I would like to publish some of these extensions on the OpenVSX marketplace as well, as I have had reqests for it in my repositorie's issues.

**Comment by kineticsquid** [comment]
@1nVitr0 Thanks for your contributions!
