### ISSUE TITLE
Claiming namespace usethesource since we own usethesource.io and github.com/usethesource 

### ISSUE THREAD

**Issue by jurgenvinju** [EclipseFdn/open-vsx.org#1613]
* <http://github.com/usethesource> hosts all the code related to the design, implementation, and use of the Rascal metaprogramming language. See also <http://www.usethesource.io> and <http://www.rascal-mpl.org> for more information.
* Rascal can be used to generate plugins for Eclipse, based on the IDE metatooling platform (a former eclipse incubation project), but also VScode extensions from language descriptions and implementations using an "LSP multiplexer". 
* A friendly user asked us to hurry up and publish our vsix on open-vsx.org, so here we are.

Thanks for this opportunity!

**Comment by kineticsquid** [comment]
@jurgenvinju Good to have you!
