### ISSUE TITLE
Claiming namespace [Gydunhn]

### ISSUE THREAD

**Issue by Gydunhn** [EclipseFdn/open-vsx.org#1615]
Hello,

I do not know what type of credentials I need to present, since I am not a native speaker of English, so I could have interpreted part of the documentation differently. Even so, I will leave the links of my profiles on different platforms in case this can serve as validation:

* GitHub: https://github.com/Gydunhn
* Visual Studio MarketPlace: https://marketplace.visualstudio.com/publishers/Gydunhn
* LinkedIn: https://www.linkedin.com/in/javiercamus/

Grateful in advance.

Gydunhn

**Comment by kineticsquid** [comment]
@Gydunhn Thanks for your contribution!

**Comment by kineticsquid** [comment]
Oops, looks like a hiccup at open-vsx.org.

**Comment by kineticsquid** [comment]
@Gydunhn You're good now.
