### ISSUE TITLE
Claiming namespace hocus

### ISSUE THREAD

**Issue by gorbak25** [EclipseFdn/open-vsx.org#1616]
Hi!

I'm the cofounder of [Hocus](https://hocus.dev) which is an quick and simple self-hosted alternative for Gitpod or Github Codespaces. We're planning on publishing our vscode integration soon and we would like to publish it under the Hocus namespace :) I'm also the owner of the [hocus-dev](https://github.com/hocus-dev) organization.

Best Regards,
Grzegorz

**Comment by kineticsquid** [comment]
@gorbak25 Good to have you!
