### ISSUE TITLE
Claiming namespace narumincho

### ISSUE THREAD

**Issue by narumincho** [EclipseFdn/open-vsx.org#1621]
My name is narumincho and I am the publisher of definy ( https://open-vsx.org/extension/narumincho/definy ).

I use the name "narumincho" in the following accounts and others.

- GitHub ( https://github.com/narumincho )
- Home page ( https://narumincho.com/ )
- YouTube ( https://www.youtube.com/@narumincho )
- Minecraft ( https://ja.namemc.com/profile/narumincho.1 )

**Comment by kineticsquid** [comment]
@narumincho Thanks for your contribution!
