### ISSUE TITLE
Claiming namespace xlab-steampunk

### ISSUE THREAD

**Issue by matejart** [EclipseFdn/open-vsx.org#1626]
I'd like to claim ownership of the `xlab-steampunk` domain. I am one of the owners of the xlab-steampunk namescpace/group both at [GitHub](https://github.com/orgs/xlab-steampunk/people) and at [GitLab](https://gitlab.com/groups/xlab-steampunk/-/group_members).

The aim of the new domain is to publish artifacts developed for the [XLAB Steampunk](https://steampunk.si/) brand.

**Comment by kineticsquid** [comment]
@matejart Thanks for your contribution!
