### ISSUE TITLE
Claiming namespace SonatypeCommunity

### ISSUE THREAD

**Issue by brent-spiner** [EclipseFdn/open-vsx.org#164]
Hi there!

I'm working on getting some of the Sonatype VS Code extensions on Open VSX, and I went ahead and created the `SonatypeCommunity` namespace. I work for Sonatype, and I'm actually a bot account (lol), but this would be the rightful owner of the `SonatypeCommunity` namespace. If you need any supporting evidence, etc... let me know. This is being written by: https://github.com/DarthHater , who is the Product Manager of Developer Experience at Sonatype.

I as well created a `sonatype` namespace, but realized a touch late that our publisher field is `SonatypeCommunity`. If we could maintain ownership over the `sonatype` namespace, that would be ideal too. We tend to publish our Open Source Community projects as `SonatypeCommunity`, and `sonatype` for the tools that we tend to provide more exclusive support for!

Cheers!

**Comment by spoenemann** [comment]
Hi @DarthHater, I would prefer assigning a real user here. Once that is done, you can add bot accounts as contributors to your namespaces in https://open-vsx.org/user-settings/namespaces

You need to log in to https://open-vsx.org to have your user account created so I can assign it to the namespaces.

**Comment by brianking** [comment]
More information on namespaces.
https://github.com/eclipse/openvsx/wiki/Namespace-Access

**Comment by DarthHater** [comment]
Hello @spoenemann @brianking , I believe I've got my account created on open-vsx, FIRE AWAY!! Once you've got ownership setup for it I'll add the bot, etc... and get things settled.

**Comment by brianking** [comment]
@DarthHater You are now the namespace owner. Thanks for your contributions.

**Comment by DarthHater** [comment]
Thank you!!!!
