### ISSUE TITLE
Claiming namespace boltex

### ISSUE THREAD

**Issue by boltex** [EclipseFdn/open-vsx.org#1648]
Hi, I'd like to claim the namespace "boltex".

I'm Félix, (github profile: https://github.com/boltex , website: https://boltex.github.io/ ) the writer of LeoInteg and LeoJS, the two "Leo" extensions for vscode/vscodium. I'd like to publish the extensions on this platform and so I followed the instructions to become a publisher on https://open-vsx.org/.

'boltex' is the user name I've got on github, and it's the 'publisher' value of the package.json file in all of the extensions I intend to publish. 

Thanks for allowing me to claim this name.

**Comment by kineticsquid** [comment]
Granted! Nice pic!
