### ISSUE TITLE
Claiming namespace databricks

### ISSUE THREAD

**Issue by fjakobs** [EclipseFdn/open-vsx.org#1653]
I'd like to claim the namespace `databricks` so I'm able to publish the official Databricks extensions also to Open VSX:

https://marketplace.visualstudio.com/items?itemName=databricks.databricks
https://marketplace.visualstudio.com/items?itemName=databricks.sqltools-databricks-driver

You can see that I have created both of these extensions and that I'm still an active contributor to both.
I'm employee of Databricks and acting on Databrick's behalf.

**Comment by kineticsquid** [comment]
@fjakobs Thanks for your contribution!

**Comment by fjakobs** [comment]
Thanks John for approving my request.

Not sure this is the right channel but I'm unable to upload an icon or define social links.

When I try to upload a PNG icon I'm getting a 500 error message.

All of my social links are rejected as invalid URLs:
- https://www.linkedin.com/company/databricks
- https://github.com/databricks
- https://twitter.com/databricks

I was only able to update display name and description.

**Comment by kineticsquid** [comment]
Actually, let's track this in a separate issue, https://github.com/eclipse/openvsx/issues/689.
