### ISSUE TITLE
Claiming namespace qxcode

### ISSUE THREAD

**Issue by ararunaufc** [EclipseFdn/open-vsx.org#1655]
Hello. [I'm a Professor](https://www.quixada.ufc.br/docente/arthur-rodrigues-araruna/) at Federal University of Ceará, Campus of Quixadá. I'm enrolled in an informal project called "QxCode," which gathers teachers of courses requiring programming assignments within its activities. This is a local project on our campus.

This namespace will be used by me and by some colleagues to publish, initially, some extension packs for suggested extensions to help our students enhance their coding experience. The "Qx" part of the name is an allusion to the name of the city ("Quixadá").

We already claimed this same namespace on Microsoft's Marketplace.

**Comment by kineticsquid** [comment]
@ararunaufc Thanks for you contributions. Great to have you and your students!
