### ISSUE TITLE
Claiming namespace tauri-apps & tauri

### ISSUE THREAD

**Issue by Beanow** [EclipseFdn/open-vsx.org#1670]
Hello, I'm a Board Director of the Tauri Programme within the Commons Conservancy
https://tauri.app/
https://github.com/tauri-apps
https://dracc.commonsconservancy.org/0035/

We also currently publish as `tauri-apps` for vscode.
https://github.com/tauri-apps/tauri-vscode
https://marketplace.visualstudio.com/items?itemName=tauri-apps.tauri-vscode

And have a trademark for the Tauri name:
https://trademarks.ipo.gov.uk/ipo-tmcase/page/Results/1/UK00003711842

The namespaces we would like to claim are:
- `tauri-apps`
- `tauri`

The first for consistency with current releases.
The second as we hold the trademark, want to avoid confusion, and consider migrating to this namespace.

**Comment by kineticsquid** [comment]
@Beanow Great to have your contributions, thanks!
