### ISSUE TITLE
Claim namespace ownership and remove certain versions

### ISSUE THREAD

**Issue by maximtrp** [EclipseFdn/open-vsx.org#1682]
Hi! I would like to claim namespace ownership for `maximtrp`.

These links may be useful:
* https://marketplace.visualstudio.com/items?itemName=maximtrp.drone-ci
* https://github.com/maximtrp/droneci-vscode-extension

And please remove versions 1.2.1, 1.2.0, 1.1.0 of the [published extension](https://open-vsx.org/extension/maximtrp/drone-ci).

**Comment by kineticsquid** [comment]
@maximtrp Namespace granted and I removed those three versions of your extension.
