### ISSUE TITLE
Open VSX 502 error

### ISSUE THREAD

**Issue by ml6156** [EclipseFdn/open-vsx.org#1684]
Just installed VS Codium.  Tried searching for extensions and it returns error, "Error while fetching extensions. Server returned 502,"

https://open-vsx.org/ returns "502 Bad Gateway".

Any idea when this will be back up?

Thanks!

**Comment by redtux** [comment]
JFYI, I have tried different mirrors but they all seem to be down or empty:
https://download.eclipse.org/oomph/archive/mirror.php?location=openvsx

So I guess we have no option than to cross fingers and be patient.
(Got used to it after rubygems.org was down some days ago. 😸)

**Comment by ml6156** [comment]
Thanks. I’ll wait. Hopefully it will be available before I get back to it.

**Comment by benz0li** [comment]
@eclipsewebmaster Please start an incident on the Eclipse side.

FYI @amvanbaren

**Comment by amvanbaren** [comment]
Thanks @ml6156 for opening this issue and @benz0li for bringing this to my attention. https://open-vsx.org is back up and running.

**Comment by Xachman** [comment]
It's down again isn't it?

**Comment by amvanbaren** [comment]
Thanks @Xachman! Yes it was. It's up again.

**Comment by ml6156** [comment]
Thank you @Xachman! On Mar 15, 2023, at 9:01 AM, Aart van Baren ***@***.***> wrote:﻿
Thanks @Xachman! Yes it was. It's up again.

**Comment by gflow33** [comment]
I think it is down again

**Comment by amvanbaren** [comment]
@gflow33 Thanks, Iet me check

**Comment by amvanbaren** [comment]
@eclipsewebmaster is working on the issue

**Comment by ZMensRain** [comment]
@amvanbaren  I think it has gone down could you please check, thanks.
