### ISSUE TITLE
Claiming namespace PulkitGangwar

### ISSUE THREAD

**Issue by pulkitgangwar** [EclipseFdn/open-vsx.org#1691]
Hi 
I'd like to become the owner of the namespace PulkitGangwar. I am the creator of the extension [Nextjs Snippets](https://github.com/pulkitgangwar/next.js-snippets) and would like to publish it to [open-vsx.org](https://open-vsx.org/)

**Comment by kineticsquid** [comment]
@pulkitgangwar Good to have you!
