### ISSUE TITLE
Claiming namespace fisheva

### ISSUE THREAD

**Issue by fisheva** [EclipseFdn/open-vsx.org#1703]
I am writing to claim ownership of the fisheva namespace on open-vsx.org.

I intend to use this namespace to publish my Eva Theme plugin on open-vsx.org. As such, I would like to request that ownership of the fisheva namespace so that I can proceed with publishing my plugin under this namespace.

Thanks!

**Comment by kineticsquid** [comment]
@fisheva Thanks for your contribution!
