### ISSUE TITLE
Ability to remove namespace

### ISSUE THREAD

**Issue by amvanbaren** [EclipseFdn/open-vsx.org#1707]
Hi - I mistakenly created a namespace in my account and I don't see an option to remove or rename it now. I can't even update its name anymore. How can I contact you via email to request removal of a namespace from my personal account?

**Comment by kineticsquid** [comment]
@amvanbaren I can see this is resolved with https://github.com/eclipse/openvsx/issues/709. Do you need me to do anything with this issue?
