### ISSUE TITLE
Claiming namespace chris-hayes

### ISSUE THREAD

**Issue by Christopher-Hayes** [EclipseFdn/open-vsx.org#1716]
I am requesting the namespace, `chris-hayes`, being the name as a developer I go by. It's a slightly shorter version of my GitHub username, @christopher-hayes.
`chris-hayes` is the same namespace I go by on the Visual Studio Marketplace: https://marketplace.visualstudio.com/publishers/chris-hayes
I've published one of my extensions to Open VSX (unverified) here: https://open-vsx.org/extension/chris-hayes/chatgpt-reborn

**Comment by kineticsquid** [comment]
@Christopher-Hayes Granted!
