### ISSUE TITLE
Claiming namespace fregante

### ISSUE THREAD

**Issue by fregante** [EclipseFdn/open-vsx.org#1726]
Hello, the namespace is my name, used across all related social media:

- https://github.com/fregante
- https://twitter.com/fregante
- https://marketplace.visualstudio.com/publishers/fregante
- https://open-vsx.org/extension/fregante/ghost-text

Related discussion for the extension I'm publishing:

- https://github.com/fregante/GhostText/issues/235

**Comment by kineticsquid** [comment]
@fregante Thanks for your contribution!
