### ISSUE TITLE
Claiming namespace bradgashler

### ISSUE THREAD

**Issue by bgashler1** [EclipseFdn/open-vsx.org#1752]
I've been publishing under my own name in Microsoft's VS Code Extension Marketplace since 2015. You can see my work on the same marketplace and that my GitHub account is the same one on commits since this time. I request ownership of the namespace of my own proper name on this marketplace also.

Thanks,

Brad Gashler

**Comment by kineticsquid** [comment]
@bgashler1 Thanks for your contributions!
