### ISSUE TITLE
Please update the version of Jupyter extension

### ISSUE THREAD

**Issue by Mr-Spade** [EclipseFdn/open-vsx.org#1755]
After the version of vscode was updated to 1.77, the api has undergone some changes. In order to adapt to these changes, the 2023.3.100 version of the Jupyter extension has also been adjusted and released on the official marketplace.

However, the Jupyter extension on open-vsx.org does not seem to be updated, resulting in some compatibility issues with the jupyter extension after the vscodium that uses open-vsx as the extension repository is updated to version 1.77.

It would be great if the version of jupyter can be updated. Thank you very much for your willingness to build a platform like open-vsx.org, I have benefited a lot from it!

**Comment by kineticsquid** [comment]
@Mr-Spade Not sure I understand your request; I might be missing something. I see `2023.3.100` published here: https://open-vsx.org/extension/ms-toolsai/jupyter.

**Comment by Mr-Spade** [comment]
In fact, version 2023.3.100 of the Jupyter extension has been further updated since then, and does not appear to have changed its name, while the open-vsx.org version is an older version. Details are described [here](https://github.com/open-vsx/publish-extensions/issues/674).

**Comment by filiptronicek** [comment]
Hey there @Mr-Spade, as noted in the issue you linked, the issue is within the repo of Jupyter's extension - we are blocked by https://github.com/microsoft/vscode-jupyter/issues/13260 and because of it cannot compile the extension for ourselves.

**Comment by kineticsquid** [comment]
@filiptronicek Does https://github.com/EclipseFdn/open-vsx.org/issues/1789 resolve this?

**Comment by filiptronicek** [comment]
@kineticsquid ok to close now, the version is updated, although the underlying issue is still not solved, manual intervention resolved it this time.
