### ISSUE TITLE
Claiming namespace [mike-lischke]

### ISSUE THREAD

**Issue by mike-lischke** [EclipseFdn/open-vsx.org#1763]
I want to publish my VS Code extension also on Open VSX, so I'd like to claim the namespace mike-lischke. Thanks.

**Comment by kineticsquid** [comment]
Thanks @mike-lischke, good to have you!

**Comment by mike-lischke** [comment]
Thanks @kineticsquid. I had uploaded my extension before claiming my namespace, so it still shows up as deactivated. Can you please activate or remove it, so I can upload again? Thanks.
