### ISSUE TITLE
Remove `ms-toolsai.jupyter`@`2023.3.100`

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#1789]
tl;dr: this version is broken and the commit published as this version is not the same as Microsoft's-intended, which started making issues - see https://github.com/open-vsx/publish-extensions/issues/674. 

cc @kineticsquid

**Comment by filiptronicek** [comment]
Just as an aside: it would be interesting to explore if we can give me permissions to do this in the future, so I don't have to bug you all the time John 😆.

**Comment by kineticsquid** [comment]
@filiptronicek Version `2023.3.100` removed. Unfortunately, as this is currently an admin task, it needs to be performed by an EF employee or  contractor.

**Comment by filiptronicek** [comment]
Thanks for the removal!

I guess I'll have to get employed by Eclipse then...

**Comment by benz0li** [comment]
> Thanks for the removal!
> 
> I guess I'll have to get employed by Eclipse then...

@filiptronicek The Eclipse Foundation asking to [Help Them Sustain Open-vsx.org!](https://blogs.eclipse.org/post/john-kellerman/help-us-sustain-open-vsxorg) and with [An Emerging Open VSX Working Group!](https://blogs.eclipse.org/post/john-kellerman/emerging-open-vsx-working-group) it should be possible to get you properly involved at Eclipse.

@kineticsquid What's next for the Open VSX Working Group? As already confirmed by email, [b-data](https://github.com/b-data) is willing to support open-vsx.org financially.  
👉 I kindly ask you to publicly inform how the Eclipse Foundation intends to proceed with this.

**Comment by kineticsquid** [comment]
@benz0li We had our first call for interested parties on April 4. Materials and recording on the [openvsx](https://accounts.eclipse.org/mailing-list/openvsx) mailing list. I'll be providing an update there shortly. Bottom line is that we have enough organizations that have verbally agreed to be part of a working group to run open-vsx.org. At this point, we just need to get the signed participation agreements back.

**Comment by benz0li** [comment]
> Materials and recording on the [openvsx](https://accounts.eclipse.org/mailing-list/openvsx) mailing list.

@kineticsquid Whenever I try creating an Eclipse account with username `benz0li` it says `Your account could not be created as requested. Please contact the Eclipse Webmaster.`

The username is highlighted and message `The username must contain only-aplha-numeric characters.` shown below it.

🤷

**Comment by kineticsquid** [comment]
@benz0li certainly looks alpha-numeric to me. And unfortunately you need an eclipse account to create a ticket about your inability to create an eclipse account. Suggest you send an email to webmaster@eclipse.org. Here's contact info: https://www.eclipse.org/org/foundation/contact.php
