### ISSUE TITLE
Claiming namespace pedro-bronsveld

### ISSUE THREAD

**Issue by Pedro-Bronsveld** [EclipseFdn/open-vsx.org#1794]
This namespace is my first and last name which I already use on websites such as GitHub and LinkedIn.
I've published an extension on Open VSX Registry and on VSCode Marketplace under this publisher name, and intend to use it in the future for other extensions released under my name.

Thanks in advance,
Pedro Bronsveld

**Comment by kineticsquid** [comment]
@Pedro-Bronsveld Good to have you!
