### ISSUE TITLE
Claiming namespace CodiumAI (Omri Grossman)

### ISSUE THREAD

**Issue by OmriGM** [EclipseFdn/open-vsx.org#1795]
I want to claim a namespace ownership for being able to deploy CodiumAI's vscode extension (example from vscode marketplace: https://marketplace.visualstudio.com/items?itemName=Codium.codium) and here is our website: codium.ai

**Comment by OmriGM** [comment]
Deployed: https://open-vsx.org/extension/Codium/codium

**Comment by kineticsquid** [comment]
@OmriGM It looks like you deployed this to namespace `Codium` vs `CodiumAI`. Do you want ownership of `Codium`? If you prefer `CodiumAI`, I can un-publish this extension in order for you to re-publish it in the `CodiumAI` namespace.

**Comment by OmriGM** [comment]
`Codium` is fine since it's our publisher name

**Comment by kineticsquid** [comment]
@OmriGM Granted!

**Comment by OmriGM** [comment]
Thanks!
Should this message be gone after that?
<img width="869" alt="image" src="https://user-images.githubusercontent.com/24547476/235760432-ae527a8d-f181-4aa6-a678-513863fe1f44.png">

**Comment by kineticsquid** [comment]
It should. Your viewing this URL https://open-vsx.org/extension/Codium/codium? I don't see the orange banner when visit that page:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/681707/235766541-d28e0fba-2336-47c7-817b-8c72a5496cac.png">

There is some caching, I'm wondering if the caches hadn't caught up. Do you still see this banner?
