### ISSUE TITLE
Claiming namespace TabbyML

### ISSUE THREAD

**Issue by icycodes** [EclipseFdn/open-vsx.org#1798]
I would like to claim the namespace TabbyML. I am a member of [TabbyML](https://github.com/TabbyML) and maintain the VSCode Extension for [Tabby](https://github.com/TabbyML/tabby).  
I have just published [vscode-tabby](https://open-vsx.org/extension/TabbyML/vscode-tabby) on open-vsx.org.
Thank you.

**Comment by kineticsquid** [comment]
@icycodes Thanks for your contribution!
