### ISSUE TITLE
Assist testing eclipse-openvsx-api

### ISSUE THREAD

**Issue by ZacharySabourin** [EclipseFdn/open-vsx.org#1802]
I'm from the Eclipse Foundation Webdev team. We are currently in the process of decoupling some of our services from Drupal and migrating them to our Quarkus stack. 

One of these services is the [eclipse-openvsx-api](https://gitlab.eclipse.org/eclipsefdn/it/api/eclipse-openvsx-api) which allows logged-in users to sign, view, and revoke Open-vsx publisher agreements. We are currently at the testing stage and would like some assistance to verify that the new service behaves as expected and that it is stable. 

We currently have an instance of this API on staging that we would like your help in testing. I think the easiest way to go about testing this would be to create a staging instance of open-vsx.org, point it at our staging server, and go about the normal flow. The base staging URL is https://api-staging.eclipse.org/

This is mainly a place to generate discussion and coordinate between the teams.
/cc @chrisguindon @autumnfound

**Comment by chrisguindon** [comment]
@amvanbaren,

Is this something you can help us with? Our main goal here is to test and confirm that our new Open-VSX publisher agreement API works as expected on staging before deploying it to production.

/cc @kineticsquid

**Comment by kineticsquid** [comment]
@chrisguindon @ZacharySabourin We have a staging instance: https://staging.open-vsx.org/. Can you use this? What do you need us to do to help with the testing?

**Comment by amvanbaren** [comment]
@ZacharySabourin I've changed the `ovsx.eclipse.base-url` property. You can test it on https://staging.open-vsx.org. The staging instance uses Basic authentication to restrict access. You can reach out to me or @kineticsquid on Slack to get the credentials.

**Comment by ZacharySabourin** [comment]
@amvanbaren Perfect, thanks!

**Comment by ZacharySabourin** [comment]
@amvanbaren So I ran a quick test and signed an agreement for myself. It looks like your staging instance is still pointed at our production URL.

**Comment by amvanbaren** [comment]
@ZacharySabourin The deploy failed. It is running on staging now. You can try again.

**Comment by ZacharySabourin** [comment]
After a bit of testing, and some digging around in code, it looks like the [Eclipse/openvsx](https://github.com/eclipse/openvsx) project might be what's communicating with our API. It also appears to still be pointed at our production server. 

I just want to bring this up since the change to the URL didn't seem to be sufficient in getting this to function as intended. 
@chrisguindon Thoughts?

**Comment by chrisguindon** [comment]
> I just want to bring this up since the change to the URL didn't seem to be sufficient in getting this to function as intended.
> @chrisguindon Thoughts?

My understanding is that the [Eclipse/openvsx](https://github.com/eclipse/openvsx) project is included in the [Eclipse/openvsx(https://github.com/EclipseFdn/open-vsx.org) project.

I would expect us to be able to configure the [Eclipse/openvsx](https://github.com/eclipse/openvsx) project here to allow us to test using our staging server for api-staging.eclipse.org.

@spoenemann,

Can you provide us with some guidance? We are currently migrating the Openvsx Publisher agreement from Drupal 7 to Drupal. The source code for this new API is here:
https://gitlab.eclipse.org/eclipsefdn/it/api/eclipse-openvsx-api

Before we push it to production, we would like to ensure that all is well-using https://staging.open-vsx.org/ and https://api-staging.eclipse.org/. However, we've been unsuccessful so for to do that. 

All our testing seems to be going through our production API server which is located https://api.eclipse.org.

**Comment by autumnfound** [comment]
I attempted to help Zach test earlier today, but I was unable to link the accounts properly, as I was getting SSL cert errors in the site UI:

```
Request for retrieving user profile failed: I/O error on GET request for "https://api-staging.eclipse.org/openvsx/profile": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by amvanbaren** [comment]
@ZacharySabourin yes.
https://github.com/eclipse/openvsx/blob/f013e2d8ec9e4e4cc4b9fdc14980c2d59584cc66/server/src/main/java/org/eclipse/openvsx/eclipse/EclipseService.java#L157-L187

**Comment by ZacharySabourin** [comment]
@amvanbaren 
Does the condition [here](https://github.com/eclipse/openvsx/blob/f013e2d8ec9e4e4cc4b9fdc14980c2d59584cc66/server/src/main/java/org/eclipse/openvsx/eclipse/EclipseService.java#L170) match with empty JSON objects?

[My profile](https://api.eclipse.org/account/profile/zacharysabourin) returns `"publisher_agreements":{}` but it does not seem to be updating whether or not I have an active agreement.

**Comment by ZacharySabourin** [comment]
@amvanbaren 
The user object returned from `https://staging.open-vsx.org/user` is: 
```
{"loginName":"ZacharySabourin","tokensUrl":"https://staging.open-vsx.org/user/tokens","createTokenUrl":"https://staging.open-vsx.org/user/token/create","fullName":"Zachary Sabourin","avatarUrl":"https://avatars.githubusercontent.com/u/45858290?v=4","homepage":"https://github.com/ZacharySabourin","provider":"github","publisherAgreement":{"status":"signed","timestamp":"2023-05-03T17:48:21Z"},"additionalLogins":[{"loginName":"zacharysabourin","provider":"eclipse"}]}
```

It is showing as `signed`. 

Also, since I forgot to include it in my earlier message, my staging profile info also shows `publisher_agreements: {}`: https://api-staging.eclipse.org/account/profile/zacharysabourin

**Comment by amvanbaren** [comment]
@ZacharySabourin Ok, I tried revoking your publisher agreement, so you can try again. But I get an error: 'Authorization by Eclipse required.' This is a long standing issue: https://github.com/eclipse/openvsx/issues/409. 

When you sign the publisher agreement on https://open-vsx.org, does it show up in the production API (api.eclipse.org)?

**Comment by ZacharySabourin** [comment]
@amvanbaren 
I logged in to open-vsx.org and signed a new agreement. Here is the updated profile info: https://api.eclipse.org/account/profile/zacharysabourin

It has updated to: `{"open-vsx":{"version":"1"}}`

**Comment by ZacharySabourin** [comment]
@chrisguindon Do you have any idea what might be causing this? https://github.com/eclipse/openvsx/issues/409

**Comment by ZacharySabourin** [comment]
@amvanbaren 
Could you also revoke my agreement on staging? My `user-setting/profile` page on staging.open-vsx.org still shows that I have a signed agreement. If all goes well, I should be able to sign the agreement and also see it in our staging DB.

Thanks in advance!

**Comment by kineticsquid** [comment]
@amvanbaren I tried revoking @ZacharySabourin publisher agreement on both staging and production, but get the following error:

<img width="446" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/eb5c07d4-13de-4db5-938a-1be9058684cb">

**Comment by amvanbaren** [comment]
@kineticsquid I'm getting the same error. It's a long standing issue: https://github.com/eclipse/openvsx/issues/409.

**Comment by ZacharySabourin** [comment]
It appears that you have an issue with your user token: https://github.com/eclipse/openvsx/blob/f013e2d8ec9e4e4cc4b9fdc14980c2d59584cc66/server/src/main/java/org/eclipse/openvsx/eclipse/EclipseService.java#L493

@amvanbaren 
https://github.com/eclipse/openvsx/blob/9e261e01ab3398f0405c81e5882309ef6e18bf13/server/src/main/java/org/eclipse/openvsx/security/TokenService.java#L126-L141 ? 
It appears to just return null if the user has no token, which would explain the error message. Am I wrong in my assumption that getting a new token would solve this?

**Comment by amvanbaren** [comment]
I tried to publish an extension to staging, but I get the following error:
```
Error: Request for retrieving user profile failed: I/O error on GET request for "https://api-staging.eclipse.org/account/profile/amvanbaren": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I'm switching it back to the production API, so that I can test the improved query endpoint.

**Comment by chrisguindon** [comment]
@eclipsewebmaster Do you why @amvanbaren is experiencing an issue connecting to https://api-staging.eclipse.org/account/profile/amvanbaren

Based on the logs that he shared, it appears to be an SSL issue..

I seem to be able to connect to staging without any issues:
https://api-staging.eclipse.org/

It's not clear to me if the error is on api-staging.eclipse.org or https://staging.open-vsx.org. I suspect of these have outdated SSL libs or certs that needs to be updated.

**Comment by ZacharySabourin** [comment]
@amvanbaren We are ready to go live with this but would like your approval before doing so. Any objections?

**Comment by amvanbaren** [comment]
@ZacharySabourin No objections. Does it require a open-vsx.org deployment?

**Comment by ZacharySabourin** [comment]
@amvanbaren Perfect! As long as the base URL is pointed at `https://api.eclipse.org`, which I assume it already is, it shouldn't require anything on your end. I will keep you posted on our progress.

**Comment by chrisguindon** [comment]
@ZacharySabourin ,

May I recommend that we pick a time when @amvanbaren is available to do the switchover just in case there is an issue and we need to react to that?

**Comment by ZacharySabourin** [comment]
Thanks for the suggestion, @chrisguindon. I agree that would probably be best. 

@amvanbaren Is there a time next week that would work best for you? 

I will ensure everything is properly set up on our end for the switch.

**Comment by ZacharySabourin** [comment]
Our new service is now live on production and appears to be fully stable! 

Thanks @amvanbaren and everyone who helped during the process :)

If there are any problems that pop up in the future, please do not hesitate to create an issue here: https://gitlab.eclipse.org/eclipsefdn/it/api/eclipse-openvsx-api/-/issues

**Comment by chrisguindon** [comment]
This is awesome news! Big thanks to @ZacharySabourin for seeing this thought from start to finish and to @amvanbaren for helping us test the update!

//cc @kineticsquid

**Comment by kineticsquid** [comment]
Excellent news indeed, many thanks @ZacharySabourin and @amvanbaren!
