### ISSUE TITLE
Claiming namespace Guyutongxue

### ISSUE THREAD

**Issue by guyutongxue** [EclipseFdn/open-vsx.org#1804]
I'm the author of VS Code extension [Cpp Reference](https://github.com/Guyutongxue/VSC_CppReference) (Guyutongxue.cpp-reference), and I'd like to [publish it](https://open-vsx.org/extension/Guyutongxue/cpp-reference) on open-vsx.org. Thanks!

**Comment by kineticsquid** [comment]
@Guyutongxue thanks for your contribution!
