### ISSUE TITLE
Claiming namespace `lokalise/i18n-ally`

### ISSUE THREAD

**Issue by terales** [EclipseFdn/open-vsx.org#1805]
Hello, I'm maintaining the i18n Ally extension and need to update a token to publish i18n Ally into Open VSX.
The previous person has changed workplace, and I want to connect my account instead.

Here is our repo to prove that I have write/publishing access:
https://github.com/lokalise/i18n-ally

**Comment by kineticsquid** [comment]
@terales ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response

**Comment by terales** [comment]
I have published two versions v2.9.0 and v2.9.1:
https://open-vsx.org/extension/lokalise/i18n-ally

Is there anything else that should be done?

**Comment by kineticsquid** [comment]
@terales I see @beinarovic is already an owner of this namespace.

**Comment by kineticsquid** [comment]
@terales ^^^^

**Comment by kineticsquid** [comment]
@terales ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
