### ISSUE TITLE
Claiming namespace [SecurityExpertsCommunity]

### ISSUE THREAD

**Issue by aw350m33d** [EclipseFdn/open-vsx.org#1814]
I'm the maintainer of the SEC community - an open community of security experts with a focus on defense. I created a namespace to publish extensions created by our community.

**Comment by aw350m33d** [comment]
Accidentally, in the previous version of the extension (v.3.3.3), the publisher was specified in the wrong format with dashes: Security-Experts-Community. Please remove this namespace and extension version 3.3.3.

**Comment by kineticsquid** [comment]
@aw350m33d I've unpublished the the extension in `Security-Experts-Community` and assigned you ownership of `SecurityExpertsCommunity`. Good to have you!
