### ISSUE TITLE
Unpublish Extension

### ISSUE THREAD

**Issue by ederign** [EclipseFdn/open-vsx.org#1825]
Hi, we changed the namespace of our extension. So could you please unpublish https://open-vsx.org/extension/kie-group/serverless-workflow-vscode-extension ?

The name space of our extension now is: https://open-vsx.org/extension/kie-group/swf-vscode-extension

**Comment by kineticsquid** [comment]
@ederign When attempting to unpublish `https://open-vsx.org/extension/kie-group/serverless-workflow-vscode-extension`, I get this error message:

```
The following extensions have a dependency on kie-group.serverless-workflow-vscode-extension: 
kie-group.vscode-extension-kogito-bundle-0.28.1
```

Were you aware of this dependency?

**Comment by ederign** [comment]
@amvanbaren can we unpublished just the kie-group.vscode-extension-kogito-bundle-0.28.1 bundle version? (and keep the other ones?)

**Comment by amvanbaren** [comment]
@ederign Yes, that's possible. @kineticsquid can you make that happen?

**Comment by kineticsquid** [comment]
@ederign I've removed `kie-group.vscode-extension-kogito-bundle-0.28.1`. Do you now want me to unpublish https://open-vsx.org/extension/kie-group/serverless-workflow-vscode-extension?

**Comment by ederign** [comment]
@kineticsquid yes, please!

**Comment by kineticsquid** [comment]
Done!

**Comment by ederign** [comment]
Thank you so much!
