### ISSUE TITLE
Claiming namespace wget

### ISSUE THREAD

**Issue by wget** [EclipseFdn/open-vsx.org#1830]
My e-dentity as a dev is known as wget, yes like the UNIX command, but actually a play on words with my first and last names. This is also the name of my private company.

I have an agreement with the GNU Wget maintainers to avoid conflicts. These are using the GNUWget namespace everywhere (agreement settled when they swicthed to GitLab SaaS a long time ago).

I would like to publish extensions under my namespace, extensions useful for myself, but also made as part of my work/contributions to Mattermost and Collabora Online.

I'm currently in discussion with KokaKiwi wrt. [Markdown Preview Github Styling](https://open-vsx.org/extension/bierner/markdown-preview-github-styles) as this one is not validated and is a bit lagging behind in terms of releases.

**Comment by kineticsquid** [comment]
@wget Got it. Go ahead a publish to that namespace and I'll make you owner.

**Comment by kineticsquid** [comment]
@wget ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
