### ISSUE TITLE
Claiming namespace expo

### ISSUE THREAD

**Issue by byCedric** [EclipseFdn/open-vsx.org#1831]
Hi! My name is Cedric, and I work for https://expo.dev (https://github.com/expo).

We are currently in the process of moving over one of our extensions "Expo Tools" to the official Expo publisher. Right now, it's published under my name (https://open-vsx.org/extension/byCedric/vscode-expo), but lives under the expo github org (https://github.com/expo/vscode-expo). For that, we'd love to claim the `expo` namespace, to not only publish it on the marketplace, but also publish it on open-vsx.org (just as we are doing now - [my personal namespace claim](https://github.com/EclipseFdn/open-vsx.org/issues/1107)).

If there is anything I need to prove I'm working with Expo, lmk! You can mail me at cedric@expo.dev to confirm that.

Thanks!

**Comment by kineticsquid** [comment]
@byCedric I can see your extension is currently published in the `byCedric` namespace. I can rename that namespace to `expo`. If you'd rather keep `byCedric` and create `expo`, go ahead an publish to `expo` and I'll then assign ownership of it to you.

**Comment by byCedric** [comment]
@kineticsquid renaming would be awesome, if it's no trouble :) I don't have any other extensions scheduled atm.

**Comment by kineticsquid** [comment]
Done! Note, it can take up to a couple of hours for all the changes to take effect.

**Comment by byCedric** [comment]
Thank you!
