### ISSUE TITLE
Claiming namespace miguelsolorio

### ISSUE THREAD

**Issue by suwermave** [EclipseFdn/open-vsx.org#1835]
I would like to publish [vscode-symbols](https://github.com/miguelsolorio/vscode-symbols) theme that is released by MIT License. Author of this theme is not interested in publishing it in OpenVSX
I did log in in open VSX.

**Comment by kineticsquid** [comment]
@suwermave I see that @Surendrajat has already published to this namespace this extension, https://open-vsx.org/extension/miguelsolorio/fluent-icons.

**Comment by Surendrajat** [comment]
@kineticsquid feel free to remove me and reassign others. I am not the owner.

**Comment by kineticsquid** [comment]
@Surendrajat Thanks!

@suwermave You have ownership. Good to have you.
