### ISSUE TITLE
Claiming namespace kodezi

### ISSUE THREAD

**Issue by assadullahchaudhry** [EclipseFdn/open-vsx.org#1837]
Hello,

I am the founding developer working at [Kodezi](https://kodezi.com) responsible for publishing the extension at https://open-vsx.org

For verification purpose, please feel free to contact us at [info@kodezi.com](info@kodezi.com).

If you want to contact me directly, you can shoot me an email at  [assad@kodezi.com](assad@kodezi.com).

Thank you!

**Comment by kineticsquid** [comment]
Granted @assadullahchaudhry!
