### ISSUE TITLE
Claiming namespace [eclipse-titan]

### ISSUE THREAD

**Issue by ppank5** [EclipseFdn/open-vsx.org#1844]
We already claimed the ownership of namespace 'titan'. Is is possible to move/change it to namespace 'eclipse-titan'? I asked for it wrongly last time, my bad, sorry. Thank you for your help!
Link to the other issue: https://github.com/EclipseFdn/open-vsx.org/issues/1813

**Comment by kineticsquid** [comment]
@ppank5 Thanks for your contribution!
