### ISSUE TITLE
Error display when searching with a keyword

### ISSUE THREAD

**Issue by RitamAgrawal** [EclipseFdn/open-vsx.org#1847]
When I type keyword in the search box. It displays the result accurately but before that it displays an error (failed GET request) like this.
<img width="1085" alt="2023-05-24_16-17-05" src="https://github.com/EclipseFdn/open-vsx.org/assets/72183558/a4c9364a-fa0c-487d-a1cb-0aaf3f37171d">

**Comment by RitamAgrawal** [comment]
I tried searching with 
`sales` -> no display of error
`salesfo` -> no error
`salesfor` -> displays Error 
`salesforce` -> displays Error

**Comment by kineticsquid** [comment]
@amvanbaren I was able to reproduce this. I attempted to open each of the listed extensions after dismissing the error and found this one missing (appears to be the cause of the error message):
<img width="976" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/1d1d5058-2d52-4026-8f62-2ef07c8ec9bb">

**Comment by kineticsquid** [comment]
OK, that extension appeared to be corrupt. I unpublished it and the search appears to be working now.

**Comment by kineticsquid** [comment]
@manifestinteractive Sorry, can you republish to your namespace?

**Comment by RitamAgrawal** [comment]
Thank you so much @kineticsquid & @amvanbaren for your prompt actions.
