### ISSUE TITLE
Can I configure a private and an open vsx marketplace?

### ISSUE THREAD

**Issue by kajberg84** [EclipseFdn/open-vsx.org#1849]
I use Visual studio - Code OSS.
I have a private open vsx where I have stored som private extensions.
When I use Visual studio and search for an extension I want to configure it so it searches the private first and then the open vsx marketplace.

Is this possible and if so any guide about this?
I have tried to search for documentation regarding this but sofar no results.

**Comment by kineticsquid** [comment]
I think this is going to be a question for the Code OSS folks.

**Comment by MatthewKhouzam** [comment]
Hey, AFAIK vscode does not want multiple back-ends. Theia solutions will soon support multi-vsx. I am very excited about it! :) https://github.com/eclipse-theia/theia/pull/12040

**Comment by kajberg84** [comment]
True @kineticsquid.
Sound great @MatthewKhouzam 

Ty for the fast response.

**Comment by amvanbaren** [comment]
@kajberg84, you can add
'''
ovsx:
  upstream:
    url: https://open-vsx.org
```
to the application.yml of your private instance.

**Comment by kineticsquid** [comment]
@kajberg84 OK to close this now?

**Comment by kineticsquid** [comment]
@kajberg84 ^^^^
