### ISSUE TITLE
Claiming namespace [Karsten7]

### ISSUE THREAD

**Issue by Karsten7** [EclipseFdn/open-vsx.org#1863]
I'm claiming ownership of the Karsten7 namespace on Open-VSX.

I'd like to republish my VSCode extension (https://marketplace.visualstudio.com/items?itemName=Karsten7.mojo-vscode) to the Open VSX Registry: https://open-vsx.org/extension/Karsten7/mojo-vscode

**Comment by kineticsquid** [comment]
@Karsten7 Thanks for your contribution!
