### ISSUE TITLE
Claiming namespace [Semgrep]

### ISSUE THREAD

**Issue by ajbt200128** [EclipseFdn/open-vsx.org#1875]
Current main maintainer of [semgrep-vscode](https://github.com/returntocorp/semgrep-vscode)

Doing this as prompted by [this issue on our repo](https://github.com/returntocorp/semgrep-vscode/issues/23)

Feel free to check this is true by asking on our [community slack](http://go.semgrep.dev/slack) (also linked in repo), or checking commit history :)

**Comment by kineticsquid** [comment]
@ajbt200128 Granted!
