### ISSUE TITLE
Claiming namespace tailscale

### ISSUE THREAD

**Issue by tylersmalley** [EclipseFdn/open-vsx.org#1882]
We just launched a [VS Code extension](https://marketplace.visualstudio.com/items?itemName=tailscale.vscode-tailscale) and have [a request](https://github.com/tailscale-dev/vscode-tailscale/issues/3) to publish it to the open-vsx directory. As I understand it, we would need to do this under the namespace to provide other contributors access to publish.

Thanks!

**Comment by kineticsquid** [comment]
@tylersmalley Good to have you!
