### ISSUE TITLE
Can't publish extension

### ISSUE THREAD

**Issue by suwermave** [EclipseFdn/open-vsx.org#1890]
I recently claimed ownership for a namespace miguelsolorio.
When I click on Extensions -> Publish extension it says to me there is no eclipse data available for me
![image](https://github.com/EclipseFdn/open-vsx.org/assets/50447661/ee663206-af64-48b6-8b76-4f2787b1592a)

**Comment by kineticsquid** [comment]
@chrisguindon Can you check this ID too?

**Comment by chrisguindon** [comment]
Should be fixed now! Please re-open if you are still experiencing issues.

**Comment by kineticsquid** [comment]
Thanks @chrisguindon!
