### ISSUE TITLE
All extensions I published under KylinIdeTeam have disappeared

### ISSUE THREAD

**Issue by KylinIdeTeam** [EclipseFdn/open-vsx.org#1915]
Hi Boss, all extensions I published have disappeared, my id is KylinIdeTeam, could you tell me why? Thank you!

**Comment by kineticsquid** [comment]
@KylinIdeTeam My sincerest apologies. While I can't go into details, the extensions in your namespace were flagged as potential security vulnerabilities. We decided we needed to take action. Please re-publish when you're able. If your extensions get flagged again, we'll be sure to reach out to you to resolve. Again, I'm sorry for the hassle and churn.

**Comment by quanzhuo** [comment]
Thanks a lot. Could I know about how the flag been made? Is there any tool I can use to examin whether the extensions might have some potential security vulnerabilities or to avoid this situation happening ?

**Comment by KylinIdeTeam** [comment]
Thanks a lot. Could I know about how the flag been made? Is there any tool I can use to examin whether the extensions might have some potential security vulnerabilities or to avoid this situation happening ?

**Comment by kineticsquid** [comment]
@KylinIdeTeam I'm sorry for the delay in responding. No, and again I can't go into details here, other than to say it was a number of actors that when added together gave us concern. I'm sorry for the churn on your end and I'm glad to see you've re-published.
