### ISSUE TITLE
Update Banner with text pointing to the recent press release on the establishment of the Open VSX Working Group

### ISSUE THREAD

**Issue by kineticsquid** [EclipseFdn/open-vsx.org#1932]
Link to the press release:

https://www.globenewswire.com/news-release/2023/06/27/2695137/0/en/The-Open-VSX-Registry-a-Vendor-Neutral-Community-Supported-Alternative-to-the-Visual-Studio-Marketplace-Gets-its-Own-Working-Group-at-the-Eclipse-Foundation.html

Possible text:

We've established a working group devoted entirely to the operation, maintenance, and promotion of this Open VSX Registry. Read more in our recent press release [link].

Banner text is here: 
https://github.com/EclipseFdn/open-vsx.org/blob/40e74d2ddf6f4bbf3831797e514b9867e13b2221/website/src/page-settings.tsx#L40

**Comment by kineticsquid** [comment]
@croundy thoughts?

**Comment by croundy** [comment]
That's the correct link and I like what you wrote @kineticsquid. Perhaps just swap out "this" for "the"

We've established a working group devoted entirely to the operation, maintenance, and promotion of the Open VSX Registry. Read more in our recent press release [link]

**Comment by kineticsquid** [comment]
New words:

We've established a working group devoted entirely to the operation, maintenance, and promotion of the Open VSX Registry. Read more in our recent press release [link].
