### ISSUE TITLE
Claiming namespace trustfall

### ISSUE THREAD

**Issue by obi1kenobi** [EclipseFdn/open-vsx.org#1933]
I'm the author of the Trustfall query engine: https://github.com/obi1kenobi/trustfall

My collaborators and I are interested in publishing extensions that improve the user experience of using Trustfall. We'd like to do that under the "trustfall" namespace, which we hereby request to claim.

Thanks!

**Comment by kineticsquid** [comment]
@obi1kenobi May the force be with you!

**Comment by obi1kenobi** [comment]
Thank you 😁
