### ISSUE TITLE
Claiming namespace cdda-toys

### ISSUE THREAD

**Issue by irwiss** [EclipseFdn/open-vsx.org#1934]
Good time of day,

I'd like to publish an extension (or may be multiple later) for open source project:
https://marketplace.visualstudio.com/items?itemName=cdda-toys.cdda-json-formatter
under same prefix
https://open-vsx.org/extension/cdda-toys/cdda-json-formatter

**Comment by kineticsquid** [comment]
@irwiss We can always use more pickles!
