### ISSUE TITLE
Take ownership of list of deprecated and malicious extensions

### ISSUE THREAD

**Issue by kineticsquid** [EclipseFdn/open-vsx.org#1938]
Our colleagues at Gitpod currently keep a list of deprecated and malicious extensions: https://github.com/gitpod-io/gitpod/blob/main/components/ide-proxy/static/code/marketplace.json.

This list is created by scanning daily the public that Microsoft maintains for the Visual Studio Marketplace: https://az764295.vo.msecnd.net/extensions/marketplace.json

We should take over this list as a central resource for consumers of extensions from open-vsx.org. 

This will require some policy discussions and implementation procedures.

**Comment by kineticsquid** [comment]
- Extensions get abandoned
- Extensions can be dangerous … and we want to make users aware
- MS introduced deprecated extensions in 05/2022 and has a [GitHub Discussions thread](https://github.com/microsoft/vscode-discussions/discussions/1) for people to contribute to the list
- Eclipse should host it, because
   - It will make sure anyone can use it (VSCodium, Gitpod, Coder, Theia, …)
   - It will ensure that people are free to contribute and add visibility to the effort

**Comment by kineticsquid** [comment]
@filiptronicek To clarify, currently we just maintain this list, there is no UI treatment of deprecated extensions?

**Comment by filiptronicek** [comment]
@kineticsquid exactly. The only interface you can use the data from as of now is searching for deprecated extensions in a VS Code client.

**Comment by kineticsquid** [comment]
I just realized @filiptronicek you'd created https://github.com/EclipseFdn/open-vsx.org/issues/1121 last year for this. Closing this one.
