### ISSUE TITLE
Need to update information for https://open-vsx.org/extension/maattdd/gitless

### ISSUE THREAD

**Issue by kineticsquid** [EclipseFdn/open-vsx.org#1939]
This is the extension on VS Marketplace: https://marketplace.visualstudio.com/items?itemName=maattdd.gitless.

The name, the repo, and the homepage make it clear that this is a fork of https://github.com/gitkraken/vscode-gitlens by @mattdd.

However, the Open VSX page obscures this instead pointing to the GitLens repo and homepage and using GitLens content in the Open VSX Registry entry. 

@maattdd, would you update your extension information, similar to what you have at https://marketplace.visualstudio.com/items?itemName=maattdd.gitless and re-publish to make it clear that this is your fork. 

@mbarbero @waynebeaton FYI

**Comment by kineticsquid** [comment]
No response. I can the see author's github org, but none of the repos permit me to open an issue, in an effort to make direct content. Therefore, I'm going to un-publish this extension.

**Comment by maattdd** [comment]
I've never publish the extension myself anywhere but on the official VS Marketplace.
