### ISSUE TITLE
Claiming namespace [Mai-Lapyst]

### ISSUE THREAD

**Issue by Mai-Lapyst** [EclipseFdn/open-vsx.org#1942]
I use the name "Mai-Lapyst" pretty much everywhere; it's also my username on [github.com](https://github.com/Mai-Lapyst) and open-vsx.org. I also have an same-named developer account on vscode's marketplace: https://marketplace.visualstudio.com/publishers/Mai-Lapyst

**Comment by kineticsquid** [comment]
@Mai-Lapyst Thanks for your contribution!
