### ISSUE TITLE
Claiming namespace ellacrity

### ISSUE THREAD

**Issue by ellacrity** [EclipseFdn/open-vsx.org#1945]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I am the owner of the namespace `ellacrity`. I created the namespace to publish my extension, [`recoil`](https://github.com:ellacrity/recoil-vscodium-theme). The extension itself is a color theme under active development.

I chose this namespace as it is the same name as my GitHub account.
-----BEGIN PGP SIGNATURE-----

iKMEARYIAEsWIQTYo+rb4xwDuSzDpEsQQspJaYE2wAUCZKXJxy0cMTE2NDExMDU0
K2VsbGFjcml0eUB1c2Vycy5ub3JlcGx5LmdpdGh1Yi5jb20ACgkQEELKSWmBNsDL
rwD8Dkzvg8Z1id7AwrUPllAq60eLSwHY5j68DYC642pJyrEA/01/xNgofTXwoaWt
c8VXPbcGNRJrX9qvEcpGRURFApsE
=VLwL
-----END PGP SIGNATURE-----

**Comment by kineticsquid** [comment]
@ellacrity Thanks for your contribution!
