### ISSUE TITLE
Error on publishing extension

### ISSUE THREAD

**Issue by 4lex4** [EclipseFdn/open-vsx.org#1946]
I'm trying to publish an extension into the claimed namespace, but it shows that the extension is inactive. After trying to publish with ovsx I get an error:  
`Extension 4lex4.precious-themes-vscode 1.0.0 is already published, but currently isn't active and therefore not visible.`

**Comment by kineticsquid** [comment]
@4lex4 ^^^^

**Comment by 4lex4** [comment]
`ovsx publish ./build/precious-themes-vscode-1.0.0.vsix -p `*`token`*

**Comment by kineticsquid** [comment]
@4lex4 This is getting curiouser and curiouser... Using my admin creds, I added myself to your `4lex4` namespace. I then cloned your repo, built the extension, and attempted to publish. Same result as you. As an aside, the `vsce build` command fussed at the statement `"icon": "./icons/icon.png",`. I changed it to `"icon": "icons/icon.png",` to resolve the error. 

I then tried a simple hello world extension I had previously published, changed `package.json` to point to your namespace, built it, attempted to publish, and same deactivation result. 
<img width="1041" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/5f172900-e71e-4620-baee-c06777e53206">

I'm wondering if something is out of whack with your Eclipse publisher account. Have you published this extension on the Visual Studio Marketplace?

On more relatively simple thing we can try is for me to cancel the publisher agreement and have you re-execute it to see if that fixes things.

**Comment by 4lex4** [comment]
@kineticsquid 
> Have you published this extension on the Visual Studio Marketplace?

No, I have not, did not even intend to. I use code oss, it does not use microsoft's marketplace.

> On more relatively simple thing we can try is for me to cancel the publisher agreement and have you re-execute it to see if that fixes things.

Of course, I am not in a hurry and am ready to try. There is a bug somewhere, that is for sure.

**Comment by sjsepan3** [comment]
I am getting a message like the OP. I found a misnamed-file error in my package.json, and corrected it, but I cannot clear the two old attempts. I am considering bumping the version again, but would like to avoid that.

user is sjsepan3 on Open VSX same as here

**Comment by kineticsquid** [comment]
@sjsepan3 Not sure I understand your un-publish reference. Do you have an outstanding un-publish request?

**Comment by kineticsquid** [comment]
@4lex4 I did some more poking around with your extension. I was able to publish it to my namespace, `kineticsquid`. I cloned your repo and changed `publisher` and `icon` as follows:
```
"icon": "icons/icon.png",
"publisher": "kineticsquid",
```

Then packaged and published to https://open-vsx.org/extension/kineticsquid/precious-themes-vscode.

Prior to this, I initially got it to succeed, in addition to the above changes, by changing `name:` to something random. I then changed it back to `precious-themes-vscode` and tried again. Deactivated. I ended up, after a few minutes, refreshing the browser and the extension rendered as activated. I'm not sure exactly what is happening other than a suspicion this is a byproduct of some caching. 

Could you try again?

@amvanbaren @spoenemann Thoughts on this one?

**Comment by amvanbaren** [comment]
The server runs file processing async in the background. The Spring EntityManager should be context aware (know which thread is calling the EntityManager). However, in an `@Async` method it doesn't seem to work, because when multiple `FileResource` entities are persisted at the same time, it inserts the `FileResource` entities with the same primary key. This throws a constraint violation exception and causes the publishing process to fail.

Follow https://github.com/eclipse/openvsx/issues/779

**Comment by sjsepan3** [comment]
> @sjsepan3 Not sure I understand your un-publish reference. Do you have an outstanding un-publish request?

At the time I posted here, I did not know that I could just request an 'unpublish' via the Issues, and the OP's issue sounded similar to mine. You can disregard my post here. Thx.
