### ISSUE TITLE
Need to configure SonarQube

### ISSUE THREAD

**Issue by kineticsquid** [EclipseFdn/open-vsx.org#1957]
Need to configure SonarQube to run analyses on these three repos:
- https://github.com/eclipse/openvsx/
- https://github.com/EclipseFdn/open-vsx.org/
- https://github.com/open-vsx/publish-extensions/

The first two have an EF SonarQube token configured. The third repo also will need a token. 

Then, configure to have the analyses run. Details on that in this help desk ticket: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3331

**Comment by kineticsquid** [comment]
@amvanbaren How much work do you estimate this will take? I'd like to consider getting it in this year.

**Comment by amvanbaren** [comment]
@kineticsquid Wasn't @heurtematte working on this?

**Comment by kineticsquid** [comment]
@amvanbaren He was, but he needs us to make these changes. The helpdesk ticket above has the instructions for what we need to do.

**Comment by kineticsquid** [comment]
@amvanbaren @kineticsquid I can see the config file here, https://github.com/EclipseFdn/open-vsx.org/blob/main/sonar-project.properties. Where would I find the reports?

**Comment by amvanbaren** [comment]
@kineticsquid SonarQube doesn't analyze a PR from a forked repository: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3331#note_1266116

**Comment by kineticsquid** [comment]
@amvanbaren Sorry, I'm not following. None of these three repos are forks:

-     https://github.com/eclipse/openvsx/
-     https://github.com/EclipseFdn/open-vsx.org/
-     https://github.com/open-vsx/publish-extensions/

**Comment by amvanbaren** [comment]
@kineticsquid Right. It's about the origin of the PR, those are from forked repos, e.g. `https://github.com/amvanbaren/openvsx/`

**Comment by kineticsquid** [comment]
@amvanbaren Making sure we're talking about the same thing. We were to do some configuration work to enable SonarQube scanning for these three repos (an not forks of the repos). That was my intent with this issue (and the related information in the Gitlab issue). Is that enablement work complete? I'm asking because I was expecting to see some kind of report and I don't (maybe I'm looking in the wrong place).

**Comment by amvanbaren** [comment]
Reports can be viewed in the sonarcloud dashboard: https://sonarcloud.io/organizations/open-vsx/projects
