### ISSUE TITLE
Claiming namespace steedos

### ISSUE THREAD

**Issue by baozhoutao** [EclipseFdn/open-vsx.org#1964]
I have already published two applications in the steedos namespace. However, the recent version of the published application is being displayed as inactive.
A warning has appeared on the application.
https://open-vsx.org/extension/steedos/steedosdx-vscode-core/reviews

npx ovsx@0.2.1 publish error:
```
❌  Extension steedos.steedosdx-vscode 2.3.3 is already published, but currently isn't active and therefore not visible.
```

**Comment by kineticsquid** [comment]
@baozhoutao ^^^^
