### ISSUE TITLE
Claiming namespace ENDPLAYStudio

### ISSUE THREAD

**Issue by profitrollgame** [EclipseFdn/open-vsx.org#1979]
I'm the creator of END PLAY Studio, domain [end-play.xyz](https://end-play.xyz) is registered and owned by me as well as the [publisher instance on MS Marketplace](https://marketplace.visualstudio.com/publishers/ENDPLAYStudio). I'd like to publish extension packs I have on MS platform here as well in order to smoothen my team's transition from VSCode to VSCodium and also enable others to use those packs from open-vsx.

**Comment by kineticsquid** [comment]
@profitrollgame Good to have you!
