### ISSUE TITLE
unpublish two instances of extension

### ISSUE THREAD

**Issue by sjsepan3** [EclipseFdn/open-vsx.org#1982]
please un-publish the following:

sjsepan/vscode-gambas3 0.0.4 
sjsepan/vscode-gambas 0.0.5

The name difference is not a typo, I changed the extension name, thinking I had inconsistent names somewhere internally in 0.0.4; I later discovered a misnamed file reference as well in 0.0.5. 

Thanks in advance

**Comment by kineticsquid** [comment]
@sjsepan3 Done. That leaves 3 versions of `sjsepan/vscode-gambas3`.

**Comment by sjsepan3** [comment]
Nah, it's still coming up deactivated (republished 0.0.5) -- it would be nice if there were some error messages telling us *what* the upload-process doesn't like. I'm not saying we don't make mistakes, but they're not always obvious. ;-)
Steve
