### ISSUE TITLE
Claiming namespace jumppad

### ISSUE THREAD

**Issue by eveld** [EclipseFdn/open-vsx.org#1989]
We would like to publish vscode extensions for jumppad (https://jumppad.dev) to the open-vsx registry.
Jumppad can be found on github at https://github.com/jumppad-labs where I am one of the owners.

**Comment by eveld** [comment]
we have also published the extensions to the vscode marketplace @ https://marketplace.visualstudio.com/items?itemName=jumppad.workspace-config

**Comment by kineticsquid** [comment]
@eveld Good to have you!
