### ISSUE TITLE
unpublish sjsepan/vscode-gambas3 0.0.3

### ISSUE THREAD

**Issue by sjsepan3** [EclipseFdn/open-vsx.org#1990]

**Comment by kineticsquid** [comment]
@sjsepan3 un-published `0.0.3`, leaving `0.0.1` and `0.0.2`.

**Comment by sjsepan3** [comment]
> @sjsepan3 un-published `0.0.3`, leaving `0.0.1` and `0.0.2`.

0.0.2, 0.0.1 are not visible to me (well, 0.0.2 wasn't until 0.0.3 was deleted -- seriously, we publishers need more visibility into the stuff here ;-)  )
