### ISSUE TITLE
unpublish sjsepan/vscode-gambas 0.0.5

### ISSUE THREAD

**Issue by sjsepan3** [EclipseFdn/open-vsx.org#1991]
Not sure why this is going 'deactivated' though; the extension uploaded OK to the MS Marketplace, and installs OK into Code and Codium.
Really wish there was more feedback from the process.
Thanks in advance.
Steve

**Comment by kineticsquid** [comment]
@sjsepan3 I've un-published the one version.

Had you published this extension successfully before to open-vsx.org? If so, and you continue to have issues with activation, can you create another issue in this repo for that?

**Comment by sjsepan3** [comment]
> @sjsepan3 I've un-published the one version.
> 
> Had you published this extension successfully before to open-vsx.org? If so, and you continue to have issues with activation, can you create another issue in this repo for that?

No, this one has not been successfully  posted on this registry. Will try again soon, once these are cleared out.
