### ISSUE TITLE
unable to update the extension

### ISSUE THREAD

**Issue by andiwang1993** [EclipseFdn/open-vsx.org#1996]
Hello I have updated our extension [CodeGeeX](https://open-vsx.org/extension/AMiner/codegeex) to version 2.0.4, it has been 2 days, and this time we've changed the display name of our extension. But until today, it hasn't been updated to this version. So I want to know if there is any problem.

**Comment by kineticsquid** [comment]
@andiwang1993 Here are the versions I see on my admin panel:
```
1.1.1
1.1.2
1.1.4
1.1.6
2.0.2
2.0.3
2.0.4
```

I don't see `2.0.3` and `2.0.4` on the extension page. You changed `displayName` with `2.0.4`? What was the change from `2.0.2` to `2.0.3`?

**Comment by andiwang1993** [comment]
> @andiwang1993 Here are the versions I see on my admin panel:
> 
> ```
> 1.1.1
> 1.1.2
> 1.1.4
> 1.1.6
> 2.0.2
> 2.0.3
> 2.0.4
> ```
> 
> I don't see `2.0.3` and `2.0.4` on the extension page. You changed `displayName` with `2.0.4`? What was the change from `2.0.2` to `2.0.3`?

hello, I've seen the latest update of open-vsx, but because the version 2.0.4 is already update and still invalid, I can't update this version now (because of bugs in version 2.0.3, I just want to update version 2.0.4), so I want to know if it is possible to remove the invalid versions 2.0.3 and 2.0.4 from my panel?

**Comment by kineticsquid** [comment]
@andiwang1993 I can see you've published `2.1.0`. Are we good to close this?

**Comment by andiwang1993** [comment]
> @andiwang1993 I can see you've published `2.1.0`. Are we good to close this?

yes, thank you so much, I will close this by myself :)
