### ISSUE TITLE
Claiming namespace file-icons

### ISSUE THREAD

**Issue by Alhadis** [EclipseFdn/open-vsx.org#2001]
Hello,

I'm the author and maintainer of the @file-icons project, including an extension for VS Code ([**Marketplace**](https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons) | [**Repository**](https://github.com/file-icons/vscode)). In <samp>[file‑icons/vscode#70](https://github.com/file-icons/vscode/issues/70#issuecomment-1154703871)</samp>, two users encouraged me to make an official release on [open-vsx.org], which is what I'm doing now.

Note that there appears to be a duplicate (and outdated) version of this package on [open-vsx.org], published by one @enriquecaballero with the ID [`fileicons.file-icons`](https://open-vsx.org/extension/fileicons/file-icons). The correct version of the package (and the one I'm claiming ownership of) is [`file-icons.file-icons`](https://open-vsx.org/extension/file-icons/file-icons).

/cc @jwaggy, @Lewatoto

[open-vsx.org]: https://open-vsx.org/

**Comment by enriquecaballero** [comment]
Alright, even better. How can I unpublish?

**Comment by Alhadis** [comment]
> How can I unpublish?

I'm not sure. Hopefully somebody here can answer that question for us. 😅

**Comment by kineticsquid** [comment]
@enriquecaballero Thanks!

@Alhadis Fortunately, I have that super power. I've un-published 1 version of `fileicons.file-icons`.  Currently namespace `file-icons` has one member, @appelgriebsch. I am making you owner. I'll note that your extension is currently auto-published. See [extensions.json](https://github.com/open-vsx/publish-extensions/blob/29e50c66e0f087c5ce8e636222f99dac8fd19b7f/extensions.json#L345). You can leave this, or submit a PR to remove the lines which will leaving publishing in your hands.

**Comment by Alhadis** [comment]
> I'll note that your extension is currently auto-published.

That means I only need to publish updates to VSCode's Marketplace, right? And open-vsx.org will mirror new releases automatically? Because that'd be grouse. 😁

**Comment by kineticsquid** [comment]
Yep, makes sense to remove @appelgriebsch. And yes, when the auto-publishing job runs (I think it's nightly) if you've updated your [extension](https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons) in the Visual Studio Marketplace, we'll update as well. I can see you're `1.1.0` in both registries with both updates happening about 2 weeks ago.
