### ISSUE TITLE
Claiming namespace richterger

### ISSUE THREAD

**Issue by richterger** [EclipseFdn/open-vsx.org#2008]
I am the author of Perl::LanguageServer (https://github.com/richterger/Perl-LanguageServer), a vscode plugin, already publish in the microsoft vscode marketplace (https://marketplace.visualstudio.com/items?itemName=richterger.perl).

I signed the Eclipse Foundation Open VSX Publisher Agreement and create a namespace with `npx ovsx create-namespace richterger -p  TOKEN`, but I am not allowed to publish my extention. As far as I understand I need to claim then namespace first...

**Comment by richterger** [comment]
@kineticsquid I never heared this name and I don't know who is @marcdumais-work.

**Comment by kineticsquid** [comment]
@richterger Understood. I'm assigning you ownership and removing @marcdumais-work since there is nothing published. Good to have you!

**Comment by marcdumais-work** [comment]
Hi @richterger ,

Thanks for taking-over your namespace and publishing your extension on openvsx! The reason my name was associated is that I probably published a version of your extension, in the early days of openvsx. I used to do lots of Perl years ago - thanks for the extension!
