### ISSUE TITLE
Create a members page

### ISSUE THREAD

**Issue by oliviergoulet5** [EclipseFdn/open-vsx.org#2011]
From @kineticsquid:

Since we don't have a separate working group site from open-vsx.org, we'll need to use it as the working group site. We'll build this out over time. To get started, can we get a page, doesn't have to be hooked into the UI yet, with just a title and list of members. The member graphics will be the same as used on the EF members page and will link back to the members' EF member pages. Add the wording from the open-vsx.org entry on https://www.eclipse.org/org/workinggroups/explore.php to this new page.

Original issue: https://gitlab.eclipse.org/eclipsefdn/it/websites/eclipse.org/-/issues/355

**Comment by oliviergoulet5** [comment]
Thanks for merging @amvanbaren. But I don't see the members page I created.

I'm receiving an error page when accessing https://staging.open-vsx.org/members

Did the deployment fail?

**Comment by amvanbaren** [comment]
@oliviergoulet5 No, the deploy succeeded. There are no errors in the logs. 
Maybe you can fix the error by using the `terms-of-use` page as a guideline. It is another page that is only available for open-vsx.org.

**Comment by amvanbaren** [comment]
Sorry, I didn't mean the literal content of the terms of use page. I ment the technical implementation. You can look at how the `terms-of-use` page is created and routed, and compare that to the `members` page.

**Comment by oliviergoulet5** [comment]
@kineticsquid Here is a preview: https://staging.open-vsx.org/members

Where do we want to link the page?

Also, some member logos aren't transparent and it can be very noticeable in the dark mode of open-vsx.org. Updated logos would have to be uploaded. 

Otherwise we can fill the boxes with a white background:

![image](https://github.com/EclipseFdn/open-vsx.org/assets/17685861/7b1d3be6-8420-4961-98cc-25104981c641)

Now that I think about it more, I think the white backgrounds may be the better option. Especially in the case of displaying a darker log because, there wouldn't be enough contrast.

**Comment by kineticsquid** [comment]
@oliviergoulet5 I agree, I think we need to keep the white backgrounds. Some thoughts. Need to include Huawei. Can you order alphabetically. Can you enlarge logos? I'm asking for two reasons. I think visually Posit, Google, and (to a lesser extent) Siemens appear smaller. Also, to reduce the white space a bit. 

In terms of linking this in, first priority is a members link on the Open VSX working group entry on the EF working group page: https://www.eclipse.org/org/workinggroups/explore.php.

Linking here I think is going to require more changes. We need a 'Working Group' entry with the navigation links on the top right. But that's going to make it too busy. One thought would be to remove the 'FAQ' entry and add that to the 'About' page. Also remove the 'Community' entry and add that also to the about page also. This would make the nav links:

`Documentation Status Working Group Sponsor About`

The working group page would, for now, be this members page. 

Just my thoughts, certainly open to better ideas.

**Comment by oliviergoulet5** [comment]
@kineticsquid About the logo sizing, I can certainly reduce the whitespace. However, Google and Posit appear smaller because their logos were uploaded with a lot of white space. See the image [here](https://membership.eclipse.org/organization/images/1592-web.png). To fix that, the logos would need to be updated in the DB. 

Siemens is well-cropped. I can tweak the sizing constraints to better suit wider logos such as Siemens. Although there is no one size fits all solution as these logos all have different aspect ratios. Some will just appear smaller than others.

**Comment by kineticsquid** [comment]
@oliviergoulet5 Understood. I'll ask the members about updating the logos. In the meantime, just do what you can with what we have. Thanks!

**Comment by amvanbaren** [comment]
@oliviergoulet5 I've updated the webui. Please make sure the members page still looks as expected. Let me know when it is ready for deployment.

**Comment by shanda-eclipse** [comment]
@kineticsquid have you considered how this page will be added to the menu? I would suggest we make a top-level menu item "Working Group" and we can make this "Members" page a sub-page. 

We also have some standard pages about membership and WG documents we can add to that menu item (similar content to existing WGs). If that's the direction you want to go, let me know and I can recommend the other pages to add in the WG submenu.

**Comment by shanda-eclipse** [comment]
> @shanda-eclipse I had an idea in this [comment above](https://github.com/EclipseFdn/open-vsx.org/issues/2011#issuecomment-1662568112). Certainly open to suggestions!

Sorry, I missed it in the longer comment. 

> Documentation Status Working Group Sponsor About

Looks good to me and I think we can add some additional pages to the Working Group menu fairly easily.

**Comment by oliviergoulet5** [comment]
@shanda-eclipse Note that the current navbar and mobile menu don't currently support submenus. What you see on the navbar contains only links. 

If we do decide to go with a working group menu it would require more time for implementation.

**Comment by kineticsquid** [comment]
@oliviergoulet5 At the Open VSX working group today, I asked Posit and Google for better logos. What's your schedule on deploying? I'd like to give them an idea. I told them we wouldn't wait and would update when we got improved logos.

**Comment by oliviergoulet5** [comment]
I'll shoot for end of next week @kineticsquid. I'll share one more preview early next week with the Working Group page and the navigation updates.

**Comment by oliviergoulet5** [comment]
@kineticsquid Apologies for the delay. At the moment, my focus is directed towards addressing some other high-priority tasks. I will have time to revisit this next week.

**Comment by kineticsquid** [comment]
@amvanbaren Hold off on this. We have a broader discussion underway regarding a separate site for the working group.

**Comment by amvanbaren** [comment]
@kineticsquid This issue is blocking deployments. What's the status?

**Comment by oliviergoulet5** [comment]
@amvanbaren Feel free to reset or revert the commits. I have them on my fork, so we can always re-add them later if needed.

**Comment by kineticsquid** [comment]
@oliviergoulet5 Today @croundy @chrisguindon @amvanbaren and I went over the current implementation. We agreed on the following updates when you get a moment:

Members page:
- Remove the member classification as this refers to their foundation status vs their working group status. I think simple tiles with no heading is fine.
- Because some of the icons are transparent, they don't show up well on a dark background. Suggest adding a white background behind the icons. My screen cap below.
- Squash the layout a bit, maybe two rows of three
- Move the call to action to the top of the page
- Add links to the members that don't have them. All the links should point to their EF membership page, e.g. https://www.eclipse.org/membership/showMember.php?member_id=1380
<img width="879" alt="Screenshot 2023-11-02 at 12 28 02 PM" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/555156b7-8da8-425d-aa6a-7627901eecef">

Adopters page:
- Move the call to action to the top of the page.
- These links are fine as they may not be EF members.

**Comment by chrisguindon** [comment]
@oliviergoulet5 Can you find some time next week to finalize this task please based on the changes that @kineticsquid is requesting?

**Comment by amvanbaren** [comment]
@kineticsquid, you can see @oliviergoulet5's changes at staging.open-vsx.org. What do you think?

**Comment by kineticsquid** [comment]
@oliviergoulet5 A couple more details.
- On the Adopters page, can you move the call to action button to the top after the text.
- On the Members page, the links for ST, Siemens, and SalesForce should go the their EF member pages
- Likely a nit: On FF (I'm using dark background) I get a bright flash of a completely white page for about a second before the page renders. Happens for both Members and Adopters. I tried Safari and Chrome and I don't see the same behavior.

**Comment by amvanbaren** [comment]
@kineticsquid You can view the changes on staging.open-vsx.org. Do you still get a bright flash?

**Comment by kineticsquid** [comment]
All gone, thanks!

**Comment by kineticsquid** [comment]
Nice work @amvanbaren @oliviergoulet5
