### ISSUE TITLE
move extensions to a different namespace

### ISSUE THREAD

**Issue by martinlippert** [EclipseFdn/open-vsx.org#2016]
I would like to move all five extensions under the `Pivotal` namespace to the `VMware` namespace. Can you help me with that? That would be awesome.

**Comment by kineticsquid** [comment]
@amvanbaren Can you sanity check me on this? `Pivotal` namespace has 5 published extensions, `VMWare` has none. I believe I can change the `Pivotal` namespace to `VMWare` and choose the merge option to effectively move the extensions. Sound right?

**Comment by amvanbaren** [comment]
yes, sounds right. just give it some time for the namespace change to complete.

**Comment by martinlippert** [comment]
@kineticsquid + @amvanbaren Thanks a lot for your help here. Let me know as soon as the extensions have been moved over, then I will go ahead and publish new versions to get the marketplace up-to-date again

**Comment by kineticsquid** [comment]
@amvanbaren I submitted this namespace change/merge `Pivotal` > 'VMWare` yesterday at about 16:00 CEST. I looked this morning and things are status quo ante. Do you see anything in the logs?

**Comment by martinlippert** [comment]
Any news on this? The new release is not now and I would love to push out the new versions once the extensions have moved... :-)

**Comment by kineticsquid** [comment]
@martinlippert It looks like these extensions are finally moved. @amvanbaren is there a scenario here in which this background process could have taken days to complete?

**Comment by amvanbaren** [comment]
@kineticsquid Yes, the job is retried 10 times using an exponential backoff strategy.

**Comment by martinlippert** [comment]
@kineticsquid @amvanbaren Yes, the extensions got moved to the new namespace, so everything looks excellent now. And I updated the extensions to the latest versions as well, so let me close this issue here. Many many thanks again for your help with this, much appreciated!!!
