### ISSUE TITLE
Claiming namespace Querix

### ISSUE THREAD

**Issue by qxalsh** [EclipseFdn/open-vsx.org#2017]
Querix is a big multi-cultural company with a long history, which legally owns the Querix domain (https://querix.com). The company is officially registered in the United Kingdom. We have an official VS-Code marketplace and we want to add our product to the OpenVSX platform because we want to make installation possible on projects such as a code server.

**Comment by kineticsquid** [comment]
@qxalsh Thanks for your contribution!
