### ISSUE TITLE
Claiming namespace meximized

### ISSUE THREAD

**Issue by meximized** [EclipseFdn/open-vsx.org#2018]
Hi! I've recently published my first extension package in order to make the onboarding process for my colleagues more simple. I'd like to claim ownership of the namespace I've created to prevent unauthorized commits and to manage contributors by myself (and to remove the warning sign from the extension page because I think it can confuse people). Much appreciate your work, I find publishing extension process simple and thoughtful!

**Comment by kineticsquid** [comment]
@meximized Thanks for your contribution!
