### ISSUE TITLE
Claiming namespace jetpack-io

### ISSUE THREAD

**Issue by loreto** [EclipseFdn/open-vsx.org#2025]
I'm the founder of `jetpack.io`. We own the domain `jetpack.io` and we currently publish an extension in the VSCode extension marketplace as `jetpack.io`: https://marketplace.visualstudio.com/items?itemName=jetpack-io.devbox

We'd like to claim the same namespace in the VSX marketplace, hence this request.

**Comment by kineticsquid** [comment]
@loreto Good to have you!

**Comment by loreto** [comment]
Hi OpenVSX team,

We had to rename our company from Jetpack.io to Jetify. As a result we also changed our domain name from jetpack.io to jetify.com

You can see that we already changed the name and domain in the official VSCode extension marketplace: https://marketplace.visualstudio.com/items?itemName=jetpack-io.devbox

Would you be able to help us rename our namespace in OpenVSX to `Jetify`?

**Comment by loreto** [comment]
Opening a new issue instead.
