### ISSUE TITLE
Claim namespace ownership

### ISSUE THREAD

**Issue by ppnoufal** [EclipseFdn/open-vsx.org#2029]

**Comment by kineticsquid** [comment]
@ppnoufal what namespace?

**Comment by ppnoufal** [comment]
yes, it's for open-vsx.org deployment

**Comment by kineticsquid** [comment]
What is the namespace you are requesting to own?

**Comment by ppnoufal** [comment]
![image](https://github.com/EclipseFdn/open-vsx.org/assets/56575670/1350e6d3-2976-4eb2-b767-ec537c47d4ca)

namespace: noufalpp
