### ISSUE TITLE
Claiming namespace for learn-pack/learnpack-vscode

### ISSUE THREAD

**Issue by alesanchezr** [EclipseFdn/open-vsx.org#2030]
I'm the owner of https://open-vsx.org/extension/learn-pack/learnpack-vscode

You can see I'm one of the [most significant contributors](https://github.com/learnpack/vscode/graphs/contributors).
I published the last commit: https://github.com/learnpack/vscode/commits/master

[I also published the first commit](https://github.com/learnpack/vscode/commit/b5b814f4ed23bbc14c90498778d942347510b603)

**Comment by kineticsquid** [comment]
@alesanchezr Are you asking about namespace 'learn-pack'? If so, it is currently owned by @tommygonzaleza

**Comment by kineticsquid** [comment]
@alesanchezr ^^^^

**Comment by tommygonzaleza** [comment]
Hello, it's correct, @alesanchezr is the owner

**Comment by kineticsquid** [comment]
@tommygonzaleza Thanks!

@alesanchezr I've made you owner and @tommygonzaleza a contributor. You're free to make leave them as is, make an owner, or remove.
