### ISSUE TITLE
Claiming namespace htmlhint

### ISSUE THREAD

**Issue by coliff** [EclipseFdn/open-vsx.org#2036]
Hello! I'd like to claim the namespace htmlhint as I'm a maintainer of the HTMLHint VS Code Extension and a core member of the HTMLHint team (https://github.com/orgs/htmlhint/teams/core)

https://marketplace.visualstudio.com/items?itemName=HTMLHint.vscode-htmlhint&ssr=false#overview

I've created the htmlhint namespace at: https://open-vsx.org/user-settings/namespaces and would like to publish the extension to the Open VSX Registry.

Thanks!

**Comment by kineticsquid** [comment]
@coliff Good to have you!

**Comment by coliff** [comment]
thanks! Got it published: https://open-vsx.org/extension/htmlhint/vscode-htmlhint
