### ISSUE TITLE
Unpublish redhat.vscode-rhoas

### ISSUE THREAD

**Issue by fbricon** [EclipseFdn/open-vsx.org#2038]
Red Hat shut down RHOSAK, its Managed Kafka offering, making redhat.vscode-rhoas useless. I've already unpublished it from the Microsoft VS Code Marketplace and [archived its repo](https://github.com/redhat-developer/vscode-rhoas#readme), now I want to do the same for Open VSX.
Can you please unpublish it?

**Comment by kineticsquid** [comment]
Done.

**Comment by fbricon** [comment]
Thanks @kineticsquid
