### ISSUE TITLE
Publisher's extensions list: current versions; details pages: old version, including actual link

### ISSUE THREAD

**Issue by sjsepan3** [EclipseFdn/open-vsx.org#2050]
https://open-vsx.org/user-settings/extensions
- 7 out of 9 entries in the publisher's (my) listing show current versions, while the details page show an older version and links to the older version
- those same 7 out of 9 entries do not have icons visible, even though they were visible on earlier publishing attempts

name,                    pub. list v,     details v,.  link
sjsepan-humanelike,      0.0.6,           0.0.5,       https://open-vsx.org/extension/sjsepan/sjsepan-humanelike
sjsepan-blueish,         0.0.3 ,          0.0.2,       https://open-vsx.org/extension/sjsepan/sjsepan-blueish
sjsepan-greenish,        0.0.3 ,          0.0.2,       https://open-vsx.org/extension/sjsepan/sjsepan-greenish
sjsepan-reddish,         0.0.3 ,          0.0.2,       https://open-vsx.org/extension/sjsepan/sjsepan-reddish
vscode-smallvisualbasi,c 0.0.4 ,          0.0.2,       https://open-vsx.org/extension/sjsepan/vscode-smallvisualbasic
vscode-xsharp ,          0.0.4,           0.0.2,       https://open-vsx.org/extension/sjsepan/vscode-xsharp
vscode-jsharp,           0.0.4,           0.0.2,       https://open-vsx.org/extension/sjsepan/vscode-jsharp

-I *have* cleared my cache, but the condition remains

**Comment by kineticsquid** [comment]
@sjsepan3 For the 7 entries in question, on your /user-settings/extensions page, do any of them show as 'Deactivated'? Like this:
<img width="268" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/2ea479dc-6ffb-4fa6-a19b-91709d2e4a98">

**Comment by sjsepan3** [comment]
![Screenshot from 2023-08-14 21-08-34](https://github.com/EclipseFdn/open-vsx.org/assets/121126599/386ab698-86f1-4366-bc04-29639cbb4501)

Mu listing shows me only the most recent -- if there are older versions, they do not seem to be visible to me in the view illustrated.

**Comment by sjsepan3** [comment]
![Screenshot from 2023-08-14 21-11-51](https://github.com/EclipseFdn/open-vsx.org/assets/121126599/daf15780-26fb-4a10-87b0-ed4397a0dd9e)

In this example of one of the detail pages, which is what is directly linked from the list view, I do not notice any indication that this  (older) version is deactivated.

**Comment by kineticsquid** [comment]
@sjsepan3 Thanks, that answered my question. A deactivated extension version will show up on the /user-settings/extensions page and I don't see that on the screen cap above. 

Looking specifically at XSharp, you have published 2 versions, `0.0.2` and `0.0.4`, you can see `0.0.4` from your settings but clicking on that tile from your settings page takes you to the extension details page where you see only `0.0.2`. Is that correct? 

Just out of curiosity, what changes did you make from `0.0.2` to `0.0.4`, any changes to `package.json`?

Do you get any error messages when you publish with `npx osvx publish ... --debug`?

**Comment by sjsepan3** [comment]
Yes, that is correct; the list show 0.0.4 and the detail shows 0.0.2.

I will have to check my Git to see what the changes were, but its likely there will some in package.json. I will try to follow up with that info.

I cannot test the npx stuff (yet) because the machine I used is not available. ( I built a new system this week, and  moved my home drive  to it, but not all of the tools are installed on the new machine, yet. The older machine is re-purposed.

**Comment by kineticsquid** [comment]
To get the debug information you need to use the command line. And I make this mistake all the time. It's `ovsx` not `osvx`. You can confirm your installed node stuff with `npm list`.

**Comment by sjsepan3** [comment]
the publish w/ debug output looks like
```
$npx ovsx publish sjsepan.vscode-xsharp-0.0.4.vsix --debug --pat  [redacted]
Error: Extension sjsepan.vscode-xsharp 0.0.4 is already published, but currently isn't active and therefore not visible.
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/ovsx/lib/registry.js:185:40)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by sjsepan3** [comment]
I'm not sure what the context of 'npm list' should be. When run from the publish location, I get 
`/home/sjsepan/Projects/VSCode/sjsepan.vscode-xsharp
└── (empty)
`

**Comment by kineticsquid** [comment]
@sjsepan3 The publishing error above is because that version is already published, but not activated because of some error. This is more or less what I expected. But it's odd that it's not showing up that way on your settings page. 

Rev the version number on `package.json` to, say, `0.0.5` and try again to publish with the `--debug` option.

If you're able to give me access to this repo, I'll clone it and experiment a bit to see what's going on.

**Comment by sjsepan3** [comment]
> If you're able to give me access to this repo, I'll clone it and experiment a bit to see what's going on.

Let me know if you are unable to clone from the repo, which is at :
[]((https://gitlab.com/sjsepan/sjsepan.vscode-xsharp))

**Comment by sjsepan3** [comment]
> Rev the version number on `package.json` to, say, `0.0.5` and try again to publish with the `--debug` option.

@kineticsquid
OK, did that...
`0.0.5.vsix --debug --pat [redacted]`
`🚀  Published sjsepan.vscode-xsharp v0.0.5`
Will check the listings and see the outcome...

**Comment by kineticsquid** [comment]
Thanks, I can see the repo. I'll poke at this a bit.

**Comment by kineticsquid** [comment]
@sjsepan3 I cloned your repo and made one change: `"publisher": "kineticsquid",`. Package and published. Worked for me: https://open-vsx.org/extension/kineticsquid/vscode-xsharp. I suspect this is having something to do with your changes to `package.json`. Can you show me what they were?

**Comment by sjsepan3** [comment]
Early on, after I cloned the original extension, and before I published here (I think), the original version# was higher (1.0.3) and the published id I was using for extensions was a guid. While learning how to publish, I observed that the guid was not going to be very user-friendly, and I really had no reason to carry over the version like I had carried-over the license. I also added some more metadata.
![Screenshot from 2023-08-17 15-27-25](https://github.com/EclipseFdn/open-vsx.org/assets/121126599/78e5b69f-d1e7-442e-a31b-a7f855aac77b)


Between v 0.0.2 and 0.0.3 I fixed the repo url from github to gitlab (it was never on github).

Other than version numbers, the package has not changed much.

**Comment by kineticsquid** [comment]
@sjsepan3 OK, I made a bit of progress. I added myself to your namespace as a contributor (one of my super powers). Then I attempted to publish to your  namespace your most recent version, the one I successfully published to my namespace. That failed. I noticed that there were several versions published in your namespace since `0.0.2` that were not active. So I deleted all the deactivated versions, leaving only `0.0.2`. I then attempted again to publish your most recent code as `0.0.4`. That worked. You can see that here: https://open-vsx.org/extension/sjsepan/vscode-xsharp. I'm wondering if there was an error in one of the deactivated versions that somehow put things in a bad state. To be sure, I tried again with `0.0.5`. That worked.

Can you try now to publish another version of sjsepan/vscode-xsharp.

**Comment by sjsepan3** [comment]
@kineticsquid 
OK, that appeared to have worked -- 0.0.6 is published in the list AND detail; the icon appears in the list item.

So, for the others...rather than bumping the version on all of them (which will require me pushing Git updates to two online repos (GitLab and Codeberg), and publishing to both OVSX and the VSCE / MS marketplace) ... can I just attempt to unpublish the older version that are causing the 'log-jam', as it were?

**Comment by kineticsquid** [comment]
@sjsepan3 Unfortunately you can't unpublish, that is something I need to do.  For each of the remaining extensions, here's what I did:
- sjsepan-humanelike, kept `0.0.5`, removed `0.0.6`
- sjsepan-blueish, kept `0.0.2`, removed `0.0.3`
- sjsepan-greenish, kept `0.0.2`, removed `0.0.3`
- sjsepan-reddish, kept `0.0.2`, removed `0.0.3`
- vscode-smallvisualbasi, kept `0.0.2`, removed `0.0.3` and `0.0.4`
- vscode-jsharp, kept `0.0.2`, removed `0.0.3` and `0.0.4`

Would you try now to re-publish.

**Comment by sjsepan3** [comment]
> Would you try now to re-publish.

Understood; will update you with the results...

**Comment by kineticsquid** [comment]
Tracking this general issue in #2062

**Comment by kineticsquid** [comment]
@sjsepan3 I agree there appears to be some funniness with the caching. Let's treat that separately. Thanks for your patience.

**Comment by netomi** [comment]
fyi: the personal access token with description `Publishing token` has been revoked as it was posted to this issue.

**Comment by sjsepan3** [comment]
> fyi: the personal access token with description `Publishing token` has been revoked as it was posted to this issue.

OK, but where? I don't see it. The only thing close that I see are publisher id and id in a screenshot, but neither are my token.

**Comment by netomi** [comment]
There have been edits to this issue, secret scanning issued an alert with a valid token so it was reverted, just fyi.
