### ISSUE TITLE
Claiming namespace Rej

### ISSUE THREAD

**Issue by Rejdesu** [EclipseFdn/open-vsx.org#2051]
I am wanting to claim ownership of the namespace [Rej](https://open-vsx.org/namespace/Rej). 

I want to be able to maintain my extensions and themes on Open VSX Registry. 

You can also find my namespace on the [Virtual Studio Marketplace](https://marketplace.visualstudio.com/publishers/Rej) and on my [GitHub](https://github.com/Rejdesu).

**Comment by kineticsquid** [comment]
@Rejdesu Good to have you!
