### ISSUE TITLE
Claiming namespace AndrewButson

### ISSUE THREAD

**Issue by arbs-io** [EclipseFdn/open-vsx.org#2053]
I have AndrewButson as the publisher name (my rl-name). This was reserved by my code signing cert for some visual studio extensions. I have kept the publisher for all of my vs-code extensions. I have recently published vscode-openai as a few requests have been made to add the extension for VSCodium.

Extension: 
- github: [https://github.com/arbs-io/vscode-openai](https://github.com/arbs-io/vscode-openai)
- open-vsx: [open-vsx.org](https://open-vsx.org/extension/AndrewButson/vscode-openai)
- vs-code: [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=AndrewButson.vscode-openai)

**Comment by kineticsquid** [comment]
@arbs-io Welcome!
