### ISSUE TITLE
Claiming namespace AnthonyFuller

### ISSUE THREAD

**Issue by AnthonyFuller** [EclipseFdn/open-vsx.org#2054]
I created this namespace, and have published an extension under this namespace, which is also on the VSC marketplace.

GitHub of the extension: https://github.com/AnthonyFuller/vscode-mnscript
VSC Marketplace for the extension: https://marketplace.visualstudio.com/items?itemName=AnthonyFuller.mnscript

**Comment by kineticsquid** [comment]
@AnthonyFuller Thanks for your contribution!
