### ISSUE TITLE
Claiming namespace JScearcy

### ISSUE THREAD

**Issue by JScearcy** [EclipseFdn/open-vsx.org#2060]
This namespace is my Github username, and I've published the `rust-doc-viewer` extension in the Visual Studio marketplace [here](https://marketplace.visualstudio.com/items?itemName=JScearcy.rust-doc-viewer), and to open-vsx [here](https://open-vsx.org/extension/JScearcy/rust-doc-viewer)

**Comment by kineticsquid** [comment]
@JScearcy Welcome!
