### ISSUE TITLE
Delete extension from personal namespace

### ISSUE THREAD

**Issue by xsebek** [EclipseFdn/open-vsx.org#2071]
Hi, could you please delete swarm-language from my personal namespace?

https://open-vsx.org/extension/xsebek/swarm-language

<sup>(The right one is https://open-vsx.org/extension/swarm-game/swarm-language.)</sup>

If there is a way to delete the extension myself, that would be great too. There is a button for that on Visual Studio Marketplace and it seems like an oversight that such a simple feature is not (easily found?) here.

**Comment by kineticsquid** [comment]
Done.
