### ISSUE TITLE
Request to unpublish Ionic and Nuxtr extension

### ISSUE THREAD

**Issue by zhaolinlau** [EclipseFdn/open-vsx.org#2072]
Request to unpublish the following extensions:

![image](https://github.com/EclipseFdn/open-vsx.org/assets/68846168/a742c2bb-4cf5-4edf-84d9-7ca191dd017c)

[Nuxtr](https://open-vsx.org/extension/Nuxtr/nuxtr-vscode)

[Ionic](https://open-vsx.org/extension/Ionic/ionic)

**Comment by kineticsquid** [comment]
Done.

**Comment by adhamfarrag** [comment]
@zhaolinlau Thanks for wanting to put Nuxtr on Open VSX. I just noticed it and I appreciate your interest and effort. :)

**Comment by zhaolinlau** [comment]
the ionic one is not removed yet
