### ISSUE TITLE
delete KoichiSasada/vscode-rdbg

### ISSUE THREAD

**Issue by 0x7A74626C77** [EclipseFdn/open-vsx.org#2075]
i thought i could delete on my own and uploaded a package i didn't write. Please delete this package

**Comment by kineticsquid** [comment]
@0x7A74626C77 unfortunately I can't delete this as it is bundled by `andrewmcodes.rails-extension-power-pack-1.0.0`. @andrewmcodes FYI.

**Comment by kineticsquid** [comment]
@andrewmcodes @ @0x7A74626C77 FYI

**Comment by kineticsquid** [comment]
@andrewmcodes @0x7A74626C77 ^^^^

**Comment by kineticsquid** [comment]
closing for lack of response
