### ISSUE TITLE
Claiming namespace [Sorae]

### ISSUE THREAD

**Issue by Sorae** [EclipseFdn/open-vsx.org#2078]
Hi!
I'm the developer of the [vscode-escoria](https://marketplace.visualstudio.com/items?itemName=sorae.vscode-escoria&ssr=false#overview) extension on the MS Marketplace and I just push a [first release to the OpenVSX registry](https://open-vsx.org/extension/sorae/vscode-escoria).

The extension is published from this repository https://github.com/Sorae/vscode-escoria that I own.

Would it be possible to claim the namespace "sorae" on OpenVSX?

Thanks

**Comment by kineticsquid** [comment]
@Sorae Thanks for your contibution!
