### ISSUE TITLE
Claiming namespace kittycad

### ISSUE THREAD

**Issue by jessfraz** [EclipseFdn/open-vsx.org#2081]
Hi I work @kittycad (https://github.com/kittycad) I am the CEO. We are publishing a new extension for our programming language we are about to launch soon.

I wrote an lsp server for it. https://github.com/KittyCAD/kcl-lsp

It is a functional language for mechanical CAD design. Thanks!

**Comment by kineticsquid** [comment]
@jessfraz Good to have you!
