### ISSUE TITLE
Claiming namespace codacy-app

### ISSUE THREAD

**Issue by alerizzo** [EclipseFdn/open-vsx.org#2083]
I am a Lead Engineer at [Codacy](https://www.codacy.com/) and the primary developer and maintainer of the [Codacy VisualStudio Code Extension](https://github.com/codacy/codacy-vscode-extension). I'm also the owner of[ codacy-app publisher at Visual Studio Marketplace](https://marketplace.visualstudio.com/publishers/codacy-app).

**Comment by kineticsquid** [comment]
@alerizzo Welcome!
