### ISSUE TITLE
Claiming namespace [k2view]

### ISSUE THREAD

**Issue by safisa** [EclipseFdn/open-vsx.org#2090]
Hi,
I am working at K2View, and I am developing vscode extensions for Theia use.
I want to publish them to our on-prem instance of open VSX. 
I published a test extension to the on-prem instance and I am seeing a warning message: That user account is not a verified publisher of the namespace “k2view” of this extension.
So do I need also to do this claim namespace ownership for our on-prem open vsx instance?

Thanks

**Comment by kineticsquid** [comment]
@safisa I'm not sure what you mean by your on-prem instance. I can only handle admin stuff for open-vsx.org. I've created namespace `k2view`. I cannot assign it to you until you sign the publisher agreement.

**Comment by kineticsquid** [comment]
@safisa ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
