### ISSUE TITLE
Claiming namespace alexravenna

### ISSUE THREAD

**Issue by alexravenna** [EclipseFdn/open-vsx.org#2095]
I previously published my [VS Code theme](https://open-vsx.org/extension/alexravenna/monokai-dimmed-vibrant) on the [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=alexravenna.monokai-dimmed-vibrant) under the same publisher name and am the owner of the [repository](https://github.com/alexravenna/vscode-dimmed-vibrant) for it.

**Comment by kineticsquid** [comment]
@alexravenna Welcome!
