### ISSUE TITLE
Claiming namespace typescript-nameof

### ISSUE THREAD

**Issue by manuth** [EclipseFdn/open-vsx.org#2096]
For my project "TypeScript `nameof`", which is [available on GitHub](https://github.com/typescript-nameof/nameof), I'd love to claim ownership of the namespace `typescript-nameof`.

As I hope to let this project be community-driven, I think it's apropriate to use a dedicated namespace for it instead of my personal `manuth` namespace.

**Comment by kineticsquid** [comment]
@manuth Welcome!
