### ISSUE TITLE
Claiming namespace saurabh

### ISSUE THREAD

**Issue by saurabhdaware** [EclipseFdn/open-vsx.org#2097]
Heya I just published my extension on open-vsx under namespace `saurabh`

I have also published the same extension under same namespace on vscode marketplace - https://marketplace.visualstudio.com/items?itemName=saurabh.abell-language-features

You can probably verify it by 
- checking the email of publisher there. It will match the email of my open-vsx account.
- or checking the github link on vscode marketplace which links to the github org account abell that I created

Let me know if there is any other information needed. Thanks!

**Comment by kineticsquid** [comment]
@saurabhdaware Good to have you!
