### ISSUE TITLE
Unpublishing request for `ms-azuretools.vscode-docker`

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#2100]
The latest version is broken (1.26.1) because of an issue with packaging on our side. We have fixed that now, and I would like to republish this version. 

https://open-vsx.org/extension/ms-azuretools/vscode-docker/1.26.1

**Comment by kineticsquid** [comment]
@filiptronicek Done. But... I think we have a new bug in the admin code. @amvanbaren 

I selected the one version to remove and all the published versions were removed.

**Comment by kineticsquid** [comment]
Opened https://github.com/eclipse/openvsx/issues/809.
