### ISSUE TITLE
Claiming namespace bithappens

### ISSUE THREAD

**Issue by bithappens** [EclipseFdn/open-vsx.org#2106]
I am the author of an extension (see [the project on github](https://github.com/bithappens/vscode-plain-sidebar)). I also own the corresponding extension in the [vs code marketplace](https://marketplace.visualstudio.com/items?itemName=bithappens.vscode-plain-sidebar). It would be nice to publish the extension on open-vsx with the same namespace.

Thanks a lot in advance.

**Comment by kineticsquid** [comment]
Brilliant name!
