### ISSUE TITLE
Claiming namespace NikolaiKudasovfizruk

### ISSUE THREAD

**Issue by fizruk** [EclipseFdn/open-vsx.org#2108]
I have the corresponding publisher name in VS Code Marketplace, and maintain [`vscode-rzk` extension](https://github.com/rzk-lang/vscode-rzk) for Rzk proof assistant, which I would like to make available in Open VSX Registry as well (prompted by request from users of Rzk).

**Comment by kineticsquid** [comment]
@fizruk Granted!
