### ISSUE TITLE
ISSUE: can not be granted rights over personal use of others data

### ISSUE THREAD

**Issue by mskelleygvt** [EclipseFdn/open-vsx.org#2118]

**Comment by kineticsquid** [comment]
@mskelleygvt Can you provide more detail here. I'm sure I understand the issue you're raising.

**Comment by mskelleygvt** [comment]
> @mskelleygvt Can you provide more detail here. I'm sure I understand the issue you're raising.

cloned version of data used  and unauthorizated and privacy rights violated.. working to explain but noticed a counter placed within this registery
![Screenshot (72)](https://github.com/EclipseFdn/open-vsx.org/assets/136962588/245904c3-0597-4d49-9f38-2a0b9ea21294)
![Screenshot (73)](https://github.com/EclipseFdn/open-vsx.org/assets/136962588/5a5b56ef-cb79-49ad-b873-911c38802844)
![Screenshot (74)](https://github.com/EclipseFdn/open-vsx.org/assets/136962588/3802b5f1-6866-4d22-bb88-99e1df5e4eaf)

**Comment by kineticsquid** [comment]
@mskelleygvt I'm sorry, I'm still not seeing the issue. Do you believe an extension published to open-vsx.org is misusing personal data? If so, which extension? Or that the site itself is?

**Comment by kineticsquid** [comment]
@mskelleygvt ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
