### ISSUE TITLE
Claiming namespace l3aalteshuva

### ISSUE THREAD

**Issue by vecnathewhisperd** [EclipseFdn/open-vsx.org#2123]

**Comment by kineticsquid** [comment]
@vecnathewhisperd I've created the namespace `l3aalteshuva` but I can't assign you ownership. Have you signed the publisher's agreement?

**Comment by kineticsquid** [comment]
@vecnathewhisperd ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
