### ISSUE TITLE
Claiming namespace brian-team

### ISSUE THREAD

**Issue by mstimberg** [EclipseFdn/open-vsx.org#2128]
Hi. I am the lead developer of the ["Brian simulator"](https://briansimulator.org) which we develop under the `brian-team` organisation on GitHub: https://github.com/brian-team.

I'd like to claim the `brian-team` namespace, so that we can use it to publish our forthcoming VS Code extension (https://github.com/brian-team/brian-code-editor) under this name. Thanks!

**Comment by kineticsquid** [comment]
@mstimberg Good to have you!
