### ISSUE TITLE
Claiming namespace semanticdiff

### ISSUE THREAD

**Issue by slackner** [EclipseFdn/open-vsx.org#2129]
Hello everyone,

I'm one of the co-founders and developers of https://semanticdiff.com/, and I'd like to claim the `semanticdiff` namespace to make sure users can easily recognize our official plugin.

I've decided to publish to Open-VSX due to user requests, e.g. [this](https://github.com/Sysmagine/SemanticDiff/issues/44) one we got recently. The extension is already available [here](https://open-vsx.org/extension/semanticdiff/semanticdiff).

Please let me know if you need any additional information to validate ownership. You can send an email to support@semanticdiff.com, for example.

Best Regards,
Sebastian Lackner

**Comment by kineticsquid** [comment]
@slackner Thanks for your contribution!
