### ISSUE TITLE
Claiming namespace lexical-lsp

### ISSUE THREAD

**Issue by Blond11516** [EclipseFdn/open-vsx.org#2140]
Lexical is a recently created language server for the Elixir programming language. I am the primary author and maintainer of the VSCode extension for said language server, which is published on the VSCode marketplace under the same namespace.

Language server repository: https://github.com/lexical-lsp/lexical
VSCode extension repository: https://github.com/lexical-lsp/vscode-lexical
VSCode extension marketplace link: https://marketplace.visualstudio.com/items?itemName=lexical-lsp.lexical

**Comment by kineticsquid** [comment]
@Blond11516 Welcome!
