### ISSUE TITLE
Claiming namespace icyleaf

### ISSUE THREAD

**Issue by icyleaf** [EclipseFdn/open-vsx.org#2141]
I am developer and user of code server, i [forked](https://open-vsx.org/extension/icyleaf/gatito-theme-fork) [Gatito Theme](https://github.com/pawelgrzybek/gatito-theme) to Open VSX and want use it, but author [no response](https://github.com/pawelgrzybek/gatito-theme/issues/17) for a long time. Thanks.

**Comment by kineticsquid** [comment]
@icyleaf Thanks for your contribution!
