### ISSUE TITLE
Unpublish request for the latest version of `ms-python.python` (`2023.18.0`)

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#2142]
The latest version of the extension has been published without its bundled libraries (same as https://github.com/EclipseFdn/open-vsx.org/issues/2132 last week), which we have corrected in our build step now as well in https://github.com/open-vsx/publish-extensions/commit/87c52764cb53a8eed3cb09d940e1907a18670374.

cc @kineticsquid

**Comment by kineticsquid** [comment]
Done!
