### ISSUE TITLE
Claiming namespace paulober

### ISSUE THREAD

**Issue by paulober** [EclipseFdn/open-vsx.org#2149]
That's my GitHub account and I also use it to publish in the Microsoft Visual Studio Code Marketplace (where I'm verified).

**Comment by paulober** [comment]
One additional question: is it possible to change the supported platforms of my extension listing in Open-VSX like in the MS VS Code Marketplace?

**Comment by kineticsquid** [comment]
@paulober Welcome!

**Comment by kineticsquid** [comment]
@paulober I'm not sure of the answer to your question about changing the supported platforms. This is likely a better question on https://github.com/eclipse/openvsx. Can you ask it there?
