### ISSUE TITLE
Claiming namespace mofosyne

### ISSUE THREAD

**Issue by mofosyne** [EclipseFdn/open-vsx.org#2153]
Just logged in to https://open-vsx.org/ and aiming to upload https://github.com/mofosyne/vscode-quickcalc

**Comment by mofosyne** [comment]
Okay published https://open-vsx.org/extension/mofosyne/quickcalc and just need to be verified as a real person

**Comment by kineticsquid** [comment]
@mofosyne Thanks for your contribution!
