### ISSUE TITLE
Claiming namespace levrotech

### ISSUE THREAD

**Issue by levrotech** [EclipseFdn/open-vsx.org#2154]
I have already published my VS Code extension "[Znippets](https://github.com/levrotech/zig-znippets)" on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=levrotech.zig-znippets). However, I also want to contribute to OSS by publishing my extension in open-vsx.org. By claiming the namespace "levrotech", I can ensure that my extension is the only one that is published under that namespace. This will help to avoid confusion for users and make it easier for them to find my extension.

I am committed to supporting my extension and contributing to the open-vsx community. I hope that you will approve my request to claim the namespace "levrotech".

**Comment by kineticsquid** [comment]
@levrotech Welcome!

**Comment by levrotech** [comment]
Thank you so much 🙏 I'll working on publishing my extension right away!
