### ISSUE TITLE
Claiming namespace [Cosine]

### ISSUE THREAD

**Issue by SamStenner** [EclipseFdn/open-vsx.org#2156]
Hey! I'm the CTO and co-founder of [Cosine](https://cosine.sh)

Our product is a VS Code extension, which we've published on the official [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Cosine.cosine-vscode) (under the official 'Cosine' namespace over there). We've had feedback that some users would prefer to access our tool via OpenVSX.

Our official company name is Cosine. We would like to claim this namespace to provide authenticity for our product.

Many thanks!
Sam

**Comment by kineticsquid** [comment]
@SamStenner Good to have you!
