### ISSUE TITLE
drop duplicate Database Client extensions

### ISSUE THREAD

**Issue by GitMensch** [EclipseFdn/open-vsx.org#2161]
This report goes foremost to the extension author @cweijan, but also "to the community".

There are 3 extensions [published under this namespace](https://open-vsx.org/namespace/cweijan) which _seem_ to be identical.
Please update the "main" one and drop the duplicates. To be able to be found, just use the keywords in the package.json.

Thanks for taking care!

**Comment by cweijan** [comment]
Postgresql and database client were accidentally posted by me, but since openvsx cannot delete extensions, they are there.

**Comment by GitMensch** [comment]
@cweijan Thanks for the note. I do wonder why you want to keep the "MySQL" extension because the package name is database-client2, the the repo name database-client and the extension is for general purpose (not only MySQL - or did I understood the README wrong)?

Once this is clear @kineticsquid can unpublish the duplicates.

**Comment by cweijan** [comment]
At first, this extension only supported MySQL. Support for other databases will be added in the future, but since MySQL is the most popular, it is still the main update.

**Comment by GitMensch** [comment]
ok, that's unexpected (also because MySQL and PostgreSQL are often "common" and there seems to be a plugin extension that adds Oracle via JDBC); actually it is not only unexpected but the README is really confusing then:

> # MySQL
> ## Database manager for MySQL/MariaDB, PostgreSQL, SQLite, Redis and ElasticSearch.
> This project is a database client for VSCode, supports manager **MySQL/MariaDB, PostgreSQL, SQLite, Redis, ClickHouse, 达梦**, and **ElasticSearch**, and works as an **SSH** client, boost your maximum productivity!

also in package.json:

```json
  "description": "Database manager for MySQL/MariaDB, PostgreSQL, SQLite, Redis and ElasticSearch.",
  "keywords": [
    "SQL",
    "MySQL",
    "Database",
    "Postgresql",
    "Redis"
  ],
```

and the review

> Very good, it isn't simple support mysql, it is a full supported database manager include clickhouse!! The first wonderful clickhouse vscode plugin!

but you're the publisher, not me, so I'll stop here.

As requested by @cweijan above:
> Postgresql and database client were accidentally posted by me, but since openvsx cannot delete extensions, they are there.

@kineticsquid: Can you please unpublish https://open-vsx.org/extension/cweijan/vscode-postgresql-client2 and https://open-vsx.org/extension/cweijan/vscode-database-client2?

**Comment by cweijan** [comment]
I confirm, please cancel them.

**Comment by kineticsquid** [comment]
@GitMensch @cweijan I removed https://open-vsx.org/extension/cweijan/vscode-postgresql-client2 , but when I attempted to remove https://open-vsx.org/extension/cweijan/vscode-database-client2, I see the following:

Extension cweijan.vscode-database-client2 is bundled by the following extension packs: fsimonov.awesome-backend-pack-0.0.1, fsimonov.awesome-backend-pack-0.0.4, fsimonov.awesome-backend-pack-0.0.3, oldisek.maybe-frontend-0.0.1, oldisek.maybe-frontend-2-1.0.0, fsimonov.awesome-backend-pack-0.0.5, fsimonov.awesome-backend-pack-0.0.2, oldisek.maybe-frontend-1.0.0

**Comment by kineticsquid** [comment]
@GitMensch How would you like to proceed?

**Comment by GitMensch** [comment]
If it is bundled then there is not that much we can reasonably do. @fsimonov seems to not be active on GH, but he may want to switch to the suggested extension by its author.

Does open-vsx has the option to "deprecate" extensions? In this case this should be done here.

**Comment by kineticsquid** [comment]
@GitMensch @cweijan I have email contact information for this publisher by virtue of the publisher's agreement they signed. I'll reach out to them to ask that they either un-publish their extensions or re-publish them without including your extension. 

We do not have a way to deprecate extensions today, though it is on our requirements list.

**Comment by cweijan** [comment]
It doesn't matter, if Database Client can't be unpublish, I will update the Database Client extension with the next release.

**Comment by kineticsquid** [comment]
@cweijan @GitMensch I have not heard from the publisher of the extensions that are preventing me from un-publishing your extension. So, I have unpublished the following:
```
fsimonov.awesome-backend-pack-0.0.1
fsimonov.awesome-backend-pack-0.0.4
fsimonov.awesome-backend-pack-0.0.3
oldisek.maybe-frontend-0.0.1
oldisek.maybe-frontend-2-1.0.0
fsimonov.awesome-backend-pack-0.0.5
fsimonov.awesome-backend-pack-0.0.2
oldisek.maybe-frontend-1.0.0
```

This allowed me to un-publish https://open-vsx.org/extension/cweijan/vscode-database-client2.
