### ISSUE TITLE
Claiming namespace Hutte

### ISSUE THREAD

**Issue by mmoyaferrer** [EclipseFdn/open-vsx.org#2162]
Hi,

I'm Manuel, from the Hutte organization. We created a VSCode extension which we want to publish to Open VSX (https://github.com/hutte-io/hutte-vscode-extension), hence we would like to get Hutte namespace to publish it. You can see I am member of the organization here https://github.com/orgs/hutte-io/people.

Regards,
Manuel

**Comment by kineticsquid** [comment]
@mmoyaferrer Welcome!
