### ISSUE TITLE
Claiming namespace pmd

### ISSUE THREAD

**Issue by adangel** [EclipseFdn/open-vsx.org#2164]
Hi,

I'm maintaining https://github.com/pmd/pmd and co-maintaining https://github.com/ChuckJonas/vscode-apex-pmd

I'd like to publish the vscode-apex-pmd extension on open-vsx.org as well (currently available under https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-pmd)

Regards,
Andreas

**Comment by kineticsquid** [comment]
@adangel Thanks for your contribution!
