### ISSUE TITLE
Claiming namespace chamboug

### ISSUE THREAD

**Issue by chamboug** [EclipseFdn/open-vsx.org#2168]
Hello,

I'm maintaining the extension [Javascript Auto Backticks](https://github.com/chamboug/vscode-extension-js-auto-backticks) and someone suggested in [this issue](https://github.com/chamboug/vscode-extension-js-auto-backticks/issues/15) to make it available to open-vsx.org as well. It is currently available under https://marketplace.visualstudio.com/items?itemName=chamboug.js-auto-backticks.

Regards,
Gaëtan.

**Comment by kineticsquid** [comment]
@chamboug Good to have you!
