### ISSUE TITLE
Request for Removal of Test Extension from Open VSX Registry

### ISSUE THREAD

**Issue by rizhamid** [EclipseFdn/open-vsx.org#2169]
Dear Open VSX Support Team,

I hope this message finds you well. My name is Rizwan Hamid and I am associated with the extensions related to "CloudFix Linter" hosted on the Open VSX Registry. I am writing to request the removal of three specific extensions, which were uploaded for testing purposes and are not meant for production use.

**Extensions to be Removed:**

Extension Name: CloudFix Linter (rizhamid)
URL: https://open-vsx.org/extension/rizhamid/cloudfix-linter
Extension Name: CloudFix Linter Test (krystianlieber)
URL: https://open-vsx.org/extension/krystianlieber/cloudfix-linter-test
Extension Name: CloudFix Linter (krystianlieber)
URL: https://open-vsx.org/extension/krystianlieber/cloudfix-linter

**Extension to Keep:**
Extension Name: CloudFix Linter (devfactory)
URL: https://open-vsx.org/extension/devfactory/cloudfix-linter

**Reason for Removal:**
The three extensions listed for removal were initially uploaded as tests and are not production versions. They were not intended for public use or distribution. To avoid confusion and to maintain the integrity of the registry, I kindly request the removal of these specific test extensions, while keeping the main production extension (devfactory) active.

I understand that the Open VSX Registry does not currently provide an option for self-service deletion of extensions via the user interface. Therefore, I am reaching out to you for assistance with this matter.

Please let me know if there are any additional steps I need to take or any information I need to provide to facilitate this process. Your prompt attention to this request would be greatly appreciated.

Thank you for your time and assistance. I look forward to your confirmation regarding the removal of the specified test extensions.

Best regards,
Rizwan Hamid
rizwan.hamid@aurea.com

**Comment by krystian-lieber** [comment]
I second this request; please remove the extensions that I had uploaded but are no longer needed.

**Comment by kineticsquid** [comment]
@krystian-lieber @rizhamid Removed the three versions above and left https://open-vsx.org/extension/devfactory/cloudfix-linter.
