### ISSUE TITLE
Who/where auto-publishes cdt-gdb-vscode?

### ISSUE THREAD

**Issue by jonahgraham** [EclipseFdn/open-vsx.org#2171]
Who or where does the auto-publishing of https://open-vsx.org/extension/eclipse-cdt/cdt-gdb-vscode happen?

The project has done some significant refactoring of the extension and I want to understand how it goes from the [source](https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode) in GitHub to the extension on open-vsx.

**Comment by thegecko** [comment]
I'm not aware of any auto-publishing for that extension, there aren't any obvious CI tasks.

For reference, other extensions use org secrets and github actions to undertkae this:

https://github.com/eclipse-cdt-cloud/vscode-memory-inspector/blob/main/.github/workflows/ci.yml#L50

https://github.com/eclipse-cdt-cloud/vscode-websocket-adapter/blob/main/.github/workflows/ci.yml#L52

**Comment by jonahgraham** [comment]
Very weird - someone/somewhere does publish it because if I tag the repo the next day that tagged version gets published. I would be happy to change to do it explicitly.

**Comment by thegecko** [comment]
This is strange. I can see its published to open-vsx, but not the vscode marketplace.

As it is published under the `eclipse-cdt` namespace, I assume it needs to use the same key as the other extensions we have there.

cc @heurtematte

**Comment by planger** [comment]
Very weird indeed. I can't recall any job that publishes `cdt-gdb-vscode` to OpenVSX.

**Comment by kineticsquid** [comment]
There's an auto-publishing job that runs nightly from https://github.com/open-vsx/publish-extensions/actions. `cdt-gdb-vscode` is included in the list of extensions that get auto-published: https://github.com/open-vsx/publish-extensions/blob/d2bd58ab8b7b65aeef97a10ac349a84606061086/extensions.json#L274.
