### ISSUE TITLE
Claiming namespace metaphore

### ISSUE THREAD

**Issue by metapho-re** [EclipseFdn/open-vsx.org#2174]
I published an extension using that namespace: [https://open-vsx.org/extension/metaphore/kanagawa-vscode-color-theme](https://open-vsx.org/extension/metaphore/kanagawa-vscode-color-theme).
I am the maintainer: [https://github.com/metapho-re/kanagawa-vscode-theme](https://github.com/metapho-re/kanagawa-vscode-theme).

**Comment by kineticsquid** [comment]
@metapho-re Thanks for your contribution!
