### ISSUE TITLE
Claiming namespace Nuxtr

### ISSUE THREAD

**Issue by adhamfarrag** [EclipseFdn/open-vsx.org#2175]
Hello, I'm the creator of [Nuxtr VSCode](https://marketplace.visualstudio.com/items?itemName=Nuxtr.nuxtr-vscode) extension and [Nuxt Extension Pack](https://marketplace.visualstudio.com/items?itemName=Nuxtr.nuxt-vscode-extentions). Both of them are published under the [Nuxtr](https://marketplace.visualstudio.com/publishers/Nuxtr) publisher. I'd love to claim namespace and list both of them on Open VSX.

**Comment by kineticsquid** [comment]
@adhamfarrag It looks like @zhaolinlau is listed as a contributor. Are you familiar with this developer?

**Comment by adhamfarrag** [comment]
@kineticsquid No.

**Comment by kineticsquid** [comment]
I found an email address on Github. Let me reach out to him.

**Comment by adhamfarrag** [comment]
Thanks @kineticsquid  I think he was just trying to put publish release extensions he's uses but not associated with. https://github.com/EclipseFdn/open-vsx.org/issues/2072. But why aren't neither of them listed ? 

@zhaolinlau can you please help us reclaim the namespace ? :)

**Comment by zhaolinlau** [comment]
> Thanks @kineticsquid  I think he was just trying to put publish release extensions he's uses but not associated with. https://github.com/EclipseFdn/open-vsx.org/issues/2072. But why aren't neither of them listed ? 
> 
> @zhaolinlau can you please help us reclaim the namespace ? :) 

Of course, how can i help you?

**Comment by adhamfarrag** [comment]
@kineticsquid @zhaolinlau Is there a way to transfer ownership of namespace ?

**Comment by zhaolinlau** [comment]
> @kineticsquid @zhaolinlau Is there a way to transfer ownership of namespace ?

I have no idea and I did open an issue to remove the namespace, it seems like they did not completely remove the namespace

**Comment by kineticsquid** [comment]
@zhaolinlau I can take care of assigning the namespace. Just wanted to hear from you first. 

@adhamfarrag It is now yours.

Thanks!
