### ISSUE TITLE
Claiming namespace Shopify

### ISSUE THREAD

**Issue by andyw8** [EclipseFdn/open-vsx.org#2176]
As a Shopify employee and contributor to [vscode-ruby-lsp](https://github.com/Shopify/vscode-ruby-lsp), I am claiming the `Shopify` namespace on behalf of Shopify.

cc @vinistock and @dirceu

**Comment by kineticsquid** [comment]
@andyw8 Good to have you!

**Comment by andyw8** [comment]
@kineticsquid I want to add additional colleagues to this give them publishing permissions. Can you advise on the best way to do this? In particular:

* Can we avoid needing everyone to create an Eclipse account to sign the agreement?
* How do we add/revoke permissions when someone is joining/leaving?

**Comment by andyw8** [comment]
(and is there a way to allow anyone within the Shopify organization to publish?)

**Comment by kineticsquid** [comment]
@andyw8 As owner of the namespace, you have control over this. Open your settings, click 'NAMESPACES' and then the namespace you want to manage. You can add others as 'Owner' or 'Contributor'. You can also remove users the same way. However, anyone with permission to publish needs to have signed the publisher's agreement.
