### ISSUE TITLE
Please delete/unpublish IBM.zopendebug-profileui-3.1.0

### ISSUE THREAD

**Issue by jsswan** [EclipseFdn/open-vsx.org#2181]
I recently attempted to publish 3.1.0 versions of two extensions. One of them (`IBM.zopendebug`) published successfully, but the other (`IBM.zopendebug-profileui`) did not.

Attempting to republish the failing extension now displays this error message:
`Error: Extension IBM.zopendebug-profileui 3.1.0 is already published, but currently isn't active and therefore not visible.`

The error occurs both with the web UI and the ovsx command line tool. In both cases I am attempting to publish a pre-packaged .vsix file.

Can the failed v3.1.0 version of `IBM.zopendebug-profileui` be deleted or unpublished so that I can try again? Thanks!

**Comment by jsswan** [comment]
related to issues like #2062

**Comment by ArvinB** [comment]
@kineticsquid 
Hi John....is there anything you can do to help out with the above please?

Thanks,
Arvin

**Comment by kineticsquid** [comment]
@ArvinB Just removed 3.1.0 of `IBM.zopendebug-profileui`.

**Comment by jsswan** [comment]
Thanks, I have successfully re-published v3.1.0 again

**Comment by kineticsquid** [comment]
Excellent, thanks!

**Comment by ArvinB** [comment]
@kineticsquid 
John thank you very much!
