### ISSUE TITLE
[Bug] Emoji is invalid

### ISSUE THREAD

**Issue by wenfangdu** [EclipseFdn/open-vsx.org#2185]
```
Invalid character found in field 'description': 🏃‍♂️ Jump/Select to the Start/End of a word in VSCode (index 2)
```
When publishing an extension, open-vsx throws:
![image](https://github.com/EclipseFdn/open-vsx.org/assets/28700378/3fc422f2-dae6-4fc4-be05-7fadf39df8e8)
Which is allowed in [VS marketplace](https://marketplace.visualstudio.com/items?itemName=wenfangdu.jump).

**Comment by kineticsquid** [comment]
@wenfangdu This repo is for deployment specifics for open-vsx.org. Can you open your defect here: https://github.com/eclipse/openvsx/issues.

@amvanbaren FYI
