### ISSUE TITLE
Claiming namespace sfdc

### ISSUE THREAD

**Issue by guw** [EclipseFdn/open-vsx.org#2187]
I am working on the Bazel VS Code Java extension and would like to publish to `sfdc` namespace.
https://github.com/salesforce/bazel-vscode-java

We are using the same namespace in VS Code.
https://marketplace.visualstudio.com/items?itemName=sfdc.bazel-vscode-java

**Comment by kineticsquid** [comment]
@guw Thanks for your contribution!
