### ISSUE TITLE
Claiming namespace Lightning-Flow-Scanner

### ISSUE THREAD

**Issue by RubenHalman** [EclipseFdn/open-vsx.org#2188]
I am the publisher and owner of the Open Source Project [Lightning-Flow-Scanner](https://github.com/Lightning-Flow-Scanner), which has different repositories related to this namespace. I also own the same namespace in the VSCode extension marketplace. I hope that information suffices for this request. Kind regards

**Comment by kineticsquid** [comment]
@RubenHalman Granted!
