### ISSUE TITLE
Claiming namespace ForceConfigControl

### ISSUE THREAD

**Issue by RubenHalman** [EclipseFdn/open-vsx.org#2189]
I am the publisher and owner of the Open Source Project ForceConfigControl / [Lightning-Flow-Scanner](https://github.com/Lightning-Flow-Scanner), which has different repositories related to this namespace. I also own the same namespace in the VSCode extension marketplace(ForceConfigControl). I hope that information suffices for this request. Kind regards

**Comment by kineticsquid** [comment]
@RubenHalman Good to have you!
