### ISSUE TITLE
Claiming namespace [rubocop]

### ISSUE THREAD

**Issue by koic** [EclipseFdn/open-vsx.org#2191]
I am a member of the RuboCop core team and also the owner of RuboCop Headquarters on the Visual Studio Marketplace:

- https://github.com/rubocop/rubocop?tab=readme-ov-file#team
- https://marketplace.visualstudio.com/publishers/rubocop

Following the request in https://github.com/rubocop/vscode-rubocop/issues/16, I will also distribute to the Open VSX Registry in a similar manner.

**Comment by kineticsquid** [comment]
@koic Thanks for your contribution!
