### ISSUE TITLE
Claiming namespace [Bayrell]

### ISSUE THREAD

**Issue by ildar-ceo** [EclipseFdn/open-vsx.org#2192]
I am CEO of Bayrell company.
The github: https://github.com/orgs/bayrell/people
Website: https://bayrell.org/
About me: https://blog.bayrell.org/ru/about
LinkedIn: https://www.linkedin.com/in/ildar-bikmamatov/
VSCode extension: https://marketplace.visualstudio.com/items?itemName=Bayrell.bay-lang

**Comment by kineticsquid** [comment]
@ildar-ceo Welcome!
