### ISSUE TITLE
Claiming namespace ProVerif

### ISSUE THREAD

**Issue by famoser** [EclipseFdn/open-vsx.org#2196]
I want to publish https://github.com/ProVerif/vscode-proverif-language-service; under the same namespace as done in the vscode marketplace: https://marketplace.visualstudio.com/items?itemName=ProVerif.vscode-proverif

I am a member of the ProVerif organization on GitHub: https://github.com/orgs/ProVerif

**Comment by kineticsquid** [comment]
@famoser Good to have you!
