### ISSUE TITLE
Claiming namespace adguard

### ISSUE THREAD

**Issue by ameshkov** [EclipseFdn/open-vsx.org#2197]
Hi,

I am a CTO of AdGuard so it's natural for me to claim this namespace.

I did this on open-vsc.org already, but it still "not verified". What needs to be done to make it verified?

**Comment by kineticsquid** [comment]
@ameshkov Thanks for your contribution!

**Comment by ameshkov** [comment]
@kineticsquid thank you! Is it okay that the extension still looks like "unverified"? https://open-vsx.org/extension/adguard/adblock

**Comment by kineticsquid** [comment]
@ameshkov This is strange. I can see you are the publisher and you have signed a publisher agreement and you are the owner of this namespace (on my admin dashboard):
<img width="811" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/c30d54e0-3e63-4a03-b9fd-8ac7fd63389b">

Can you check your settings under 'namespaces' to ensure you're listed there as an owner of namespace `adguard`?

**Comment by ameshkov** [comment]
Yeah, everything is good now, probably it needed some time to update.

**Comment by kineticsquid** [comment]
Our pleasure!
