### ISSUE TITLE
Deprecate / remove florianalexandermoser/vscode-proverif-language-service

### ISSUE THREAD

**Issue by famoser** [EclipseFdn/open-vsx.org#2199]
Hi, thank you for all the work on this project!

I published under my personal name https://open-vsx.org/extension/florianalexandermoser/vscode-proverif-language-service
But the project got more official and is now republished under the ProVerif name: https://open-vsx.org/extension/ProVerif/vscode-proverif Only the later will continue to receive updates.

Please deprecate or remove https://open-vsx.org/extension/florianalexandermoser/vscode-proverif-language-service (probably removing is more appropriate, but I am not sure how users then know that they are supposed to install the other plugin?)

All the best

**Comment by kineticsquid** [comment]
@famoser Done!
