### ISSUE TITLE
Claiming namespace [securedevops]

### ISSUE THREAD

**Issue by mattias-mohlin** [EclipseFdn/open-vsx.org#2206]
I have created a new namespace "securedevops" which we plan to use instead of our current "hcltechnologies" for publishing extensions that are jointly developed by HCL Software and IBM Corporation. The first extension we plan to publish under this namespace is Code RealTime which is the GA version of what currently is called [RTist in Code](https://open-vsx.org/extension/HCLTechnologies/hcl-rtistic-ce).

**Comment by kineticsquid** [comment]
@mattias-mohlin Welcome!
