### ISSUE TITLE
Claiming namespace hangxingliu

### ISSUE THREAD

**Issue by hangxingliu** [EclipseFdn/open-vsx.org#2214]
Hi, I would like to claim the namespace **hangxingliu**, which is the same as my Github username and my Eclipse account.  
I have login https://open-vsx.org/ more than once.

And I am gonna to publish my following existed extensions into Open VSX:
- https://marketplace.visualstudio.com/items?itemName=hangxingliu.vscode-systemd-support
- https://marketplace.visualstudio.com/items?itemName=hangxingliu.vscode-nginx-conf-hint

I need to claim the namespace **hangxingliu** first in here.

---
References:
- <https://github.com/hangxingliu/vscode-systemd/issues/4>

**Comment by kineticsquid** [comment]
@hangxingliu Granted! Note that @yupswing is currently listed as a contributor, though has nothing published to this namespace.
