### ISSUE TITLE
Claiming namespace fluent-vue

### ISSUE THREAD

**Issue by Demivan** [EclipseFdn/open-vsx.org#2215]
I want to publish https://github.com/fluent-vue/vscode-extension under the same namespace as in the vscode marketplace: https://marketplace.visualstudio.com/items?itemName=fluent-vue.fluent-vue

I am the owner of the `fluent-vue` organization on GitHub: https://github.com/orgs/fluent-vue/people

**Comment by kineticsquid** [comment]
@Demivan Thanks for your contribution!
