### ISSUE TITLE
Unable to log in with an Eclipse Foundation account

### ISSUE THREAD

**Issue by rome-yongkang** [EclipseFdn/open-vsx.org#2227]
In order to sign the Eclipse Foundation Open VSX Publisher Agreement, I went to my profile page on open-vsx.org and tried to login with Eclipse.

However, after authorizing open-vsx.org to access my Eclipse account, an error appears when it takes me back to open-vsx.org.

<img width="637" alt="Snipaste_2023-12-04_19-19-52" src="https://github.com/EclipseFdn/open-vsx.org/assets/152864076/911f8349-73a9-4750-9ccb-302ee8e0bcee">

(By the way, the link color doesn't look right, it's white while the background is also white.)

Even if I already have my GitHub Username set in my Eclipse profile, and a GitHub link icon is already shown on [my Eclipse profile page](https://accounts.eclipse.org/users/romeyongkang).

<img width="424" alt="Snipaste_2023-12-04_19-21-27" src="https://github.com/EclipseFdn/open-vsx.org/assets/152864076/4fab3b49-4e8e-40ac-a233-0319a4424a8a">

**Comment by rome-yongkang** [comment]
@kineticsquid Thank you for responding. Yes, that's right and it's working right now.

I tried clearing cookies and local storage of my browser yesterday, but no luck with that.
However it appears to be working today, I guess it's cache problem on some end. As a user, all I have to do is wait for some time.

Anyway, it's working now so I'm closing this issue. Thank you.

**Comment by kineticsquid** [comment]
@rome-yongkang Yeah, the authentication processing does cache some stuff. Glad you got it working!
