### ISSUE TITLE
Claiming namespace [linuxsuren]

### ISSUE THREAD

**Issue by LinuxSuRen** [EclipseFdn/open-vsx.org#2243]
Hi team, I am the author of [linuxsuren.api-testing](https://marketplace.visualstudio.com/items?itemName=linuxsuren.api-testing). Below is the source code repository:

* https://github.com/LinuxSuRen/vscode-api-testing

You can see that I have the full permission of it from below screenshot:

![image](https://github.com/EclipseFdn/open-vsx.org/assets/1450685/7689dee2-6caf-49c3-997c-957b6ee1b3bd)

Hopefully, I can claim the namespace `linuxsuren`. Thanks for that.

**Comment by kineticsquid** [comment]
@LinuxSuRen Thanks for your contribution!
