### ISSUE TITLE
Claiming namespace quackai

### ISSUE THREAD

**Issue by frgfm** [EclipseFdn/open-vsx.org#2249]
Hi team :wave: 

Owner of the GitHub org [quack-ai](https://github.com/quack-ai) and its domain names, including the publisher account on VS Studio marketplace (https://marketplace.visualstudio.com/items?itemName=quackai.quack-companion). Since we're developing VSCode extensions, I thought it would be nice to also publish on the open VSX Registry.

I've completed the namespace registration, and logged on open-vsx, signed the publisher agreement after creating the eclipse foundation account. Could you please indicate how I can claim & get verification for the namespace please? :pray: 

Best

**Comment by kineticsquid** [comment]
@frgfm Thanks for your contribution!
