### ISSUE TITLE
Claiming namespace comnori

### ISSUE THREAD

**Issue by comnori** [EclipseFdn/open-vsx.org#2253]
The namespace name `comnori` is my github username.
I use the namespace to publish vscode extension.

It is already deployed under the same publisher name in the VSCode marketplace.

[Visual Studio Marketplace](https://marketplace.visualstudio.com/publishers/comnori)

https://github.com/comnori/vscode-java-pack/issues/2
https://github.com/comnori/vscode-javascript-pack/issues/2

**Comment by kineticsquid** [comment]
@comnori Welcome!
