### ISSUE TITLE
Claiming namespace daytonaio

### ISSUE THREAD

**Issue by Tpuljak** [EclipseFdn/open-vsx.org#2255]
I would like to claim ownership of the `daytonaio` namespace. 

I am a Software Engineer and Dev Advocate of [Daytona](https://www.daytona.io) and the lead on IDE and Extension Development. 

I have owner privileges in the [daytonaio Github organization](https://github.com/orgs/daytonaio/people) and will publish to open-vsx through Github Actions.

Edit:

I already set up publishing to the VS Code Marketplace ([URL](https://marketplace.visualstudio.com/items?itemName=daytonaio.daytona))

**Comment by kineticsquid** [comment]
@Tpuljak Welcome!
