### ISSUE TITLE
Claiming namespace tboby

### ISSUE THREAD

**Issue by tboby** [EclipseFdn/open-vsx.org#2258]
`tboby` is my github username, and I have used this namespace to publish on the VS Code Marketplace. There are only two extensions found when I search for tboby (https://marketplace.visualstudio.com/search?term=tboby&target=VSCode&category=All%20categories&sortBy=Relevance), which are both mine.

To my knowledge, nobody else uses this exact username.

**Comment by kineticsquid** [comment]
@tboby Welcome!
