### ISSUE TITLE
Claiming namespace WhisperYourWishLokeshKumar

### ISSUE THREAD

**Issue by neodisk17** [EclipseFdn/open-vsx.org#2261]
Hi team,\
I am the owner of the plugin Python Madad. Here is the repository
https://github.com/neodisk17/python-madad

I wanted to make sure I have everything before I can publish the extension on the MarketPlace

Also the reason for choosing this namespace is that  "I wanted to have my domain which might be used in future along with my name" 

Here is my extension
https://open-vsx.org/extension/WhisperYourWishLokeshKumar/python-madad

https://marketplace.visualstudio.com/items?itemName=WhisperYourWishLokeshKumar.python-madad

**Comment by kineticsquid** [comment]
@neodisk17 Thanks for your contribution.
