### ISSUE TITLE
Claiming namespace TEX3R / Deleting TEX-3-RIVIERES namespace

### ISSUE THREAD

**Issue by Tex3rivieres** [EclipseFdn/open-vsx.org#2262]
I initiated the TEX3R project and created the namespace TEX3R, and therefore am asking the ownership for TEX3R Namespace.
You can check [the Github repo of the extension that I own](https://github.com/Tex3rivieres/TeX3R-Workshop).

Previously, I was using the TEX-3-RIVIERES Namespace  on which I have not claimed ownership yet. TEX 3 RIVIERES is the old extension name, and I want to delete it. Do I have to claim the ownership before asking for the removal of the TEX-3-RIVIERES extension, or could you do it right now ?

Best regards.

**Comment by kineticsquid** [comment]
@Tex3rivieres I can rename `TEX-3-RIVIERES` to `TEX3R` and un-publish the current extension. Will that work?

**Comment by vcrombez** [comment]
It's fine for me as long as my extension is called TEX3R, and that there is only one extension ! Thanks !

**Comment by Tex3rivieres** [comment]
@kineticsquid It's fine for me as long as my extension is called TEX3R, and that there is only one extension ! Thanks !

**Comment by kineticsquid** [comment]
Done!
