### ISSUE TITLE
Claiming namespace IvanDemchenko

### ISSUE THREAD

**Issue by ivan-demchenko** [EclipseFdn/open-vsx.org#2265]
I am a maintainer of an [extension](https://marketplace.visualstudio.com/items?itemName=IvanDemchenko.roc-lang-unofficial) for the Roc language. I've got a [request #18](https://github.com/ivan-demchenko/roc-vscode-unofficial/issues/18) to publish to Open VSX too. I have created a namespace `IvanDemchenko` and I would like to claim ownership of it. Thank you!

**Comment by kineticsquid** [comment]
@ivan-demchenko Welcome!
