### ISSUE TITLE
Claiming namespace [TIC]

### ISSUE THREAD

**Issue by lyu571** [EclipseFdn/open-vsx.org#2266]
We'd like to claim the **TIC** as our namespace.
The TIC's full name is Tencent Cloud Infrastructure as Code.
Our team is focusing on the Infrastructure as Code relevant works in the DevOps domain.

My open-vsx profile as following:
Profile
Login name: lyu571

**Comment by kineticsquid** [comment]
@lyu571 Thanks for your contribution!
