### ISSUE TITLE
Claiming namespace [Anksio]

### ISSUE THREAD

**Issue by AnksioXD** [EclipseFdn/open-vsx.org#2267]
Hello, I am the creator and maintainer of <a href="https://github.com/AnksioXD/Tsoding-Gruber-Minimal-For-VSCode">Tsoding Gruber Minimal</a> theme for VSCode. 
I kindly request approval to claim the namespace on <a href="https://open-vsx.org/extension/Anksio/tsoding-emacs-gruber-minimal">open-vsx.org</a>.
Danke

**Comment by kineticsquid** [comment]
@AnksioXD Thanks for your contribution!
