### ISSUE TITLE
Claiming namespace [IceCraftStudio]

### ISSUE THREAD

**Issue by PavelDobCZ23** [EclipseFdn/open-vsx.org#2268]
I am the author of the extension `Insert Molang File` [posted on Open VSX Registry](https://open-vsx.org/extension/IceCraftStudio/insert-molang-file) and I would like to claim the ownership of the namespace `IceCraftStudio` used as the publisher of the extension. I use IceCraft Studio as my branding, the [original source code](https://github.com/IceCraft-Studio/Insert-Molang-File-VSC-Ext) of the extension is available under a GitHub organization I own called [IceCraft Studio](https://github.com/orgs/IceCraft-Studio/) and all external resources like the [website](https://www.icecraftstudio.repl.co) or [discord server](https://discord.gg/K28m8cKp74) mentioned in the README of the extension are also owned by me.

**Comment by kineticsquid** [comment]
@PavelDobCZ23 Welcome, good to have you!

**Comment by PavelDobCZ23** [comment]
> @PavelDobCZ23 Welcome, good to have you!

Thanks!
