### ISSUE TITLE
Claiming namespace srcery-colors

### ISSUE THREAD

**Issue by gagbo** [EclipseFdn/open-vsx.org#2269]
@Srcery-colors is a group that maintains ports of the Srcery colorscheme. I have written a [port of the theme for VSCode](https://github.com/srcery-colors/srcery-vscode), and already published it as well on the [MS marketplace](https://marketplace.visualstudio.com/items?itemName=srcery-colors.srcery-colors)

Ping @MindTooth, you should create an Eclipse and an Open VSX account so I can add you as owner ASAP

**Comment by MindTooth** [comment]
> Ping @MindTooth, you should create an Eclipse and an Open VSX account so I can add you as owner ASAP

Done.

**Comment by kineticsquid** [comment]
@gagbo Nice work, thanks for your contribution!
