### ISSUE TITLE
Claiming namespace apicurio

### ISSUE THREAD

**Issue by jetmartin** [EclipseFdn/open-vsx.org#2270]
Hi,

My plugin is going to be integrated on the apicurio org.
I created the apicurio namespace to publish the extentions under the organisation umbrella.
When validated I will add other organisation members.

see https://www.apicur.io/
and https://github.com/Apicurio/apicurio-registry-vscode-plugin

Best.

J-Et. Martin

**Comment by kineticsquid** [comment]
@jetmartin Welcome!
