### ISSUE TITLE
Claiming namespace [Privy]

### ISSUE THREAD

**Issue by srikanth235** [EclipseFdn/open-vsx.org#2273]
Hello, 

I am the creator and maintainer of [Privy](https://marketplace.visualstudio.com/items?itemName=privy.privy-vscode&ssr=false#overview) extension for VSCode.
I kindly request approval to claim the namespace on [open-vsx.org](https://open-vsx.org/extension/Privy/privy-vscode).

Thanks,
Srikanth.

**Comment by kineticsquid** [comment]
@srikanth235 Thanks for your contribution!
