### ISSUE TITLE
Claiming namespace Kadena

### ISSUE THREAD

**Issue by DevopsGoth** [EclipseFdn/open-vsx.org#2274]
I am in the operations department at [Kadena](https://kadena.io)., an open source blockchain company.  We have created an account to cross publish our [VSCode extension for the Pact smartcontract language](https://github.com/kadena-community/pact-vscode).

I have just verified via DNS with Microsoft's extension platform.  To confirm ownership of our organization's domain, I have created a txt record at openvsx.kadena.io with the value `hell_openvsx_we_are_rather_big_fans_of_open_source_platforms`

Thank you,
~Operations

**Comment by kineticsquid** [comment]
@DevopsGoth Granted, good to have you!
