### ISSUE TITLE
Claiming namespace Mufanza

### ISSUE THREAD

**Issue by Mufanza** [EclipseFdn/open-vsx.org#2275]
Hello, I am the author of the [E-Ink](https://github.com/Mufanza/vs-code-e-ink-theme) theme, a high-contrast accessibility theme designed to be used with E-ink monitors.

I'm also dumb and I've lost the Access Token that I originally used to publish this theme on OVSX. Therefore, if you grant me the ownership, I won't be able to update the theme with the newest contributions. Is there any way to salvage this?

**Comment by kineticsquid** [comment]
@Mufanza Thanks for your contribution!
