### ISSUE TITLE
Claiming namespace helm-ls

### ISSUE THREAD

**Issue by qvalentin** [EclipseFdn/open-vsx.org#2276]
Hello,

I'm the current maintainer of the language server [helm-ls](https://github.com/mrjosh/helm-ls/) and author of the vscode(ium) [extension](https://github.com/qvalentin/helm-ls-vscode/) for it.

I kindly request approval to claim the namespace on [open-vsx.org](https://open-vsx.org/extension/Privy/privy-vscode).

Thanks
Valentin

**Comment by kineticsquid** [comment]
@qvalentin Thanks for your contribution!
