### ISSUE TITLE
Claiming namespace yoavbls

### ISSUE THREAD

**Issue by yoavbls** [EclipseFdn/open-vsx.org#2277]
I desire to claim ownership of the "yoavbls" namespace.
I'm the legitimate owner of the namespace because it's my GitHub username since 2013 and my VSCode extensions "Pretty TypeScript errors" developed under this namespace:
https://github.com/yoavbls/pretty-ts-errors

I want the extension to be verified in [open-vsx](https://open-vsx.org/extension/yoavbls/pretty-ts-errors) to be verified exactly like it is in VisualStudio marketplace:
https://marketplace.visualstudio.com/items?itemName=yoavbls.pretty-ts-errors

Thank you!

**Comment by kineticsquid** [comment]
@yoavbls Nice to have you!
