### ISSUE TITLE
Claiming namespace EvilBeaver

### ISSUE THREAD

**Issue by EvilBeaver** [EclipseFdn/open-vsx.org#2278]
I'm an author and mainainer of OneScript execution engine

* https://oscript.io
* https://github.com/EvilBeaver/OneScript

I want to publish my Debugger VSIX extension on https://open-vsx.org/

Original VS Code extension is https://marketplace.visualstudio.com/items?itemName=EvilBeaver.oscript-debug

**Comment by kineticsquid** [comment]
Granted!
