### ISSUE TITLE
Claiming namespace 1c-syntax

### ISSUE THREAD

**Issue by EvilBeaver** [EclipseFdn/open-vsx.org#2280]
I'm one of members of [1c-syntax community](https://github.com/1c-syntax). We produce developer's tools for 1C and BSL ecosystem in open-source.

We want to publish our VS Code extensions on open-vsx.

Also, owhership of namespace should belong to @nixel2007 @theshadowco @otymko @asosnoviy

**Comment by kineticsquid** [comment]
@EvilBeaver Good to have you (but please stay away from the landscaping).

**Comment by nixel2007** [comment]
Hello, @kineticsquid. I've checked my open-vsx profile and I can't find any available namespace. Could you double check, please?

**Comment by kineticsquid** [comment]
@nixel2007 My mistake. I've just added @nixel2007 and @asosnoviy. I can't add @otymko and @theshadowco because it looks like they have not yet signed the publisher's agreement.

**Comment by nixel2007** [comment]
@TheShadoWCo @otymko folks, could you login to open-vsx.org and sign and agreement, please?

**Comment by EvilBeaver** [comment]
@kineticsquid I'm sorry, what is "landscaping" in this context?

**Comment by spytheman** [comment]
@EvilBeaver I think it is a joke, based on your username EvilBeaver -> `злой бобер`. Beavers can do a lot of changes to the environment, due to them building dams on rivers. An evil beaver could use its powers for destruction.

**Comment by EvilBeaver** [comment]
> An evil beaver could use its powers for destruction.

Ah! Yes I can, that's true! But I do my best to not harm the production environment at my job :)

**Comment by kineticsquid** [comment]
Thanks @spytheman 😄

**Comment by nixel2007** [comment]
Hi, @kineticsquid! Both @otymko and @TheShadoWCo signed the agreement.
Also could you check @EvilBeaver permissions? I don't see him as owners in 1c-syntax namespace anymore

**Comment by kineticsquid** [comment]
Just added @EvilBeaver, @otymko and @theshadowco. If you'd confirm and then close the issue. Thanks!

**Comment by nixel2007** [comment]
Yep, everything is fine. Thank you!
