### ISSUE TITLE
Claiming namespace OCamlPro

### ISSUE THREAD

**Issue by nberth** [EclipseFdn/open-vsx.org#2282]
Dear OpenVSX repository maintainer,

I am working for OCamlPro (https://ocamlpro.com/ — https://github.com/OCamlPro). We are planning to start publishing some VS Code extensions.

I therefore kindly request ownership of the "OCamlPro" namespace.

Please note, if possible, ownership should also be granted to @lefessan and @ddeclerck.

Many thanks in advance

**Comment by kineticsquid** [comment]
@nberth Welcome!
