### ISSUE TITLE
Claiming namespace masterustacean

### ISSUE THREAD

**Issue by codeitlikemiley** [EclipseFdn/open-vsx.org#2284]
Hi I already publish some of my vscode plugins 

https://marketplace.visualstudio.com/items?itemName=masterustacean.cargo-bin

https://marketplace.visualstudio.com/items?itemName=masterustacean.cargo-runner

it is on my github account

https://github.com/codeitlikemiley/cargo-runner
https://github.com/codeitlikemiley/cargo-bin

I cannot use anymore my codeitlikemiley on vscode , so i have no choice but to create
masterustacean namespace.

Please approved it so other users can use my rust plugin thanks

**Comment by kineticsquid** [comment]
Nice graphic!

**Comment by codeitlikemiley** [comment]
> Nice graphic!

thanks :)
