### ISSUE TITLE
Claiming namespace Alibaba-Cloud

### ISSUE THREAD

**Issue by bowei-jbw** [EclipseFdn/open-vsx.org#2293]
Hello, I'm a memebr of Alibaba Cloud, we want to publish our vscode extension - [TONGYI Lingma](https://marketplace.visualstudio.com/items?itemName=Alibaba-Cloud.tongyi-lingma) to open-vsx(https://open-vsx.org/extension/Alibaba-Cloud/tongyi-lingma).

Hope you could add the verification of the namespace Alibaba-Cloud. Thank you very much!

**Comment by kineticsquid** [comment]
@bowei-jbw Thanks for your contribution!
