### ISSUE TITLE
Can we unpublish a misleading extension?

### ISSUE THREAD

**Issue by msujew** [EclipseFdn/open-vsx.org#2294]
Someone has published a version of the [chinese localization to open-vsx](https://open-vsx.org/extension/zhanghua/vscodium-language-pack-zh-cn) 3 years ago without continuing support for it. Meanwhile there's an [official, updated version of the same extension](https://open-vsx.org/extension/MS-CEINTL/vscode-language-pack-zh-hans) available, published by open-vsx itself. Unfortunately, when searching for chinese language packs, the outdated version appears first:

![image](https://github.com/EclipseFdn/open-vsx.org/assets/4377073/4a4d488b-bc37-4184-a932-2fe03abbbff1)

This could be a discussion about how open-vsx orders items (i.e. one could argue that a version of the same extension with more downloads and more updates should be preferred), but this could lead to other issues down the line. Instead, I want to ask whether it's possible to completely unpublish the old extension. It has absolutely no benefit, only drawbacks compared to the official one and can easily confuse adopters, see https://github.com/eclipse-theia/theia/issues/13270.

**Comment by kineticsquid** [comment]
@msujew this makes sense.

@zhanghua000 are you OK with us removing your publication in favor the more up to date one?

**Comment by kineticsquid** [comment]
@msujew IMO I think our search results should be more heavily weighted toward the downloads.

**Comment by msujew** [comment]
> IMO I think our search results should be more heavily weighted toward the downloads.

@kineticsquid I agree, but I didn't want to open a larger can of worms just for this issue in particular.

**Comment by zhanghua000** [comment]
> @msujew this makes sense.
> 
> @zhanghua000 are you OK with us removing your publication in favor the more up to date one?

Yes, please remove my publication. I create the publication just because there was no language pack I prefer, but the official one had been uploaded, so I think my job has already been completed and there is no need to waste public resource.

**Comment by kineticsquid** [comment]
We should be good now.
