### ISSUE TITLE
Claiming namespace BIGWIN_LLC

### ISSUE THREAD

**Issue by vforbes1** [EclipseFdn/open-vsx.org#2301]

**Comment by vforbes1** [comment]
> @vforbes1 What namespace are you requesting ownership of?

My business

**Comment by kineticsquid** [comment]
@vforbes1 What is the name of your company?

**Comment by vforbes1** [comment]
BIGWIN LLC

**Comment by kineticsquid** [comment]
@vforbes1 I have the namespace created, `BIGWIN_LLC`. To assign ownership to you, you first need to sign the publisher's agreement. Let me know when you've done that.

**Comment by kineticsquid** [comment]
@vforbes1 ^^^^

**Comment by vforbes1** [comment]
Hi

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kineticsquid** [comment]
@vforbes1 Just making sure you understood my comment [above](https://github.com/EclipseFdn/open-vsx.org/issues/2301#issuecomment-1915081105). We need to have you sign the publisher's agreement. Instructions [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by kineticsquid** [comment]
@vforbes1 ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
