### ISSUE TITLE
Claiming namespace L-IGH-T

### ISSUE THREAD

**Issue by L-IGH-T** [EclipseFdn/open-vsx.org#2305]
Hello can you please verify my namespace L-IGH-T for this extension:

[Open VSX extension page](https://open-vsx.org/extension/l-igh-t/vscode-theme-seti-folder)
[Original marketplace extension page](https://marketplace.visualstudio.com/items?itemName=l-igh-t.vscode-theme-seti-folder)

Thank you
L-IGH-T

**Comment by kineticsquid** [comment]
@L-IGH-T Welcome!
