### ISSUE TITLE
gen-deployment.sh and expected structure of configuration.yml

### ISSUE THREAD

**Issue by xai** [EclipseFdn/open-vsx.org#2314]
Hello! I am currently experimenting with a local test environment of openvsx on a local cluster to explore logging capabilities and performance metrics.

Our goal is to gain some insights that help to improve the reliability of the service. See also [this helpdesk ticket](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4132) for context.

I used [`gen-deployment.sh`](https://github.com/EclipseFdn/open-vsx.org/blob/main/kubernetes/gen-deployment.sh) to generate a yml file that I then fed to `kubectl apply`.

So currently, I am either doing something wrong, or for successfully running openvsx in a setup as close as possible to the one at open-vsx.org, some additional parts in the configuration are required:
```
---
// [...]
"spec":
  // [...]
  "template":
    // [...]
    "spec":
      // [...]
      "containers":
      - "env":
        - "name": "DEPLOYMENT_CONFIG"
          "value": "/run/secrets/open-vsx.org/deployment/configuration.yml"
        // [...]

```

What would be the expected structure of this `configuration.yml` secret (`DEPLOYMENT_CONFIG`)? Thanks for your help!

**Comment by fredg02** [comment]
This is the format of the configuration file for the staging instance:
```
"ovsx":
  "elasticsearch":
    "clear-on-start": true
    "host": "<elasticsearch-host>:<elasticsearch-port>"
    "password": "<elasticsearch-password>"
    "ssl": true
    "truststore": "<path-to>/elasticsearch-http-certs.keystore"
    "truststorePassword": "<truststore-password>"
    "username": "<username>"
  "logs":
    "azure":
      "sas-token": "<sas-token-logs>"
      "service-endpoint": "<service-endpoint-logs>"
  "storage":
    "azure":
      "blob-container": "resources"
      "sas-token": "<sas-token-storage>"
      "service-endpoint": "<service-endpoint-storage>"
    "gcp":
      "bucket-id": "<gcp-bucket-id>"
      "project-id": "<project-id>"
"spring":
  "datasource":
    "password": "<spring-password>"
    "url": "jdbc:postgresql://<postgresql-url>:<postgresql-port>/openvsx-staging"
    "username": "<username>"
  "security":
    "oauth2":
      "client":
        "registration":
          "eclipse":
            "client-id": "<client-id>"
            "client-secret": "<client-secret>"
            "redirect-uri": "<redirect-url>"
          "github":
            "client-id": "<gh-client-id>"
            "client-secret": "<gh-client-secret>"
```

**Comment by xai** [comment]
Thank you very much for your help @fredg02!

**Comment by agafgfafa** [comment]
Was this somehow committed to the repo?

**Comment by fredg02** [comment]
> Was this somehow committed to the repo?

Not yet.
