### ISSUE TITLE
Claiming namespace JimothyTheGreat

### ISSUE THREAD

**Issue by JimothyTheGreat** [EclipseFdn/open-vsx.org#2320]
I am JimothyTheGreat. I would like to claim this namespace for the purposes of publishing a .vsxi for [vscodium-nand2tetris-hdl](https://github.com/JimothyTheGreat/vscodium-nand2tetris-hdl).

Please let me know if I can provide any further details.

**Comment by kineticsquid** [comment]
What a great name!
