### ISSUE TITLE
Claiming namespace [LionDoge]

### ISSUE THREAD

**Issue by LionDoge** [EclipseFdn/open-vsx.org#2324]
The namespace is the same as my Github username where I hold the project that I uploaded to OpenVSX from the following repository: https://github.com/LionDoge/vscode-vscript-debugger
I have already used it on the official Visual Studio marketplace here: https://marketplace.visualstudio.com/items?itemName=LionDoge.vscript-debug

**Comment by kineticsquid** [comment]
@LionDoge Good to have you!
