### ISSUE TITLE
Claiming namespace [rjmacarthy]

### ISSUE THREAD

**Issue by rjmacarthy** [EclipseFdn/open-vsx.org#2326]
I am the legitimate owner of this namespace, please check my profile etc.

**Comment by kineticsquid** [comment]
@rjmacarthy Welcome!

**Comment by rjmacarthy** [comment]
Thanks @kineticsquid, however I am still unable to create access token inside `https://open-vsx.org/user-settings/tokens` because my publisher agreement is `outdated` how can I reset this?  

Thanks.

**Comment by kineticsquid** [comment]
@rjmacarthy We just deployed a change to address similar symptoms. Before I take action, could you check again to see if you see the same message?

**Comment by kineticsquid** [comment]
@rjmacarthy ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response

**Comment by rjmacarthy** [comment]
All good now, thanks and sorry for lack of response!
