### ISSUE TITLE
Claiming namespace [respawn-initiative]

### ISSUE THREAD

**Issue by mattschlebusch** [EclipseFdn/open-vsx.org#2332]
Good day,

I'm looking to claim the namespace `respawn-initiative`. I don't believe it has been taken and would like to finalize this as a detail prior to attempting to publish any extensions to osvx. I have set up all other components (registered on osvx, created a token etc). Please confirm and let me know if you need any other details.

**Comment by kineticsquid** [comment]
@mattschlebusch Good to have you!
