### ISSUE TITLE
Claiming namespace [Aligotr]

### ISSUE THREAD

**Issue by Aligotr** [EclipseFdn/open-vsx.org#2336]
Re-publishing the same extension from VS Code Extension marketplace to open VSX under the same name and publisher etc... https://marketplace.visualstudio.com/items?itemName=Aligotr.markdown-preview-toc-sidebar

P.S. Can you help me remove version 1.0.0, it is not correct.

**Comment by kineticsquid** [comment]
@Aligotr Thanks for your contribution!
