### ISSUE TITLE
Claiming namespace `soupbowl`

### ISSUE THREAD

**Issue by soup-bowl** [EclipseFdn/open-vsx.org#2339]
Hi. I would like to be able to publish plugins to this namespace as it matches both my username, [website](https://soupbowl.io) and [VSMarketplace](https://marketplace.visualstudio.com/publishers/soupbowl) claim.

I have signed the Eclipse Foundation Open VSX Publisher Agreement.

**Comment by kineticsquid** [comment]
@soup-bowl Good to have you!
