### ISSUE TITLE
Claiming namespace [j.p westerveld]

### ISSUE THREAD

**Issue by jurgen-paul** [EclipseFdn/open-vsx.org#2343]
OISTAR’S WEBSHOP&BRANDS is a company founded by Jurgen Paul Westerveld, a former stage performer and web & data tech enthusiast. [The company offers a wide range of entertainment products, such as musicals, games, films, and live events, through its online platform](https://vimeo.com/channels/1862470)[1](https://vimeo.com/channels/1862470). [The namespace [j.p westerveld] likely refers to Jurgen Paul Westerveld himself, who is the legitimate owner of this brand and its associated webshop](https://vimeo.com/channels/1862470)[1](https://vimeo.com/channels/1862470). [If you have any further inquiries or need additional information, feel free to explore their website or contact them directly](https://www.oistarswebshopbrands.com/blank-1)[2](https://www.oistarswebshopbrands.com/blank-1). 🌟🎭🛒

**Comment by kineticsquid** [comment]
@jurgen-paul namespaces can have neither spaces, " ", nor periods, ".". Suggest you create the namespace you want, publish, then let me know and I'll make you owner.

**Comment by jurgen-paul** [comment]
alright  i will work on it

Op di 13 feb 2024 om 02:10 schreef John Kellerman ***@***.***

**Comment by kineticsquid** [comment]
@jurgen-paul Any update?

**Comment by jurgen-paul** [comment]
No, not yet.

Op ma 26 feb 2024 om 17:40 schreef John Kellerman ***@***.***

**Comment by kineticsquid** [comment]
@jurgen-paul Any news on this?

**Comment by kineticsquid** [comment]
closing for lack of response
