### ISSUE TITLE
Delete Sigasi extension

### ISSUE THREAD

**Issue by tivervac** [EclipseFdn/open-vsx.org#2361]
Since new Sigasi versions are not supported on [Open VSX](https://github.com/EclipseFdn/open-vsx.org/issues/2300#issuecomment-1946231607), we have decided to drop the platform. We simply cannot have a marketplace that only offers outdated Sigasi versions.

As manual [unpublishing is not possible](https://github.com/eclipse/openvsx/issues/58), I'm asking you here to please delete [our extension](https://open-vsx.org/extension/Sigasi/sigasi-vscode) but leave us in control of the namespace.

**Comment by kineticsquid** [comment]
@tivervac I have removed all versions of your extension. I'm sorry we're not able to accommodate you with our current limitations. If this should change in the future, we'll be sure to let you know.
