### ISSUE TITLE
Claiming namespace vitest

### ISSUE THREAD

**Issue by sheremet-va** [EclipseFdn/open-vsx.org#2367]
As a core maintainer of [Vitest package](https://github.com/vitest-dev/vitest), I would like to have the rights to publish to "vitest" namespace. Right now it says the name is already taken. I created the publisher "vitest" for VSCode Marketplace and would like to keep it the same also for Open VSX.

**Comment by kineticsquid** [comment]
@sheremet-va I need you to first sign the publisher's agreement. Then I can assign ownership. @zxch3n is listed as a contributor, but he hasn't published anything.

**Comment by sheremet-va** [comment]
> I need you to first sign the publisher's agreement

I already signed it:

![Screenshot 2024-02-19 at 21 15 59](https://github.com/EclipseFdn/open-vsx.org/assets/16173870/2532ea63-8111-4420-b6ed-05156a5c9d81)

**Comment by sheremet-va** [comment]
> is listed as a contributor, but he hasn't published anything.

As far as I know, he published https://open-vsx.org/extension/ZixuanChen/vitest-explorer which is a mirror of https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer

**Comment by kineticsquid** [comment]
Thanks, I can see the agreement now; I've made you owner. I meant that he hadn't yet published anything to this namespace. Good to have you!
