### ISSUE TITLE
Claiming namespace RafaelMartinez

### ISSUE THREAD

**Issue by rafalou38** [EclipseFdn/open-vsx.org#2372]
Why I am legitimate:
1. That's my legal name.
2. That's the namespace under which I publish the [Svelte-Preview](https://open-vsx.org/extension/RafaelMartinez/svelte-preview) extension, of which I am the developper: [rafalou38/svelte-preview](https://github.com/rafalou38/svelte-preview)

**Comment by kineticsquid** [comment]
@rafalou38 Thanks for your contribution!
