### ISSUE TITLE
Claiming namespace AOS

### ISSUE THREAD

**Issue by A-0-5** [EclipseFdn/open-vsx.org#2393]
I am looking to publish an extension on open-vsx. I have already published this extension on vscode [marketplace](https://marketplace.visualstudio.com/items?itemName=AOS.gostmortem-table) under the same publisher name. So I request the maintainers to grant me the ownership of this namespace.
The extension I am looking to publish is https://github.com/A-0-5/gostmortem-table

**Comment by kineticsquid** [comment]
@A-0-5 Welcome!
