### ISSUE TITLE
Claiming namespace Letgamer

### ISSUE THREAD

**Issue by Letgamer** [EclipseFdn/open-vsx.org#2396]
The namespace Name is my long used Github name, which I also use on other platforms.
Under this Nickname I want to only public two extensions:
sweet-vscode and sweet-vscode-icons
I am in Love with these two extensions as I use them daily. But unfortunately they are not natively available on Vscodium.
Therefore I forked the two repositories and via Github actions provide the two Themes for everybody, who wants to use them.
https://github.com/Letgamer/sweet-vscode
https://github.com/Letgamer/sweet-vscode-icons
https://open-vsx.org/extension/Letgamer/sweet-vscode
https://open-vsx.org/extension/Letgamer/sweet-vscode-icons

I do not plan to change the Extensions unless the original Extensions get updates, which I highly doubt.

**Comment by kineticsquid** [comment]
@Letgamer Welcome!
