### ISSUE TITLE
Help deleting specific versions of an extension

### ISSUE THREAD

**Issue by zFernand0** [EclipseFdn/open-vsx.org#2398]
Hello Open VSX team,

I would like to remove a few versions that I mistakenly published to the registry.

The extension name is `Zowe.cics-extension-for-zowe`
https://open-vsx.org/extension/Zowe/cics-extension-for-zowe

And the versions to delete are basically all pre-releases, which makes 2.3.4 the latest version 😋 
![image](https://github.com/EclipseFdn/open-vsx.org/assets/37381190/ed43bbaf-3dfd-4da6-a725-42ae3375024b)

Thanks in advance for the help! 🙏🏽

**Comment by kineticsquid** [comment]
@zFernand0 In addition to those 5 versions, I also see `3.0.0-next.202402271249`. Would you like me to remove it also?

**Comment by zFernand0** [comment]
Hey @kineticsquid,
I appreciate you getting back to me on this.
No need to remove that latest prerelease that was published about 7 hours ago 😋 

Thanks so much!

**Comment by kineticsquid** [comment]
@zFernand0 You should be set.

**Comment by zFernand0** [comment]
Hey @kineticsquid 
much appreciated! 🙏🏽
