### ISSUE TITLE
Claiming namespace SemioticLabs

### ISSUE THREAD

**Issue by anirudh2** [EclipseFdn/open-vsx.org#2400]
Hey there! I'm leading a software effort at [Semiotic Labs](https://semiotic.ai/), part of which involves developing an extension for VSCode. You can see me listed under the [organisation on GitHub](https://github.com/orgs/semiotic-ai/people). If you need any further evidence from me, let me know!

**Comment by kineticsquid** [comment]
@anirudh2 Good to have you!

**Comment by anirudh2** [comment]
Thanks!
