### ISSUE TITLE
Claiming namespace deimonn

### ISSUE THREAD

**Issue by deimonn** [EclipseFdn/open-vsx.org#2401]
'Tis my username!

I've already published an extension under it on both the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=deimonn.oro-theme) and just recently [Open VSX](https://open-vsx.org/extension/deimonn/oro-theme) as well.

If you need anything from me, just let me know.

**Comment by kineticsquid** [comment]
@deimonn Welcome!
