### ISSUE TITLE
Claiming namespace Mosorior

### ISSUE THREAD

**Issue by Mosorior** [EclipseFdn/open-vsx.org#2403]
Hello,

I am requesting exclusive publishing rights for the namespace "Mosorior" on Open VSX. I am the maintainer/author of the extensions published under this namespace and here is my GitHub repository as evidence of my work and ownership of the extensions: https://github.com/Mosorior/rajoyipsum

I have previously logged in to https://open-vsx.org with my account @Mosorior to ensure my request can be properly processed.

Thank you for considering my request.

Best regards,
Marco

**Comment by kineticsquid** [comment]
@Mosorior Thanks for your contribution!
