### ISSUE TITLE
Claiming namespace haiku

### ISSUE THREAD

**Issue by haiku-balls** [EclipseFdn/open-vsx.org#2405]
I own the extension, since it's published under on the official Microsoft Visual Studio Marketplace by me.
![image](https://github.com/EclipseFdn/open-vsx.org/assets/65756037/e7fbc837-9df7-4e7b-9366-c8fc9a82e1c9)

**Comment by kineticsquid** [comment]
@haiku-balls Granted. We can always use more poets!
