### ISSUE TITLE
Need to delete 1.* versions of extension

### ISSUE THREAD

**Issue by anirudh2** [EclipseFdn/open-vsx.org#2406]
We had a bug in our release pipeline that was causing us to incorrectly version releases. Mind deleting 1.* versions of https://open-vsx.org/extension/SemioticLabs/semiotic-sql-studio?

**Comment by kineticsquid** [comment]
Deleted 1.0.1 and 1.0.2.

**Comment by anirudh2** [comment]
Thanks!
