### ISSUE TITLE
Claiming namespace [name]YourHomeModPro.com

### ISSUE THREAD

**Issue by YourHomeModPro** [EclipseFdn/open-vsx.org#2408]

**Comment by YourHomeModPro** [comment]
YourHomeModPro.com

**Comment by kineticsquid** [comment]
@YourHomeModPro My bad, I responded too quickly. A namespace name is defined by this regex `[\w\-\+\$~]+`. Would you like `YourHomeModPro`?

**Comment by kineticsquid** [comment]
@YourHomeModPro ^^^^

**Comment by kineticsquid** [comment]
@YourHomeModPro ^^^^

**Comment by kineticsquid** [comment]
Closing for lack of response
