### ISSUE TITLE
Claiming namespace [ginfuru]

### ISSUE THREAD

**Issue by edheltzel** [EclipseFdn/open-vsx.org#2409]
I created a few extensions for vscode, several themes and a few extensions. 
I used to go by the sudo name `ginfuru` which is what my MS account is called when I published my extensions, ie: [Better Nunjucks](https://marketplace.visualstudio.com/items?itemName=ginfuru.better-nunjucks) 
If you examine the URL - you will see `ginfuru.better-nunjucks` but if you go to the vscode market place you'll see that I've changed/updated my information to read `edheltzel`

I'd like to publish my extensions on Open VSX registry - so this is me claiming the name spaces for 

`ginfuru`
&
`edheltzel`

**Comment by kineticsquid** [comment]
@edheltzel Welcome! I've granted you ownership of the two namespaces. Note that https://open-vsx.org/extension/ginfuru/ginfuru-better-solarized-dark-theme is currently being auto-published to `ginfuru`. If you don't want that to continue, submit a PR to remove it from [`extensions.json`](https://github.com/open-vsx/publish-extensions/blob/master/extensions.json).

**Comment by edheltzel** [comment]
Thanks!!
