### ISSUE TITLE
Claiming namespace AnHeuermann

### ISSUE THREAD

**Issue by AnHeuermann** [EclipseFdn/open-vsx.org#2419]
I have published [AnHeuermann/metamodelica](https://open-vsx.org/extension/AnHeuermann/metamodelica) and am the owner of https://github.com/AnHeuermann/metamodelica-language-vscode, which was used to create the extension file.

So I want to claim my GitHub name as a namespace.

**Comment by kineticsquid** [comment]
@AnHeuermann Welcome!
