### ISSUE TITLE
Claiming namespace [Dynatrace]

### ISSUE THREAD

**Issue by Dynatrace-Developer** [EclipseFdn/open-vsx.org#2420]
I'd like to claim ownership of the Dynatrace namespace, as we're using it to publish our official Dynatrace VS Code extension. 
To support the legitimacy of this request: we are using the same namespace on the [VS Marketplace](https://marketplace.visualstudio.com/publishers/dynatrace) and I am happy to share further evidence on request.

**Comment by kineticsquid** [comment]
@Dynatrace-Developer Thanks for your contribution!
