### ISSUE TITLE
Deleting duplicated extension

### ISSUE THREAD

**Issue by daumantas-kavolis-sensmetry** [EclipseFdn/open-vsx.org#2423]
We published an extension with only a changed name https://open-vsx.org/extension/sensmetry/syside by mistake, original is at https://open-vsx.org/extension/sensmetry/sysml-2ls. Could you delete it?

**Comment by kineticsquid** [comment]
Poof!

**Comment by daumantas-kavolis-sensmetry** [comment]
Thank you.
