### ISSUE TITLE
Claiming namespace jgrundback

### ISSUE THREAD

**Issue by whoopsjohnnie** [EclipseFdn/open-vsx.org#2424]
I would like to claim the namespace jgrundback which was created when I imported a VSCode extension from https://github.com/whoopsjohnnie/vscode-mc-theme into my open vsx account. Here is the corresponding VSCode marketplace theme: https://marketplace.visualstudio.com/items?itemName=jgrundback.vscode-mc-theme

**Comment by kineticsquid** [comment]
@whoopsjohnnie Welcome!
