### ISSUE TITLE
Claiming namespace [rpinski]

### ISSUE THREAD

**Issue by Rpinski** [EclipseFdn/open-vsx.org#2425]
I've been asked by people to publish my [Shebang Snippets](https://github.com/Rpinski/vscode-shebang-snippets) extension on Open VSX, as well. It has been present on [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=rpinski.shebang-snippets) for years. So here is my namespace for future publishing, which I would like to become owner of :)

Thank you very much in advance!

**Comment by kineticsquid** [comment]
@Rpinski Good to have you!
