### ISSUE TITLE
Claiming namespace [just-seba]

### ISSUE THREAD

**Issue by just-seba** [EclipseFdn/open-vsx.org#2426]
I am the publisher and maintainer of the extension [just-seba.vscode-code-butler](https://marketplace.visualstudio.com/items?itemName=just-seba.vscode-code-butler).
I'm the owner of the `just-seba` namespace on the VS Code marketplace and would like to also publish my extension(s) on Open VSX.

https://github.com/just-seba
https://marketplace.visualstudio.com/publishers/just-seba

**Comment by kineticsquid** [comment]
@just-seba Thanks for your contribution!
