### ISSUE TITLE
delete versions for `graphql.vscode-graphql`

### ISSUE THREAD

**Issue by acao** [EclipseFdn/open-vsx.org#2428]
Hello there! I'm one of the maintainers of `GraphQL.vscode-graphql` extension. we had some publishing issues impacting open-vsx users only (because we didnt re-use the vsce bundle) and need to revert to 0.8.25 as the latest release, and delete the most recent ones. we have an upstream fix coming, but we especially need to delete _at least the 0.10.1 release_ so we can re-sync our release cycle.

you can see how many users are tracking [this bug for example](https://github.com/graphql/graphiql/issues/3516) 😓 

thank you!

**Comment by kineticsquid** [comment]
@acao Deleted the following versions: `0.9.0`, `0.9.1`, `0.9.2`, `0.9.3` and `0.10.1`.

**Comment by acao** [comment]
thank you so much!!
