### ISSUE TITLE
Claiming namespace [vscode-snippet]

### ISSUE THREAD

**Issue by mre** [EclipseFdn/open-vsx.org#2429]
I am the publisher and maintainer of the extension [vscode-snippet](https://marketplace.visualstudio.com/items?itemName=vscode-snippet.Snippet).
I'm the owner of the vscode-snippet namespace on the VS Code marketplace and would like to already published my extension on Open VSX under https://open-vsx.org/extension/vscode-snippet/snippet. 

If possible, please add @VladBrok as an administrator of the `vscode-snippet` namespace as well. If not, I will do so manually later.

https://github.com/mre/vscode-snippet
https://marketplace.visualstudio.com/publishers/vscode-snippet

**Comment by kineticsquid** [comment]
@mre Thanks for your contribution!
