### ISSUE TITLE
Claiming namespace [FittenTech]

### ISSUE THREAD

**Issue by lzhengning** [EclipseFdn/open-vsx.org#2432]
I'd like to claim ownership of the FittenTech namespace, as we're using it to publish our official [Fitten Code](https://marketplace.visualstudio.com/items?itemName=FittenTech.Fitten-Code)  VS Code extension.

I am one of the members of [Fitten](https://github.com/FittenTech), which is the official GitHub organization. The GitHub organization also publish an open source Vim extension.

**Comment by kineticsquid** [comment]
@lzhengning Thanks for your contribution!
