### ISSUE TITLE
Contact Adopters to give a Heads Up about launch

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/open-vsx.org#244]
Gitpod, VSCodium, and others.

Give them a heads up about the launch on Monday, and ask them to monitor their community for reports of anything breaking.

**Comment by brianking** [comment]
@spoenemann Do you have a full list of adopters? I can send emails to product owners.

**Comment by spoenemann** [comment]
No, I never made any research about other adopters. I think there are more VS Code forks besides VSCodium that are using Open VSX, though.
