### ISSUE TITLE
Claiming namespace [rossidiogo]

### ISSUE THREAD

**Issue by Diogo-Rossi** [EclipseFdn/open-vsx.org#2440]
Briefly explain what makes you a legitimate owner of the namespace mentioned in
the issue title.

I have created it to publish an extension.

I could not publish with the [older namespace](https://github.com/EclipseFdn/open-vsx.org/issues/2436), so I created this new one.

**Comment by kineticsquid** [comment]
@Diogo-Rossi Granted! Curious, why couldn't you publish to the previous namespace?

**Comment by Diogo-Rossi** [comment]
I don't know... I know there was an error message, but can't remember now.

**Comment by kineticsquid** [comment]
OK, I'm going to close this. Please open an issue if you see it return. Thanks!
