### ISSUE TITLE
Changing orgs to `eclipse-openvsx`

### ISSUE THREAD

**Issue by kineticsquid** [EclipseFdn/open-vsx.org#2441]
Three repos make up EF open-vsx.org deployment. In addition to this one, there are:
- https://github.com/eclipse/openvsx
- https://github.com/open-vsx/publish-extensions

The three are under three different orgs, two under Eclipse responsibility and one, `publish-extensions`, not. This inconsistency presents some difficulties, e.g. contributor agreement checks. In an effort to remedy this, we plan to bring the three repos together under a new org, `eclipse-openvsx`. These moves will not change committer status.

This issue is for general discussion and to provide status updates.

**Comment by kkistm** [comment]
From my point of view the idea to gather all three project under a single organization is a good one.

**Comment by kineticsquid** [comment]
@amvanbaren @spoenemann @filiptronicek @mbarbero @akosyakov @yiningwang11 FYI

**Comment by spoenemann** [comment]
Sounds good, however you'll probably still want to make a difference between the project code (`eclipse-openvsx` org) and the code related to the public instance, operated by EF (`EclipseFdn` org). I suggest that the `publish-extensions` repo should reside under `EclipseFdn` because it's strictly related to that public instance, or WDYT?

**Comment by kineticsquid** [comment]
@spoenemann Definitely agree that `publish-extensions` needs to be with `EclipseFdn/open-vsx.org` as it's specific to the deployment. I think the general trend at EF is to move away from the generic `eclipse` org to more specific ones. Given that, we thought it best to keep the three repos together. @waynebeaton anything to add?

**Comment by waynebeaton** [comment]
+1

**Comment by kineticsquid** [comment]
@waynebeaton Thanks. I'll provide one more notice on the Slack channel and then we can make the move. To whom do I say "go"?

**Comment by waynebeaton** [comment]
Ask the IT Team for help with the moves when you're ready.

**Comment by kineticsquid** [comment]
Created issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4540
