### ISSUE TITLE
Claiming namespace [alefragnani]

### ISSUE THREAD

**Issue by alefragnani** [EclipseFdn/open-vsx.org#2445]
Hi,

I am the creator of the Bookmarks (https://github.com/alefragnani/vscode-bookmarks) , Project Manager (https://github.com/alefragnani/vscode-project-manager) and Read-Only Indicator (https://github.com/alefragnani/vscode-read-only-indicator)
And many others https://github.com/alefragnani / https://marketplace.visualstudio.com/publishers/alefragnani

Thank you

**Comment by kineticsquid** [comment]
@alefragnani I can see three others already listed as contributors: @KokaKiwi, @PhilippeVay and @appelgriebsch. Are they part of your team?

**Comment by alefragnani** [comment]
Hi @kineticsquid , No, they are not.

**Comment by kineticsquid** [comment]
OK, it looks like they have previously published your extensions to this namespace. Given this is your GiHub ID, I'm going to assign it to you. You can choose to  remove or leave the existing contributors to the namespace.

**Comment by alefragnani** [comment]
Hi @kineticsquid ,

First of all, thank you for the assign.

BTW, is there any additional step that I need to take (or is it just a matter of time) in order to be able to use the namespace? 

My profile page still doesn´t show any linked namespace, and trying to publish an extension using the `ovsx` tool, raises an error message:  _"Insufficient access rights for publisher: alefragnani"_.

Thank you

**Comment by kineticsquid** [comment]
Doh, my bad, you should be good now. Sorry and thanks for letting me know.

**Comment by kineticsquid** [comment]
Please confirm and I'll close the issue

**Comment by alefragnani** [comment]
Hi @kineticsquid ,

Confirmed ! ✅ 

I'm seeing the namespace on my profile and already published a new extension. I didn´t update the ones already published, but it should work just fine too.

I would like to take the opportunity to thank @KokaKiwi, @PhilippeVay and @appelgriebsch for publishing the early versions of those extensions. I'll keep those extensions up to date from now on.

Thank you
