### ISSUE TITLE
Claiming namespace [nextflow]

### ISSUE THREAD

**Issue by ewels** [EclipseFdn/open-vsx.org#2452]
The namespace [nextflow](https://open-vsx.org/namespace/nextflow) and [associated extension](https://open-vsx.org/extension/nextflow/nextflow) are already present on Open VSX, by @sjroth and unverified.

I'd like to claim ownership of the namespace and plugin please. I am employed at [Seqera](https://seqera.io/nextflow/) and am product manager for open-source products there, including Nextflow. I control the publishing of the [same plugin](https://marketplace.visualstudio.com/items?itemName=nextflow.nextflow) at the VSCode Marketplace. The plugin version on the Open VSX Registry is very old (0.1.1, released 2018) and I would like to update it.

I have a PR ready to automate the publishing once I have ownership: https://github.com/nextflow-io/vscode-language-nextflow/pull/29

**Comment by sjroth** [comment]
Yes. Happy and eager to relinquish ownership to @ewels. Please let me know what I can do to help resolve this.

**Comment by kineticsquid** [comment]
@sjroth Thanks for your quick response!

@ewels I've made you owner, welcome!

**Comment by ewels** [comment]
Amazing - thank you both!

**Comment by sjroth** [comment]
Not a problem at all! I originally had taken ownership because no one at Seqera had taken up the mantle. I look forward to developments in the future!

**Comment by ewels** [comment]
Ah, @kineticsquid - I now have ownership of the namespace and was able to update that. But I don't have access of the plugin itself: https://open-vsx.org/extension/nextflow/nextflow

Could I have that transferred to me as well please? Thanks

**Comment by ewels** [comment]
Ah.. or could it be that I just need to publish a new version? And it's just this old version that shows up that way? I'll try it now..

**Comment by ewels** [comment]
Ok false alarm, I think we're all good: https://open-vsx.org/extension/nextflow/nextflow

Sorry for the comment spam, and thanks again!
