### ISSUE TITLE
Claiming namespace Couchbase

### ISSUE THREAD

**Issue by deniswsrosa** [EclipseFdn/open-vsx.org#2455]
Hi!, 
I would like to claim Ownership of the namespace "Couchbase" https://open-vsx.org/extension/couchbase/ . We are already publishing at https://marketplace.visualstudio.com/items?itemName=Couchbase.vscode-couchbase and I would like to publish the same extension here as well.

**Comment by kineticsquid** [comment]
@deniswsrosa Good to have you!
