### ISSUE TITLE
Deletion request for `IBM.clearcase`

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#2463]
Forwarding a [request](https://github.com/open-vsx/publish-extensions/issues/751) from the https://github.com/open-vsx/publish-extensions repo: 

> Hello some months ago i mistakingly created an extension (was learning how to use this site). As we do not support Codium or Theia at the moment I do need to get it removed.
Here the URL: https://open-vsx.org/extension/IBM/clearcase
Thank You in advance!

**Comment by filiptronicek** [comment]
@kineticsquid if you could help here 🙏

**Comment by kineticsquid** [comment]
Done!
