### ISSUE TITLE
Claiming namespace [vanyauhalin]

### ISSUE THREAD

**Issue by vanyauhalin** [EclipseFdn/open-vsx.org#2475]
Hi Eclipse Team,

I'm working on my [theme](https://github.com/vanyauhalin/moondusttheme) and I'm interested in publishing it on Open VSX. My theme has already been [successfully published](https://marketplace.visualstudio.com/items?itemName=vanyauhalin.moondusttheme) on the VSCode Marketplace. 

Thank you for your time.

**Comment by kineticsquid** [comment]
@vanyauhalin Good to have you!
