### ISSUE TITLE
Claiming namespace [thinking80s]

### ISSUE THREAD

**Issue by Thinking80s** [EclipseFdn/open-vsx.org#2476]
Hi Eclipse Team,

I'm working on my [theme](https://github.com/Thinking80s) and I'm interested in publishing it on Open VSX. My theme has already been [successfully published](https://open-vsx.org/extension/thinking80s/vscode-extension-code-ext)

Thank you for your time.

**Comment by kineticsquid** [comment]
@Thinking80s Thanks for your contribution!
