### ISSUE TITLE
Claiming namespace beaugust

### ISSUE THREAD

**Issue by metacurb** [EclipseFdn/open-vsx.org#2478]
I own the extension blamer-vs, mentioned [here](https://github.com/open-vsx/publish-extensions/issues/690). I'd like to claim ownership of the namespace so that I can publish updates

**Comment by kineticsquid** [comment]
@BeauAgst Granted. You have an extension that is being auto-published currently. If you don't want that to continue, submit a PR to https://github.com/open-vsx/publish-extensions/blob/master/extensions.json.

**Comment by eclipsewebmaster** [comment]
@BeauAgst has changed their user to @metacurb .  @kineticsquid can you help them reclaim their namespace?

**Comment by kineticsquid** [comment]
@eclipsewebmaster I've added @metacurb as owner and removed @BeauAgst.
