### ISSUE TITLE
Login Session Times Out Regularly on Firefox (Staging)

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/open-vsx.org#248]
On Staging, my session regularly times out. I never close the tab or window. I have not timed it, but it could be 1-2 hours after not using the site, maybe even sooner.

Firefox has Enhanced Tracking Protection ON by default for the site, so I wonder if that is for example expiring cookies regularly.

**Comment by spoenemann** [comment]
The session cookie has expiration set to "Session", which means that it's the responsibility of the browser to decide when it expires.

**Comment by mbarbero** [comment]
I think we're done here.
