### ISSUE TITLE
Claiming namespace snowflake

### ISSUE THREAD

**Issue by sfc-gh-klin** [EclipseFdn/open-vsx.org#2486]
Hello! 

I work for [Snowflake](https://github.com/snowflakedb) and would like to claim the namespace. This will be used to facilitate  making the [Snowflake VS Code Extension](https://marketplace.visualstudio.com/items?itemName=snowflake.snowflake-vsc) available on Open VSX.

**Comment by kineticsquid** [comment]
@sfc-gh-klin Good to have you!
