### ISSUE TITLE
Claiming namespace yunier_olivera

### ISSUE THREAD

**Issue by yunier-olivera** [EclipseFdn/open-vsx.org#2492]
Hello,

I am Yunier Olivera, an independent developer and the creator of the "Markdown & Quarto Word Count" extension for Markdown and Quarto documents in the VSCode Marketplace. My extension has been well-received in the VSCode community, and I am now looking to expand its availability to the VSCodium user base through the Open VSX Registry.

The namespace "yunier_olivera" directly represents my name and is consistent with my identity across various developer platforms, including GitHub and the VSCode Marketplace. This namespace will be used exclusively for publishing my projects and extensions, such as the Word Counter for MD and QMD documents.

I have already logged into https://open-vsx.org with my account to ensure my claim can be processed without issues. You can verify my identity and extension through my GitHub profile and existing publication in the VSCode Marketplace.

Thank you for considering my request to claim the "yunier_olivera" namespace in the Open VSX Registry.

Best,
Yunier Olivera

**Comment by kineticsquid** [comment]
@yunier-olivera Welcome!
