### ISSUE TITLE
Claiming namespace yunierolivera

### ISSUE THREAD

**Issue by yunier-olivera** [EclipseFdn/open-vsx.org#2493]
Hello,

I'm Yunier Olivera, the developer behind the "Markdown & Quarto Word Count" extension, which is currently published on the VSCode Marketplace. My current VSX namespace does not match my extension namespace, and I want to also claim the namespace "yunierolivera," to better serve both VSCode and VSCodium communities.

Best regards,
Yunier Olivera

**Comment by kineticsquid** [comment]
@yunier-olivera Thanks for your contribution!
