### ISSUE TITLE
move extensions to a different namespace

### ISSUE THREAD

**Issue by dannysteenman** [EclipseFdn/open-vsx.org#2500]
I've been wanting to push some updates for my extensions on open-vsx. I noticed the feature with the ability to change namespace name was merged sometime ago: https://github.com/eclipse/openvsx/pull/469. Here's my previous gh issue: https://github.com/EclipseFdn/open-vsx.org/issues/958

Can you please move my two extensions under the dsteenman namespace to the dannysteenman namespace and delete the old namespace (dsteenman) for me?

**Comment by kineticsquid** [comment]
@dannysteenman You should be good to go!

**Comment by dannysteenman** [comment]
@kineticsquid thank you for the quick update! The transfer worked!

However it seems I get a big warning now:

<img width="838" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/15192660/4a37483b-4f2d-4f0f-91c2-2012209a2673">

Any tip on how to get rid of that warning and have that namespace verified?
