### ISSUE TITLE
Claiming namespace elm-land

### ISSUE THREAD

**Issue by ludat** [EclipseFdn/open-vsx.org#2505]
I want to republish the [elm-lang extension](https://marketplace.visualstudio.com/items?itemName=elm-land.elm-land) (which is already published on the vscode marketplace)

The author is ok with me republishing the extension https://github.com/elm-land/elm-land/issues/172#issuecomment-2053680756 since they are not interested in doing that work.

So I'd like to claim the namespace for elm-land

**Comment by kineticsquid** [comment]
@ludat Welcome!
