### ISSUE TITLE
Claiming namespace KorbinianEckstein

### ISSUE THREAD

**Issue by korbinian90** [EclipseFdn/open-vsx.org#2509]
My github account: https://github.com/korbinian90

The app I'm developing and uploading to openvsx: https://github.com/niivue/niivue-vscode

Previously was only available on vscode marketplace: https://marketplace.visualstudio.com/items?itemName=KorbinianEckstein.niivue

**Comment by kineticsquid** [comment]
> @korbinian90 Thanks for your contribution!
