### ISSUE TITLE
Claiming namespace swyddfa

### ISSUE THREAD

**Issue by alcarney** [EclipseFdn/open-vsx.org#2516]
I develop and maintain the `swyddfa.esbonio` extension: https://github.com/swyddfa/esbonio

It was previously published to open-vsx.org by the open-vsx account: https://github.com/open-vsx/publish-extensions/pull/742#issuecomment-1979475802

I'm assuming I need to claim the namespace so that I can publish an update to it?

**Comment by kineticsquid** [comment]
@alcarney I've made you owner of the namespace. If the auto-publishing is fixed you can leave this in place and let updates to the MS registry cause Open VSX to be updated. Or, submit a PR to have your extension removed from https://github.com/open-vsx/publish-extensions/.

**Comment by alcarney** [comment]
Awesome, thanks!
