### ISSUE TITLE
Claiming namespace jasew

### ISSUE THREAD

**Issue by jasonwilliams** [EclipseFdn/open-vsx.org#2518]
Hello, I would like to claim the namespace jasew
I have already been publishing extensions under this name for quite a while, see:

https://marketplace.visualstudio.com/items?itemName=jasew.vscode-helix-emulation
https://marketplace.visualstudio.com/items?itemName=jasew.anki
https://open-vsx.org/extension/jasew/vscode-helix-emulation

**Comment by kineticsquid** [comment]
@jasonwilliams Good to have you!
