### ISSUE TITLE
Claiming namespace omBratteng

### ISSUE THREAD

**Issue by omBratteng** [EclipseFdn/open-vsx.org#252]
I just published my extension from the desertbit organization under my user name: [omBratteng/nftables](https://open-vsx.org/extension/omBratteng/nftables)
Original vscode plugin: https://marketplace.visualstudio.com/items?itemName=omBratteng.nftalbs

**Comment by spoenemann** [comment]
@omBratteng it seems you published the extension twice, the first time with a typo in its name (`omBratteng.nftalbs`). Shall I delete that first version?

**Comment by omBratteng** [comment]
I noticed the spelling mistake after I published, so I have published a corrected one on OpenVSX and VS Marketplace. But you could remove the one with the typo

**Comment by spoenemann** [comment]
Deleted.
