### ISSUE TITLE
Claiming namespace [dannysteenman]

### ISSUE THREAD

**Issue by dannysteenman** [EclipseFdn/open-vsx.org#2520]
Last week my namespace was transferred to a new namespace, thanks for that!

However the new namespace gives a big red warning, see: https://github.com/EclipseFdn/open-vsx.org/issues/2500#issuecomment-2053585988

It says I need to claim ownership according to the docs, can you please verify the namespace dannysteenman for me?

Thanks!

**Comment by kineticsquid** [comment]
@dannysteenman Welcome!
