### ISSUE TITLE
Claiming namespace [CraigRBroughton]

### ISSUE THREAD

**Issue by CRBroughton** [EclipseFdn/open-vsx.org#2522]
I've had a user for one of my VSCode extensions reach out to me, to publish on your website:

https://github.com/CRBroughton/htmx-attributes/issues/5
https://open-vsx.org/extension/CraigRBroughton/htmx-attributes

I'd like to claim the namspace CraigRBroughton.

If there's anything else I need to do, please could you respond to this issue. Thank you.

**Comment by kineticsquid** [comment]
@CRBroughton Thanks for your contribution!
