### ISSUE TITLE
Claiming namespace mplodeai

### ISSUE THREAD

**Issue by fredxfred** [EclipseFdn/open-vsx.org#2531]
I have a startup called mplode.ai - as you can see by visiting https://mplode.ai and clicking on the link under "[experience shipping cloud products](https://www.linkedin.com/in/frederick-weitendorf-40b505b6/)", I (Fred Weitendorf) am affiliated (Founder) with the domain and company. We also have a stub presence on Github: https://github.com/mplode-ai

You can also see that in the official visual studio marketplace, I have just registered the [same namespace](https://marketplace.visualstudio.com/publishers/mplodeai) although it may not yet be verified by the time you check (it isn't yet).

For good measure I have added a new TXT record to my domain mplode.ai which you can query with

```
dig @stanley.ns.cloudflare.com mplode.ai TXT
```
after which you should see an entry "pleaseEclipseAndOpenVsxRecognize_fredxfred_onGithubAsAVerifiedEmployeeAndAllowNamespaceOwnership"

Hope that's sufficient. Thanks!

**Comment by kineticsquid** [comment]
@fredxfred Thanks for your contributions!
