### ISSUE TITLE
Claiming namespace Enoslyznne

### ISSUE THREAD

**Issue by lyznne** [EclipseFdn/open-vsx.org#2532]
"I am the legitimate owner of the personal namespace Enoslyznne  that I intend to use for publishing  themes and extensions on open-vsx.org. This is my personal namespace, and I have the right to publish extensions and themes under it."

**Comment by kineticsquid** [comment]
@lyznne Good to have you!

**Comment by lyznne** [comment]
@kineticsquid  Thank you! for  granting the namespace
