### ISSUE TITLE
Claiming namespace MobinX

### ISSUE THREAD

**Issue by MobinX** [EclipseFdn/open-vsx.org#2533]
I use this namespace every where like in vscode , linkedin , even here in github. For prove , anyone can see my linkedin and vscode marketplace id
linkedin:https://www.linkedin.com/in/mobinx/
vscode:https://marketplace.visualstudio.com/manage/publishers/mobinx

**Comment by kineticsquid** [comment]
@MobinX Thanks for your contribution!
