### ISSUE TITLE
Claiming namespace phpactor

### ISSUE THREAD

**Issue by zobo** [EclipseFdn/open-vsx.org#2540]
I would like to claim the namespace phpactor to publish vscode-phpactor extension. I already manage publishing to vscode marketplace. 

Some relevant threads on vscode-phpactor GH repo:
https://github.com/phpactor/vscode-phpactor/issues/40
https://github.com/phpactor/vscode-phpactor/issues/118

**Comment by kineticsquid** [comment]
@zobo Thanks for your contribution!
