### ISSUE TITLE
Claiming namespace metalware-inc

### ISSUE THREAD

**Issue by ihathbeer** [EclipseFdn/open-vsx.org#2542]
I am one of the co-founders of Metalware, Inc. looking to publish our extension on openVSX. You can see commits from me (@ihathbeer) to our [ public repo ](https://github.com/metalware-inc/public-assets/commits/main/). [Here](https://marketplace.visualstudio.com/items?itemName=metalware-inc.hdl-copilot) is our extension as it is exists on the VScode marketplace. The pictures in the README link directly back to the public repo I linked.

I'd like to claim `metalware-inc`.

**Comment by kineticsquid** [comment]
@ihathbeer Good to have you!
