### ISSUE TITLE
Claiming namespace realeinar

### ISSUE THREAD

**Issue by realeinar** [EclipseFdn/open-vsx.org#2547]
Hi,
I'm a user 'realeinar' in open-vsx.org and I like to verify my namespace 'realeinar'. I published my theme 'dracula midnight', which I owned repository in Github and I had this theme in vscode marketplace too.

ref:
https://github.com/realeinar/dracula-midnight
https://marketplace.visualstudio.com/items?itemName=realeinar.theme-dracula-midnight

**Comment by kineticsquid** [comment]
@realeinar Thanks for your contribution, we can always use a touch of the macabre.

**Comment by realeinar** [comment]
thanks. 😇
