### ISSUE TITLE
Claiming namespace hershel-theodore-layton

### ISSUE THREAD

**Issue by hershel-theodore-layton** [EclipseFdn/open-vsx.org#2582]
I am the developer who writes under the alias hershel-theodore-layton.

I have ownership of the hershel-theodore-layton Github Account. This account has been active since [March 2021](https://github.com/hershel-theodore-layton?tab=overview&from=2021-12-01&to=2021-12-31). The projects published in this account are also published to Packagist, where I am also the owner of the hershel-theodore-layton namespace.

 - https://github.com/hershel-theodore-layton
 - https://packagist.org/users/Hershel%20Theodore%20Layton/packages/
 
 If I need to provide more information to meet the standards of proof set out by the Eclipse Foundation, please notify me via a reply on this Github Issue.

**Comment by kineticsquid** [comment]
@hershel-theodore-layton Thanks for your contribution!
