### ISSUE TITLE
Claiming namespace [rwth-moves]

### ISSUE THREAD

**Issue by darionhaase** [EclipseFdn/open-vsx.org#2583]
I work at the Chair for Software Modeling and Verification at RWTH Aachen University (https://moves.rwth-aachen.de). Our GitHub group is https://github.com/moves-rwth.
We want to publish extensions like https://github.com/moves-rwth/caesar (see https://marketplace.visualstudio.com/items?itemName=rwth-moves.caesar) also on the Open VSX repository in the namespace `rwth-moves`.
Can you grant me the ownership? Thanks!

**Comment by kineticsquid** [comment]
@darionhaase Welcome!
