### ISSUE TITLE
Claiming namespace JuanGerardoMedellinIbarra

### ISSUE THREAD

**Issue by thegera4** [EclipseFdn/open-vsx.org#2587]
I made the extension 'Sqlite Viewer-Browser' that I would like to publish. This extension is already published in the VSCode marketplace: 

https://marketplace.visualstudio.com/items?itemName=JuanGerardoMedellinIbarra.sqlite-viewer-browser

https://github.com/thegera4/sqlite-viewer

I'd like to claim ownership of the namespace so that I can publish more extensions and updates in the future.

**Comment by kineticsquid** [comment]
@thegera4 Welcome!
