### ISSUE TITLE
Claiming namespace sema4ai

### ISSUE THREAD

**Issue by sahokas** [EclipseFdn/open-vsx.org#2589]
We currently own two extensions under namespace robocorp:
 - [https://open-vsx.org/extension/robocorp/robocorp-code](https://open-vsx.org/extension/robocorp/robocorp-code)
 - [https://open-vsx.org/extension/robocorp/robotframework-lsp](https://open-vsx.org/extension/robocorp/robotframework-lsp)

Robocorp has been acquired by Sema4.ai as announced [here](https://robocorp.com/blog/robocorp-joins-sema4.ai-advancing-human-ai-collaboration).

We are rebranding our developer offering under Sema4.ai and would like to claim the namespace.

Links to our relevant web presence:
 - [https://sema4.ai](https://sema4.ai)
 - [https://github.com/sema4ai](https://github.com/sema4ai)
 - [https://www.linkedin.com/company/sema4-ai](https://www.linkedin.com/company/sema4-ai)
 - VSCode Marketplace, extension(s) to to be published in the near future [https://marketplace.visualstudio.com/publishers/sema4ai](https://marketplace.visualstudio.com/publishers/sema4ai)

**Comment by kineticsquid** [comment]
@sahokas Thanks for your contributions!
