### ISSUE TITLE
Claiming namespace LeonardSSH

### ISSUE THREAD

**Issue by leonardssh** [EclipseFdn/open-vsx.org#2593]
Hi, I'm not sure how and why, but I had my ownership removed from the LeonardSSH namespace, the namespace on which I had my VSCode extension for discord.

![image](https://github.com/EclipseFdn/open-vsx.org/assets/35312043/a20d28d5-c947-4119-bae8-b6a598bea2cd)

I tried to release a new version of the extension, but it throws an error.

![image](https://github.com/EclipseFdn/open-vsx.org/assets/35312043/5a3315b3-87bd-4f4c-a15c-2677fa2a2fa9)

https://github.com/leonardssh/vscord

**Comment by kineticsquid** [comment]
@leonardssh This is strange because on my admin panel I show you as owner:
<img width="804" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/854a7542-11dc-4880-9650-6c6b0f7177e4">

On your profile page, when you click `NAMESPACES`, what do you see?

**Comment by leonardssh** [comment]
![image](https://github.com/EclipseFdn/open-vsx.org/assets/35312043/d5d2c56c-82b5-41bb-aec6-c6994d790e5f)
![image](https://github.com/EclipseFdn/open-vsx.org/assets/35312043/5bc88346-54b4-4275-9a07-dfe6c707fa63)

**Comment by kineticsquid** [comment]
I see this for publisher `LeonardSSH`:
<img width="791" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/53d85bee-ea23-4611-8e66-b02192a912f4">

And this for publisher `leonardssh`:
<img width="786" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/ec274698-6ba5-42a6-b77f-10fecc2e8e2d">

**Comment by kineticsquid** [comment]
Just a thought, could you be mixing up keys between the IDs?

**Comment by leonardssh** [comment]
I don't think so, I was using the same key since I published the extension to OpenVSX, but after I changed my name (same name only as lowercase), it stopped working. 

I thought it needed renewing or something, that's why I created another one, but it doesn't seem to be working as I expected. 😂 

can't my namespace be transferred from LeonardSSH account to the lowercase one?

**Comment by kineticsquid** [comment]
Effectively yes, I do that by 'renaming' `LeonardSSH` to `leonardssh` and ask that the extensions be merged. Can you confirm this is what you want?
<img width="667" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/854403d9-3d09-42c3-8d72-db7873a05b77">

**Comment by leonardssh** [comment]
@kineticsquid

**Comment by leonardssh** [comment]
Yes, it works now, thanks!
