### ISSUE TITLE
The server responded with status 504: Gateway Time-out

### ISSUE THREAD

**Issue by phaumer** [EclipseFdn/open-vsx.org#261]
I uploaded a new version of https://open-vsx.org/extension/IBM/zopeneditor at 12/13 around 7:45pm Pacific time and received this error:

```bash
$ npx ovsx publish zopeneditor-1.1.3.vsix -p <my-key>
❌  The server responded with status 504: Gateway Time-out
```

The resulting download looks ok, though.

**Comment by spoenemann** [comment]
@mbarbero are there more details in the server log?

**Comment by mbarbero** [comment]
Thanks for reporting this. I see a couple of connect timeout on 12/13 from our reverse proxy to open-vsx.org server. I've started internal investigation.

**Comment by brianking** [comment]
@mbarbero Any conclusions about this one yet?

**Comment by ssbarnea** [comment]
I got the same few minutes ago but after few refreshes I was able to login.

**Comment by mbarbero** [comment]
@ssbarnea Thanks for reporting this.

There has been a spike load around the time you've experienced the issue, so I guess the app has been longer to reply than the proxy was ready to wait for. Also, I see only a couple of 504 in today's logs and only around the time you are mentioning.

We don't have JVM monitoring active currently on the application. We may need to investigate this path to see if some low level stuff (e.g. GC pauses) are causing the spike load, or if it's just increased traffic.

**Comment by brianking** [comment]
We've made a number of tweaks recently to improve performance. Please open a new issue if something similar happens again.

**Comment by phaumer** [comment]
I published a new version of our extension last Thursday and the problem was gone. Thanks a lot.
