### ISSUE TITLE
Claiming namespace smallcloud

### ISSUE THREAD

**Issue by oxyplay** [EclipseFdn/open-vsx.org#2616]
Hello, we publish our extension in vscode marketplace under smallcloud namespace https://marketplace.visualstudio.com/items?itemName=smallcloud.codify. Want to use same namespace at open-vsx, not sure how to confirm because of corporate account.  You can find my account at members page https://github.com/orgs/smallcloudai/people

**Comment by kineticsquid** [comment]
@oxyplay Welcome!
