### ISSUE TITLE
Claiming namespace pfwobcke

### ISSUE THREAD

**Issue by cooolbros** [EclipseFdn/open-vsx.org#2624]
My extension is published under the publisher name `pfwobcke` on the Visual Studio Marketplace. The marketplace page also links to the Github repository, which is owned by my Github account.

Marketplace: https://marketplace.visualstudio.com/items?itemName=pfwobcke.vscode-vdf
Github Repository: https://github.com/cooolbros/vscode-vdf

**Comment by kineticsquid** [comment]
@cooolbros Good to have you!
