### ISSUE TITLE
Claiming namespace Decodetalkers

### ISSUE THREAD

**Issue by Decodetalkers** [EclipseFdn/open-vsx.org#2633]
My extension is published under the publisher name Decodetalkers on the Visual Studio Marketplace. The marketplace page also links to the Github repository, which is owned by my Github account.

Marketplace: https://marketplace.visualstudio.com/items?itemName=Decodetalkers.neocmake-lsp-vscode
Github Repository: https://github.com/Decodetalkers/vscode-neocmakelsp

**Comment by kineticsquid** [comment]
@Decodetalkers Thanks for your contribution!
