### ISSUE TITLE
Claiming namespace PixelcopResearch

### ISSUE THREAD

**Issue by chetan** [EclipseFdn/open-vsx.org#2634]
I own pixelcop.net, github.com/pixelcop and have also published this extension on the [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=PixelcopResearch.themestar) under the same ID. [open-vsx link](https://open-vsx.org/extension/PixelcopResearch/themestar)

**Comment by kineticsquid** [comment]
@chetan Thanks for your contribution!
