### ISSUE TITLE
Claiming namespace michaeljolley

### ISSUE THREAD

**Issue by michaeljolley** [EclipseFdn/open-vsx.org#2635]
I am Michael Jolley. 😄

I have several extensions I'll be publishing to OpenVSX.

I thought this had been done, but apparently there's a mixup.

**Comment by kineticsquid** [comment]
@michaeljolley My admin panel shows you as owner of this namespace:
<img width="723" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/716e242e-d9af-4954-9748-fecbebae72a5">

**Comment by michaeljolley** [comment]
That's odd @kineticsquid. My account: 
![image](https://github.com/EclipseFdn/open-vsx.org/assets/1228996/80f999d7-f91b-41ee-a474-2384acba3452)

![image](https://github.com/EclipseFdn/open-vsx.org/assets/1228996/75419cbd-1d76-4431-a007-6e38966b8562)

I know it **was** there because I published an extension. Only noticed it now because I tried to publish another extension and it says I'm not part of the namespace.

**Comment by michaeljolley** [comment]
Looking at your screenshot and mine, could this be an issue with casing? My account shows all lowercase michaeljolley where yours shows MichaelJolley.

**Comment by kineticsquid** [comment]
@michaeljolley Yes, that's it. Here's what I see for publisher `michaeljolley`:
<img width="729" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/2d24f6f9-9d13-4ed9-967f-5c8587b68774">

And here's what I see for publisher `MichaelJolley`:
<img width="724" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/9e6f6421-28b2-4a69-98dc-5a16a9ecdc71">

The namespace is owned by the `MichaelJolley` ID.

**Comment by michaeljolley** [comment]
Can we remove it from MichaelJolley and give it to michaeljolley? Not sure why/how they're different.

**Comment by kineticsquid** [comment]
@michaeljolley Namespaces are not case sensitive, publisher IDs are. Did you change your Github ID at some point?

I've added publisher `michaeljolley` to the namepsace. See if this works:
<img width="699" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/71ff418c-74cc-4a5e-919f-c95f8d40cece">

**Comment by michaeljolley** [comment]
Heck, I barely remember what I did yesterday. _Maybe I changed it._

Regardless, good to go now. Thanks!

**Comment by kineticsquid** [comment]
@michaeljolley We good now, can I close this?

**Comment by michaeljolley** [comment]
Yup. Good to go.
