### ISSUE TITLE
Remove outdated `cschleiden.vscode-github-actions` extension

### ISSUE THREAD

**Issue by sgraband** [EclipseFdn/open-vsx.org#2639]
This extension has been [moved to the GitHub org](https://github.blog/2023-03-28-announcing-the-github-actions-extension-for-vs-code/) a year ago and the old repository has been [read-only since then](https://github.com/github/vscode-github-actions).

The extension is now published as `github.vscode-github-actions` on open-vsx.org. Could the old unmaintained version be removed to avoid confusion?

**Comment by kineticsquid** [comment]
Done!
