### ISSUE TITLE
Regarding namespace Fr43nk / Fr43nks

### ISSUE THREAD

**Issue by fr43nk** [EclipseFdn/open-vsx.org#2644]
Hi,

I uploaded my extension
https://open-vsx.org/extension/Fr43nks/seito-openfile.
I now saw, that there is my extension already uploaded by  open-vsx. Why is that and can I take the ownership of this as it is my normal namespace / publisher name Fr43nk.

<img width="661" alt="Bildschirmfoto 2024-06-14 um 02 39 19" src="https://github.com/EclipseFdn/open-vsx.org/assets/3279247/114f46e1-5963-444b-9790-b1b323c32602">

**Comment by fr43nk** [comment]
@kineticsquid do you know anything about it?

**Comment by kineticsquid** [comment]
@fr43nk Well, treat this as a compliment. Someone at some point submitted a PR to have your extension auto-published as part of this related project: https://github.com/open-vsx/publish-extensions. There's a job that runs nightly iterating over a list of extensions, looking for those that have been updated on the VS Code marketplace and attempts to publish the updated to open-vsx.org. Here's your extension: https://github.com/open-vsx/publish-extensions/blob/2d3d33f8bf244ddfb73e4b15e7da46f776cf3086/extensions.json#L376.

What outcome to you want? Have this published to just one of the namespaces? You can own one or both of the namespaces and continue to have it auto-publish. Or turn off the auto-publishing.

**Comment by fr43nk** [comment]
Hi,
thank you for the information. Indeed, I wasn't aware of that 🙂.
If it is possible, I would like to own the Fr43nk namespace. This was my long term publisher name and I needed to change it to publish my extension here.
So how do we proceed now?

Best regards,
Frank

**Comment by kineticsquid** [comment]
@fr43nk You are now the proud owner of said namespace!

**Comment by fr43nk** [comment]
Good work. Is it also possible to delete the Fr43nks namespace or at least the extension? So, everyone who wants to download the extension does it from the right namespace (Fr43nk).

Best regards,
