### ISSUE TITLE
Claiming namespace moonbit

### ISSUE THREAD

**Issue by bzy-debug** [EclipseFdn/open-vsx.org#2650]
Sorry for the confusion, but similar to #2645, we are also the owner of github organisation @moonbit, and the extension we publish before (https://open-vsx.org/extension/moonbit/moonbit-lang) is actually under namespace moonbit. So we'd like to also get the ownership of namespace moonbit

**Comment by bzy-debug** [comment]
any update on this issue?

**Comment by kineticsquid** [comment]
@bzy-debug Granted! Thanks for your contributions.
