### ISSUE TITLE
Got Internal Server Error when publish extension

### ISSUE THREAD

**Issue by quanzhuo** [EclipseFdn/open-vsx.org#2651]
Please help, I met the following error when publish a new version of my extension

`ovsx publish --pat <token> .\qt-support-Kylin-IDE-0.0.5.vsix`
❌  Internal Server Error
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Publisher: KylinIdeTeam
name: qt-support
version 0.0.5

**Comment by kineticsquid** [comment]
Closing this as https://github.com/EclipseFdn/open-vsx.org/issues/2654 is resolved.
