### ISSUE TITLE
Claiming namespace marimo-team

### ISSUE THREAD

**Issue by mscolnick** [EclipseFdn/open-vsx.org#2653]
Claiming: `marimo-team`
I am the the main contributor to: https://github.com/marimo-team/vscode-marimo
Which has the publisher as marimo-team: https://github.com/marimo-team/vscode-marimo/blob/main/package.json#L5
You can also find the extension published to: https://marketplace.visualstudio.com/items?itemName=marimo-team.vscode-marimo

**Comment by kineticsquid** [comment]
@mscolnick Thanks for your contribution!
