### ISSUE TITLE
publishing of an extension update gets stuck and fails to complete

### ISSUE THREAD

**Issue by jsswan** [EclipseFdn/open-vsx.org#2654]
I am attempting to publish an updated version of the `IBM.zopendebug` extension (from version `4.1.0` to version `4.2.0`) using the 'Publish Extension' button in the open-vsx browser interface. I've tried a couple of times, but the upload/publish process never finishes.

I drag and drop the .vsix into the 'Publish Extension' dialog and press the 'Publish' button as usual, but the progress spinner just spins forever, and the extension page is never updated with the new version. I didn't time it exactly, but I waited at least an hour for the first attempt to complete before cancelling it and trying again.

**Comment by Christopher-Hayes** [comment]
I'm having the same issue. Was happening 2 days ago, still happening today.

[Open VSX Registry Status](https://status.open-vsx.org/) says everything's okay, but it seems like that status isn't checking the publish API.

In the network tools, it's a `500` "Internal Server Error". No more information than that. It just retries over and over, if you go to Settings > Keys, you'll probably see a million keys. It creates a new "one-time" API key every time it retries the publish API.

Looks like it's happening over API too: #2651 

For debugging:

```yaml
Publisher: Christopher-Hayes
Namespace: chris-hayes
Extension: chris-hayes/chatgpt-reborn
```

**Comment by bzy-debug** [comment]
Still get the same issue today

**Comment by Christopher-Hayes** [comment]
This issue is also being tracked on Eclipse's GitLab Help Desk:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4749

**Comment by Christopher-Hayes** [comment]
Looks like "Publish" is working again.

**Comment by jsswan** [comment]
Confirmed, publishing now works. It's also much faster than it used to be.
