### ISSUE TITLE
Claiming namespace tuttieee

### ISSUE THREAD

**Issue by tuttieee** [EclipseFdn/open-vsx.org#269]
I need this namespace to publish a VSCode extension, Awesome Emacs Keymap, that I have developed.
Related links follow:
* [Open VSX page (still unverified)](https://open-vsx.org/extension/tuttieee/emacs-mcx)
* [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=tuttieee.emacs-mcx)
* [GitHub repository](https://github.com/tuttieee/vscode-emacs-mcx)

**Comment by brianking** [comment]
Granted. Thanks for your contributions.
