### ISSUE TITLE
Claiming namespace MinecraftCommands

### ISSUE THREAD

**Issue by RitikShah** [EclipseFdn/open-vsx.org#2691]
I'm the publisher of the [syntax-mcfunction](https://marketplace.visualstudio.com/items?itemName=MinecraftCommands.syntax-mcfunction) extension. I maintain it via the [MinecraftCommands](https://github.com/MinecraftCommands/syntax-mcfunction) org that I'm a contributor of on Github.

**Comment by kineticsquid** [comment]
@RitikShah Thanks for your contribution!
