### ISSUE TITLE
Claiming namespace probe-rs

### ISSUE THREAD

**Issue by noppej** [EclipseFdn/open-vsx.org#2692]
I am the original developer of the extension at https://github.com/probe-rs/vscode/blob/master/package.json, and also one of the maintainers for the `probe-rs` organization on GitHub.

**Comment by Murmele** [comment]
I created the namespace for testing publishing probe-rs. @noppej will take it over. Thanks!

**Comment by kineticsquid** [comment]
@Murmele Welcome!

**Comment by Murmele** [comment]
@noppej I added you as owner.

@kineticsquid how can I remove me as owner of probe-rs so that @noppej is the only owner?
