### ISSUE TITLE
Claiming namespace altairengineering

### ISSUE THREAD

**Issue by tomqwpl** [EclipseFdn/open-vsx.org#2699]
I am claiming ownership of altairengineering namespace in order to publish extensions on behalf of the company Altair Engineering. We already publish to VSCode Marketplace as that publisher and are verified as such. Hopefully you can see from my profile email, and the fact that I'm a member and contributor to the Altair Engineering Github org that I am authorised to act to claim this namespace

**Comment by kineticsquid** [comment]
@tomqwpl Welcome!
