### ISSUE TITLE
Claiming namespace [betterthantomorrow]

### ISSUE THREAD

**Issue by PEZ** [EclipseFdn/open-vsx.org#270]
I am the creator of the Github organisation https://github.com/BetterThanTomorrow which is the umbrella for Calva (which I also created) development. We namespace everything Calva with this. I also own the domain `betterthantomorrow.com`.

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by PEZ** [comment]
Thanks. Now I just need to make Calva work in Theia. 😄 Super inspiring that Gitpod uses Open VSX as an extension store.
