### ISSUE TITLE
Delete extension altairengineering/slc

### ISSUE THREAD

**Issue by tomqwpl** [EclipseFdn/open-vsx.org#2709]
As a test of the process I published the above extension, but now want to remove it until ready to publish for real, and to change a few things. I don't want to change the version number. Same version is also published on vscode marketplace, so changing the version number isn't practical just for this purpose.
As far as I can tell there is no way I can do this myself (easy with MS VSCode marketplace, I can unpublish individual version, or whole extension), and the process appears to be I raise a ticket.

**Comment by kineticsquid** [comment]
@tomqwpl Yes, unfortunately we haven't surfaced to publishers the ability to un-publish their extensions. I need to do it as an admin. Poof!
