### ISSUE TITLE
Claiming namespace tumido

### ISSUE THREAD

**Issue by tumido** [EclipseFdn/open-vsx.org#271]
Hi, @tumido is my GH handle. I use this handle to publish packages at various locations and I'd be glad if I can continue using it on Open VSX site as well.

- [Open VSX package](https://open-vsx.org/extension/tumido/cron-explained) (unverified)
- Corresponing [VS Marketplace package](https://marketplace.visualstudio.com/items?itemName=tumido.cron-explained)
- [Github repo](https://github.com/tumido/cron-explained)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
