### ISSUE TITLE
Delete prematurely published extension

### ISSUE THREAD

**Issue by esmasth** [EclipseFdn/open-vsx.org#2712]
I had tried to test publish a pre-pre-release of an extension which is not yet usable without a backend, without knowing that revert/delete is not easy/possible.

As manual https://github.com/eclipse/openvsx/issues/58, I'm asking you here to please delete [my extension](https://open-vsx.org/extension/SiddharthSharma/pyang) but leave me in control of the namespace

**Comment by kineticsquid** [comment]
@esmasth Done!

**Comment by esmasth** [comment]
Thanks a lot!
