### ISSUE TITLE
Claiming namespace kuba-p

### ISSUE THREAD

**Issue by KubaP** [EclipseFdn/open-vsx.org#2715]
See [line 6 of package.json](https://github.com/KubaP/vscode-pink-candy/blob/881f588c8f2de5a8512ef809637ff407f3f7a290/package.json#L6) in my repository `vscode-pink-candy`.

The extension on the Microsoft vscode marketplace can be found [here](https://marketplace.visualstudio.com/items?itemName=kuba-p.theme-pink-candy).

**Comment by kineticsquid** [comment]
@KubaP I see that @megatank58 has already contributed https://open-vsx.org/extension/kuba-p/theme-pink-candy to this namespace. Can you reach out to them to see if they agree with you owning the namespace?

**Comment by megatank58** [comment]
Hello! Yes i do agree with this change

**Comment by kineticsquid** [comment]
Thanks @megatank58! Done!
