### ISSUE TITLE
Claiming namespace astro-tai

### ISSUE THREAD

**Issue by Tai-Zhou** [EclipseFdn/open-vsx.org#2716]
I am the developer of [ITH2Ome](https://marketplace.visualstudio.com/items?itemName=astro-tai.ith2ome), with the publisher name `astro-tai`. You may check it in the GitHub repo [here](https://github.com/Tai-Zhou/ITH2Ome/blob/main/package.json#L22).

Thank you so much~

**Comment by kineticsquid** [comment]
@Tai-Zhou Welcome!
