### ISSUE TITLE
Claiming namespace OpenModelica

### ISSUE THREAD

**Issue by AnHeuermann** [EclipseFdn/open-vsx.org#2717]
I'm one of the maintainers of the OpenModelica organization https://github.com/OpenModelica.
You can write a mail to the OSMC technical coordinator Adrian Pop:
https://openmodelica.org/home/contact-us/

We want to publish VS Code extensions like https://github.com/OpenModelica/modelica-language-server or https://github.com/OpenModelica/metamodelica-language-server on Open VSX Registry.

--------

Adding Technical Coordinator Adrian Pop @adrpo
Adding OSMC Director Francesco Casella @casella

**Comment by kineticsquid** [comment]
@AnHeuermann Good to have OpenModelica!
