### ISSUE TITLE
Claiming namespace [entan-gl]

### ISSUE THREAD

**Issue by empathicqubit** [EclipseFdn/open-vsx.org#272]
I have claims to this namespace through my existing published extension on the VSCode Marketplace, source repo available at https://github.com/empathicqubit/vscode-cc65-vice-debug, and published at https://marketplace.visualstudio.com/items?itemName=entan-gl.cc65-vice. I also own the domain name entan.gl, which has a similar name.

Thank you,
EmpathicQubit

**Comment by brianking** [comment]
Granted, thanks for your contributions to the Open VSX community.
