### ISSUE TITLE
Question: how to get extension download statistics?

### ISSUE THREAD

**Issue by bzy-debug** [EclipseFdn/open-vsx.org#2724]
In vscode extension marketpalce, as an extension author, I can view extension download statistics in extension manage panel. 

Here's a screenshot of the statistics page:

<img width="1445" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/71200607/0225ea0b-ac6d-4c8d-a3a2-a2cec2450fe2">

Does open vsx have similar extension download statistics for publishers? If so, where can I find it?

**Comment by kineticsquid** [comment]
@bzy-debug We don't provide this level of activity detail to publishers. @amvanbaren To what level of detail do we track dowloads and pageviews?

**Comment by kineticsquid** [comment]
@amvanbaren Thanks. @bzy-debug Closing this now. If you're interested in pursuing this, I'd suggest an enhancement request at https://github.com/eclipse/openvsx/issues (ideally with a PR).
