### ISSUE TITLE
Claiming namespace Venage5603

### ISSUE THREAD

**Issue by Venage5603** [EclipseFdn/open-vsx.org#2727]
i created the namespace as a way of being able to publish my vscode themes on different, more open platform. all the extension i post are either made by me or are edits of other themes with permissive licenses. the theme i plan on publishing is open sourced and is avalable [here](https://github.com/Venage5603/Tokyo-Night-Dark-Enhanced)

**Comment by kineticsquid** [comment]
@Venage5603 Thanks for your contribution!
