### ISSUE TITLE
Claiming namespace `akphi` and `blacksteed232`

### ISSUE THREAD

**Issue by akphi** [EclipseFdn/open-vsx.org#2729]
Hi,

I want to claim namespace `akphi` and `blacksteed232`. These are my 2 gthub and gitlab handles from where I intend to publish plugins. Also, for akphi, I own the domain https://akphi.com/
Thanks!

---
Links:
https://gitlab.com/blacksteed232
https://akphi.com/
https://github.com/akphi

**Comment by kineticsquid** [comment]
And they're yours!
