### ISSUE TITLE
Claiming namespace Postman

### ISSUE THREAD

**Issue by postman-ide** [EclipseFdn/open-vsx.org#2730]
I am claiming ownership of 'Postman' namespace in order to publish extensions on behalf of the company https://www.postman.com/. 
We already publish the Postman Extension to VSCode Marketplace as a verified publisher (https://marketplace.visualstudio.com/items?itemName=Postman.postman-for-vscode) and are working to publish the same to OpenVSX as well.
For verification purpose, the GitHub email address can be checked for this profile i.e. postman-ide@postman.com. 
Please let us know if any further details are required.

**Comment by kineticsquid** [comment]
@postman-ide Thanks for the additional info to help me validate your identity. Good to have you!
