### ISSUE TITLE
Claiming namespace PollywogGames

### ISSUE THREAD

**Issue by japhib** [EclipseFdn/open-vsx.org#2735]
Hi, I'm the developer of this extension:

https://open-vsx.org/extension/PollywogGames/pico8-ls

It's already published on vscode marketplace under the same namespace:

https://marketplace.visualstudio.com/items?itemName=PollywogGames.pico8-ls

I'm the owner & main developer on the source repo: https://github.com/japhib/pico8-ls

**Comment by kineticsquid** [comment]
@japhib Thanks for your contribution!

**Comment by japhib** [comment]
Thanks!
