### ISSUE TITLE
Claiming namespace [errata-ai]

### ISSUE THREAD

**Issue by ChrisChinchilla** [EclipseFdn/open-vsx.org#275]
I am trying to claim the namespace for myself, and ideally also @jdkato (though I don't think they have an account, or have had any interaction with Open VSX yet, but it's their organisation I think I need to include them here).

I created an extension of 'vale-vscode' manually, and would now like to automate the publication and build process.

**Comment by brianking** [comment]
Granted, thanks for your contributions to the Open VSX community.
