### ISSUE TITLE
Claiming namespace SrIzan

### ISSUE THREAD

**Issue by SrIzan10** [EclipseFdn/open-vsx.org#2759]
VSX Username: `SrIzan`

#### Evidence of Ownership
1. GitHub Profile: [GitHub Profile](https://github.com/SrIzan10)
2. [First extension published](https://open-vsx.org/extension/SrIzan/sern-snippets)'s GitHub page: [sern Snippets](https://github.com/sern-handler/snippets)
3. Owner of https://srizan.dev ([source code here](https://github.com/SrIzan10/mainwebsite)

I confirm that I have logged into OpenVSX at least once.

**Comment by kineticsquid** [comment]
@SrIzan10 Thanks for your contribution!
