### ISSUE TITLE
Claiming namespace jansim

### ISSUE THREAD

**Issue by jansim** [EclipseFdn/open-vsx.org#2768]
I'd like to claim the namespace `jansim`, since it's the same as my GitHub account and I already use it both on open-vsx and the official vscode marketplace (https://marketplace.visualstudio.com/items?itemName=jansim.solarized-sunset).

Just wanted to do this real quick to get rid of the warning on open vsx, thanks in advance!

**Comment by kineticsquid** [comment]
@jansim Thanks for your contribution!
