### ISSUE TITLE
Claiming namespace [openhab]

### ISSUE THREAD

**Issue by Confectrician** [EclipseFdn/open-vsx.org#277]
Hi,

I would like to claim the `openhab` namespace for usage with the https://github.com/openhab/openhab-vscode extension.
Currently we are only publishing to the [visualstudio extension marketplace](https://marketplace.visualstudio.com/items?itemName=openhab.openhab).

With https://github.com/openhab/openhab-vscode/issues/211 we got a request to also support the VSX Marketplace and VSCodium, which i am now trying to set up.

Thanks in advance for your feedback.

**Comment by brianking** [comment]
Granted, thanks for your contributions to the Open VSX community.
