### ISSUE TITLE
Claiming namespace jbro

### ISSUE THREAD

**Issue by jbro** [EclipseFdn/open-vsx.org#2770]
Hi I would like to use the same namespace on Open VSX Registry as I do on the official VSCode Marketplace.

Here is the link to an exstention in that namespace, that links to a project on GitHub, under my name: https://marketplace.visualstudio.com/items?itemName=jbro.vscode-default-keybindings

**Comment by kineticsquid** [comment]
@jbro Thanks for your contribution!
