### ISSUE TITLE
Claiming namespace PaisleySoftworks

### ISSUE THREAD

**Issue by furudean** [EclipseFdn/open-vsx.org#2772]
I'm the owner of the [Visual Studio Code Extension PaisleySoftworks.renpyWarp](https://marketplace.visualstudio.com/items?itemName=PaisleySoftworks.renpyWarp), as you can see in the metadata fields for this extension. I'd like to start mirroring this extension on Open VSX under the same namespace and name and I would like for this ownership to be verified.

**Comment by kineticsquid** [comment]
@furudean Thanks for your contribution!
