### ISSUE TITLE
Claiming namespace "PrismLink"

### ISSUE THREAD

**Issue by devarshishimpi** [EclipseFdn/open-vsx.org#2773]
I own the github organization https://github.com/prismlinkapp
As well have my VSCode extension published to the store at https://marketplace.visualstudio.com/items?itemName=PrismLink.lunar-theme
And just published the extension here at https://open-vsx.org/extension/PrismLink/lunar-theme

Just wanted to do this real quick to get rid of the warning on open vsx, thanks!

**Comment by kineticsquid** [comment]
@devarshishimpi Thanks for your contribution!
