### ISSUE TITLE
Claiming namespace "mikerheault"

### ISSUE THREAD

**Issue by mrheault** [EclipseFdn/open-vsx.org#2779]
Claiming my name to publish extensions. one on vscode marketplace https://marketplace.visualstudio.com/items?itemName=mikerheault.vscode-better-css-stacking-contexts
and published here: https://open-vsx.org/extension/mikerheault/vscode-better-css-stacking-contexts
Confirming have logged in once

**Comment by kineticsquid** [comment]
@mrheault Thanks for your contribution!
