### ISSUE TITLE
Claiming namespace RyliePavlik

### ISSUE THREAD

**Issue by rpavlik** [EclipseFdn/open-vsx.org#2786]
It's my name :grin:  I have verified ownership of the matching VS Code Marketplace namespace: https://marketplace.visualstudio.com/publishers/RyliePavlik

You should be able to see in my GitHub profile that I have verified ownership of the ryliepavlik domain name to associate with this user account, too (via meta tags) - there is only one Rylie Pavlik as far as I know.

**Comment by kineticsquid** [comment]
@rpavlik Good to have you!
