### ISSUE TITLE
EIGFA

### ISSUE THREAD

**Issue by MrSIHAB** [EclipseFdn/open-vsx.org#2795]
Hello I'm SIHAB. I actually planned to make a publisher named EIGFA and publish our already made extensions that We have made for vs code and codium. Unfortunately I found our extensions on vs code. But not in Vscodium. I like to use codium as my primary code editor.
So, I dive into deeper and found open-vsx.

I just created a namespace and uploaded my first [Mathab] theme which I specially designed for myself and decided to share with others.

Then I noticed about namespace ownership. 
I don’t like anyone use my namespace and publish anything. That should be limited.

**Comment by kineticsquid** [comment]
@MrSIHAB Good to have you!
