### ISSUE TITLE
Claiming namespace SnakeskinTpl

### ISSUE THREAD

**Issue by aabounegm** [EclipseFdn/open-vsx.org#2818]
Hello, I just published my extension at https://open-vsx.org/extension/SnakeskinTpl/snakeskin.
I am a member of the [SnakeskinTpl GitHub organization](https://github.com/SnakeskinTpl). I also published the same extension on the [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=SnakeskinTpl.snakeskin), so I would like to claim the same namespace on Open VSX as well.

**Comment by aabounegm** [comment]
Thanks!
Btw, do I need to publish a new version to get rid of this banner?
<img width="1030" alt="Screenshot 2024-08-06 at 6 54 12 PM" src="https://github.com/user-attachments/assets/0692f7f7-bdcd-482d-a683-b71bc0da33d5">

**Comment by kineticsquid** [comment]
Was probably a caching thing. Looks good to me now.
