### ISSUE TITLE
Cannot publish VSCode extensions to Open VSX Registry

### ISSUE THREAD

**Issue by daphne-sfdc** [EclipseFdn/open-vsx.org#2823]
I'm trying to publish a new release of the Salesforce Extensions for VSCode to the Open VSX Registry.  I ran [this workflow](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10287491467/job/28529669504) to publish the extensions and got a 502 Bad Gateway error.
```
Run cmd=$(find ./extensions -type f -name "*.vsix" -print0 | xargs -0 -I {} printf 'npx ovsx publish --skip-duplicate "%s" -p "%s" && ' '{}' "${OVSX_PAT}" | sed 's/ && $//') && [ -n "$cmd" ] && eval "$cmd" && echo "SUCCESSFULLY published"
❌  The server responded with status 502: Bad Gateway
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
Error: Process completed with exit code 1.
```

After doing some research I got to the [Open VSX Registry status page](https://status.open-vsx.org/), which shows that Open VSX Registry had been down for the past 2.5 hours and is still down.  The website https://open-vsx.org/ also has the same error.

I'm creating this issue to inform the Open VSX Registry Team of the issue and to get updates about when this would be fixed so that I can complete my extensions publish job.

**Comment by amvanbaren** [comment]
open-vsx.org is back up and running.
