### ISSUE TITLE
Claiming namespace [egovframework]

### ISSUE THREAD

**Issue by chris-yoon** [EclipseFdn/open-vsx.org#2824]
I'm the owner of the following urls regarding egovframework(or eGovFrame).
https://github.com/egovframework 
https://www.egovframe.go.kr/

* eGovFrame, the e-Government Standard Framework, is a platform-specific standardized development framework for public sector IT projects in Korea.
* It is the pre-implemented core functions via standardization of design patterns and source code. 
* The information system is completed by developing add-ins and assembling them.

* 251 common components
* Applied to over 768 e-Government projects (1.8 billion dollars) in Korea
* 48 open sources selected
Biz. transaction : Spring & 23
Data : MyBatis, iBatis, Hibernate & 1
Development tool : Eclipse & 4
Test tool : Junit & 4
Distribution tool : Maven & 4
Configuration Management tool : Sebversion & 1
Mobile UX : JQueryMobile & 2

**Comment by kineticsquid** [comment]
@chris-yoon Good to have you!
