### ISSUE TITLE
Claiming namespace pXius

### ISSUE THREAD

**Issue by pXius** [EclipseFdn/open-vsx.org#2825]
As per this Github and open-vsx.org account I am the author of the extension I'm attempting to publish some of the extensions linked in to my Github account.

These extensions are already published on the MS marketplace using the same Github account.

https://marketplace.visualstudio.com/items?itemName=pxius.carbon-owl

I can provide any other information if required.

**Comment by kineticsquid** [comment]
@pXius Welcome!
