### ISSUE TITLE
Extension '<extension-name>' not found

### ISSUE THREAD

**Issue by benz0li** [EclipseFdn/open-vsx.org#2826]
My pipelines, e.g.

* https://gitlab.b-data.ch/jupyterlab/julia/base/-/pipelines
* https://gitlab.b-data.ch/jupyterlab/cuda/julia/base/-/pipelines

currently fail.

**Comment by benz0li** [comment]
I install several extensions. If one installation fails, the pipeline fails.

**Comment by benz0li** [comment]
@amvanbaren Has there been a *rate limit* put in place?

(The requests of my pipelines origin from IP `dig +short b-data.ch`)

**Comment by benz0li** [comment]
There are still multiple runs required: https://gitlab.b-data.ch/jupyterlab/python/base/-/jobs/117043

It passes at some point.

**Comment by benz0li** [comment]
If this service is load balanced: This looks as if (at least) one of the upstream servers is offline.

**Comment by benz0li** [comment]
This issue seems to be resolved now.

It is still unclear why this happened while https://status.open-vsx.org stated "All services are online".

**Comment by benz0li** [comment]
Maybe related:

* https://github.com/EclipseFdn/open-vsx.org/issues/2827
  * https://github.com/eclipse/openvsx/issues/972

**Comment by benz0li** [comment]
I am running into this again.

**Comment by kineticsquid** [comment]
@benz0li We adjusted the rate limiting recently. Still seeing this?

**Comment by benz0li** [comment]
@kineticsquid Thank you for the update.

> @benz0li We adjusted the rate limiting recently. Still seeing this?

Right now: No. But tomorrow all my [Jupyter](https://github.com/b-data/jupyterlab-mojo-docker-stack)[Lab](https://github.com/b-data/jupyterlab-julia-docker-stack) [docker](https://github.com/b-data/jupyterlab-python-docker-stack) [stacks](https://github.com/b-data/jupyterlab-r-docker-stack) – which include `code-server` – will be rebuilt.

Let's see if that works... I will keep you updated.

**Comment by benz0li** [comment]
@kineticsquid Seems to be resolved.

Thank you.

**Comment by benz0li** [comment]
I am running into this again.

**Comment by benz0li** [comment]
My [Jupyter](https://github.com/b-data/jupyterlab-julia-docker-stack)[Lab](https://github.com/b-data/jupyterlab-mojo-docker-stack) [docker](https://github.com/b-data/jupyterlab-python-docker-stack) [stack](https://github.com/b-data/jupyterlab-r-docker-stack) builds started failing:

* https://gitlab.b-data.ch/jupyterlab/r/base/-/pipelines/35320
* https://gitlab.b-data.ch/jupyterlab/cuda/r/base/-/pipelines/35321

**Comment by benz0li** [comment]
I paused my builds for two hours, which seems to have gotten me out of the *rate limit*.
