### ISSUE TITLE
Open VSX Registry rate-limit mechanism misbehavior respond with 429 Too Many Requests

### ISSUE THREAD

**Issue by garylavayou** [EclipseFdn/open-vsx.org#2827]
> This issue should have been first reported to this repository, but I have not noticed the existence of this repository.
> The same issue can be visited at <https://github.com/eclipse/openvsx/issues/972#issue-2457831988>.

**Comment by amvanbaren** [comment]
Hi @garylavayou, thanks for reporting this issue. 
Let's discuss this further at https://github.com/eclipse/openvsx/issues/972
