### ISSUE TITLE
Unpublish duplicated extension

### ISSUE THREAD

**Issue by marabesi** [EclipseFdn/open-vsx.org#2830]
It happens that I changed the name in package.json of my extension and it turned to be duplicated in the website: https://open-vsx.org/namespace/marabesi.

The correct version is the one with 0.0.15.

This one should be deleted: https://open-vsx.org/extension/marabesi/smelly-vscode
This one should remain: https://open-vsx.org/extension/marabesi/smelly-test

I am creating this issue based on the recommendation from: https://github.com/eclipse/openvsx/issues/58, if this is not the place let me know how I can get this version unpublished.

**Comment by kineticsquid** [comment]
Done!
