### ISSUE TITLE
Claiming namespace [name]

### ISSUE THREAD

**Issue by GITRUTH0** [EclipseFdn/open-vsx.org#2833]
Gitruth

**Comment by kineticsquid** [comment]
@GITRUTH0 I've created namespace `Gitruth`. To assign ownership, you need to execute the publisher agreement.

**Comment by kineticsquid** [comment]
@GITRUTH0 ^^^^

**Comment by GITRUTH0** [comment]
I have executed the agreement

**Comment by kineticsquid** [comment]
Done!
