### ISSUE TITLE
Claiming namespace jlansford

### ISSUE THREAD

**Issue by JEdward7777** [EclipseFdn/open-vsx.org#2847]
According to ovsx  I just created this namespace.
```
🚀  Created namespace jlansford
```
It is also my first initial and last name, so unless someone else wants it I am claiming it.

**Comment by JEdward7777** [comment]
If you scroll to the bottom of my homepage at [lansfords.com](https://lansfords.com), you see my git repo cross referenced from there.

**Comment by kineticsquid** [comment]
@JEdward7777 Welcome!
