### ISSUE TITLE
Claiming namespace jroesch

### ISSUE THREAD

**Issue by gebner** [EclipseFdn/open-vsx.org#285]
I am the main developer and maintainer of the extension with the id `jroesch.lean` ([github repo](https://github.com/leanprover/vscode-lean), [Open VSX](https://open-vsx.org/extension/jroesch/lean), [Microsoft marketplace](https://marketplace.visualstudio.com/items?itemName=jroesch.lean)) and I would like to claim the namespace `jroesch`.

(For historical reasons, the namespace is the username of the original author.  I am already an owner of the `jroesch` publisher id on the Microsoft marketplace.)

**Comment by brianking** [comment]
Granted, thanks for your contributions!
