### ISSUE TITLE
Claiming namespace DrMerfy

### ISSUE THREAD

**Issue by DrMerfy** [EclipseFdn/open-vsx.org#286]
Happy new year,
I have published the overtype extension under the namespace DrMerfy (https://open-vsx.org/extension/DrMerfy/overtype)

This is the continuation forked extension of Adam Mara's that was built for MS Visual Studio Code and is now discontinued (https://github.com/AdamMaras/vscode-overtype/pull/13).

**Comment by brianking** [comment]
Granted, thanks for your contributions!
