### ISSUE TITLE
Claiming namespace [sh-cho]

### ISSUE THREAD

**Issue by sh-cho** [EclipseFdn/open-vsx.org#2865]
I've created vscode-fluent-bit extension

- vscode marketplace: https://marketplace.visualstudio.com/items?itemName=sh-cho.vscode-fluent-bit
- openvsx: https://open-vsx.org/extension/sh-cho/vscode-fluent-bit

**Comment by kineticsquid** [comment]
@sh-cho Thanks for your contribution!
