### ISSUE TITLE
Claiming namespace raspberry-pi

### ISSUE THREAD

**Issue by will-v-pi** [EclipseFdn/open-vsx.org#2869]
I'm developing the [pico-vscode](https://github.com/raspberrypi/pico-vscode) extension, and have ownership of the raspberry-pi publisher on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/publishers/raspberry-pi). We've been requested to publish to the open-vsx registry as well by some users (https://github.com/raspberrypi/pico-vscode/issues/20), hence the creation of this namespace.

**Comment by kineticsquid** [comment]
@will-v-pi Good to have you!
