### ISSUE TITLE
Claiming namespace isontheline

### ISSUE THREAD

**Issue by isontheline** [EclipseFdn/open-vsx.org#2877]
Hello 👋

I would like to claim the namespace "isontheline" because it's my nickname on all major platforms and it's also my GitHub username : @isontheline

* https://open-vsx.org/extension/isontheline/vscode-sysmon
* https://github.com/isontheline/vscode-sysmon
* https://marketplace.visualstudio.com/items?itemName=isontheline.vscode-sysmon

Thank you 🙏

**Comment by kineticsquid** [comment]
@isontheline Thanks for your contribution!
