### ISSUE TITLE
Claiming namespace sap-partner-eng

### ISSUE THREAD

**Issue by andrewlunde** [EclipseFdn/open-vsx.org#288]
I (Andrew Lunde[andrew.lunde@sap.com]) am the tooling owner for SAP Partners and support SAP Partner Edge program participants.

If you require further confirmation, please reach out to my direct manager Sunil Wadhwa <sunil.wadhwa01@sap.com>.

-Andrew

**Comment by brianking** [comment]
Granted, thanks for your contributions.
