### ISSUE TITLE
Claiming namespace RomainLEON 

### ISSUE THREAD

**Issue by PeekLeon** [EclipseFdn/open-vsx.org#2881]
Hello,

I am requesting ownership of the namespace RomainLEON on Open VSX. Here is some context about my account and the extension:

Identity and Explanation:

I am Romain LEON, and I manage the extension gitvarmng (Extension Repository: [Gitlab Var Manager VSCode](https://github.com/PeekLeon/gitlab-var-manager-vscode)).  
Although my GitHub username is **PeekLeon**, I am the same person as the **RomainLEON** namespace I am requesting.
My GitHub profile can be found here: [PeekLeon GitHub Profile](https://github.com/PeekLeon).  

Thank you for your assistance!

**Comment by kineticsquid** [comment]
@PeekLeon Thanks for your contribution!
