### ISSUE TITLE
Claiming namespace vanruesc

### ISSUE THREAD

**Issue by vanruesc** [EclipseFdn/open-vsx.org#2885]
Hi, I'd like to claim the namespace `vanruesc`.

I've created a publisher account on https://marketplace.visualstudio.com yesterday and found out that I also need to publish extensions on https://open-vsx.org to be able to find them with VSCodium.

This is the theme I've published: https://marketplace.visualstudio.com/items?itemName=vanruesc.whimsical-vscode-theme (https://open-vsx.org/extension/vanruesc/whimsical-vscode-theme) and here's the repo: https://github.com/vanruesc/whimsical-vscode-theme.

**Comment by kineticsquid** [comment]
@vanruesc Welcome!
