### ISSUE TITLE
Claiming namespace cyrusfirheir

### ISSUE THREAD

**Issue by cyrusfirheir** [EclipseFdn/open-vsx.org#289]
I am the author of the extension `cyrusfirheir.twee3-language-tools` ([Open VSX](https://open-vsx.org/extension/cyrusfirheir/twee3-language-tools), [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=cyrusfirheir.twee3-language-tools), [GitHub repo](https://github.com/cyrusfirheir/twee3-language-tools)) extension and I would like to claim the namespace `cyrusfirheir` (which is my username on GitHub.)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
