### ISSUE TITLE
Claiming namespace `tum-aet`

### ISSUE THREAD

**Issue by krusche** [EclipseFdn/open-vsx.org#2893]
I am the professor of the research group Applied Education Technologies (`aet`) at the Technical University of Munich (tum). We currently have the website https://ase.cit.tum.de but will soon change to https://aet.cit.tum.de (which does not work yet)

**Comment by kineticsquid** [comment]
@krusche I see that @janthoXO has published https://open-vsx.org/extension/tum-aet/artemis-scorpio in this namespace. Are they a colleague of yours?

**Comment by krusche** [comment]
Yes, it would be great if we could make sure that no warning is shown any more

**Comment by kineticsquid** [comment]
Yes, that warning will go away when I assign ownership. Can I get confirmation from @janthoXO that they are OK with you taking ownership?

**Comment by janthoXO** [comment]
yes @krusche should be the owner of the namespace and would be good if I get the contributor role

**Comment by kineticsquid** [comment]
@janthoXO thanks for confirming. @krusche Have you signed the publisher agreement? Need you to do that before I can assign ownership.

**Comment by krusche** [comment]
Where can I find it?

**Comment by kineticsquid** [comment]
@krusche On open-vsx.org, click on your GitHub profile pic in the upper right and then 'settings'. You'll see a link there:
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/f0ce0c73-d8ea-4818-891b-fa11ebf941c1">

**Comment by krusche** [comment]
@kineticsquid thanks for the link. I did that now. Everything good now?

**Comment by kineticsquid** [comment]
@krusche You should be good. You are owner and @janthoXO is a contributor.
