### ISSUE TITLE
Claiming namespace SuperGregM

### ISSUE THREAD

**Issue by SuperGregM** [EclipseFdn/open-vsx.org#2894]
I would like to Request exclusive publishing rights to SuperGregM namespace on Open VSX.

Thank You

**Comment by kineticsquid** [comment]
@SuperGregM good to have you!

**Comment by SuperGregM** [comment]
Hi my extension still has the unverified warning. Is there anything left for me to do to take ownership of it? [SuperGreatMonokai](https://open-vsx.org/extension/SuperGregM/supergreatmonokai)
