### ISSUE TITLE
Delete v0.21.5 of davidlday/languagetool-linter.

### ISSUE THREAD

**Issue by davidlday** [EclipseFdn/open-vsx.org#2900]
Please delete v0.21.5 of davidlday/languagetool-linter.

My current GitHub pipeline publishes to both Open VSX and VS Code Marketplace. Publishing to VS Code Marketplace failed, and due to how I have my pipeline setup, I can't rerun because now publishing to Open VSX fails. I will split this into two separate pipelines to avoid this situation in the future.

**Comment by kineticsquid** [comment]
Poof!
