### ISSUE TITLE
Claiming namespace `wabifoundation`

### ISSUE THREAD

**Issue by furby-tm** [EclipseFdn/open-vsx.org#2903]
I am the executive director of the [Wabi Foundation](https://github.com/wabiverse). I had just setup this namespace today, to publish an extension for VSCode (VSX as well as Open VSX). Please let me know if you need any additional information, thanks!

What I had published is the following:
- [VSX Extension](https://marketplace.visualstudio.com/items?itemName=wabifoundation.vscode-galah-syntax)
- [Open VSX Extension](https://open-vsx.org/extension/wabifoundation/vscode-galah-syntax)

**Comment by kineticsquid** [comment]
@furby-tm Welcome!
