### ISSUE TITLE
Claiming namespace `SanjulaGanepola`

### ISSUE THREAD

**Issue by SanjulaGanepola** [EclipseFdn/open-vsx.org#2905]
Hello! I am a Software Developer that would like to claim the namespace `SanjulaGanepola` to publish a VS Code extension. Please let me know if any other information is required.

**Comment by kineticsquid** [comment]
@SanjulaGanepola Good to have you!

**Comment by SanjulaGanepola** [comment]
@kineticsquid Thank you. Would you also be able to delete an extra namespace which I created and no longer need: `SampleTest`.

**Comment by kineticsquid** [comment]
Done!
