### ISSUE TITLE
Please unpublish sap-partner-eng.sap-partner-eng-extension-pack

### ISSUE THREAD

**Issue by andrewlunde** [EclipseFdn/open-vsx.org#291]
And one more thx.

https://open-vsx.org/extension/sap-partner-eng/sap-partner-eng-extension-pack

sap-partner-eng.sap-partner-eng-extension-pack

I've tightened up my scripts so that shouldn't happen in the future.

-Andrew

**Comment by brianking** [comment]
This extension has been removed.
