### ISSUE TITLE
Claiming namespace vrognas

### ISSUE THREAD

**Issue by vrognas** [EclipseFdn/open-vsx.org#2917]
I am the creator and maintainer of the NMTRAN extension.
I created the extension in the VSCode marketplace: https://marketplace.visualstudio.com/items?itemName=vrognas.nmtran
It provides syntax highlighting and other features when working with NONMEM control streams, a common software for pharmacokinetic modeling in the pharmaceutical industry.

I own the domain vrognas.com.

**Comment by kineticsquid** [comment]
@vrognas Good to have you!
