### ISSUE TITLE
Remove Thunder Client up to v2.20.0

### ISSUE THREAD

**Issue by amvanbaren** [EclipseFdn/open-vsx.org#2922]
From https://github.com/eclipse/openvsx/issues/983:

> Hi
>
> I am the owner of the extension [Thunder Client](https://open-vsx.org/extension/rangav/vscode-thunder-client)
>
> We would like to request the OpenVSX team to delete the older versions of our extension due to legal and security concerns. We have > made significant changes to the third-party libraries in the latest version, and the older versions are no longer supported.
>
>    Extension Name: [Thunder Client](https://open-vsx.org/extension/rangav/vscode-thunder-client)
>    Older Versions to be Deleted: All versions up to v2.20.0
>    Reason: Legal and security issues.
>
> Thanks

**Comment by rangav** [comment]
Thank you @amvanbaren for moving the issue to this repo.

**Comment by kineticsquid** [comment]
@rangav I'm assuming you do not want v2.20.0 deleted.

**Comment by rangav** [comment]
@kineticsquid you can remove 2.20.0 also. Thanks

**Comment by kineticsquid** [comment]
@rangav Done!

**Comment by rangav** [comment]
Thanks @kineticsquid, appreciate your help.

**Comment by rangav** [comment]
Hi @kineticsquid 

I have another deletion request.

The versions up to `v2.22.0 `are using outdated third-party libraries that are no longer supported. Could you please delete all versions up to and including `v2.22.0`?

Thanks for the support.

**Comment by kineticsquid** [comment]
@rangav Poof!

**Comment by rangav** [comment]
Thanks @kineticsquid

**Comment by rangav** [comment]
Hi @kineticsquid

Sorry to bother you again, 

The versions up to `v2.25.9` are using outdated third-party libraries that are no longer supported. 

Could you please delete all versions up to and including `v2.25.9`?

Thanks for the support.

**Comment by kineticsquid** [comment]
Done!
<img width="617" alt="image" src="https://github.com/user-attachments/assets/77f6b01e-9334-4f59-a946-3c22310e33cf">

**Comment by rangav** [comment]
Perfect, thanks for your support.

**Comment by rangav** [comment]
Hi @kineticsquid

Could you please delete all versions up to and including **v2.29.10**?

These versions are no longer supported, and we would like them to be removed.

Thank you for your support.

**Comment by rangav** [comment]
@kineticsquid can you process the above request?
