### ISSUE TITLE
Claiming namespace dafny-lang

### ISSUE THREAD

**Issue by keyboardDrummer** [EclipseFdn/open-vsx.org#2924]
I'm one of the people in the organization https://github.com/orgs/dafny-lang/people, and one of the main active contributors of the Dafny extension located at https://github.com/dafny-lang/ide-vscode, as can be seen from GH contributor insights: https://github.com/dafny-lang/ide-vscode/graphs/contributors?from=9%2F10%2F2022

**Comment by kineticsquid** [comment]
@keyboardDrummer Welcome!
