### ISSUE TITLE
Claiming namespace rszyma

### ISSUE THREAD

**Issue by rszyma** [EclipseFdn/open-vsx.org#2926]
As of [the request](https://github.com/rszyma/vscode-kanata/issues/38) of a user of vscode-kanata extension, that I'm author of, I'm trying to publish the extension to open-vsx. I'm already the owner of the same namespace on vscode marketplace - https://marketplace.visualstudio.com/items?itemName=rszyma.vscode-kanata, so I'd like to claim the same namespace on open-vsx.

**Comment by kineticsquid** [comment]
@rszyma Welcome!
