### ISSUE TITLE
Claiming namespace [davraamides]

### ISSUE THREAD

**Issue by davraamides** [EclipseFdn/open-vsx.org#293]
I built the `davraamides.todotxt-mode` extension for VS code and was asked to publish it here. `davraamides` is my Github login and my open-vsx login.

Thanks,
-David

**Comment by brianking** [comment]
Granted, thanks for your contributions.

Don't forget to sign the publisher agreement is you have not already!

**Comment by davraamides** [comment]
I don’t see where to sign it. I can read it, but where do I sign it?

On Jan 7, 2021, at 10:57 AM, Brian King <notifications@github.com> wrote:

﻿
Granted, thanks for your contributions.

Don't forget to sign the publisher agreement is you have not already!

**Comment by spoenemann** [comment]
Signing the agreement is documented in steps 1 and 2 here:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by davraamides** [comment]
Thanks, Miro. I just signed the agreement and was able to publish an update
to my extension.
