### ISSUE TITLE
Delete `biomejs.biome-nightly`

### ISSUE THREAD

**Issue by nhedger** [EclipseFdn/open-vsx.org#2937]
Hey :wave:,

Could you please delete [`biomejs/biome-nightly`](https://open-vsx.org/extension/biomejs/biome-nightly)? We've switched to the pre-release model instead of maintaining two separate extensions the, and existence of the nightly version keeps confusing our users.

We've already unpublished it's counterpart on the Visual Studio Marketplace.

Thanks!

**Comment by kineticsquid** [comment]
Done!

**Comment by nhedger** [comment]
Thanks @kineticsquid, much appreciated!
