### ISSUE TITLE
Need to unpublish accidentally published broadcomMFD.explorer-for-endevor 1.9.0-BETA

### ISSUE THREAD

**Issue by roman-kupriyanov** [EclipseFdn/open-vsx.org#2938]
Hello,

I would need to request to unpublish a beta version of the Explorer for Endevor extension 1.9.0-BETA https://open-vsx.org/extension/BroadcomMFD/explorer-for-endevor. It was published on the accident because of the error in the pipeline and should be avoided from being installed as the latest release for the users. There is no mechanism to unpublish the versions automatically which is requested here: https://github.com/eclipse/openvsx/issues/58 so I need to ask for it here.

Thank you!

**Comment by kineticsquid** [comment]
@roman-kupriyanov Confirming you want me to unpublish _only_ version `1.9.0-BETA`?

**Comment by roman-kupriyanov** [comment]
> @roman-kupriyanov Confirming you want me to unpublish _only_ version `1.9.0-BETA`?

Yes, _only_ `1.9.0-BETA` to unpublish. We also released `1.8.2` yesterday but it is expected release and should stay as the latest.

**Comment by kineticsquid** [comment]
Done!
