### ISSUE TITLE
Claiming namespace Antyos

### ISSUE THREAD

**Issue by Antyos** [EclipseFdn/open-vsx.org#294]
I am the author of the extension `antyos.openscad` ([GitHub repo](https://github.com/Antyos/vscode-openscad), [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Antyos.openscad))

I would like to be the owner of the namespace `Antyos` so that I can publish my extensions on OpenVSX. It is the username I use for publishing extensions to VSCode, my GitHub username, as well as the alias I use across the internet.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
