### ISSUE TITLE
Claiming namespace [sbg-rabix]

### ISSUE THREAD

**Issue by kghose** [EclipseFdn/open-vsx.org#295]
I lead open source efforts at Seven Bridges which owns the Rabix trademark. We publish the VS Code extension Benten under the namespace `sbg-rabix`. The code for this extension is found at https://github.com/rabix/benten

Thank you.

**Comment by brianking** [comment]
Granted, thanks for your contributions.

Please consider adding a Readme to the extension with next upload.
