### ISSUE TITLE
Claiming namespace treuks

### ISSUE THREAD

**Issue by treuks** [EclipseFdn/open-vsx.org#2956]
Hey, I'd love to upload my extensions to Open VSX.

For example, here's a theme that I have created:
https://github.com/treuks/blowington-theme

Here is the same theme uploaded to the VS marketplace:
https://marketplace.visualstudio.com/items?itemName=treuks.blowington-theme

The theme on the marketplace leads back to this github account and the prior mentioned repository.

Thank you for your time.

**Comment by kineticsquid** [comment]
@treuks Thanks for your contribution!
