### ISSUE TITLE
Claiming namespace Yseop

### ISSUE THREAD

**Issue by yseop-services** [EclipseFdn/open-vsx.org#296]
This account is a service account owned by the OPS team of Yseop and needs to be the owner of the official Yseop namespace created by @alacambre-yseop, the developer of the YseopML VSCode extension (https://github.com/yseop/vscode-yseopml).

Thanks.

**Comment by brianking** [comment]
@yseop-services is now the namespace owner, thanks for your contributions.

**Comment by brianking** [comment]
I'm afraid I have had to revoke ownership of the namespace for @yseop-services. I forgot that we do not grant namespace ownership to bots and service accounts.

https://github.com/EclipseFdn/open-vsx.org/wiki/Guidelines-on-Namespaces#checking-ownership-requests

If you nominate someone with an individual GitHub account, we can make them owner.

**Comment by spoenemann** [comment]
@alacambre-yseop Note that you can add more namespace members (including service accounts) yourself in https://open-vsx.org/user-settings/namespaces

**Comment by alacambre-yseop** [comment]
> I forgot that we do not grant namespace ownership to bots and service accounts.

Sorry, we missed this part too. 

Let me ask for ownership, then.
Thanks for this project!

**Comment by brianking** [comment]
@alacambre-yseop You are now the namespace owner.
