### ISSUE TITLE
Claiming namespace Linxford

### ISSUE THREAD

**Issue by Linxford** [EclipseFdn/open-vsx.org#2970]
### Namespace Claim for 'Linxford'

I am requesting ownership of the 'Linxford' namespace. Below are the details of why I am the legitimate owner:

- I have logged into the Open VSX registry using the account associated with the Linxford namespace.
- I am the creator and maintainer of projects under the 'Linxford' namespace, including the SVG Icon Extension and related repositories.
- I own the corresponding namespace on GitHub (, which is linked to these projects.

Please verify and assign the namespace to me.

Thank you!

**Comment by kineticsquid** [comment]
@Linxford Welcome!
