### ISSUE TITLE
Claiming namespace anibalsolon

### ISSUE THREAD

**Issue by anibalsolon** [EclipseFdn/open-vsx.org#298]
Dear all,

I am Anibal Solon, and I'd like to claim the namespace `anibalsolon` as the rightful heir of this throne.

Besides being my username everywhere (or mostly, since we cannot change the username on Eclipse.org 👎), I am already a [publisher in the VSCode Marketplace](https://marketplace.visualstudio.com/publishers/anibalsolon) and would like very much to be a verified publisher on [OpenVSX](https://open-vsx.org/extension/anibalsolon/neuro-viewer).

Thank you and keep coding!

**Comment by brianking** [comment]
All hail the King! Thanks for your contributions.

**Comment by anibalsolon** [comment]
hahaha thank you @brianking
