### ISSUE TITLE
Claiming namespace [aimebertrand]

### ISSUE THREAD

**Issue by macownersclub** [EclipseFdn/open-vsx.org#2989]

**Comment by macownersclub** [comment]
Well, not [aimebertrand] but rather aimebertrand

**Comment by kineticsquid** [comment]
@macownersclub Thanks for your contributions! Are you going to want your extensions moved to `macownersclub` namespace?

**Comment by macownersclub** [comment]
Not really. I thought I needed to claim it since it is my GitHub handle.

**Comment by kineticsquid** [comment]
We good then, just checking

**Comment by macownersclub** [comment]
Hi there,

I don't know if reopen or not, but it looks like the namespace `aimebertrand` (Aimé Bertrand is the display name) is not granted:

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/ecd6ce2e-de90-4910-9dbe-2eaa95bb616b">
