### ISSUE TITLE
Deleting duplicate - macownersclub/timu-macos-vscode

### ISSUE THREAD

**Issue by macownersclub** [EclipseFdn/open-vsx.org#2997]
# Appologies:
* Accidentally published the following duplicate in the wrong namespace:
https://open-vsx.org/extension/macownersclub/timu-macos-vscode

* The correct is published here:
https://open-vsx.org/extension/macownersclub/timu-macos-vscode

Is it possible to delete https://open-vsx.org/extension/macownersclub/timu-macos-vscode

**Comment by kineticsquid** [comment]
@macownersclub Clarifying... the correct URL above is the same as the duplicate URL.

**Comment by macownersclub** [comment]
Again - Appologies:

Correct: https://open-vsx.org/extension/aimebertrand/timu-macos-vscode
To be deleted: https://open-vsx.org/extension/macownersclub/timu-macos-vscode

**Comment by kineticsquid** [comment]
Got it, thanks. Deleted.
