### ISSUE TITLE
fossil-scm.org/home/vpatch?from=d84eef54be05c5eb&to=1958448c6ef271e4

### ISSUE THREAD

**Issue by qMatr1xp** [EclipseFdn/open-vsx.org#3000]
https://fossil-scm.org/home/vpatch?from=d84eef54be05c5eb&to=1958448c6ef271e4

**Comment by kineticsquid** [comment]
@qMatr1xp Getting a lot of noise from you and this repo. It looks unintentional. Can you check your GitHub integrations?
