### ISSUE TITLE
Claiming namespace "crave-io"

### ISSUE THREAD

**Issue by mohitkumat** [EclipseFdn/open-vsx.org#3004]
Member of [Crave.io](https://crave.io/) team with emails `mohit@crave.io` & `mohitkumat776@gmail.com`, trying to publish "Crave Devspaces" VSCode extension. Already published on Visual Studio Marketplace. Please grant the ownership. Thanks.

**Comment by kineticsquid** [comment]
@mohitkumat Thanks for your contribution!
