### ISSUE TITLE
Claiming namespace pixiedev

### ISSUE THREAD

**Issue by pixiedevpraveen** [EclipseFdn/open-vsx.org#3007]
Hi, 
I am Praveen Yadav, I do publish extension for vscode in vscode marketplace and just now want to publish my extensions on open vsx too. But in vscode marketplace my username is pixiedev and here, I can't change it, because open vsx took it from my github username. So kindly verify me as owner of pixiedev namespace.

**Comment by kineticsquid** [comment]
@pixiedevpraveen Thanks for your contributions!
