### ISSUE TITLE
Delete duplicate mk12.bqn-language extension

### ISSUE THREAD

**Issue by mk12** [EclipseFdn/open-vsx.org#3009]
I am moving development of the BQN extension to my fork https://github.com/mk12/bqn-vscode because razetime unfortunately passed away.

I accidentally published v0.1.7 twice under my namespace mk12. The first one, "BQN language", was in error. I want to delete that one and only keep the one named "BQN".

**Comment by kineticsquid** [comment]
@mk12 Deleted one version of `mk12.bqn-language`.
