### ISSUE TITLE
Claiming namespace ast-grep (transferring it if possible)

### ISSUE THREAD

**Issue by herrwusel** [EclipseFdn/open-vsx.org#3020]
I created the namespace to test a workflow to publish [ast-grep](https://github.com/ast-grep/ast-grep)'s [vscode extension](https://github.com/ast-grep/ast-grep-vscode) to openvsx.

I would like to ideally transfer the namespace to @HerringtonDarkholme also named "HerringtonDarkholme" on openvsx. If a transfer is not possible I'd like to claim the namespace and add them as owner.

**Comment by HerringtonDarkholme** [comment]
Hi open-vsx team, I am [ast-grep](https://ast-grep.github.io/)'s author. Thank @herrwusel for creating this extension on open-vsx. 

ast-grep is a command-line tool for precise code search and manipulation using abstract syntax trees (ASTs). It offers multiple languages support. ast-grep-vscode brings ast-grep’s capabilities to Visual Studio Code, offering structural search, replace, and linting directly within the editor.

I will greatly appreciate open-vsx team's response to help the claim possible! Thanks

**Comment by kineticsquid** [comment]
@herrwusel I have added @HerringtonDarkholme to the namespace and made them owner. @herrwusel is still listed as a contributor.
