### ISSUE TITLE
Remove Solidity (Wake) extension

### ISSUE THREAD

**Issue by michprev** [EclipseFdn/open-vsx.org#3024]
Hello!
We are experiencing users reporting duplicate extensions in their Code-like IDEs as we published the extension under a different namespace on Open VSIX compared to what we use on MS Marketplace:
- https://open-vsx.org/extension/AckeeBlockchainSecurity/tools-for-solidity
- https://marketplace.visualstudio.com/items?itemName=AckeeBlockchain.tools-for-solidity

I want to ask to remove the extension and also the AckeeBlockchainSecurity namespace, if possible. I am the owner.

**Comment by kineticsquid** [comment]
@michprev Done!
