### ISSUE TITLE
Claiming namespace zoma

### ISSUE THREAD

**Issue by wottpal** [EclipseFdn/open-vsx.org#3030]
My personal pseudonym. Owner of [zoma.(dev|email|blog)](https://zoma.dev/) domains. Twitter [@dennis_zoma](https://x.com/dennis_zoma). Already published VSCode extension under this namespace 2 years ago [here](https://marketplace.visualstudio.com/items?itemName=zoma.vscode-auto-open-workspace).

**Comment by kineticsquid** [comment]
@wottpal Thanks for your contribution!

**Comment by wottpal** [comment]
Nice, many thanks for the fast processing! I guess it takes a couple of hours/days that this takes effect on the Open VSX site? (… as it's still unclaimed there)

**Comment by kineticsquid** [comment]
@wottpal There is some caching and so can be a delay. I just checked and I'm not seeing the warning. Do you still see it?

**Comment by wottpal** [comment]
working now 👌
