### ISSUE TITLE
Claiming namespace AckeeBlockchain

### ISSUE THREAD

**Issue by michprev** [EclipseFdn/open-vsx.org#3031]
As a follow-up of https://github.com/EclipseFdn/open-vsx.org/issues/3024 I would like to ask to claim the AckeeBlockchain namespace.

I am member of https://github.com/Ackee-Blockchain and contributor of the extension to be published https://github.com/Ackee-Blockchain/solidity-for-vscode.

**Comment by kineticsquid** [comment]
@michprev Gooed to have you!
