### ISSUE TITLE
Claiming namespace [zzxwill]

### ISSUE THREAD

**Issue by zzxwill** [EclipseFdn/open-vsx.org#3047]
I am a developer contributing elegant coding tools. `zzxwill` is the handler for my github, LinkedIn, twitter as below.
- https://www.github.com/zzxwill
- https://www.linkedin.com/in/zzxwill
- https://www.twitter.com/zzxwill

I would like to publish IDE extensions in the namespace of `zzxwill`.

Thanks :)

**Comment by kineticsquid** [comment]
@zzxwill Welcome!
