### ISSUE TITLE
Buggy MS Python Extension Should be Removed

### ISSUE THREAD

**Issue by kirupa** [EclipseFdn/open-vsx.org#3065]
The ms-python.python extension version 2024.14.0 got released to open-vsx 2 months ago. And it incorrectly claims that it supports vscode version 1.89 while it actually requires a much newer vscode version. Additionally it is missing certain binary files that prevent this version from working correctly even on newer versions of vscode.

While it looks like the subsequently released version 2024.14.1 fixes both issues, the unintended consequence of this is that when running vscode 1.89, installing the latest python extension results in version 2024.14.0 being installed, which has the above bugs preventing it from functioning.

The reason it affects IDX is that we currently run on code-oss 1.89. Is there anything that can be done to fix the issue for us?

One likely solution is that 2024.14.0 is removed from OpenVSX.

**Comment by kineticsquid** [comment]
@kirupa I can remove that extension version. Can you confirm that in the absence of ms-python.python 2024.14.0, running vscode 1.89 will result in the correct version of  ms-python.python being installed?

**Comment by kirupa** [comment]
@kineticsquid - yes, please remove that version. That will ensure the correct version is picked up.

**Comment by kineticsquid** [comment]
Done!
