### ISSUE TITLE
Remove nhcham/pixelflow-canvas

### ISSUE THREAD

**Issue by specht** [EclipseFdn/open-vsx.org#3070]
Please remove nhcham/pixelflow-canvas and keep gymnasiumsteglitz/pixelflow-canvas – I changed the publisher and cannot remove the old version which I uploaded as nhcham. Having both extensions in the marketplace may confuse my students and I would like to have the duplicate (old) entry removed. Thanks!

**Comment by kineticsquid** [comment]
Gone!
