### ISSUE TITLE
Website open-vsx.org is down: Bad gateway 502

### ISSUE THREAD

**Issue by priyankark** [EclipseFdn/open-vsx.org#3073]
Started seeing 502 Bad Gateway since the past 15-20 minutes.
<img width="564" alt="Screenshot 2024-10-29 at 9 05 56 PM" src="https://github.com/user-attachments/assets/fdbb4931-4822-4afb-b1ca-f23d95a930f2">

**Comment by priyankark** [comment]
The above issue is fixed. But publishing extensions is failing with:

**Comment by kineticsquid** [comment]
I'm not seeing any errors. Still failing for you?

**Comment by priyankark** [comment]
This got fixed. I was able to publish my extension. Issue can be closed, thanks for the response!
