### ISSUE TITLE
Unpublish extension https://open-vsx.org/extension/zzxwill/vefaas-code-deployer

### ISSUE THREAD

**Issue by zzxwill** [EclipseFdn/open-vsx.org#3075]
Per the request https://github.com/EclipseFdn/open-vsx.org/issues/3072, we don't need to host extensions in namespace `zzxwill`. So please help to remove all the extensions from `zzxwill`.

Then users won't get confused like this.
![image](https://github.com/user-attachments/assets/fd65f6aa-1e23-4c56-b795-c59dc55eed1c)

Thank you @kineticsquid :)

**Comment by kineticsquid** [comment]
@zzxwill Done!
