### ISSUE TITLE
Claiming namespace [name]Officialfedar

### ISSUE THREAD

**Issue by OfficialFedar** [EclipseFdn/open-vsx.org#3080]

**Comment by kineticsquid** [comment]
@OfficialFedar I've created the namespace. In order to assign it to you, I need you to sign the publisher agreement.

**Comment by kineticsquid** [comment]
Welcome!

**Comment by OfficialFedar** [comment]
> @OfficialFedar I've created the namespace. In order to assign it to you, I need you to sign the publisher agreement.

Ok
