### ISSUE TITLE
Claiming namespace cycode

### ISSUE THREAD

**Issue by MarshalX** [EclipseFdn/open-vsx.org#3082]
Hello, I am SE at Cycode ([cycode.com](https://cycode.com/)). I maintain different IDE plugins including VS Code one. We are interested in publishing our extension to open-vsx. This is our extension https://github.com/cycodehq/vscode-extension (you can see me here as main contributor). Thank you!

**Comment by kineticsquid** [comment]
@MarshalX Thanks for your contribution!
