### ISSUE TITLE
Claiming namespace firefox-devtools

### ISSUE THREAD

**Issue by hbenl** [EclipseFdn/open-vsx.org#3087]
I am the main author of the [vscode-firefox-debug extension](https://open-vsx.org/extension/firefox-devtools/vscode-firefox-debug) as you can see from the commits in its [repository](https://github.com/firefox-devtools/vscode-firefox-debug) and I'd like to update the extension on open-vsx.

**Comment by kineticsquid** [comment]
@hbenl Thanks for your contribution!
