### ISSUE TITLE
Claiming namespace [lucien-martijn]

### ISSUE THREAD

**Issue by luusluus** [EclipseFdn/open-vsx.org#3096]
I am the sole developer of https://github.com/luusluus/vscode-parquet-visualizer.
Vscode marketplace here: https://marketplace.visualstudio.com/items?itemName=lucien-martijn.parquet-visualizer

So I'd like to claim the namespace lucien-martijn for openvsx.

**Comment by kineticsquid** [comment]
@luusluus Good to have you!
