### ISSUE TITLE
Claiming namespace [brunobastosg]

### ISSUE THREAD

**Issue by brunobastosg** [EclipseFdn/open-vsx.org#3102]
I'm the author of the extension [Gerador CPF/CNPJ](https://github.com/brunobastosg/gerador-cpf-cnpj-vscode), which is published under my namespace.

**Comment by kineticsquid** [comment]
@brunobastosg Welcome!

**Comment by brunobastosg** [comment]
> @brunobastosg Welcome!

Thank you. My extension is still unverified, though (https://open-vsx.org/extension/brunobastosg/gerador-cpf-cnpj). Is there anything else I need to do or do I have to just wait?
