### ISSUE TITLE
backend binary

### ISSUE THREAD

**Issue by compliance-7-369-vortical-mechanism** [EclipseFdn/open-vsx.org#3118]
uses shape binary for implementing access to alternate vortical mechanisms

**Comment by kineticsquid** [comment]
@amvanbaren Do you understand this?

**Comment by amvanbaren** [comment]
@kineticsquid Nope. @compliance-7-369-vortical-mechanism is a fresh account and #3117 is just as cryptic. I think we can ignore this.

**Comment by compliance-7-369-vortical-mechanism** [comment]
thankyou
