### ISSUE TITLE
Claiming namespace treblecode-vsc

### ISSUE THREAD

**Issue by trebleCode** [EclipseFdn/open-vsx.org#3121]

**Comment by trebleCode** [comment]
I own the publisher ID treblecode-vsc in the Visual Studio Code Marketplace manager section and my github handle is trebleCode.
![Screenshot from 2024-11-15 17-41-11](https://github.com/user-attachments/assets/0d327e04-10af-4314-b2bc-373bec4b3ba0)

**Comment by kineticsquid** [comment]
@trebleCode Good to have you!
