### ISSUE TITLE
Claiming namespace brioche-dev

### ISSUE THREAD

**Issue by kylewlacy** [EclipseFdn/open-vsx.org#3124]
We just published [`brioche-dev.brioche-vscode`](https://open-vsx.org/extension/brioche-dev/brioche-vscode), which also just went up with the latest release on the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=brioche-dev.brioche-vscode). This extension is part of [Brioche](https://brioche.dev), and the extension itself lives in the repo https://github.com/brioche-dev/brioche-vscode (I'm the owner of the `brioche-dev` GitHub org and the `brioche-vscode` repo)

**Comment by kineticsquid** [comment]
@kylewlacy We can always use more bakers!
