### ISSUE TITLE
Claiming namespace rphlmr

### ISSUE THREAD

**Issue by rphlmr** [EclipseFdn/open-vsx.org#3127]
👋 I've created the same extension published to the Microsoft marketplace: [Drizzle ORM](https://marketplace.visualstudio.com/items?itemName=rphlmr.vscode-drizzle-orm).
[Sources](https://github.com/rphlmr/drizzle-lab) 

I have the same namespace here and on X 🫡

**Comment by kineticsquid** [comment]
@rphlmr Welcome!
