### ISSUE TITLE
Claiming namespace launchdarklyofficial

### ISSUE THREAD

**Issue by rmanalan** [EclipseFdn/open-vsx.org#313]
I maintain the LaunchDarkly VSCode extension and also an employee of LaunchDarkly. I'd like to claim this namespace.

**Comment by brianking** [comment]
Hi @rmanalan, just checking but I don't see you listed as a contributor at https://github.com/launchdarkly/ld-vscode. Can you define what you mean by maintain? Thanks.

**Comment by rmanalan** [comment]
I'm fairly new to the project, but now the owner. You can see my recent
commits on https://github.com/launchdarkly/ld-vscode/commits/beta

**Comment by brianking** [comment]
Granted, thanks for your contributions.
