### ISSUE TITLE
Claiming namespace disneystreaming

### ISSUE THREAD

**Issue by Baccata** [EclipseFdn/open-vsx.org#3147]
I am a principal engineer at Disney, working on the Disney+ platform. I also am the maintainer of this vscode extension, currently published on the official microsoft-owned vscode marketplace:  https://github.com/disneystreaming/vscode-smithy/

I am a current admin of the `github.com/disneystreaming` organisation, which I think makes the claim to the namespace legitimate. 

Happy to provide additional information to support the claim, if necessary.

**Comment by kineticsquid** [comment]
@Baccata great to have you and Disney! I'll observe that @kubukoz is currently a contributor to this namespace.
