### ISSUE TITLE
Claiming namespace yocto-project

### ISSUE THREAD

**Issue by halstead** [EclipseFdn/open-vsx.org#3151]
Hello, I am the infrastructure lead for Yocto Project at the Linux Foundation. 

I'm the DNS admin for yoctoproject.org and an owner of https://github.com/yoctoproject/

I need to claim this namespace in order to verify that the Yocto Project has in fact sponsored https://open-vsx.org/extension/yocto-project/yocto-bitbake. The extension will continue to be maintained by https://github.com/deribaucourt.

Thank you for any assistance.

**Comment by kineticsquid** [comment]
@halstead I've made both you and @deribaucourt owners of the namespace.

**Comment by deribaucourt** [comment]
Amazing, I confirm the extension is now properly authenticated.
Thank you very much
