### ISSUE TITLE
Claiming namespace GitGuardian

### ISSUE THREAD

**Issue by GitGuardian-team** [EclipseFdn/open-vsx.org#3152]
Hi,

My name is [Mathieu Bellon](https://github.com/mathieubellon), Senior Product Manager at GitGuardian and on behalf of the company I am claiming both :

- the `gitguardian-secret-security` namespace
- the `GitGuardian` namespace.

Our Vscode extension allow developers to scan their code for secrets and alert them before they publish it to a public repository.

The service has a free tier to allow any dev to benefit from it.

Thanks for your assistance

**Comment by kineticsquid** [comment]
@GitGuardian-team Welcome!
