### ISSUE TITLE
Claiming namespace boshyxd

### ISSUE THREAD

**Issue by boshyxd** [EclipseFdn/open-vsx.org#3158]
I am the creator and maintainer of the VSCode extension "Remove All Comments" published under the namespace "boshyxd". I have already published the extension to Open VSX Registry and have set up the following verification:

1. I have created a GitHub repository at https://github.com/boshyxd/remove-all-comments
2. The repository contains a verification file at `.open-vsx/boshyxd` with my Open VSX access token
3. I have logged into open-vsx.org and am currently publishing under this namespace

This namespace matches my GitHub username (boshyxd) and I am requesting ownership to properly verify my extensions.

**Comment by kineticsquid** [comment]
@boshyxd Good to have you!
