### ISSUE TITLE
Claiming namespace polarity-lang

### ISSUE THREAD

**Issue by BinderDavid** [EclipseFdn/open-vsx.org#3167]
Hi,

I am one of the two maintainers of the research language polarity-lang: https://polarity-lang.github.io for which we maintain a vscode extension in this repository: https://github.com/polarity-lang/vscode which is also released in the Microsoft extension store here: https://marketplace.visualstudio.com/items?itemName=polarity-lang.polarity We also want to serve this extension to users of vscodium and other editors which are compatible with this extension format.

**Comment by kineticsquid** [comment]
@BinderDavid Thanks for your contribution!
