### ISSUE TITLE
Claiming namespace readthedocs

### ISSUE THREAD

**Issue by Mesteery** [EclipseFdn/open-vsx.org#317]
I am currently working on: https://github.com/readthedocs-fr/bin-vscode.
I would like to host it on open-vsx.

And can you delete https://open-vsx.org/extension/readthedocs/bin?
I released the wrong version, so it creates a huge gap with the rest (v1.0.0 vs v0.1.0 on repo and VSCode)

**Comment by brianking** [comment]
Granted, thanks for your contributions.

readthedocs.bin has been removed.
