### ISSUE TITLE
Claiming namespace [GuillaumeCLEMENT]

### ISSUE THREAD

**Issue by CorwinFr** [EclipseFdn/open-vsx.org#3172]
Hello,

I would like to claim the namespace GuillaumeCLEMENT on Open VSX. I am the developer of the Visual Studio Code extension "X3 4GL Tools," which enhances Sage X3 4GL development. As the creator and maintainer of this open-source project, I want to ensure that the namespace is appropriately linked to me for proper representation and to avoid confusion with other developers.

I have logged in to https://open-vsx.org/ and am ready to proceed with any additional steps required to verify my ownership.

Thank you for your support!

Best regards,
Guillaume Clément
https://www.linkedin.com/in/guillaume-clement-erp-cloud/

**Comment by CorwinFr** [comment]
By the way i'm the owner of this namespace on Azure, https://marketplace.visualstudio.com/items?itemName=GuillaumeCLEMENT.x3-4gl-tools

**Comment by kineticsquid** [comment]
@CorwinFr Thanks for your contribution!
