### ISSUE TITLE
Claiming namespace squad.ai

### ISSUE THREAD

**Issue by PeterNMcArthur** [EclipseFdn/open-vsx.org#3179]
I'm a founder of https://meetsquad.ai I created the extension that is used in the vscode market place:

https://marketplace.visualstudio.com/items?itemName=Squadai.squad-ai

**Comment by kineticsquid** [comment]
@PeterNMcArthur That's not a value namespace name. How about 'squadai' or 'squad-ai'?

**Comment by PeterNMcArthur** [comment]
Sorry @kineticsquid you're right. It's squad-ai

**Comment by kineticsquid** [comment]
Granted!
