### ISSUE TITLE
Claiming namespace SDTTTTT

### ISSUE THREAD

**Issue by sdttttt** [EclipseFdn/open-vsx.org#319]
Hello, I am `open-vsx.org/extension/SDTTTTT/bangumiopen` developers,I received a suggestion from `github.com/sdttttt/vscode-bangumi/issues/150 [Open VSX Listing: Signing the Publisher Agreement]`. , I hope to have the namespace SDTTTTT, iteration for future extensions.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
