### ISSUE TITLE
Claiming namespace codescene

### ISSUE THREAD

**Issue by jlindbergh** [EclipseFdn/open-vsx.org#3197]
Hi!
I'm the current main contributor to the [codescene/codescene-vscode](https://github.com/codescene-oss/codescene-vscode) extension and has been for the last 1+ year. Currently a full-time employee at [CodeScene AB](https://codescene.com/).

Best regards,
/Johan Lindbergh, CodeScene AB

**Comment by kineticsquid** [comment]
Hi @jlindbergh. To assign a namespace, I need you to sign a publisher agreement. Also, I can see @anderbergpeter is currently a contributor to this namespace.

**Comment by jlindbergh** [comment]
Sure, could you provide me with the agreement and I'll sign it as soon as I can. 
Peter is a colleague of mine, I can vouch for him. Or if you like we can remove him and I'll add him back at a later time.

**Comment by kineticsquid** [comment]
@jlindbergh Click your icon on the upper right of the homepage and then 'settings'. You'll see a link there. Once I assign ownership of the namespace, you can manage the contributors and other owners.

**Comment by kineticsquid** [comment]
@jlindbergh Thanks, I've added you as owner.
