### ISSUE TITLE
Claiming namespace loong-vsx

### ISSUE THREAD

**Issue by darkyzhou** [EclipseFdn/open-vsx.org#3199]
Hi, I'm the organizer of [LoongCodium](https://github.com/loongcodium), an organization focusing on bringing VSCodium and its extensions to the LoongArch architecture. I'd like to claim the `loong-vsx` namespace to host our ported extensions.

You can check out my contributions to VSCodium [here](https://github.com/VSCodium/vscodium/commits?author=darkyzhou), where I've submitted several patches to implement LoongArch support.

By the way, I am also applying to delete the existing `loong-vsx.rust-analyzer` extension, I had some mistakes publishing it.

**Comment by kineticsquid** [comment]
@darkyzhou Thanks for your contribution!

**Comment by darkyzhou** [comment]
Thank you. BTW, can you delete version `0.5.0-dev` and `0.5.0-dev-no-server`?

**Comment by kineticsquid** [comment]
@darkyzhou Deleted the two versions.
