### ISSUE TITLE
Claiming namespace viper-admin

### ISSUE THREAD

**Issue by viper-admin** [EclipseFdn/open-vsx.org#320]
https://github.com/viper-admin is the account that uploads extensions like https://marketplace.visualstudio.com/items?itemName=viper-admin.prusti-assistant.

**Comment by brianking** [comment]
We don't grant namespace ownership to bot or service accounts. If you nominate someone on your team with a personal account, we'd be happy to add them as owner.

**Comment by brianking** [comment]
@fpoli Would you like to be the namespace owner for this?

**Comment by fpoli** [comment]
@brianking Yes, thank you!

**Comment by brianking** [comment]
@fpoli has been granted ownership of the viper-admin namespace, based on them being listed as a contribution on https://github.com/viperproject/prusti-assistant.

Thanks for your contributions.
