### ISSUE TITLE
Claiming namespace bowlerhatllc

### ISSUE THREAD

**Issue by joshtynjala** [EclipseFdn/open-vsx.org#3207]
I am the author of the VSCode extensions released under the bowlerhatllc publisher name on the VSCode Marketplace:

https://marketplace.visualstudio.com/publishers/bowlerhatllc

The profile at the above URL links to https://bowlerhat.dev/, which is the website for my company, Bowler Hat LLC.

The profile also links to @BowlerHatLLC, which is my company's GitHub organization.

**Comment by kineticsquid** [comment]
@joshtynjala Granted! I'll add that I see @jordonr currently listed as a contributor.

**Comment by joshtynjala** [comment]
Thank you!
