### ISSUE TITLE
Claiming namespace ayecue

### ISSUE THREAD

**Issue by ayecue** [EclipseFdn/open-vsx.org#3214]
Hey 👋 

I would like to claim the namespace `ayecue` for the extension https://open-vsx.org/extension/ayecue/greybel-vs

I am the author and main contributor of that extension. 

Here is the github repository for reference https://github.com/ayecue/greybel-vs and here is the extension in the MS Marketplace for reference https://marketplace.visualstudio.com/items?itemName=ayecue.greybel-vs

Thanks in advance

**Comment by kineticsquid** [comment]
@ayecue Thanks for your contribution!
