### ISSUE TITLE
Claiming namespace MP-Favorite-OpenSource-Extension

### ISSUE THREAD

**Issue by MarcoPalayad** [EclipseFdn/open-vsx.org#3215]
I want to claim the namespace MP-Favorite-OpenSource-Extension, its sole purpose was to collect and upload some popular open source vscode extension to open-vsx like codeSTACKr theme (credit will go to original publisher of this theme) in open-vsx so that other fork of VS code editor can freely apply this theme and yes, I logged in to Open-VSX at least once.

**Comment by kineticsquid** [comment]
@MarcoPalayad I think you now own the longest namespace name
