### ISSUE TITLE
Claiming namespace chocolateimage

### ISSUE THREAD

**Issue by chocolateimage** [EclipseFdn/open-vsx.org#3220]
I am claiming this namespace (chocolateimage) because it is my name.
I have already published an extension to the Microsoft Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=chocolateimage.chocotools and Open VSX: https://open-vsx.org/extension/chocolateimage/chocotools (GitHub is https://github.com/chocolateimage/chocotools)

**Comment by kineticsquid** [comment]
@chocolateimage We'll add you to the menu
