### ISSUE TITLE
Claiming namespace onapsis

### ISSUE THREAD

**Issue by cbiguet** [EclipseFdn/open-vsx.org#3222]
I want to claim the **onapsis** namespace as a product manager working at Onapsis (www.linkedin.com/in/constantin-biguet-31618410b), we have already published extensions in the Visual Studio Code marketplace (example: https://marketplace.visualstudio.com/items?itemName=onapsis.cca-vscode-extension) that we would like to add to open-vsx

**Comment by kineticsquid** [comment]
@cbiguet Welcome!
