### ISSUE TITLE
Claiming namespace opensim

### ISSUE THREAD

**Issue by rhornig** [EclipseFdn/open-vsx.org#3227]
We are OpenSim Kft. (OpenSim Ltd.) developers of the OMNeT++ Discrete Event Simulator Framework omnetpp.org, github.com/omnetpp.

our DUNS page is here: https://www.dnb.com/hu-hu/cegkereso/vallalati-profilok.opensim_informatikai_korl%C3%A1tolt_felel%C5%91ss%C3%A9g%C3%BC_t%C3%A1rsas%C3%A1g.7b309f4067f4949defc30e55b4a531fb.html

**Comment by kineticsquid** [comment]
@rhornig Welcome!
