### ISSUE TITLE
Claiming namespace flyde

### ISSUE THREAD

**Issue by GabiGrin** [EclipseFdn/open-vsx.org#3231]
Hey,
I am the creator of https://github.com/flydelabs/flyde and would love to publish to open-vsx as well.
- I own the @flyde npm packages:  https://www.npmjs.com/package/@flyde/core
- Am verified on the VSCode marketplace - https://marketplace.visualstudio.com/items?itemName=flyde.flyde-vscode&ssr=false#overview

Thanks in advance!

**Comment by kineticsquid** [comment]
@GabiGrin Welcome!
