### ISSUE TITLE
Claiming namespace higoka

### ISSUE THREAD

**Issue by higoka** [EclipseFdn/open-vsx.org#324]
my extension got published to vsx: https://open-vsx.org/extension/higoka/php-cs-fixer
here is the issue created: https://github.com/higoka/php-cs-fixer/issues/9
i published the extension to the vscode marketplace: https://marketplace.visualstudio.com/items?itemName=higoka.php-cs-fixer
source code can be found on my github: https://github.com/higoka/php-cs-fixer

**Comment by brianking** [comment]
Granted, thanks for your contributions.
