### ISSUE TITLE
Claiming namespace patriceoklou

### ISSUE THREAD

**Issue by patrice012** [EclipseFdn/open-vsx.org#3241]
- Namespace: patriceoklou
- Open VSX Account Username: patrice012
- GitHub Repository : https://github.com/patrice012/html-jsx-wrapper

Reason for Claiming Namespace:
I am the developer and publisher of the "HTML JSX Wrapper" extension. The namespace "patriceoklou" represents my personal identity (first name and last name joined together) and the patrice012 is my Github username , as evident from my GitHub profile and associated projects.

I have logged into the Open VSX registry with this account.

Thank you for your consideration.

**Comment by kineticsquid** [comment]
@patrice012 Welcome!
