### ISSUE TITLE
Claiming namespace [Swagata-Roy]

### ISSUE THREAD

**Issue by Swagata-Roy** [EclipseFdn/open-vsx.org#3245]
I am the legitimate owner of the namespace "Swagata-Roy" because it is the unique identifier associated with my extensions published on the VS Code marketplace under the same name. I am the creator and maintainer of these extensions, and they are available under my ownership on GitHub.

Additionally, I have logged in to https://open-vsx.org/, and my Open VSX login name is "Swagata-Roy". This matches the namespace I am requesting, further verifying my association with it.

If further verification is needed, I can provide additional information or links to my VS Code marketplace profile and GitHub repository.

**Comment by kineticsquid** [comment]
@Swagata-Roy Thanks for your contribution!
