### ISSUE TITLE
Claiming namespace 42Crunch

### ISSUE THREAD

**Issue by DSotnikov** [EclipseFdn/open-vsx.org#330]
We are trying to cross-publish our VS Code extension (https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) here. I am the CPO at 42Crunch (https://www.linkedin.com/in/dsotnikov/). Let me know if any additional information is needed.

**Comment by ak1394** [comment]
To make verification easier this is the link to our extension repository https://github.com/42Crunch/vscode-openapi where you can see Dmitry as one of the contributors.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
