### ISSUE TITLE
Claiming namespace o-dka 

### ISSUE THREAD

**Issue by o-dka** [EclipseFdn/open-vsx.org#331]
I want to cross-publish jez9999's[ vsclassic-icons](https://marketplace.visualstudio.com/items?itemName=jez9999.vsclassic-icon-theme).\
The original author did give me [permission](https://github.com/jez9999/gooeycarboncopy/issues/11#issuecomment-763193181) and also has access to it.\
 The repository: https://github.com/o-dka/vsclassic-icon-theme .

**Comment by brianking** [comment]
Granted, thanks for your contributions.
