### ISSUE TITLE
Claiming namespace uloco

### ISSUE THREAD

**Issue by uloco** [EclipseFdn/open-vsx.org#332]
uloco is my GitHub name and also VSCode marketplace user name.
Also on other platforms this is the name developers recognize me.

I am the creator and sole maintainer of the [Bluloco Light](https://marketplace.visualstudio.com/items?itemName=uloco.theme-bluloco-light) and [Bluloco Dark](https://marketplace.visualstudio.com/items?itemName=uloco.theme-bluloco-dark).

### Links

[Website](https://uloco.dev)
[Portfolio](https://uloco.github.io)
[GitHub](https://github.com/uloco)
[Marketplace](https://marketplace.visualstudio.com/publishers/uloco)
[VSCode Bluloco Light](https://marketplace.visualstudio.com/items?itemName=uloco.theme-bluloco-light)
[VSCode Bluloco Dark](https://marketplace.visualstudio.com/items?itemName=uloco.theme-bluloco-dark)
[OpenVSX Bluloco Dark](https://open-vsx.org/extension/uloco/theme-bluloco-dark)
[OpenVSX Bluloco Light](https://open-vsx.org/extension/uloco/theme-bluloco-light)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
