### ISSUE TITLE
Claiming namespace kaptainmicila

### ISSUE THREAD

**Issue by KaptainMicila** [EclipseFdn/open-vsx.org#333]
You can have proof of me creating this extension from:
VSCode's extension, by me:
https://marketplace.visualstudio.com/items?itemName=kaptainmicila.gzdoom-zscript
and ZDoom's forum page (where the "main target" for the extension is located):
https://forum.zdoom.org/viewtopic.php?f=232&t=70445

**Comment by brianking** [comment]
@KaptainMicila The namespace for your extension is kaptainmicila. Is that the one you want to claim?

**Comment by KaptainMicila** [comment]
That is **correct**, I apologize for my ignorance.

**Comment by KaptainMicila** [comment]
> @KaptainMicila The namespace for your extension is kaptainmicila. Is that the one you want to claim?

Should I correct the title of the issue?

**Comment by brianking** [comment]
That's fine, all good now. Granted. Thanks for your contributions.
