### ISSUE TITLE
Claiming namespace piersdeseilligny

### ISSUE THREAD

**Issue by piersdeseilligny** [EclipseFdn/open-vsx.org#334]
Hi,
I'd like to claim the namespace piersdeseilligny, which corresponds to my name (which i also use on the visual studio marketplace: https://marketplace.visualstudio.com/publishers/piersdeseilligny). I wrote and maintain BetterFountain, which some of my users have [requested be submitted to the open vsx registry](https://github.com/piersdeseilligny/betterfountain/issues/109).

**Comment by brianking** [comment]
Granted, thanks for your contributions.
