### ISSUE TITLE
Claiming namespace cvergne

### ISSUE THREAD

**Issue by cvergne** [EclipseFdn/open-vsx.org#335]
Hi,

I'd like to claim the namespace `cvergne`.
I've just published the following extension https://github.com/cvergne/vscode-php-getters-setters here https://open-vsx.org/extension/cvergne/vscode-php-getters-setters-cv (_which is also on VS Marketplace https://marketplace.visualstudio.com/items?itemName=cvergne.vscode-php-getters-setters-cv_ ) and someone requested to publish it on OVSX Registry ( https://github.com/cvergne/vscode-php-getters-setters/issues/3 )

Thanks for your help :)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
