### ISSUE TITLE
Claiming namespace pucelle

### ISSUE THREAD

**Issue by pucelle** [EclipseFdn/open-vsx.org#336]
Hi, there, I want to claim my namespace "pucelle", according to issue: https://github.com/pucelle/vscode-css-navigation/issues/49

**Comment by pucelle** [comment]
Otherwise, do you mind if I ask a question?

Visual studio market seems to be a great and reasonable place for vscode plugins, so, why started a new platform? What's the main reason, and why plugin authors like me should publish plugins for twice.

**Comment by brianking** [comment]
Namespace ownership granted, thanks for your contributions.

For more information on Open VSX and why it exists, see:
https://open-vsx.org/about

... and these blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

**Comment by spoenemann** [comment]
@pucelle in short: Microsoft restricts access to the Visual Studio Marketplace to their own software, so other tools supporting VS Code extensions (like [Gitpod](https://www.gitpod.io/)) are not allowed to use that.

**Comment by pucelle** [comment]
Ok, I learned, Thanks for your explanation, @spoenemann
