### ISSUE TITLE
Update Banner Text

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/open-vsx.org#337]
The banner text on the site needs to be updated.

Up to compliance cut-off on Jan 29:
The final date for existing publishers to sign our publishing agreement and your extension to have a license is January 29. Please read this blog post (link: https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry) that explains the changes, and read the Wiki page (link: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) to find out more.

After compliance cut-off on Jan 29:
If you are a publisher and your extension is no longer available because of recent requirements, you can reactivate it by signing the publihser agreemant and/or adding a license to your extension. Find out more (link: https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry).

Wait for review from @croundy before making the changes. 

Please consider fixing issue #221 with this change.

**Comment by croundy** [comment]
See below with a few minor edits. Good to go!

Up to compliance cut-off on Jan 29:
The final date for existing publishers to sign our publishing agreement and for your extension to have a license is January 29, 2021. Please read this blog post (link: https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry) that explains the changes, and read the Wiki page (link: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) to find out more.

After compliance cut-off on Jan 29:
If you are a publisher and your extension is no longer available, you can reactivate it by signing the publisher agreement and/or adding a license to your extension. Find out more (link: https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry).

**Comment by spoenemann** [comment]
The pre-compliance-cut-off text is online.

**Comment by brianking** [comment]
Thanks for adding the post-cut-off message. Adding screenshot here just as a record.

We will leave it with no takedown date for now, and review on a weekly basis if it should stay up.

<img width="896" alt="Screenshot 2021-02-01 at 14 28 23" src="https://user-images.githubusercontent.com/114116/106471910-09609d80-649a-11eb-90d7-5d08845eaae6.png">

**Comment by spoenemann** [comment]
FYI: https://github.com/streetsidesoftware/vscode-spell-checker/issues/660#issuecomment-808727683

**Comment by brianking** [comment]
I think we can remove the banner soon, and replace it with some text somewhere in the documentation.
