### ISSUE TITLE
Claiming namespace codelingo

### ISSUE THREAD

**Issue by mrcrowl** [EclipseFdn/open-vsx.org#339]
I am the product engineer at CodeLingo: https://www.linkedin.com/in/ben-crowl-08203a4/

I'd like to claim `codelingo` as our publisher name on open-vsx. We use the same publisher ID on the [VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=codelingo.codelingo).

**Comment by brianking** [comment]
Granted, thanks for your contributions.
