### ISSUE TITLE
Claiming namespace leanprover

### ISSUE THREAD

**Issue by gebner** [EclipseFdn/open-vsx.org#340]
I am one of the developers of the extension with the id `leanprover.lean4` ([github repo](https://github.com/leanprover-community/vscode-lean4), [Open VSX](https://open-vsx.org/extension/leanprover/lean4), [Microsoft marketplace](https://marketplace.visualstudio.com/items?itemName=leanprover.lean4)) and I would like to claim the namespace `leanprover`.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
