### ISSUE TITLE
Claiming namespace [REditorSupport]

### ISSUE THREAD

**Issue by renkun-ken** [EclipseFdn/open-vsx.org#341]
Hi, I'm a member of [REditorSupport](https://github.com/REditorSupport) which is the organization that maintains packages for R editors. We publish VSCode extensions to [VSCode Marketplace](https://marketplace.visualstudio.com/) and I'm one of the owners of the publisher there.

It would be nice if I could claim the namespace `REditorSupport` so that I could manage the maintainers here. Thanks!

Related: https://github.com/REditorSupport/vscode-r-lsp/issues/55

**Comment by brianking** [comment]
Granted, thanks for your contributions.
