### ISSUE TITLE
Claiming namespace adhamu

### ISSUE THREAD

**Issue by adhamu** [EclipseFdn/open-vsx.org#342]
Hi, this is my GitHub username and my actual first initial + surname

**Comment by adhamu** [comment]
I also have the same publisher namespace as I do on the Visual Studio Marketplace
https://marketplace.visualstudio.com/search?term=adhamu&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by brianking** [comment]
Granted. Looking forward to your upcoming contributions.
