### ISSUE TITLE
Improve Project Documentation

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/open-vsx.org#343]
Hey, we're looking at setting some time aside to help with a branding update of this project, but there doesn't seem to be any documentation on how we would go about updating the branding or styling on any part of the site. While there is some documentation pointing to the site settings, it seems like there would be significant effort involved in updating each component from MaterialUI or adapting Eclipse branding to work within the framework

**Comment by spoenemann** [comment]
Material UI uses the concept of theming for styling:
https://material-ui.com/customization/theming/

**Comment by chrisguindon** [comment]
I am going to try to add a bit more context to this issue. 

We are starting to work on the [ecdtools.eclipse.org website refresh](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/91). 

With this project, our designer  created a mockup for open-vsx.org:
https://projects.invisionapp.com/share/VY101BTNM849#/screens/443328269

With that said, we are looking for some documentation on we should get started on this. 

We need to know the best practices for running this application in our local environment so that we can easily test our changes while we work on this project.

We started looking into this but I instructed @autumnfound to hold off once we started to hit some roadblocks:
https://github.com/eclipse/openvsx/issues/231

**Comment by spoenemann** [comment]
This repository has a `website` directory that includes `watch:tsc` and `watch:dev` scripts for running the TypeScript compiler and Webpack in watch mode and `start:dev` to start a server so you can see how the frontend looks like with a mocked backend.

As mentioned before, you can adapt the Material UI theme and change colors, fonts, spacings etc. For more detailed changes you'd probably have to change the [webui code in the main repository](https://github.com/eclipse/openvsx/tree/master/webui). However, I doubt you will be able to make the website look as you sketched in the mockup with reasonable effort. Material UI has a predefined look that can only be modified to a certain degree. I think you'll need to adapt your mockup to the Material UI concepts. Or you reimplement the frontend from scratch :-)

**Comment by spoenemann** [comment]
One option if you want more fine-grained control is to add properties to the [PageSettings](https://github.com/eclipse/openvsx/blob/master/webui/src/page-settings.ts) interface and use them in the openvsx-webui main code. Then you can customize those new properties in this repository.

**Comment by brianking** [comment]
@autumnfound @chrisguindon Do you have enough to go on, based on Miro's comments above?

**Comment by chrisguindon** [comment]
> @autumnfound @chrisguindon Do you have enough to go on, based on Miro's comments above?

Yes and no. Miro information was quite useful and I was indeed able to start a local server without any custom configuration.

![Screenshot from 2021-02-10 08-20-12](https://user-images.githubusercontent.com/893942/107515333-e0669980-6b78-11eb-8bc5-c23854e04e92.png)

I might have missed a step but as you can see in my screenshot, my local server doesn't include any mock extensions.

Also, Miro did point out some concerns regarding the current design as it might not be possible to implement it as-is. My team would need to look at this closer to see what we will and will not be able to do.

**Comment by spoenemann** [comment]
> local server doesn't include any mock extensions

Right, that could be improved. But you can navigate directly to any extension by going to a subpath of the form `/extension/foo/bar`.

**Comment by brianking** [comment]
> I might have missed a step but as you can see in my screenshot, my local server doesn't include any mock extensions.

Could our test instance be used in this developement context? /cc @mbarbero

**Comment by chrisguindon** [comment]
@brianking Probably but not the most efficient way to develop. 

We would need to push code and wait for the change to be deployed on staging to see the results. It's a time-consuming process.

**Comment by spoenemann** [comment]
You can enhance the mock data if you like:
https://github.com/EclipseFdn/open-vsx.org/blob/master/website/dev/mock-service.ts

**Comment by chrisguindon** [comment]
If we want more people to get involved, we need to better document how people can get involved. I updated the subject of this issue to reflect that.

I would like to propose that we start with something similar to what I did with https://github.com/EclipseFdn/ecdtools.eclipse.org. 

1. Getting started: 
https://github.com/EclipseFdn/ecdtools.eclipse.org#getting-started

The readme should include instructions on how we expect developers to run the application on their machine.

2. How to contribute
https://github.com/EclipseFdn/ecdtools.eclipse.org#contributing

This section is also important for this project as we need to tell contributors which branch we expect them to use to submit code.  I think most people would expect to submit a pr to the default "master" branch, however, it seems that the main dev branch for this project is "production". 

This is a bit strange to me but I don't have a problem with this if it's documented.

**Comment by chrisguindon** [comment]
Thanks @spoenemann 

I will create an issue regarding the mock data since that issue needs to be solved before we can consider working on the re-design of open-vsx.org.

I don't see how we can work on this without any extensions! 

Please let us know if there is a better way for us to work on this project.

**Comment by spoenemann** [comment]
I have been developing both [eclipse/openvsx](https://github.com/eclipse/openvsx) and this repository with Gitpod. The config files for that are at the root of each repo. My workflow for this repo was to use the mock service to quickly test UI adaptations, and push to master for a staging deployment, which is like a preview of how it would like in production.

**Comment by chrisguindon** [comment]
Re-opening - I think my first commit is a good start but there is still lots to do here but at least now we have enough for newcomers to get started!

**Comment by ericpoirier** [comment]
> Re-opening - I think my first commit is a good start but there is still lots to do here but at least now we have enough for newcomers to get started with this project.

What would be missing here in order to close this issue?

**Comment by chrisguindon** [comment]
I wanted to see more documentation but let's close this for now. I think I am the only one requesting this.

**Comment by brianking** [comment]
More documentation is always more desirable.

What might help @chrisguindon is to break it up into chunks of what you would like to see, and file separate issues for each.
