### ISSUE TITLE
Claiming namespace murbani

### ISSUE THREAD

**Issue by marcellourbani** [EclipseFdn/open-vsx.org#348]
I'm the author of a couple of vscode extensions, particularly [ABAP remote fs](https://marketplace.visualstudio.com/items?itemName=murbani.vscode-abap-remote-fs) and would like to publish it on openvsx
Didn't test it on theia yet

Best regards
Marcello Urbani

**Comment by brianking** [comment]
Granted, looking forward to your upcoming contributions.

**Comment by marcellourbani** [comment]
Thank you.
Sadly looks like it will need a lot of effort to work in theia right now, not sure when I'll find the time.
```json
  "missingSymbols": [
    "\"vscode\".CustomTextEditorProvider",
    "\"vscode\".ExtensionContext.extensionUri",
    "\"vscode\".QuickPick.dispose",
    "\"vscode\".QuickPick.hide",
    "\"vscode\".QuickPick.ignoreFocusOut",
    "\"vscode\".QuickPick.onDidHide",
    "\"vscode\".QuickPick.show",
    "\"vscode\".Uri.joinPath",
    "\"vscode\".window.registerCustomEditorProvider"
  ],
  "missingCommands": [
    "editor.css",
    "revealInExplorer",
    "workbench.files.action.refreshFilesExplorer",
    "workbench.files.action.showActiveFileInExplorer"
  ]
```
Regards
Marcello
