### ISSUE TITLE
Claiming namespace pdesaulniers

### ISSUE THREAD

**Issue by pdesaulniers** [EclipseFdn/open-vsx.org#349]
Hello! I would like to claim the `pdesaulniers` namespace, which corresponds to my GitHub username.

I am the maintainer of the [Teal extension](https://github.com/teal-language/vscode-teal), which is currently available in the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=pdesaulniers.vscode-teal) under the `pdesaulniers` publisher.

Addresses https://github.com/teal-language/vscode-teal/issues/22.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
