### ISSUE TITLE
Claiming namespace Divlo

### ISSUE THREAD

**Issue by Divlo** [EclipseFdn/open-vsx.org#352]
Hello! :wave: 
I maintain the `vscode-styled-jsx` (https://github.com/Divlo/vscode-styled-jsx) extension so we can support `styled-jsx` inside `VSCode`, initially, I was only publishing under *VSCode Marketplace* but I find out that users with `Theia` or `VSCodium` IDE it would be easier to have the extension on *open-vsx*,  I implemented continous-deployment recently and publising my extensions under my name workspace : "Divlo".

Here are the links of the 2 extensions : 
- https://open-vsx.org/extension/Divlo/vscode-styled-jsx-syntax
- https://open-vsx.org/extension/Divlo/vscode-styled-jsx-languageserver

I would like to not have this warning :
![2021-02-03_10-25](https://user-images.githubusercontent.com/25207499/106725962-30d67800-660a-11eb-8959-ea934d63bebf.png)

Thanks!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
