### ISSUE TITLE
Claiming namespace LuqueDaniel

### ISSUE THREAD

**Issue by LuqueDaniel** [EclipseFdn/open-vsx.org#353]
Hello. I maintain the [languague-renpy](https://github.com/LuqueDaniel/vscode-language-renpy). Originally published in VSCode Marketplace: https://marketplace.visualstudio.com/items?itemName=LuqueDaniel.languague-renpy#overview

And I want to publish it on open-vsx.org.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
