### ISSUE TITLE
Claiming namespace kasik96

### ISSUE THREAD

**Issue by kasik96** [EclipseFdn/open-vsx.org#354]
Hi, on my GitHub profile you can find original source for my Extension "Nette Latte + Neon"
https://github.com/kasik96/VS-Latte

On VSCode is published here: https://marketplace.visualstudio.com/items?itemName=Kasik96.latte
Already published on Open VSX here: https://open-vsx.org/extension/kasik96/latte

I have everywhere same username Kasik96, you can find link in VSCode extension detail page to my GitHub.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
