### ISSUE TITLE
Claiming namespace activitywatch

### ISSUE THREAD

**Issue by ErikBjare** [EclipseFdn/open-vsx.org#355]
I'm the founder and lead dev/maintainer of ActivityWatch: https://github.com/ActivityWatch

Requesting the namespace since we've had our users request we publish our extension aw-watcher-vscode to your registry: https://github.com/ActivityWatch/aw-watcher-vscode/issues/16

**Comment by brianking** [comment]
Granted, thanks for your contributions.
