### ISSUE TITLE
Claiming namespace emulicious

### ISSUE THREAD

**Issue by Calindro** [EclipseFdn/open-vsx.org#356]
I am working on Emulicious for almost 10 years now. Recently, I've created and published a VS Code extension (https://marketplace.visualstudio.com/items?itemName=emulicious.emulicious-debugger) for it.
I'm claiming ownership of the namespace so that I can also publish the extension on open-vsx.org as a verified publisher.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
