### ISSUE TITLE
Claiming namespace sainnhe

### ISSUE THREAD

**Issue by sainnhe** [EclipseFdn/open-vsx.org#357]
Hello, I want to claim the ownership for "sainnhe" as this is my commonly used user name for github and vscode marketplace.

I'm the author of [gruvbox-material](https://github.com/sainnhe/gruvbox-material-vscode) which has been published in both [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=sainnhe.gruvbox-material) and [open-vsx registry](https://open-vsx.org/extension/sainnhe/gruvbox-material), and I hope to get this extension verified in open-vsx registry.

Thanks!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
