### ISSUE TITLE
Please unpublish redhat/vscode-commons 0.0.1

### ISSUE THREAD

**Issue by fbricon** [EclipseFdn/open-vsx.org#359]
Hi, 
we mistakenly published redhat.vscode-commons 0.0.1 without the `preview` flag. Subsequent releases use that flag but 0.0.1 appears as stable. As a consequence, it's installed by default in vscodium instead of the actual latest.

Can you please help us unpublishing redhat/vscode-commons 0.0.1?

**Comment by brianking** [comment]
v. 0.0.1 has been removed.
