### ISSUE TITLE
Claiming namespace [krishnaVamsi]

### ISSUE THREAD

**Issue by krishnagogada** [EclipseFdn/open-vsx.org#367]
I am new to creating plugins I am trying to learn how to create and publish a plug in using Open VSX

**Comment by spoenemann** [comment]
Hi @krishnagogada! Documentation on creating extensions is available here:

https://code.visualstudio.com/api

Publishing your extension to Open VSX is documented here:

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by brianking** [comment]
Granted, thanks for your contributions.

Please add user value to a) trying not to upload test extensions and b) adding Readme files to your extensions.
