### ISSUE TITLE
Claiming namespace kavod-io

### ISSUE THREAD

**Issue by rossknudsen** [EclipseFdn/open-vsx.org#368]
I maintain the GitHub organisation kavod.io.  You can see the single repo under that org is the source for the extension (kavod.io:vscode-jest-test-adapter) published under this namespace.  You should be able to see that I'm a member of that organisation.

**Comment by brianking** [comment]
Granted, thanks for your contributions. 

Note I did it for kavod-io and not kavod.io. If this is incorrect, please reopen.
