### ISSUE TITLE
Claiming namespace Kelvin

### ISSUE THREAD

**Issue by SchoofsKelvin** [EclipseFdn/open-vsx.org#369]
Published Open-VSX extension: [Kelvin.vscode-sshfs](https://open-vsx.org/extension/Kelvin/vscode-sshfs) ([VS Marketplace](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs))
My publisher account [Kelvin](https://marketplace.visualstudio.com/publishers/Kelvin) has a link to my GitHub profile.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
