### ISSUE TITLE
Claiming namespace madeindjs

### ISSUE THREAD

**Issue by madeindjs** [EclipseFdn/open-vsx.org#370]
Published Open-VSX extension: [madeindjs.notable](https://open-vsx.org/extension/madeindjs/notable) ( [marketplace](https://marketplace.visualstudio.com/items?itemName=madeindjs.notable) - [github](https://github.com/madeindjs/vscode-notable) )
My publisher account madeindjs has a link to my GitHub profile.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
