### ISSUE TITLE
Claiming namespace arrterian

### ISSUE THREAD

**Issue by arrterian** [EclipseFdn/open-vsx.org#371]
Hi. I'm author and owner (Nix Environment Selector)[https://open-vsx.org/extension/arrterian/nix-env-selector] extension.
I want to confirm my ownership for the workspace. My account here on github has the same name. And I use same namespese on VSCode marketplace.
https://marketplace.visualstudio.com/items?itemName=arrterian.nix-env-selector

**Comment by brianking** [comment]
Granted, thanks for your contributions.
