### ISSUE TITLE
Claiming namespace [sumneko]

### ISSUE THREAD

**Issue by sumneko** [EclipseFdn/open-vsx.org#377]
Publish https://marketplace.visualstudio.com/items?itemName=sumneko.lua to https://open-vsx.org/

**Comment by sumneko** [comment]
I found namespace `sumneko` has been created by other people.
Should I create a namespace with another name?

**Comment by brianking** [comment]
As the extension published under this namespace originally was yours, I have granted you namespace ownership. You can now publish new versions to open-vsx.org. Thanks for your contributions.
