### ISSUE TITLE
Claiming namespace [jerrygoyal]

### ISSUE THREAD

**Issue by GorvGoyl** [EclipseFdn/open-vsx.org#381]
I own `Shortcut menu bar` VSCode extension. Github repo: https://github.com/GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension
VSCode Marketplace link: https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar

I recently published this on open-vsx store. Please mark the status as verified. Link: https://open-vsx.org/extension/jerrygoyal/shortcut-menu-bar

**Comment by brianking** [comment]
Granted, thanks for your contributions.
