### ISSUE TITLE
Claiming namespace standard

### ISSUE THREAD

**Issue by feross** [EclipseFdn/open-vsx.org#383]
I would like to claim the namespace `standard`. I'm the creator and maintainer of the Standard organization.

Links:

GitHub org: https://github.com/standard
Main GitHub repo: https://github.com/standard/standard
npm package: https://www.npmjs.com/package/standard
Website: https://standardjs.com

Thanks!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
