### ISSUE TITLE
Claiming namespace MariusvanWijk-JoppeKoers

### ISSUE THREAD

**Issue by Mariusmivw** [EclipseFdn/open-vsx.org#384]
I and my friend, wrote (updated) an extension for our school, and as well as publishing it on the official market place we wanted to publish it on this open source marketplace

Git repo: https://github.com/Mariusmivw/vscode-codam-norminette-3
Extension on the official marketplace: https://marketplace.visualstudio.com/items?itemName=MariusvanWijk-JoppeKoers.codam-norminette-3
On VSX: https://open-vsx.org/extension/MariusvanWijk-JoppeKoers/codam-norminette-3

**Comment by brianking** [comment]
Granted, thanks for your contributions.
