### ISSUE TITLE
Claiming namespace RDebugger

### ISSUE THREAD

**Issue by ManuelHentschel** [EclipseFdn/open-vsx.org#385]
ovsx: https://open-vsx.org/extension/RDebugger/r-debugger
marketplace: https://marketplace.visualstudio.com/items?itemName=RDebugger.r-debugger
github: https://github.com/ManuelHentschel/VSCode-R-Debugger

The extension's package.json contains a link to my GitHub profile.
Thanks!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
