### ISSUE TITLE
Claiming namespace caponetto

### ISSUE THREAD

**Issue by caponetto** [EclipseFdn/open-vsx.org#386]
I own Diff Viewer VS Code extension. 
Github: https://github.com/caponetto/vscode-diff-viewer
VS Code Marketplace: https://marketplace.visualstudio.com/items?itemName=caponetto.vscode-diff-viewer

I just published this on open-vsx store. Please mark the status as verified.
https://open-vsx.org/extension/caponetto/vscode-diff-viewer

**Comment by brianking** [comment]
Granted, thanks for your contributions.
