### ISSUE TITLE
open-vsx is banned for irannian users?

### ISSUE THREAD

**Issue by Meshikhah** [EclipseFdn/open-vsx.org#39]
it gives this error:
**Your client does not have permission to get URL / from this server.**

**Comment by spoenemann** [comment]
We currently use Google Cloud Platform to host the website. We haven't set any restrictions, but maybe Google has some built-in restrictions.

The website will soon be transferred to the Eclipse Foundation, and in that process it may be moved to another hosting solution.

**Comment by mhf-ir** [comment]
Thanks we wait for move to Eclipse Foundation get rid of google restriction.

**Comment by HKalbasi** [comment]
Fixed in https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management

**Comment by spoenemann** [comment]
So is the new Azure based infrastructure less restricted?

**Comment by HKalbasi** [comment]
I have no problem

**Comment by HKalbasi** [comment]
Now I find download extensions still does not work. but website works and Vscodium shows list of extensions.

**Comment by brianking** [comment]
@HKalbasi Is this still an issue? Have you tried with other software using Open VSX, e.g. Gitpod. What about VS Code and the Microsoft marketplace?

**Comment by HKalbasi** [comment]
It is now working! I tried vscodium and code-server (Gitpod itself uses google servers and it is banned so It isn't applicable) and I don't know about Microsoft's one. I had not noticed until now that you mentioned me, I was installing extensions with drag and drop as usual :)

**Comment by brianking** [comment]
Ok closing, thanks for the followup.
