### ISSUE TITLE
Claiming namespace openstax

### ISSUE THREAD

**Issue by staxly** [EclipseFdn/open-vsx.org#390]
I'm a devops engineer at OpenStax (openstax.org). I'd like to claim ownership for the namespace openstax. Our developers are working on an editor for our textbook content.

**Comment by brianking** [comment]
@staxly There is no information on your GH account, so unless you tell me otherwise that it is a bot or service account which we don't grant namespace ownership too. Feel free to nominate and individual.

**Comment by staxly** [comment]
I apologize that I had not filled out the profile information. I have done that now.

**Comment by brianking** [comment]
Granted. I am looking forward to seeing the Openstax contributions.
