### ISSUE TITLE
Claiming namespace [puppet]

### ISSUE THREAD

**Issue by jpogran** [EclipseFdn/open-vsx.org#395]
This is a request to claim the [puppet](https://open-vsx.org/extension/puppet/puppet-vscode) namespace.

I am the maintainer for the official [Puppet Extension](https://pup.pt/vscode) in the VS Code Gallery, and created an account in open-vsx and accepted the Eclispe publisher agreement

**Comment by brianking** [comment]
Granted, thanks for your contributions.
