### ISSUE TITLE
Claiming namespace [tboox]

### ISSUE THREAD

**Issue by waruqi** [EclipseFdn/open-vsx.org#397]
I am author of xmake-vscode. I want to upload [xmake-vscode](https://github.com/xmake-io/xmake-vscode) extensions to open-vsx. 

So I created a namespace (`tboox`) 

https://github.com/xmake-io/xmake-vscode/blob/0abf489e9aa538b25b296e6b60b357f006cb1ef7/package.json#L6

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
