### ISSUE TITLE
Claiming namespace activecove

### ISSUE THREAD

**Issue by sourishkrout** [EclipseFdn/open-vsx.org#399]
Hello there,

I'd like to claim ownership for the `activecove` namespace to myself @sourishkrout & @admc both of who are founders and owners of the https://github.com/activecove organization.

Please check out https://activecove.com/ for more info. We also own the `activecove` namespace in the VS Code Marketplace: https://marketplace.visualstudio.com/items?itemName=activecove.marquee.

Thank you!

**Comment by brianking** [comment]
I've added you @sourishkrout and ask soon as @admc logs into Open VSX you can add them to the namespace. Thanks for your contributions.
