### ISSUE TITLE
Claiming namespace pavlitsky

### ISSUE THREAD

**Issue by pavlitsky** [EclipseFdn/open-vsx.org#400]
I'd like to claim ownership for the `pavlitsky` namespace.
I'm the creator of [YARD Documenter](https://marketplace.visualstudio.com/items?itemName=pavlitsky.yard) VSCode extension and published it to Open VSX here [pavlitsky/yard](https://open-vsx.org/extension/pavlitsky/yard) with the same namespace and my GitHub account.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
