### ISSUE TITLE
Claiming namespace jeppeandersen

### ISSUE THREAD

**Issue by jlandersen** [EclipseFdn/open-vsx.org#402]
Hi,

I'd like to claim the namespace `jeppeandersen`. Primarily for the VS Code Kafka extension which you can see here:
https://github.com/jlandersen/vscode-kafka

This is currently also published to the Visual Studio marketplace on:
https://marketplace.visualstudio.com/items?itemName=jeppeandersen.vscode-kafka

Thank you in advance!

**Comment by brianking** [comment]
Granted, looking forward to seeing your extension listed.
