### ISSUE TITLE
Claiming namespace ozgurkadir

### ISSUE THREAD

**Issue by ozgurkadir** [EclipseFdn/open-vsx.org#408]
Hi,

I'd like to claim namespace "ozgurkadir" which is my github username. 

At first, I'll use this namespace to publish my extension below.

https://github.com/ozgurkadir/vscode-cds-csv-generator

https://marketplace.visualstudio.com/items?itemName=ozgurkadir.cds-csv-generator

Thanks.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
