### ISSUE TITLE
Claiming namespace Moosecasa

### ISSUE THREAD

**Issue by james2432** [EclipseFdn/open-vsx.org#409]
I am currently publishing my software under the Moosecasa organization and would like to become verified
![image](https://user-images.githubusercontent.com/498547/110568416-db324580-814a-11eb-8dea-c307a1be803e.png)
https://marketplace.visualstudio.com/items?itemName=Moosecasa.vscode-acutest-test-adapter

**Comment by brianking** [comment]
Granted, thanks for your contributions.
