### ISSUE TITLE
Claiming namespace Marko-JS

### ISSUE THREAD

**Issue by DylanPiercey** [EclipseFdn/open-vsx.org#410]
I'd like to claim the `Marko-JS` namespace as I have the same namespace on the vscode marketplace (https://marketplace.visualstudio.com/items?itemName=Marko-JS.marko-vscode).

The content of the extension under this namespace is hosted here https://github.com/marko-js/language-server where I also have access.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
