### ISSUE TITLE
Claiming namespace [appliedengdesign]

### ISSUE THREAD

**Issue by mikecentola** [EclipseFdn/open-vsx.org#411]
Applied Eng & Design is my brand/business for open-source development, engineering, etc. I developed the G-Code extension for VSCode and I'm porting over to openvsix.

This is my extension [vscode-gcode-syntax](https://marketplace.visualstudio.com/items?itemName=appliedengdesign.vscode-gcode-syntax) on marketplace and on [github](https://github.com/appliedengdesign/vscode-gcode-syntax)

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
