### ISSUE TITLE
Claiming namespace AdaCore

### ISSUE THREAD

**Issue by setton** [EclipseFdn/open-vsx.org#412]
Hello,

I'd like to claim the namespace AdaCore.

I'm representing [AdaCore](https://adacore.com) and we are using this namespace to publish the `ada` extension which provides support for the Ada and SPARK languages.

Don't hesitate to reach out to me at setton at adacore dot com if you need further credentials.

Nicolas

**Comment by brianking** [comment]
Granted, thanks for your contributions.
