### ISSUE TITLE
Claiming namespace CodeStream

### ISSUE THREAD

**Issue by codestreamdeploy** [EclipseFdn/open-vsx.org#414]
We'd like to claim the CodeStream namespace. We're currently publishing CodeStream under the TeamCodeStream github organization and would like to become verified.

https://github.com/TeamCodeStream/codestream
https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream
![image](https://user-images.githubusercontent.com/43763656/110984559-50636d80-8339-11eb-9203-9d1a68dfaf76.png)

**Comment by brianking** [comment]
We don't grant namespace ownership to service or bot accounts, so feel free to nominate an individual for that and we will add them.

**Comment by codestreamdeploy** [comment]
ok, let's nominate @bcanzanella https://github.com/bcanzanella

![image](https://user-images.githubusercontent.com/43763656/111482424-4612ec00-870a-11eb-8146-9c15347b75bd.png)

**Comment by brianking** [comment]
@bcanzanella is now the namespace owner.
