### ISSUE TITLE
Claiming namespace timonwong

### ISSUE THREAD

**Issue by timonwong** [EclipseFdn/open-vsx.org#415]
VSCode Marketplace: https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck

**Comment by timonwong** [comment]
Closed, as we decide to create an "org" publisher instead

**Comment by timonwong** [comment]
Previously this request was closed (because we are inclined to create an org account instead, however, it's hard). So we decide to still use the "timonwong" as namespace and reopen this ticket again

**Comment by brianking** [comment]
Granted, thanks for your contributions.

You may need to file an issue at https://github.com/open-vsx/publish-extensions/issues to remove this extension from the open-vsx publish script.

**Comment by felipecrs** [comment]
Refs https://github.com/open-vsx/publish-extensions/pull/443
