### ISSUE TITLE
Claiming namespace sasjs

### ISSUE THREAD

**Issue by allanbowe** [EclipseFdn/open-vsx.org#416]
I am the founder of the sasjs project (https://sasjs.io) and I just created the sasjs namespace a few minutes ago

I would like to claim ownership on this basis.  You can see a link to this project on my linkedin profile:  https://www.linkedin.com/in/allanbowe/

Also, right here on github:

https://github.com/sasjs/

Our extension is here:  https://open-vsx.org/extension/sasjs/sasjs-for-vscode

**Comment by brianking** [comment]
Granted, thanks for your contributions.
