### ISSUE TITLE
Claiming namespace devberto

### ISSUE THREAD

**Issue by bertolinimarco** [EclipseFdn/open-vsx.org#418]
I've 2 namespaces: `bertolinimarco` and `devberto`. 
With `devberto` i've published an extension, there is a possibility to merge both namespaces or delete `bertolinimarco` at least? 

Thank you

**Comment by brianking** [comment]
@bertolinimarco You are now the namespace owner for `devberto`.

I have removed you from the `bertolinimarco` namespace, and the application will at some stage detect it as orphaned and remove it.
