### ISSUE TITLE
Claiming namespace mtxr

### ISSUE THREAD

**Issue by mtxr** [EclipseFdn/open-vsx.org#422]
Hi,

My users are currentlu requesting to publish my extensions on open-vsx.

https://github.com/mtxr/vscode-sqltools/issues/697

So if possible I'ld like to publish all my current extensions from VSCode marketplace here as well, my publisher name is `mtxr`, that would be my Namespace as well

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
