### ISSUE TITLE
Claiming namespace `unifiedjs`

### ISSUE THREAD

**Issue by wooorm** [EclipseFdn/open-vsx.org#423]
Hi! I’m a [core team member](https://github.com/unifiedjs/collective#core-team) of the [unified collective](https://github.com/unifiedjs/collective#teams) (several GH/npm orgs with 100s of packages, and a couple of extensions).

Users have [requested](https://github.com/remarkjs/vscode-remark/issues/31#issue-716907411) to publish here as well.

I’ve logged in!

Thanks

**Comment by asbjornu** [comment]
I created the namespace `unifiedjs` with my Eclipse account, but did so before realizing it had to be claimed. I, therefore, condone @wooorm's claim to the namespace.

**Comment by brianking** [comment]
@wooorm has been added as the namespace owner.

Thanks and looking forward to your contributions.
