### ISSUE TITLE
Claiming namespace SecHub

### ISSUE THREAD

**Issue by company-jcup** [EclipseFdn/open-vsx.org#424]
I am working for Daimler TSS GmbH and I am maintainer of https://github.com/Daimler/sechub OSS project.

For SecHub I want to claim the namespace "SecHub" because we want to publish our SecHub plugin for VSCode/VSCodium/Eclipse Theia on the open VSX marketplace.

Best wishes
Albert

**Comment by brianking** [comment]
Hi @company-jcup , I am not seeing you listed in the project as a contributor, nor at https://github.com/orgs/Daimler/people. Please provide more context and I'll be happy to add you.

**Comment by de-jcup** [comment]
@brianking - This is my new service account which is not linked with Daimler group at the moment. Sorry. I will request my colleagues to add this account to daimler group as well. When this has been done I will inform you.

**Comment by brianking** [comment]
For the same reason as mentioned in https://github.com/EclipseFdn/open-vsx.org/issues/425#issuecomment-806577184, @company-jcup is now the namespace owner of SecHub.

**Comment by company-jcup** [comment]
Thank you very much!
