### ISSUE TITLE
Claiming namespace Daimler

### ISSUE THREAD

**Issue by company-jcup** [EclipseFdn/open-vsx.org#425]
I am working for Daimler TSS GmbH and I am maintainer of https://github.com/Daimler/sechub OSS project.

For SecHub I want to claim the namespace "Daimler" because we want to publish our SecHub plugin for VSCode/VSCodium/Eclipse Theia on the open VSX marketplace.

Remark: this is related to https://github.com/EclipseFdn/open-vsx.org/issues/424

Best wishes
Albert

**Comment by brianking** [comment]
@company-jcup Do you want this AND the SecHub namespace, or instead of?

**Comment by de-jcup** [comment]
@brianking - I will clarify this (in combination with adding the service-account to daimler group)

**Comment by brianking** [comment]
Ah, so @company-jcup is a service account? If so, I can add you @de-jcup as the namespace owner as service accounts are not allowed.

**Comment by de-jcup** [comment]
Hm.. I have a little problem with mixing personal access parts from GitHub and eclipse with company related.

Let me explain:

1. Two different eclipse accounts
- Private account - `atregnaghi`  
I have my private eclipse account https://marketplace.eclipse.org/user/atregnaghi/listings
which is my personal one - and not related with my company.
By this account I am managing 10 of my private OSS Eclipse plugins at Eclipse marketplace.
- Company account - `adaimlertssgmbh`  
For representing my company "Daimler TSS gmbH" I created
https://marketplace.eclipse.org/user/adaimlertssgmbh/listings - so it's clear I signed eclipse related license agreements etc. in name of my company. By this account the Eclipse SecHub plugin is published at Eclipse marketplace as well.

2. Contributions at GitHub for SecHub
- `de-jcup`  
I am member of Daimler GitHub Org with my private account `de-jcup` and do all my contributions with this account (private + Daimler FOSS parts).

3. Eclipse VSX marketplace
- Trying  to login inside Eclipse VSX marketplace I was in the situation that I would be forced to connect my GitHub account (normally `de-jcup`)  with my company eclipse account `adaimlertssgmbh` to accept the Open VSX agreements.
- reading https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-9 (Can I sign the Publisher Agreement on behalf of a Service Account?) it became clear to myself that if I would do this with `de-jcup` account + `adaimlertssgmbh` I would connect my private github account with my business eclipse account and I would never be able to host any private VSCode/VSCodium/Eclipse Theia plugin on Open VFX marketplace, if I would do this. (IMHO I would not be able to connect `de-jcup` with `atregnaghi` after having already the connection to my business eclipse account)

4. Used alternative account "company-jcup"
- A few weeks ago I created another GitHub account for myself: `company-jcup` (different reasons)
- After reading https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-9 I decided to use the already created, alternative github accunt `company-jcup` for Open VSX login + linked with `adaimlertssgmbh`
- I mentioned this as a "service account" before, but maybe I misunderstood the meaning of this term. Sorry when I was creating confusion here.
-  I thought using `company-jcup` account for this would be the easiest and clearest option... 

So, @brianking : How should I/we solve this problem? Any ideas ?

**Comment by brianking** [comment]
@de-jcup I am not confident that @company-jcup is not a service account, so I will grant ownership to this latter account. What confused me was the bio on the account, which reads "This is just my company service account". I suggest some rewording for that. Thanks.

**Comment by brianking** [comment]
Fixed typo in last comment: "not confident" -> "**now** confident".

@company-jcup is now the namespace owner. 

Looking forward to your contributions.

**Comment by company-jcup** [comment]
I have now changed the bio of my "company account" - as you suggested.  I Hope it is now easier to understand/more clear.

Thank you very much!
