### ISSUE TITLE
Claiming namespace tamasfe

### ISSUE THREAD

**Issue by tamasfe** [EclipseFdn/open-vsx.org#427]
The [Even Better TOML](https://open-vsx.org/extension/tamasfe/even-better-toml) extension was published without my knowledge by @KokaKiwi.

I believe she had good intentions, and in that case I should thank her. From now on however I would like to publish automatic releases from the [repository](https://github.com/tamasfe/taplo) for more consistent updates and security reasons.

**Comment by KokaKiwi** [comment]
Woops i just wanted the extension to be available to people but maybe i also should've ping'd on the main repo, sorry x_x

**Comment by tamasfe** [comment]
> Woops i just wanted the extension to be available to people but maybe i also should've ping'd on the main repo, sorry x_x

No problem, I appreciate it a lot, thank you!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
