### ISSUE TITLE
Claiming namespace mblode

### ISSUE THREAD

**Issue by mblode** [EclipseFdn/open-vsx.org#428]
I have previously published 3 extensions over a year ago on open-vsx.org:

1. https://open-vsx.org/extension/mblode/twig-language
2. https://open-vsx.org/extension/mblode/twig-language-2
3. https://open-vsx.org/extension/mblode/pretty-formatter

I want to publish another extension but I no longer have access to the namespace "mblode":

- https://github.com/mblode/vscode-zotero

Thanks,
Matt

**Comment by brianking** [comment]
Granted, thanks for your contributions.
