### ISSUE TITLE
OpenVSX registry search extreme slow for VSCodium, does not work at all with Eclipse Theia Cloud

### ISSUE THREAD

**Issue by de-jcup** [EclipseFdn/open-vsx.org#430]
I just tried to install some extensions (not only my own) from Open VSX:
- I tried with VSCodium 1.54.3
- I tried with VSCodium 1.51.0
- Also tried  with Eclipse Theia Cloud: https://gitpod.io/#https://github.com/eclipse-theia/theia

## VSCodium
With both VSCodium variants at first I got (after a while):
![image](https://user-images.githubusercontent.com/11644753/112987185-b84feb80-9162-11eb-834c-0c8874d80222.png)

Then keeping it as is after some minutes (maybe 5) following appears:
![image](https://user-images.githubusercontent.com/11644753/112987436-04029500-9163-11eb-9586-2f23506b9719.png)

_I tried this multiple times - same behaviour always._

After pressing the `install` button 
The install was not very fast but okay and worked.

## Eclipse Theia Cloud
The search did not found anything. I tried my own extension but also other - e.g. "yaml" inside search should show some findings etc. After 5-10 minutes I still got an ongoing search:
![image](https://user-images.githubusercontent.com/11644753/112988392-14673f80-9164-11eb-8982-a0e67d48427e.png)

**Comment by mbarbero** [comment]
Thanks for you report. We are currently observing degraded services. We are working on it. Thanks.

**Comment by mbarbero** [comment]
I created an incident https://www.eclipsestatus.io/incidents/6507ks168bmq

**Comment by mbarbero** [comment]
We've implemented a fix. We're still monitoring the situation, but our monitoring says that the performance are already much better. Feel free to reopen if you see otherwise.
