### ISSUE TITLE
Unable to publish extensions: "413: Request Entity Too Large"

### ISSUE THREAD

**Issue by DanTup** [EclipseFdn/open-vsx.org#432]
I'm trying to publish extensions with:

```
npx ovsx publish flutter-3.21.0.vsix -p (token)
```

But I'm seeing this error:

```
❌  The server responded with status 413: Request Entity Too Large
```

The referenced vsix file is only 17KB and I've had no problems publishing it in the past. Ovsx version is:

```
danny@Dannys-MBP Flutter-Code % npx ovsx version                                                            
Eclipse Open VSX CLI version 0.1.0-next.e000fdb
```

I'm not sure how to debug further. There are some previous issues with this error (for ex. https://github.com/eclipse/openvsx/issues/219), but none of their solutions seem valid here.

I see the same error with the Dart extension too (although that one is larger at around 7MB).

**Comment by DanTup** [comment]
> Eclipse Open VSX CLI version 0.1.0-next.e000fdb

Looks like this is not the latest version, it's 6mo old. The docs said "The easiest way to use it is through npx, which makes sure you always use the latest version of the tool" 😬

Anyway, I upgrade to `0.1.0-next.4742dff` and that seems to throw errors, so I tried `0.1.0-next.a9154dc` but that's producing the same "Request entity too large" error.

**Comment by mbarbero** [comment]
Thanks for your report. While investigating on https://www.eclipsestatus.io/incidents/6507ks168bmq, we inadvertently introduced a strict limitation on the body size of the request. This should be fixed now, please try again.

**Comment by mbarbero** [comment]
note that we will soon restart the service, so you may face 404.

**Comment by mbarbero** [comment]
We're done with the restart, let us know if you managed to publish your extension

**Comment by DanTup** [comment]
Yep, all worked now (it seemed quite slow publishing the 7MB Dart one, but it did work). Thanks!
