### ISSUE TITLE
Claiming namespace CryptoHack

### ISSUE THREAD

**Issue by jack4818** [EclipseFdn/open-vsx.org#435]
Hi, I am one of the co-founders of CryptoHack.

I recently developed a VS Code theme, and was asked to push it to VSX for our users who chose to use VS Codium.

https://github.com/cryptohack/code-theme

Let me know if there's any additional proof I need to include to remove the namespace warning.

The namespace is currently `CryptoHack` and the colour theme is: https://open-vsx.org/extension/cryptohack/cryptohack-theme

**Comment by brianking** [comment]
Granted, thanks for your contributions.
