### ISSUE TITLE
Claiming namespace barjo

### ISSUE THREAD

**Issue by barjoco** [EclipseFdn/open-vsx.org#436]
This is me.
open-vsx.org login name: barjoco
GitHub username: barjoco
Website: barjo.co

**Comment by brianking** [comment]
Hi @barjoco, your GH account looks like a service account and not a person account. We don't grant namespace ownership to service or bot accounts.

**Comment by barjoco** [comment]
Hi @brianking, it's a person account not a service account. Barjo isn't a company name, it's my online alias.

**Comment by brianking** [comment]
Thanks for clarifying @barjoco. Would it be possible for you to add your name and a short bio into your GH account?

**Comment by brianking** [comment]
Granted, thanks for your contributions.
