### ISSUE TITLE
Claiming namespace anweber

### ISSUE THREAD

**Issue by AnWeber** [EclipseFdn/open-vsx.org#437]
Hello,

I would like to claim the namespace anweber. I am the publisher of the extensions vscode-httpyac and vscode-statusbar-command. I like the goal and purpose of OpenVSX and would like to update the extensions at the same time as the vsce releases. I already published the extensions under my OpenVSX Account.

Thanks in advance.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
