### ISSUE TITLE
Claiming namespace rubdoo

### ISSUE THREAD

**Issue by mobabur94** [EclipseFdn/open-vsx.org#440]
Hi,

I am the legitimate owner of the `rubdoo` namespace, and I have logged in to https://open-vsx.org at least once.

I want to publish my theme to the namespace: https://github.com/mobabur94/rubdoo-theme/blob/main/package.json

Thank you!

**Comment by brianking** [comment]
Granted, thanks for your contributions.

I recommend adding more information to your Readme file to make it more useful to potential users.
