### ISSUE TITLE
Claiming namespace allanoricil

### ISSUE THREAD

**Issue by AllanOricil** [EclipseFdn/open-vsx.org#441]
The namespace is my name haha
I just published the same extension that I have on VS Code Marketplace in the VSX Registry and I would like to link the namespace to my VSX Account.

Here is my extension published in the VS Code marketplace https://marketplace.visualstudio.com/items?itemName=allanoricil.salesforce-soql-editor

Here is my extension published in the VSX Registry https://open-vsx.org/extension/allanoricil/salesforce-soql-editor

**Comment by brianking** [comment]
Granted, thanks for your contributions.
