### ISSUE TITLE
Claiming namespace ahmadawais

### ISSUE THREAD

**Issue by ahmadawais** [EclipseFdn/open-vsx.org#442]
I was contacted here https://github.com/ahmadawais/shades-of-purple-vscode/issues/106 to publish the Shades of Purple theme — claiming `ahmadawais` namespace would allow me to do that.

**Comment by brianking** [comment]
Granted, thanks for your contributions. 

Note that https://open-vsx.org/extension/ahmadawais/emoji-log-vscode is already published under this namespace.
