### ISSUE TITLE
Claiming namespace PKief

### ISSUE THREAD

**Issue by PKief** [EclipseFdn/open-vsx.org#443]
Hello together, I'd like to claim the ownership of the namespace PKief to publish my VSCode extensions also at the Marketplace of open-vsx.org. For instance, I'm the author of the [Material Icon Theme extension](https://open-vsx.org/extension/PKief/material-icon-theme). You can find the GitHub repository under my GitHub account [here](https://github.com/PKief/vscode-material-icon-theme). Let me know if you need any additional information from me to claim the ownership of this namespace. Thank you in advance.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
