### ISSUE TITLE
Claiming namespace vmssoftware

### ISSUE THREAD

**Issue by vorfol** [EclipseFdn/open-vsx.org#446]
I have been requested to publish the VMS-IDE extension on this platform.
https://marketplace.visualstudio.com/items?itemName=VMSSoftwareInc.vms-ide

**Comment by brianking** [comment]
Hi @vorfol, are you part of that organization? Before we grant ownership, we like to have some evidence that the person is somehow involved with the project. As this extension doesn't seem to have a GH repository, please post some clues for us about your involved and then we'll get you set up. Thanks.

**Comment by vorfol** [comment]
Our git page:
https://github.com/vmssoftware/vms-ide
I am one of the contributors.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
