### ISSUE TITLE
Claiming namespace eventyret

### ISSUE THREAD

**Issue by Eventyret** [EclipseFdn/open-vsx.org#449]
I am the original creator of [Bootstrap 4 CDN Snippet](https://open-vsx.org/extension/eventyret/bootstrap-4-cdn-snippet)
Have a few downloads on the VScode marketplace but moved to open source, I have signed the documents needed.

**Comment by Eventyret** [comment]
Here is the  github [repo](https://github.com/Eventyret/vscode-bcdn) and here is the original [marketplace URL](https://marketplace.visualstudio.com/items?itemName=eventyret.bootstrap-4-cdn-snippet)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
