### ISSUE TITLE
Claiming namespace tiki

### ISSUE THREAD

**Issue by lynhan-tiki** [EclipseFdn/open-vsx.org#450]
Hi team, 
I'm working at Tiki corporation. We're going to published a framework build on Theia and build several vsix plugin for this.
Please help us to claim tiki namespace. 
Thanks.

**Comment by brianking** [comment]
Hi @lynhan-tiki I'm happy to get you set up.

Can you provide link(s) showing you are contributing to the Tiki VS Code extensions, or are part of the organization?

I'm also curious to hear more about the framework you are building on Theia. Can you share more about that?

Thanks.

**Comment by lynhan-tiki** [comment]
Hi @brianking, 
Thank for your response.
We're building a studio to develop mobile app. Developer can create project, start simulator, build, publish app just on studio (which is build on top of Theia IDE). The app after published can run on our commercial platform [Tiki](https://tiki.vn/). We also create a custom language server support to our language syntax (published on open vsx registry).
We are on beta launch, so at the moment this is for internal purpose only. The Theia can build internal vsx and this is a nice to have option. So it's ok if we could claim tiki namespace or not. 
Regards.

**Comment by brianking** [comment]
@lynhan-tiki I have granted you namespace ownership, and am looking forward to seeing your contributions. 

With regard to your Theia application, the community is always happy to hear success stories. Please consider being listed on our [adopters page](https://ecdtools.eclipse.org/adopters/). Instructions on how to get listed are [here](https://ecdtools.eclipse.org/adopters/how-to-be-listed-as-an-adopter).

**Comment by lynhan-tiki** [comment]
Hi @brianking ,
`With regard to your Theia application, the community is always happy to hear success stories. Please consider being listed on our adopters page. Instructions on how to get listed are here.`
Yes sure. We will
Thanks
