### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by andrewlunde** [EclipseFdn/open-vsx.org#451]
Was having some loading issues with a tool that scans this repo and ended up creating a few variations of extensions that I now need to clean up. Could you remove the following?

sap-partner-eng.docs-extension
sap-partner-eng.bas-helper-extension

Thanks,

-Andrew

**Comment by brianking** [comment]
I will do so once #447 is fixed.

**Comment by brianking** [comment]
The extensions are now removed.
