### ISSUE TITLE
extension update not showing

### ISSUE THREAD

**Issue by rognierbenoit** [EclipseFdn/open-vsx.org#453]
Hello, I have uploaded the first update 0.38.0 of the extension https://open-vsx.org/extension/edukera/archetype but the 0.35.0 is still displayed. In gitpod/theia, when I try to install the extension, the 0.38.0 is proposed but the install fails. 

Here is the command I used to publish the update:
```
>  npx ovsx publish archetype-0.38.0.vsix -p ...
Need to install the following packages:
  ovsx
Ok to proceed? (y) y
🚀  Published edukera.archetype v0.38.0
```
Thanks.

**Comment by brianking** [comment]
This sounds like it could be a Gitpod issue. @akosyakov how can this be debugged?

**Comment by rognierbenoit** [comment]
Thank you for your feedback, everything is working fine tonight! The v0.38 now appears on  https://open-vsx.org/extension/edukera/archetype and it works fine in Theia. I guess there needs some time for the upgrade to be activated. regards.
