### ISSUE TITLE
Unpublish tellurium

### ISSUE THREAD

**Issue by ousheobin** [EclipseFdn/open-vsx.org#454]
Hi, 

I am the author of [telluriumlang/tellurium](https://open-vsx.org/extension/telluriumlang/tellurium). 

We have triggered a wrong script and publish an incomplete extension to the open-vsx. 

We hope to unpublish it. Would you please help on it?

Thank you.

**Comment by brianking** [comment]
I will do so once #447 is fixed. In the meantime, if you have the complete extension available you can publish that with a higher version.

**Comment by brianking** [comment]
telluriumlang.tellurium has been removed.
