### ISSUE TITLE
Claiming namespace yandeu

### ISSUE THREAD

**Issue by yandeu** [EclipseFdn/open-vsx.org#456]
I have published `yandeu.five-server` to [open-vsx.org](https://open-vsx.org/extension/yandeu/five-server) and [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=yandeu.five-server).

Also my username on github and npmjs is yandeu.

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by yandeu** [comment]
Thanks! 😊
