### ISSUE TITLE
Claiming namespace SixtyFPS

### ISSUE THREAD

**Issue by tronical** [EclipseFdn/open-vsx.org#457]
Hi,

I'm the co-founder of the SixtyFPS project at https://github.com/sixtyfpsui/sixtyfps . We have a Visual Studio Code extension that we'd like to publish to the Open VSX registry, and in order to do that I'd like to claim the SixtyFPS namespace.

Thanks in advance :)

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
