### ISSUE TITLE
Claiming namespace viktomas

### ISSUE THREAD

**Issue by viktomas** [EclipseFdn/open-vsx.org#460]
Hello, I'd like to claim my namespace `viktomas`. I use it to publish the extension https://gitlab.com/viktomas/slipbox (https://marketplace.visualstudio.com/items?itemName=viktomas.slipbox)

I use primarily my GitLab account these days. Please let me know if you need any additional proof, that the viktomas is my namespace.

Thank you

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
