### ISSUE TITLE
Claiming namespace VMSSoftwareInc

### ISSUE THREAD

**Issue by vorfol** [EclipseFdn/open-vsx.org#462]
Hi
It is not actually claiming namespace. We already have the namespace named 'vmssoftware'. But I have mistaken with the publisher name. On the visual studio marketplace we have 'VMSSoftwareInc' publisher name.
Can you rename our 'vmssoftware' namespace to 'VMSSoftwareInc'?

**Comment by brianking** [comment]
Reference issue #446

**Comment by brianking** [comment]
We can't rename namespaces, isn't that correct @spoenemann? For now I have created 'VMSSoftwareInc' and made you owner.

However, I see you already published under 'vmssoftware'. You may need to republish under the new namespace, and then we can remove the other version.

**Comment by vorfol** [comment]
Thanks!
I have republished VMS-IDE under 'VMSSoftwareInc'. 
You may remove 'vmssoftware'.

**Comment by brianking** [comment]
I've opened #469 for the removal of 'vmssoftware'.
