### ISSUE TITLE
Claiming namespace Tobermory

### ISSUE THREAD

**Issue by 0x00000001A** [EclipseFdn/open-vsx.org#468]
I hereby request to claim ownership of the extension that I just published to open vsx. The extension name is es6-string-html - by 0x00000001A (Tobermory)

This extension was published due to issue https://github.com/0x00000001A/es6-string-html/issues/36

Kindly do the needful, much obliged.
Yours truly
0x00000001A (Tobermory)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
