### ISSUE TITLE
Claiming namespace arzg

### ISSUE THREAD

**Issue by arzg** [EclipseFdn/open-vsx.org#470]
Hi, I’m publishing [a VS Code theme of mine](https://github.com/arzg/sema) on the Open VSX Registry, and would like to claim the `arzg` namespace to go along with it.

**Comment by brianking** [comment]
Granted, thanks for your contributions.

I suggest adding a logo to your extension to make it more visually identifiable to users.

**Comment by arzg** [comment]
Thanks for the suggestion; I’ll definitely consider it.
