### ISSUE TITLE
Claiming namespace marp-team

### ISSUE THREAD

**Issue by yhatt** [EclipseFdn/open-vsx.org#473]
I'm a maintainer of [Marp for VS Code](https://github.com/marp-team/marp-vscode), and the member of @marp-team organization.

- VS Code: https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode
- Open VSX: https://open-vsx.org/extension/marp-team/marp-vscode

**Comment by brianking** [comment]
Granted, thanks for your contributions.
