### ISSUE TITLE
Claiming namespace kamikillerto

### ISSUE THREAD

**Issue by KamiKillertO** [EclipseFdn/open-vsx.org#481]
I would like to claim ownership for the namespace `kamikillerto`.
It's my github and npm username.
It's also the publisher name I use to publish vscode extension on the Microsoft market.
I'll use it to publish the [colorize](https://github.com/KamiKillertO/vscode-colorize) extension into vsx

**Comment by brianking** [comment]
Granted, thanks for your contributions.

/cc @yupswing
