### ISSUE TITLE
Claiming namespace timdmackey

### ISSUE THREAD

**Issue by timdmackey** [EclipseFdn/open-vsx.org#489]
timdmackey is the namespace that I will be using to publish my personal projects. It is the same as my public github username. 

First VSCode extension is already published to the Open VSX Directory here: https://open-vsx.org/extension/timdmackey/mechanic-liquid
Repository: https://github.com/timdmackey/vscode-mechanic-liquid

**Comment by brianking** [comment]
Granted, thanks for your contributions.
