### ISSUE TITLE
Remove chenglou.rescript-language-server

### ISSUE THREAD

**Issue by ryyppy** [EclipseFdn/open-vsx.org#490]
Hi,

We are the authors of the [`rescript-vscode`](https://github.com/rescript-lang/rescript-vscode) extension (the codebase `rescript-language-server` is part of).

This package should not be exposed, since we treat the LSP as an implementation detail, and we don't want our users to run into breaking changes / outdated versions.

Can someone help us remove the [`rescript-language-server`](https://open-vsx.org/extension/chenglou/rescript-language-server) package from `open-vsx.org`?

Thanks.

**Comment by brianking** [comment]
This is blocked by #447

**Comment by brianking** [comment]
rescript-language-server has been removed.

@ryyppy You should also file an issue at  https://github.com/open-vsx/publish-extensions/issues to remove it from the open-vsx publish script.
