### ISSUE TITLE
Claiming namespace bung87

### ISSUE THREAD

**Issue by bung87** [EclipseFdn/open-vsx.org#491]
am author of https://github.com/bung87/vscode-rails, it already in open vsx but its dependency https://github.com/bung87/vscode-gemfile is not , there's user install vscode-rails from open vsx face problem .

**Comment by brianking** [comment]
Granted, thanks for your contributions.

@bung87 Will you be taking over responsibility for publishing updates for both extensions moving forward?

**Comment by bung87** [comment]
yes, I will.
