### ISSUE TITLE
Claiming namespace jdinhlife

### ISSUE THREAD

**Issue by jdinhify** [EclipseFdn/open-vsx.org#493]
Hi team,

I have an extension published in Microsoft VS Marketplace under the organisation `jdinhlife` (https://marketplace.visualstudio.com/items?itemName=jdinhlife.gruvbox). 
I wish to publish the extension in open-vsx under the same namespace.

Please let me know if you need further information.
Thank you,

**Comment by brianking** [comment]
Granted, thanks for your contributions.
