### ISSUE TITLE
Claiming namespace mrcrowl

### ISSUE THREAD

**Issue by mrcrowl** [EclipseFdn/open-vsx.org#496]
I'd like to claim the mrcrowl namespace (the same name as my username). I use this same name to publish equivalent extensions for the VS Code Marketplace, specifically:

- [Easy LESS](https://marketplace.visualstudio.com/items?itemName=mrcrowl.easy-less) 
- [Hg](https://marketplace.visualstudio.com/items?itemName=mrcrowl.hg) 

... I have been requested to publish these extensions for VS Codium, and I would like to keep the namespace consistent with that used on the VS Code marketplace, please.

Regards

**Comment by brianking** [comment]
Granted, looking forward to your contributions!
