### ISSUE TITLE
Claiming namespace matthewpi

### ISSUE THREAD

**Issue by matthewpi** [EclipseFdn/open-vsx.org#498]
Claiming this namespace for my [vscode-caddyfile-support](https://github.com/matthewpi/vscode-caddyfile-support) extension in relation to https://github.com/matthewpi/vscode-caddyfile-support/issues/12.

https://marketplace.visualstudio.com/items?itemName=matthewpi.caddyfile-support

**Comment by brianking** [comment]
Granted, thanks for your contributions.
