### ISSUE TITLE
Claiming namespace STNE

### ISSUE THREAD

**Issue by Dasug** [EclipseFdn/open-vsx.org#501]
I am part of a team working on a syntax highlight and general language support extension for the (admittedly rather obscure) scripting language of the browser game [stne.net](https://stne.net). I've already published the extension without namespace verification [here](https://open-vsx.org/extension/STNE/stnescript-support). Another member of our team has also published the extension on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=STNE.stnescript-support).

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by brianking** [comment]
I notice nothing is showing up in the overview section of your listing. It should at least show the versions available. Feel free to open a new issue about that.

A quick fix is probably adding a readme file to your extension.
