### ISSUE TITLE
Unpublish retired vscoss.vscode-ansible extension

### ISSUE THREAD

**Issue by ssbarnea** [EclipseFdn/open-vsx.org#505]
Someone published the now retired Ansible extension from https://github.com/VSChina/vscode-ansible at https://open-vsx.org/extension/vscoss/vscode-ansible

Please remove it because is not usable and is retired, also polluting the store. Worst part is that it also produces some conflicts with other popular extensions, like YAML one.

**Comment by brianking** [comment]
This is blocked by #447

**Comment by brianking** [comment]
vscoss.vscode-ansible has been removed.

@ssbarnea I recommend you also archive the repo on GH.
