### ISSUE TITLE
Claiming namespace quick-lint

### ISSUE THREAD

**Issue by strager** [EclipseFdn/open-vsx.org#508]
I am the lead developer and maintainer of [quick-lint-js](https://quick-lint-js.com/), the flagship product of [quick-lint](https://github.com/quick-lint).

The publisher name of our [Visual Studio Code extension on their marketplace](https://marketplace.visualstudio.com/items?itemName=quick-lint.quick-lint-js) is `quick-lint`.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
