### ISSUE TITLE
Claiming namespace rafaelmardojai

### ISSUE THREAD

**Issue by rafaelmardojai** [EclipseFdn/open-vsx.org#510]
Hello, I'm the author of [this extension](https://marketplace.visualstudio.com/items?itemName=rafaelmardojai.vscode-gnome-theme). I have published it in the [OpenVSX Registry](https://open-vsx.org/extension/rafaelmardojai/vscode-gnome-theme) and now I want to claim the ownership of my username's namespace.

Thanks in advance!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
