### ISSUE TITLE
Claiming namespace Huka

### ISSUE THREAD

**Issue by hukacode** [EclipseFdn/open-vsx.org#514]
I just created the namespace Huka and would like to claim ownership of it. At the moment I've published one small extension to the namespace.
https://open-vsx.org/extension/Huka/blogging-tool
https://github.com/hukacode/blogging-tool

What other information do you need for me to be able to show that I am the owner?

Thanks.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
