### ISSUE TITLE
Claiming namespace Fushra

### ISSUE THREAD

**Issue by trickypr** [EclipseFdn/open-vsx.org#515]
Hi,

I hope you have been having a good day. I wish to claim ownership of `Fushra` for my extension [meml](https://open-vsx.org/extension/Fushra/meml). I [wrote the extension](https://github.com/fushra/vscode) and control the [Fushra](https://github.com/fushra) organization on github.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
