### ISSUE TITLE
Claiming namespace sianglim

### ISSUE THREAD

**Issue by sianglim** [EclipseFdn/open-vsx.org#516]
Hi there,

can I please claim ownership of the sianglim namespace to publish an extension?

I've registered the same username on OpenVSX but when I tried publishing to that namespace, I didn't have access to do so.

Thanks and let me know if you need more info.

**Comment by brianking** [comment]
Granted, looking forward to your contributions.

/cc @marcdumais-work who is listed as a contributor to this namespace.
