### ISSUE TITLE
Claiming namespace jamesinaxx

### ISSUE THREAD

**Issue by jamesinaxx** [EclipseFdn/open-vsx.org#520]
I am James Grasso, or *jamesinaxx* and I am the developer behind this namespace. I have published [Developer Affirmations](https://open-vsx.org/extension/jamesinaxx/vscode-devaffirmations) on here and would like to resolve the issue.

I am the owner of the extension uploaded.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
