### ISSUE TITLE
Claiming namespace leodevbro

### ISSUE THREAD

**Issue by leodevbro** [EclipseFdn/open-vsx.org#524]
I need a namespace "leodevbro" for my vscode extension "Blockman" to be verified in the open-vsx.org website.
You can see the extension here: https://marketplace.visualstudio.com/items?itemName=leodevbro.blockman

![blockman-view-extension](https://user-images.githubusercontent.com/54504880/120194809-254d3380-c22f-11eb-9228-6644106e24d5.png)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
