### ISSUE TITLE
remove Darkempire78.discord-tools

### ISSUE THREAD

**Issue by ManualMap** [EclipseFdn/open-vsx.org#530]
Can you guys get rid of "Darkempire78.discord-tools" or [here](https://open-vsx.org/extension/Darkempire78/discord-tools), please thanks, it isn't my extension and I just wanted to have it, but I realized that I shouldn't publish other people extensions.

**Comment by brianking** [comment]
This is blocked by #447

**Comment by brianking** [comment]
I don't think there is any need to remove the extension, @Darkempire78 you can just continue to publish new versions and the latest will appear.
