### ISSUE TITLE
Claiming namespace Gwion

### ISSUE THREAD

**Issue by benrogmans** [EclipseFdn/open-vsx.org#531]
Hi there,

For the extension I created for Gwion, I would like to publish to open vsx under the "Gwion" namespace. You can find the repository here and see on Github that I'm part of the Gwion organization.

https://github.com/Gwion/vscode-extension

Thank you in advance,
Best regards,

Ben Rogmans

**Comment by brianking** [comment]
Granted, thanks for your contributions.
