### ISSUE TITLE
Claiming namespace Nash

### ISSUE THREAD

**Issue by Nash0x7E2** [EclipseFdn/open-vsx.org#534]
Cross-posting my Flutter VSCode extension, Awesome Flutter Snippets, to open-vsx.org. Previously used the name "Nash" as the publisher since it the name I use online. 

For reference:
- Feature request: https://github.com/Nash0x7E2/awesome-flutter-snippets/issues/28
- https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets
- https://open-vsx.org/extension/Nash/awesome-flutter-snippets

**Comment by brianking** [comment]
Granted, thanks for your contributions.
