### ISSUE TITLE
Claiming namespace Darkempire78

### ISSUE THREAD

**Issue by Darkempire78** [EclipseFdn/open-vsx.org#540]
Hi, I'm the owner of Discord Tools extension ([VSC Marketplace](https://marketplace.visualstudio.com/items?itemName=Darkempire78.discord-tools), [GitHub Repository](https://github.com/Darkempire78/Discord-Tools))
But @Laar-u has already published my extension without telling me here ([see here his publication](https://open-vsx.org/extension/Darkempire78/discord-tools)). I would like to publish my extension under this name myself.
He also tried to remove the extension from the market in this issue #530

**Comment by brianking** [comment]
Granted, thanks for your contributions.

I don't think there is any need to remove the extension, @Darkempire78 you can just continue to publish new versions and the latest will appear.
