### ISSUE TITLE
Claiming namespace openCAESAR

### ISSUE THREAD

**Issue by melaasar** [EclipseFdn/open-vsx.org#547]
Hello. I am the owner of the openCAESAR github organization that hosts the [oml-luxor](https://github.com/opencaesar/oml-luxor) repo. From that repo, I publish the oml-luxor VS Code extension. I was publishing it also to VSX Registry, and now I saw the new namespace rules, so I want to claim the namespace openCAESAR.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
