### ISSUE TITLE
Claiming namespace Sudhan

### ISSUE THREAD

**Issue by SudhanPlayz** [EclipseFdn/open-vsx.org#553]
Hello I own Neon Dark theme, Can i claim the ownership please. For even more proofs that i own this extenstion you can check the links below and the [github repo](https://github.com/SudhanPlayz/NeonDark-Theme)

### Links
VSX: https://open-vsx.org/extension/Sudhan/neondark-theme
VSC Market Place: https://marketplace.visualstudio.com/items?itemName=Sudhan.neondark-theme
GitHub Repo: https://github.com/SudhanPlayz/NeonDark-Theme

**Comment by brianking** [comment]
Granted, thanks for your contributions.
