### ISSUE TITLE
Request to remove legacy Vlang extensions

### ISSUE THREAD

**Issue by serkonda7** [EclipseFdn/open-vsx.org#554]
As you can see on my profile, I'm in the developer team of https://github.com/vlang and at the moment bring some love to the [VS code extension](https://github.com/vlang/vscode-vlang).

I have the following problem: on OpenVSX are three extensions listed for V [_query_](https://open-vsx.org/?search=vlang&category=&sortBy=relevance&sortOrder=desc). 
Two of them where already removed from the VS Code marketplace [_query_](https://marketplace.visualstudio.com/search?term=vlang&target=VSCode&category=All%20categories&sortBy=Relevance), as they do not reflect the recent release and produce invalid bug reports and confuse some users.

Could therefore the two no longer maintained releases be removed?
Namely these two:
- https://open-vsx.org/extension/0x9ef/vscode-vlang
- https://open-vsx.org/extension/vlang-vscode/vscode-vlang

Thanks in advance.

**Comment by brianking** [comment]
This is blocked by #447

**Comment by brianking** [comment]
0x9ef.vscode-vlang and vlang-vscode.vscode-vlang have been removed.

@serkonda7 As open-vsx published both of them, I recommend you open an issue (or make a PR) at https://github.com/open-vsx/publish-extensions to request they are removed from the publish script.
