### ISSUE TITLE
open-vsx.org is down

### ISSUE THREAD

**Issue by wulfthimm** [EclipseFdn/open-vsx.org#555]
Going to the url open-vsx.org gives me a 502 response. bundle.js cannot be loaded.

![image](https://user-images.githubusercontent.com/12035025/123215857-39502200-d4c9-11eb-859e-c3a19d3c9030.png)

![image](https://user-images.githubusercontent.com/12035025/123215960-54229680-d4c9-11eb-8572-7c43d53404ad.png)

**Comment by jankeromnes** [comment]
I'm now seeing an Eclipse error page instead of OpenVSX:

<img width="1440" alt="Screenshot 2021-06-24 at 09 22 54" src="https://user-images.githubusercontent.com/599268/123219996-cac19300-d4cd-11eb-8096-3be9794fa65b.png">

**Comment by JeroenAdam** [comment]
https://www.eclipsestatus.io/
OKD Cluster - outage
Identified - Network traffic now seems to be flowing. Services will be started slowly.
Jun 24, 05:01 EDT

**Comment by brianking** [comment]
The service is back online. If you notice anything else unusual, please open a new issue. Thanks.
