### ISSUE TITLE
Claiming namespace vivaxy

### ISSUE THREAD

**Issue by vivaxy** [EclipseFdn/open-vsx.org#559]
`vivaxy` is my publisher name on VSCode marketplace (https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits).

I've released my extension on Open VSX (https://open-vsx.org/extension/vivaxy/vscode-conventional-commits).

**Comment by brianking** [comment]
Granted, thanks for your contributions.
