### ISSUE TITLE
Change banner text to point to Whitepaper

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/open-vsx.org#564]
Our compliance work is done for now, so let's utilize the banner to promote the Open VSX Whitepaper.
https://outreach.eclipse.foundation/openvsx

For reference, see #337 for last change.

**Comment by croundy** [comment]
My thoughts on the banner text:

Download this FREE white paper to learn more about Open VSX and why open source tools to support VS Code extensions are gaining in popularity.
 
**_Open VSX Registry: A Vendor Neutral, Open Source Marketplace for VS Code Extensions_**

Link to https://outreach.eclipse.foundation/openvsx

**Comment by brianking** [comment]
@spoenemann I am going to make a PR for this. What do I need to do about the cookie? The current value is:

```
cookie: {
                    key: 'post-compliance-cut-off',
                    value: 'closed',
                    path: '/'
                }
```

**Comment by spoenemann** [comment]
You can change the key to ensure that users who already dismissed the previous banner will see the new one. The key is used to identify which banner has been dismissed.

**Comment by brianking** [comment]
This is live.
