### ISSUE TITLE
Unpublish `usernamehw.run-commands-view` & `usernamehw.snippets-view`

### ISSUE THREAD

**Issue by usernamehw** [EclipseFdn/open-vsx.org#566]
Both were deprecated 2 month ago

https://open-vsx.org/extension/usernamehw/run-commands-view

https://open-vsx.org/extension/usernamehw/snippets-view

**Comment by brianking** [comment]
This is blocked by #447

**Comment by brianking** [comment]
Both have been removed.

@usernamehw Will the new versions be published on Open VSX?

**Comment by usernamehw** [comment]
One extension is: https://open-vsx.org/extension/usernamehw/commands

Snippets extension is deprecated in favor of https://open-vsx.org/extension/RandomFractalsInc/snippets-viewer

Both have 0 installs. Hmmm. ok.

**Comment by brianking** [comment]
> Both have 0 installs in 5 months. Hmmm. ok. I guess nobody needs them.

Install count is broken for a few months, but will be fixed soon. Apologies for the inconvenience.
