### ISSUE TITLE
Claiming namespace ecrax

### ISSUE THREAD

**Issue by ecrax** [EclipseFdn/open-vsx.org#570]
Hey,
I am requesting the ownership of the "ecrax" namespace. I use this namespace to publish my extension [emoji-toolbox](https://open-vsx.org/extension/ecrax/emoji-toolbox). I have the extension published on the VSCode Maket Place as well and I use the "ecrax" username pretty much everywhere (also on YouTube). The source-code is also available on my GitHub profile.

Thanks for reviewing this request. :)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
