### ISSUE TITLE
Claiming namespace BeardedBear

### ISSUE THREAD

**Issue by BeardedBear** [EclipseFdn/open-vsx.org#572]
Hello !

Following the request of one of the users of my VSCode theme, I have uploaded Bearded Theme on Open VSX Registry (https://github.com/BeardedBear/bearded-theme/issues/52), so I come to claim my namespace :)

PS:  this is the extension : https://open-vsx.org/extension/BeardedBear/beardedtheme

**Comment by brianking** [comment]
Granted, thanks for your contributions.
