### ISSUE TITLE
Claiming namespace stef-k

### ISSUE THREAD

**Issue by stef-k** [EclipseFdn/open-vsx.org#577]
I am the author of  the laravel-goto-controller extension https://github.com/stef-k/laravel-goto-controller which I have published at https://marketplace.visualstudio.com/items?itemName=stef-k.laravel-goto-controller and want to publish the extension on Open VSX registry, as per user request https://github.com/stef-k/laravel-goto-controller/issues/24

**Comment by brianking** [comment]
Granted, thanks for your contributions.
