### ISSUE TITLE
Claiming namespace codestats

### ISSUE THREAD

**Issue by Aviortheking** [EclipseFdn/open-vsx.org#580]
I was authorized by the owner of codestats.net and maintaner of the [VSCode Extension](https://gitlab.com/juha.ristolainen/code-stats-vscode) to publish the extension on OpenVSX
![Capture](https://user-images.githubusercontent.com/15822031/125160100-b8508600-e16a-11eb-910a-4a8988adf80b.PNG)

_if it is possible to remove the riussi namespace, I made an error by publishing on this namespace_

**Comment by brianking** [comment]
Granted, thanks for your contributions.
