### ISSUE TITLE
Claiming namespace kieler

### ISSUE THREAD

**Issue by NiklasRentzCAU** [EclipseFdn/open-vsx.org#585]
I am an owner of the GitHub Organization [kieler](https://github.com/orgs/kieler/people) and wish to publish an extension, that already is published under the same namespace in the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=kieler.klighd-vscode) also in the open vsx marketplace.
Thank you!

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
