### ISSUE TITLE
Claiming namespace leading-works

### ISSUE THREAD

**Issue by soriyath** [EclipseFdn/open-vsx.org#586]
Leading Works SàRL is a LLC under Swiss law, see [the registration](https://adm.appls.fr.ch/hrcmatic/hrcintapp/externalCompanyReport.action?companyOfsUid=CHE-112.337.381&lang=FR).
With this claim, I want to control the leading-works namespace in order to publish work made by my company.

**Comment by brianking** [comment]
Granted, looking forward to your contributions.

**Comment by soriyath** [comment]
@brianking I see that the [open-vsx entry for my extension](https://open-vsx.org/extension/leading-works/eml2html) points to my Github user account.
Is there a way to have it point to the company's account: https://github.com/Leading-Works-SaRL ?

**Comment by brianking** [comment]
@soriyath, no as that will always be the account that publishes the latest version. One way around it is to setup a GH user account for your org, grant it namespace contributor status, and have the account publish. It's not exactly what you want but gets you closer.

RedHat does this for their extensions, e.g. https://open-vsx.org/extension/redhat/vscode-commons

**Comment by soriyath** [comment]
Thanks for the fast response !
