### ISSUE TITLE
Claiming namespace spaceduck

### ISSUE THREAD

**Issue by YoussefBouzekri** [EclipseFdn/open-vsx.org#588]

**Comment by brianking** [comment]
@YoussefBouzekri Please provide more information your relationship to the namespace, with some links if possible.

**Comment by YoussefBouzekri** [comment]
spaceduck is originally a vim theme, I am currently the mainainer of the vscode port, see this repo's readme: https://github.com/spaceduck-theme/vscode#team

**Comment by brianking** [comment]
Great, thanks. If you agree @YoussefBouzekri we'll keep the namespace all lowercase to be consistent with the MS Marketplace. Or should it be 'Spaceduck'?

**Comment by YoussefBouzekri** [comment]
@brianking all lowercase is fine for me !

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
