### ISSUE TITLE
Claiming namespace tonsky

### ISSUE THREAD

**Issue by tonsky** [EclipseFdn/open-vsx.org#589]
I have a github handle `tonsky` and a VS Code extension in the namespace `tonsky` https://marketplace.visualstudio.com/items?itemName=tonsky.theme-alabaster

**Comment by brianking** [comment]
Granted, thanks for your contributions.

@tonsky If you intend to publish newer versions to Open VSX moving forward, please open an issue at https://github.com/open-vsx/publish-extensions/issues for it to me removed from the open-vsx publishing script.
