### ISSUE TITLE
Claiming namespace bravo68web

### ISSUE THREAD

**Issue by BRAVO68WEB** [EclipseFdn/open-vsx.org#590]
I am Bravo68web. 

Profile :- https://github.com/BRAVO68WEB
Twitter :- https://twitter.com/bravo68web

My Work :- 
https://open-vsx.org/extension/bravo68web/propstar
https://marketplace.visualstudio.com/items?itemName=Bravo68web.propstar

**Comment by brianking** [comment]
Granted, thanks for your contributions.
