### ISSUE TITLE
Claiming namespace learnpack

### ISSUE THREAD

**Issue by alesanchezr** [EclipseFdn/open-vsx.org#593]
I just created learnpack namespace about 5 minutes ago, I will publish [this learnpack vscode extension](https://github.com/learnpack/vscode) to enhance the already amazing (but still in beta) learnpack package manager for learning.

You can see I'm the main contributor in all these repos:
https://www.npmjs.com/package/learnpack
https://github.com/learnpack/learnpack-cli
https://github.com/learnpack/learnpack-node
https://github.com/learnpack/learnpack-python

**Comment by brianking** [comment]
Granted, thanks for your contributions.
