### ISSUE TITLE
Claiming namespace kleinesfilmroellchen

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [EclipseFdn/open-vsx.org#596]
I want to publish my private packages under my internet username, which I use on GitHub, Eclipse, and other places.

**Comment by brianking** [comment]
@kleinesfilmroellchen Can you clarify what you mean by "private packages"? Everything publihsed on open-vsx.org is public.

**Comment by kleinesfilmroellchen** [comment]
By private, I mean packages created my me for non-commercial purposes that are not associated with a company or organization. Sorry for causing confusion. I know that all packages are public and that's also the intention.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
