### ISSUE TITLE
open-vsx.org service is down

### ISSUE THREAD

**Issue by princerachit** [EclipseFdn/open-vsx.org#597]
open-vsx.org is down. Installation of extensions, search is not working. Related issue: https://github.com/eclipse/openvsx/issues/308

![image](https://user-images.githubusercontent.com/32481722/126593636-f5fa3f64-27e9-4fdb-9190-4e2651ee1100.png)

**Comment by princerachit** [comment]
I see an internal error when searching for extensions: 
![image](https://user-images.githubusercontent.com/32481722/126593823-54eb4b33-ed61-4990-9111-dd789026750c.png)

**Comment by mbarbero** [comment]
Thanks. I've created https://www.eclipsestatus.io/incidents/yd3qyk7g0xj3.

**Comment by mbarbero** [comment]
Incident has been resolved. Thanks for your patience.
