### ISSUE TITLE
Policy on third party (not by the author) uploads

### ISSUE THREAD

**Issue by notpushkin** [EclipseFdn/open-vsx.org#60]
Hey! I've reuploaded some (open source) extensions from [marketplace.visualstudio.com](https://marketplace.visualstudio.com/) to [open-vsx.org](https://open-vsx.org/) (and even made up [a script](https://gist.github.com/notpushkin/7fba4e2035f2c25bb04dfb9fb51a30c5) for that). Given how namespaces work (anybody can publish, but the actual authors can claim the namespace at any time), I guess it's a desirable behaviour, but I wanted an explicit confirmation if this is the case indeed :)

**Comment by spoenemann** [comment]
Hi @notpushkin! That's ok. However, it would be better to add the third party extension to https://github.com/open-vsx/publish-extensions instead of publishing it yourself because then it's more transparent (the published extensions are listed in the extensions.json file).

**Comment by brianking** [comment]
@notpushkin Anything left to do here, or can we close it out?

**Comment by notpushkin** [comment]
Nope, I think we're good here. Thanks!
