### ISSUE TITLE
Claiming namespace soerenuhrbach

### ISSUE THREAD

**Issue by soerenuhrbach** [EclipseFdn/open-vsx.org#600]
Hello,

I recently published a vscode extension with the name [vscode-deepl](https://open-vsx.org/extension/soerenuhrbach/vscode-deepl) under the namespace "soerenuhrbach".
Now I would like the namespace since the namespace presents my name. 

Thank you!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
