### ISSUE TITLE
Claiming namespace cpt_stack

### ISSUE THREAD

**Issue by clin1234** [EclipseFdn/open-vsx.org#601]
I am a contributor to hieunc229/copilot-clone. On my fork, I am adding Github Actions to publish his extension to Open VSX.

**Comment by brianking** [comment]
@clin1234 I'm reading https://github.com/hieunc229/copilot-clone/issues/11. Is this namespace still needed?

**Comment by brianking** [comment]
Closing as per https://github.com/EclipseFdn/open-vsx.org/issues/602#issuecomment-890933212
