### ISSUE TITLE
Claiming namespace captain-stack

### ISSUE THREAD

**Issue by hieunc229** [EclipseFdn/open-vsx.org#602]
I've published a new extension (https://open-vsx.org/extension/captain-stack/copilot-clone) and wanted to claim ownership of the namespace `captain-stack`.

Thanks for your time!

**Comment by brianking** [comment]
@hieunc229 Does this take precedence over #601?

**Comment by hieunc229** [comment]
Yes, that's correct. We'll be using `captain-stack`

**Comment by brianking** [comment]
Granted, thanks for your contributions.

Note I am seeing the same extension published twice, with the same name but different identifiers.
https://open-vsx.org/extension/captain-stack/captain-stack
https://open-vsx.org/extension/captain-stack/copilot-clone

**Comment by hieunc229** [comment]
Thanks, @brianking! I'll remove one of them soon.
