### ISSUE TITLE
Claiming namespace codeandstuff

### ISSUE THREAD

**Issue by pgsandstrom** [EclipseFdn/open-vsx.org#605]
I just created the namespace codeandstuff and would like to claim it.

Im planning on publishing my extensions on open-vsx. Currently they only exist on the vscode marketplace under the same publisher.

**Comment by pgsandstrom** [comment]
I have now published one of my extensions: https://open-vsx.org/extension/codeandstuff/package-json-upgrade

**Comment by brianking** [comment]
Granted, thanks for your contributions.
