### ISSUE TITLE
Claiming namespace Chrismettal

### ISSUE THREAD

**Issue by Chrismettal** [EclipseFdn/open-vsx.org#607]
I would like to claim the namespace Chrismettal which I created, to publish to Open-VSX as well.

**Comment by Chrismettal** [comment]
I have published a theme created by me to Open-VSX under:

https://open-vsx.org/extension/Chrismettal/behave-full-theme

The source repo can be found here on my account, proving the connection between account and namespace:

https://github.com/Chrismettal/Behave-full-Theme

**Comment by brianking** [comment]
Granted, thanks for your contributions.
