### ISSUE TITLE
Claiming namespace 'panekj'

### ISSUE THREAD

**Issue by panekj** [EclipseFdn/open-vsx.org#608]
I would like to publish up-to-date PowerShell extensions (`powershell` and `powershell-preview`) since Microsoft team cannot publish their packages and open-vsx has only heavily outdated `ms-vscode.powershell-preview`.
reference: https://github.com/PowerShell/vscode-powershell/issues/3474

Also namespace is same as my GitHub username

**Comment by brianking** [comment]
Granted, thanks for your contributions.
