### ISSUE TITLE
Claiming namespace rvest

### ISSUE THREAD

**Issue by idahogurl** [EclipseFdn/open-vsx.org#609]
The namespace is only used by one extension. The repository shows that I own it. https://github.com/idahogurl/vs-code-prettier-eslint/blob/3a45a59b4ccb9f07ea8305556de88bdb6533292e/package.json#L2

**Comment by brianking** [comment]
Granted, looking forward to your contributions.

Note that @ludvigsen is a contributor on this namespace. As owner you can grant and revoke access to others.
