### ISSUE TITLE
please unpublish latest version of codetour

### ISSUE THREAD

**Issue by akosyakov** [EclipseFdn/open-vsx.org#611]
It should be published as web extension, but it is not. Please see https://github.com/gitpod-io/gitpod/issues/4978 for details.

**Comment by akosyakov** [comment]
@mbarbero 👋 do you know whether it is a proper channel to request?

**Comment by brianking** [comment]
@akosyakov Yes this is the right place, however it is blocked currently by #447.

**Comment by brianking** [comment]
@akosyakov Reading over https://github.com/gitpod-io/gitpod/issues/4978 ... does this still need to be removed?

**Comment by akosyakov** [comment]
No no, VS Code internals changed and now it is not requirement.
