### ISSUE TITLE
Eclipse foundation account register issue

### ISSUE THREAD

**Issue by gengjiawen** [EclipseFdn/open-vsx.org#615]
I need to publish an extension, so I find I have to register a Eclipse Foundation account https://open-vsx.org/user-settings/profile.

But after I register (I have confirmed your registration through email), I failed to login.

When I login, it says `Sorry, unrecognized username or password. Have you forgotten your password?`. 
When I find my password, it says `your email is not recognized as a user name or an email address.` 
When I register again, it says `sorry, your name and email is token`.

My email is `technicalcute@gmail.com`. I also tried a different email, same result.

**Comment by chrisguindon** [comment]
@gengjiawen It seems that we do have an account on file for you: https://accounts.eclipse.org/user/581392

Can you try to log in or reset your password?

**Comment by gengjiawen** [comment]
> @gengjiawen It seems that we do have an account on file for you: [accounts.eclipse.org/user/581392](https://accounts.eclipse.org/user/581392)
> 
> Can you try to log in or reset your password?

Now worked. Is there an account review process ?
