### ISSUE TITLE
Claiming namespace getpsalm

### ISSUE THREAD

**Issue by tm1000** [EclipseFdn/open-vsx.org#619]
I'm the maintainer of https://github.com/psalm/psalm-vscode-plugin. I was asked by the community to get the plugin on open-vsx.org through https://github.com/psalm/psalm-vscode-plugin/issues/31 I already have access to getpsalm namespace on the VSCode marketplace and I've created the getspalm namespace on open-vsx.org. Just need to claim ownership of it

**Comment by brianking** [comment]
Granted, thanks for your contributions.
