### ISSUE TITLE
Claiming namespace toem-de

### ISSUE THREAD

**Issue by thomasAtToem** [EclipseFdn/open-vsx.org#620]
Hi,

we used toem-de as its closest to our web domain toem.de -> https://www.toem.de.
We also use  toem-de on vscode marketplace.
The first extension (toem-de.impulse) is the port of our main product  impulse (https://toem.de/index.php/products/impulse).
My name is Thomas Haber and i'm founder of toem GmbH.

thanks,
thomas

**Comment by brianking** [comment]
Granted, thanks for your contributions.
