### ISSUE TITLE
Claiming namespace mgmcdermott

### ISSUE THREAD

**Issue by michaelgmcd** [EclipseFdn/open-vsx.org#627]
Hello, I'm the owner of the [vscode-language-babel](https://github.com/michaelgmcd/vscode-language-babel) repo, and I'd like to publish my extension VSCode Language Babel on Open VSX (requested in https://github.com/michaelgmcd/vscode-language-babel/issues/80).

What information do you need other than my username?

**Comment by brianking** [comment]
Granted, thanks for your contributions.
