### ISSUE TITLE
Claiming namespace FreeFlyingSheep

### ISSUE THREAD

**Issue by FreeFlyingSheep** [EclipseFdn/open-vsx.org#628]
Hi, I'm the maintainer of [loongarch-assembly](https://github.com/FreeFlyingSheep/loongarch-assembly).
I just published the [extension](https://open-vsx.org/extension/FreeFlyingSheep/loongarch-assembly) on your site and want to remove the warning.
Thank you!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
