### ISSUE TITLE
Claiming namespace darkriszty

### ISSUE THREAD

**Issue by darkriszty** [EclipseFdn/open-vsx.org#630]
Hi, I'd like to claim the `darkriszty` namespace for my VSCode extension `markdown-table-prettify` to remove the inverified namespace warning.

Repo: https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt
Request for ovsx publishing: https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt/issues/59
Published extension: https://open-vsx.org/extension/darkriszty/markdown-table-prettify

Please let me know if you need more info.

Thanks!

**Comment by brianking** [comment]
Granted, thanks for your contributions.
