### ISSUE TITLE
Proxy layer removes CORS headers, preventing vscode from accessing registry.

### ISSUE THREAD

**Issue by berzoidberg** [EclipseFdn/open-vsx.org#633]
As per eclipse/openvsx#306, there appears to be a misconfiguration at the proxy/load-balancer level preventing CORS headers generated by the Spring framework from reaching clients. Specifically, the `access-control-allow-origin` header must be allowed to pass through. Failing to pass this header triggers security measures in the chromium-based Electron framework on which vscode runs, preventing the requested resource from loading. Current workarounds involve disabling this security feature, which may create a larger security issue for users.

**Comment by spoenemann** [comment]
We have seen a similar problem before that we could track down to an Nginx bug: The Spring server correctly includes a `vary: Origin` response header to indicate that the `Origin` request header must be included when computing cache keys. Sadly Nginx ignores that and returns the same cached response regardless of the `Origin` value:
https://trac.nginx.org/nginx/ticket/1423
As a consequence, the `access-control-allow-origin` response header is missing when a cached response without CORS is available. I think this was solved by bypassing the cache for certain messages. @mbarbero could this be the same situation here?

**Comment by mbarbero** [comment]
cc @agafgfafa

**Comment by daiyam** [comment]
Have you tried the proposed solution: `proxy_cache_key "$scheme$proxy_host$uri$is_args$args$http_authorization";`?

**Comment by eclipsewebmaster** [comment]
Some background -- 

As a general rule, we prefer to let the server app dictate what can or cannot be cached, and tend to be conservative on caching. In the initial weeks after deployment, the open-vsx server component was not capable of handling all the requests thrown at it and would time out most requests. Since it cannot scale horizontally (ie, only one instance can run), the instance was limited to the resources we could throw at it, which never seemed to be sufficient.

In addition, the for each web request, the server seemed to send dozens/hundreds of queries to the postgres database, which would cause it to run at excessively high loads for very little actual "work".

We ended up having to make some compromises on caching to reduce the amount of requests that went to the server. Adding elements to the proxy_cache_key makes the cache entries unique enough to negate caching altogether.

In the end, the server needs to scale > 1 instance AND query the database more efficiently.

**Comment by daiyam** [comment]
I understand the performance issues. But CORS headers have become a requirement to run VSCode OSS or any fork of VSCode.
Is it possible to see the config files of nginx?

**Comment by jotoho** [comment]
I do not understand why seemingly nothing has been done about this by the Eclipse team, yet. If Eclipse wants people to continue to use OpenVSX then there is no other choice than to fix this proxy misconfiguration, regardless of performance implications.

If I heard correctly, then making the clients tolerate your misconfiguration has become impossible/infeasible so OpenVSX either gets their stuff together or the service effectively performs suicide. And it makes one question why Eclipse adopted OpenVSX if they would just leave it to die a few months later. And seemingly over something as comparatively minor as a config issue at that.

**Comment by brianking** [comment]
Some unforeseen circumstances have delayed us from fixing this, but please be aware that it is the number 1 priority for us with Open VSX now and will proceed from there.

**Comment by eclipsewebmaster** [comment]
I've cleared the manipulation of headers at the reverse proxy, and I'll monitor the server's performance. The only request we intercept at this point is the OPTIONS request, since it generates a ton of server load.

When the server would become unresponsive under load, we attacked the problem with a blunt instrument. Let's see what happens if we back off.

**Comment by j3j5** [comment]
Maybe I'm missing something but can't you just cache the requests (both, OPTIONS and GET) **with** the `Access-Control-Allow-Origin` header set to `*`? I mean, you don't want to restrict access to the shop to a given origin, so the header can be on all requests. From what I understand on the bug report on Nginx, the issue is that the cache doesn't "respect" the `Vary` header, but the `Access-Control-Allow-Origin` is returned on both.

Again, sorry, if I'm missing something, but it seems to me that you shouldn't need to stop caching in order to return the CORS headers correctly.

**Comment by berzoidberg** [comment]
If caching is a concern, and we already know the URIs for endpoints that need to have the access-control-allow-origin header set to "*", you can configure nginx to explicitly send that header for those specific URIs instead of a) relying on the application to do it correctly, and b) the nginx caching mechanism to cache those headers correctly.

I understand from a philosophical perspective not wanting to do any sort of access control logic on the reverse proxy, and instead wanting to leave it up to the application code itself. However, as a systems engineer I tend to approach these things from a more holistic, user-experience based approach:

I run service X. Service X is comprised of components (proxy, app, db, etc). I should strive to achieve the best user experience possible using whichever of these components achieves the goal the quickest, while balancing long-term maintenance.

So the way I evaluate this situation is as such:

The user needs CORS headers to be sent correctly for modern vscode distributions to access the marketplace correctly. These headers are being blocked seemingly by nginx caching policy, where an nginx bug prevents headers from caching. The suggested workaround would likely put too much strain on the application, which does not scale past a single node. Improving application scalability is a large task which would block this issue for too long of a period. Thusly, a stop-gap measure should be put in place where nginx controls the CORS headers directly for the relevant endpoints until such a time that the application is made to scale well (db access improvements, multiple nodes, etc) so caching can be turned off, or nginx fixes the caching bug upstream and the reverse proxy can be fixed.

Just my two cents.

**Comment by eclipsewebmaster** [comment]
All that text is dandy --  but have we resolved the issue?

**Comment by berzoidberg** [comment]
> All that text is dandy -- but have we resolved the issue?

a) rude, b) it doesn't appear so. as per the bug on the main openvsx project, people are still seeing the issue. one other user provided a simple curl command you can use to repro this. in that same bug, there are numerous other methods for reproducing this and checking on your own end without having to directly ask the bug reporters. would you like me to copy those methods here for quick reference?

**Comment by eclipsewebmaster** [comment]
> Maybe I'm missing something

We're probably both missing something. My understanding is that setting Access-Control-Allow-Origin header to * is synonymous to solving a permissions problem with chmod 777

The vsx server sets specific hosts in the Access-Control-Allow-Origin header, we don't want to just whack that to the curb with a large hammer?

**Comment by berzoidberg** [comment]
> > Maybe I'm missing something
> 
> We're probably both missing something. My understanding is that setting Access-Control-Allow-Origin header to * is synonymous to solving a permissions problem with chmod 777

Yes, but public APIs are meant to be "chmod 777" -- the purpose of setting specific hosts is to prevent hosts not under your control from using what are supposed to be private APIs. That is not the case here.

> The vsx server sets specific hosts in the Access-Control-Allow-Origin header, we don't want to just whack that to the curb with a large hammer?

The code as-written sets the hosts to "*".

**Comment by berzoidberg** [comment]
Another option is to write the header on a per-response bases with the value set to whatever the requesting host has sent as their origin. Both are perfectly acceptable for public APIs.

**Comment by eclipsewebmaster** [comment]
Not trying to be rude; just direct. The current issue is "Proxy layer removes CORS headers, preventing vscode from accessing registry."

As we've removed the proxy layer's involvement in CORS headers, then the issue lies elsewhere.

**Comment by berzoidberg** [comment]
> Not trying to be rude; just direct. The current issue is "Proxy layer removes CORS headers, preventing vscode from accessing registry."
> 
> As we've removed the proxy layer's involvement in CORS headers, then the issue lies elsewhere.

Is the nginx configuration available somewhere that the community can review and replicate? Without being able to more properly duplicate your production environment, I cannot lend any more of a hand in debugging. I've already confirmed in a local dev environment that the spring application is writing CORS headers correctly, at least for how I'm running it.

**Comment by berzoidberg** [comment]
I would also refer back to my statement that, until the root cause can be found, writing the headers directly from nginx would be a great way to "stop the bleeding" -- even if there yet another issue between spring code and nginx that is preventing CORS headers from being sent correctly.

**Comment by eclipsewebmaster** [comment]
server {
    listen       443 ssl http2;
    server_name  open-vsx.org www.open-vsx.org;
    error_log /var/log/nginx/open-vsx.org/error.log;
    access_log  /var/log/nginx/open-vsx.org/access.log  rproxyhost;

    # Eclipse SSL - max compatibility, no HSTS
    include /etc/nginx/default.d/open-vsx.org-ssl-compat.conf;
    include /etc/nginx/default.d/proxy_cache_aggressive.inc;

    keepalive_timeout 3;

    # support larger than 8MB uploads
    client_max_body_size 250m;
    client_body_buffer_size 128k;

    # Bypass cache if an Origin: header is sent
    # proxy_cache_bypass $http_origin;

    # default robots.txt for sites that do not provide one
    location /robots.txt { alias /usr/share/nginx/html/robots.default.txt; }

    # enable caching of redirects to Azure
    location /vscode/asset {
        proxy_hide_header 'Cache-control';
        proxy_hide_header 'Expires';
        proxy_hide_header 'Pragma';
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        add_header 'Cache-Control' 'max-age=600, public';
        proxy_pass  https://okd-ingress-tls$request_uri;
    }

    location / {
        #proxy_hide_header 'access-control-allow-origin';
        #if ($http_origin) {
        #    add_header 'access-control-allow-origin' $http_origin;
        #}

        if ($request_method = 'OPTIONS') {
            add_header Content-Length 0;
            add_header Vary "Origin";
            add_header Vary "Access-Control-Request-Method";
            add_header Vary "Access-Control-Request-Headers";
            add_header Allow "GET,HEAD,POST,OPTIONS";
            add_header strict-transport-security "max-age=31536000 ; includeSubDomains";
            add_header x-frame-options "DENY";
            return 204;
        }
        proxy_pass  https://okd-ingress-tls$request_uri;
    }
}

**Comment by eclipsewebmaster** [comment]
proxy_cache_aggressive.inc contains:

    # Split keys for http and https
    proxy_cache_key "$scheme$request_method$host$request_uri";
    proxy_cache zn_cache;

    # Don't use "error" in proxy_cache_use_stale - a 200 that gets deleted (404) leads to stale content (Bug 548497)
    proxy_cache_use_stale timeout updating http_500 http_502 http_503 http_504;
    proxy_cache_background_update on;

    proxy_cache_lock on;
    add_header X-Proxy-Cache $upstream_cache_status;
    proxy_cache_valid 200     8m;
    proxy_cache_valid 302 307  2h;
    proxy_cache_valid 301      1d;
    proxy_cache_revalidate     on;

    proxy_cache_bypass $http_x_cache_bypass;

    # handle Range requests correctly for large, uncached files
    # By default nginx strips the range header and pulls everything from upstream, even if the range is one byte. This can fill the upstream network
    # Here we bypass and disable cache for range requests, and pass the Range header to upstream
    proxy_cache_bypass $http_range;
    proxy_no_cache     $http_range;
    proxy_set_header   Range $http_range;

    proxy_set_header Connection "";
    proxy_http_version 1.1;

    proxy_set_header   Host              $host;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_max_temp_file_size 0;

    proxy_buffering on; # needed for cache

    proxy_connect_timeout 20s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;

**Comment by eclipsewebmaster** [comment]
> I would also refer back to my statement that, until the root cause can be found, writing the headers directly from nginx would be a great way to "stop the bleeding" -- even if there yet another issue between spring code and nginx that is preventing CORS headers from being sent correctly.

Agreed -- and we've stopped the bleeding a few times now. I'm unsure what the fix is, in this case.

**Comment by eclipsewebmaster** [comment]
> I do not understand why seemingly nothing has been done about this by the Eclipse team, yet. If Eclipse wants people to continue to use OpenVSX then there is no other choice than to fix this proxy misconfiguration, regardless of performance implications.
> 
> If I heard correctly, then making the clients tolerate your misconfiguration has become impossible/infeasible so OpenVSX either gets their stuff together or the service effectively performs suicide. And it makes one question why Eclipse adopted OpenVSX if they would just leave it to die a few months later. And seemingly over something as comparatively minor as a config issue at that.

Just a clarification -- The Eclipse Foundation is an OSS Foundation that hosts code projects, and the open-vsx server is one of them. While we absolutely want the project to succeed, we don't actively employ developers to work on the OSS projects.

In this case, we are hosting an instance of the open-vsx server code. All of the server-side code that we run have a configuration guide to indicate how the instance should be installed and operated (such as: https://gerrit-review.googlesource.com/Documentation/config-reverseproxy.html)

Last I checked, openvsx does not have such a guide (https://github.com/eclipse/openvsx) so we're doing what we can to run it as best we know how.

If this is a hosting misconfiguration, please help point us in the right direction and we'll get this resolved.

**Comment by daiyam** [comment]
Shouldn't the OPTIONS response more like:
```
if ($request_method = 'OPTIONS') {
	add_header Content-Length 0;
	add_header access-control-allow-headers "content-type,x-market-client-id,x-market-user-id, authorization";
	add_header access-control-allow-methods "OPTIONS,GET,POST,PATCH,PUT,DELETE";
	add_header access-control-allow-origin "*";
	add_header strict-transport-security "max-age=31536000 ; includeSubDomains";
	return 200;
}
```

**Comment by berzoidberg** [comment]
> Shouldn't the OPTIONS response more like:
> 
> ```
> if ($request_method = 'OPTIONS') {
> 	add_header Content-Length 0;
> 	add_header access-control-allow-headers "content-type,x-market-client-id,x-market-user-id,authorization";
> 	add_header access-control-allow-methods "OPTIONS,GET,POST,PATCH,PUT,DELETE";
> 	add_header access-control-allow-origin "*";
> 	add_header strict-transport-security "max-age=31536000 ; includeSubDomains";
> 	return 200;
> }
> ```

I wouldn't do that on /everything/ -- note that block is for the root URI. Also HTTP 204 is an appropriate response for a OPTIONS request.

**Comment by eclipsewebmaster** [comment]
> Shouldn't the OPTIONS response more like:
> 
> ```
> if ($request_method = 'OPTIONS') {
> 	add_header Content-Length 0;
> 	add_header access-control-allow-headers "content-type,x-market-client-id,x-market-user-id,authorization";
> 	add_header access-control-allow-methods "OPTIONS,GET,POST,PATCH,PUT,DELETE";
> 	add_header access-control-allow-origin "*";
> 	add_header strict-transport-security "max-age=31536000 ; includeSubDomains";
> 	return 200;
> }
> ```

We couldn't return 200, that would generate an error, as there is no content. 204 is more applicable here.

I replicated the exact payload of the open-vsx server at the time.  Right now I see:

* SSLv2, Unknown (23):
< HTTP/1.1 200 
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST
< Access-Control-Allow-Headers: content-type, x-market-client-id, x-market-user-id
< Access-Control-Max-Age: 1800
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-Frame-Options: DENY
< Content-Length: 0
< Date: Tue, 07 Sep 2021 18:26:39 GMT


I'll imitate that and see how it goes. Thx for the tip.

**Comment by daiyam** [comment]
@berzoidberg Ok but the headers `access-control-allow-*` seem to be a must for CORS. I will have to do some research...

**Comment by berzoidberg** [comment]
I would suggest using a nested location to only put the CORS-related headers on the URLs used for API access. Here are the prefixes currently configured within the spring app for CORS:

```
/user/*
/logout
/admin/*
/api/*
/vscode/*
```

You should be able to match all of these with a regex pattern group, and inject headers as necessary. Worth noting that some clients will still error if the access-control-allow-origin header is not present on /every/ request. Only injecting into OPTIONS is insufficient.

**Comment by eclipsewebmaster** [comment]
This is the current OPTIONS payload:

    location / {
        if ($request_method = 'OPTIONS') {
            add_header Content-Length 0;
            add_header Vary "Origin";
            add_header Vary "Access-Control-Request-Method";
            add_header Vary "Access-Control-Request-Headers";
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "OPTIONS,GET,POST,PATCH,PUT,DELETE";
            add_header Access-Control-Allow-Headers "content-type, x-market-client-id, x-market-user-id";
            add_header X-Content-Type-Options "nosniff";
            add_header X-XSS-Protection "1; mode=block";
            add_header strict-transport-security "max-age=31536000 ; includeSubDomains";
            add_header x-frame-options "DENY";
            return 204;
        }
        proxy_pass  https://okd-ingress-tls$request_uri;

**Comment by berzoidberg** [comment]
I can confirm an OPTIONS request now received the access-control-allow-origin header on some requests, however for some reason this URL is still not getting it:

https://open-vsx.org/vscode/asset/ms-python/python/2021.8.1159798656/Microsoft.VisualStudio.Code.Manifest

Also non-OPTIONS requests do not receive the header either, which still prevents vscode from being able to talk to the API as intended.

**Comment by berzoidberg** [comment]
Oh I see, you have a separate location block for /vscode/asset. That section will need the same header-writing magic applied to it. I would suggest perhaps move that block to be nested under the root location block, so it can inherit the OPTIONs shortcut w/header injection.

**Comment by eclipsewebmaster** [comment]
I am of the understanding that nginx does not do nested add_header directives.  From TFM:

There could be several add_header directives. These directives are inherited from the previous configuration level if and only if there are no add_header directives defined on the current level.

http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

So I've added:
map $http_origin $acal {
  default "*";
  "~^.*"  $http_origin;
}


Then:
    location /vscode/asset {

        proxy_hide_header 'access-control-allow-origin';
        add_header 'access-control-allow-origin' $acal always;


        proxy_hide_header 'Cache-control';
        proxy_hide_header 'Expires';
        proxy_hide_header 'Pragma';
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        add_header 'Cache-Control' 'max-age=600, public';
        proxy_pass  https://okd-ingress-tls$request_uri;
    }

    location / {
        proxy_hide_header 'access-control-allow-origin';
        add_header 'access-control-allow-origin' $acal always;


        if ($request_method = 'OPTIONS') {
            add_header Content-Length 0;
            add_header Vary "Origin";
            add_header Vary "Access-Control-Request-Method";
            add_header Vary "Access-Control-Request-Headers";
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "OPTIONS,GET,POST,PATCH,PUT,DELETE";
            add_header Access-Control-Allow-Headers "content-type, x-market-client-id, x-market-user-id";
            add_header X-Content-Type-Options "nosniff";
            add_header X-XSS-Protection "1; mode=block";
            add_header strict-transport-security "max-age=31536000 ; includeSubDomains";
            add_header x-frame-options "DENY";
            return 204;
        }
        proxy_pass  https://okd-ingress-tls$request_uri;
}


I've confirmed that Origin:  is used if sent from the client; otherwise, *

**Comment by j3j5** [comment]
Just my 2 cents, adding `add_header 'access-control-allow-origin' $acal always;` instead of just `add_header 'access-control-allow-origin' '*' always;`  would just decrease the 'cacheability' of the responses w/o adding any extra security layer. As @berzoidberg said above, the header is meant to secure your own apis against other origin using them. In the case of a public API, there's no restriction on which origin can use them. Using `*` the response is the same (can be cached) for every request no matter the origin, using `$http_origin` that isn't the case anymore.

**Comment by j3j5** [comment]
Also, reading you nginx config, `proxy_cache_bypass $http_origin;` was the one causing the performance issues since probably all the requests had an origin set, hence rendering the cache useless.

**Comment by eclipsewebmaster** [comment]
> Also, reading you nginx config, `proxy_cache_bypass $http_origin;` was the one causing the performance issues since probably all the requests had an origin set, hence rendering the cache useless.

It's been commented out for months.

**Comment by eclipsewebmaster** [comment]
> Just my 2 cents, adding `add_header 'access-control-allow-origin' $acal always;` instead of just `add_header 'access-control-allow-origin' '*' always;` would just decrease the 'cacheability' of the responses w/o adding any extra security layer. As @berzoidberg said above, the header is meant to secure your own apis against other origin using them. In the case of a public API, there's no restriction on which origin can use them. Using `*` the response is the same (can be cached) for every request no matter the origin, using `$http_origin` that isn't the case anymore.

Using add_header doesn't affect "our" caching results.

In the end, I would hope the server would set these headers for us so we don't have to intercept at the reverse proxy.

**Comment by daiyam** [comment]
I can also confirm that CORS is successfully validated for `https://open-vsx.org/vscode/gallery/extensionquery`. 
But it's failing for the url given by @berzoidberg.

**Comment by eclipsewebmaster** [comment]
I've repeated the OPTIONS block for  /vscode/asset

**Comment by berzoidberg** [comment]
Can confirm everything appears to be working.

**Comment by j3j5** [comment]
Yes, can confirm on my side as well. Let's hope the changes don't cause any other issue on the hosting. Thank you very much @eclipsewebmaster for the fix and for hosting this on the first place.

**Comment by eclipsewebmaster** [comment]
Many thanks to you folks. Love the collaboration here.

I'll close this one, as it relates to the EF's hosted version, and we'll keep https://github.com/eclipse/openvsx/issues/306 open to hopefully get the changed into the server code.

**Comment by akosyakov** [comment]
It looks like now some resources cannot be downloaded at like for web extensions: https://github.com/gitpod-io/gitpod/issues/5590 Could you reopen the issue?

**Comment by akosyakov** [comment]
`Access-Control-Allow-Headers` does not seem to be correct, try following settings:
```
Access-Control-Allow-Credentials "true"
Access-Control-Allow-Headers "content-type,x-market-client-id,x-market-user-id,x-client-commit,x-client-name,x-client-version,x-machine-id"
Access-Control-Allow-Methods "OPTIONS,GET,POST,PATCH,PUT,DELETE"
Access-Control-Allow-Origin "*"
```

**Comment by mbarbero** [comment]
Reopening because of https://github.com/EclipseFdn/open-vsx.org/issues/633#issuecomment-915041788

**Comment by eclipsewebmaster** [comment]
> Access-Control-Allow-Credentials "true"
> Access-Control-Allow-Headers "content-type,x-market-client-id,x-market-user-id,x-client-commit,x-client-name,x-client-version,x-machine-id"
> Access-Control-Allow-Methods "OPTIONS,GET,POST,PATCH,PUT,DELETE"
> Access-Control-Allow-Origin "*"

That is in place now.

**Comment by mbarbero** [comment]
It seems to have fixed https://github.com/gitpod-io/gitpod/issues/5590, closing.
