### ISSUE TITLE
Request to remove obsolete zbr.vscode-ansible extension

### ISSUE THREAD

**Issue by ssbarnea** [EclipseFdn/open-vsx.org#635]
As we finally republished the Ansible extension as https://open-vsx.org/extension/redhat/ansible we now need to have https://open-vsx.org/extension/zbr/vscode-ansible removed in order to avoid user confusions with two extensions.

To be clear, I am the author of the `zbr.vscode-ansible` extension which recently become `redhat.ansible`. Practically both extensions were released from the same codebase, so there is no real reason to keep the old one present.

Related: https://github.com/eclipse/openvsx/issues/285

**Comment by brianking** [comment]
This is blocked currently by #447

**Comment by brianking** [comment]
zbr.vscode-ansible has been removed.
