### ISSUE TITLE
namespace rename due github account rename

### ISSUE THREAD

**Issue by Miezhiko** [EclipseFdn/open-vsx.org#636]
https://open-vsx.org/extension/Qeenon/hot-emo-theme -> https://open-vsx.org/extension/Miezhiko/hot-emo-theme

**Comment by brianking** [comment]
Hi @Miezhiko, thanks for your contributions.

We can't move extensions or rename namespaces. I suggest you create the new namespace, and then open a separate issue to remove the extension from the old namespace.

**Comment by Miezhiko** [comment]
this is lame

well I've created organization with old username and made a fork there
