### ISSUE TITLE
Claiming namespace cyrilletuzi

### ISSUE THREAD

**Issue by cyrilletuzi** [EclipseFdn/open-vsx.org#637]
Well, the namespace is my personal one, so I don't know what to explain. :D You can verify I'm the author of the Angular Schematics extension:
- on GitHub: [https://github.com/cyrilletuzi/vscode-angular-schematics](https://github.com/cyrilletuzi/vscode-angular-schematics)
- on VS Code Marketplace: [https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
