### ISSUE TITLE
Claiming namespace pouya

### ISSUE THREAD

**Issue by pouyakary** [EclipseFdn/open-vsx.org#638]
Hi my name is Pouya Kary and I have many projects under the name "karyfoundation" in the VS Code marketplace. For example this one has the repo link that links to this GitHub. 

https://marketplace.visualstudio.com/items?itemName=karyfoundation.idf

With this exact GitHub account I have registered for the ovsx and found the namespace "pouya" to be available which is something I really much want to have the ownership of. I don't know what else I have to provide for you.

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by pouyakary** [comment]
Thank you ♥️
