### ISSUE TITLE
Claiming namespace AvengaGermanyGmbH

### ISSUE THREAD

**Issue by malud** [EclipseFdn/open-vsx.org#639]
Hi,
as employee and maintainer for related projects[1] I would like to claim the given namespace. See my profile organization avenga: https://github.com/avenga respectively https://www.avenga.com/

*1: https://marketplace.visualstudio.com/items?itemName=AvengaGermanyGmbH.couper

**Comment by brianking** [comment]
Granted, thanks for your contributions.
