### ISSUE TITLE
Claiming namespace Natizyskunk

### ISSUE THREAD

**Issue by Natizyskunk** [EclipseFdn/open-vsx.org#640]
I'm the new maintainer of the [VSCode-SFTP](https://github.com/Natizyskunk/vscode-sftp/) extension.
I Forked it, fixed some bugs, updated it and i'm now maintaining it on my free time to help the big amount of people that uses it everyday.
For these reason I really want it to also be available on open-vsx for other projects like vscodium.

Best regards,
Natizyskunk

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by Natizyskunk** [comment]
@brianking,
Thanks 😀
