### ISSUE TITLE
Claiming namespace swellaby

### ISSUE THREAD

**Issue by calebcartwright** [EclipseFdn/open-vsx.org#649]
hello :wave: 

I'm one of the owners/maintainers of the Swellaby namespace on the VS Code Marketplace, and I'd like to reclaim that namespace here.

While we certainly want to make our extensions available where users need them, we'd also really like to get our namespace because whatever the current process that's grabbed our extensions has produced at least one incorrectly bundled version of our extension on the Open VSX Registry. That mis-packaging has been a source of issues for our users (refs https://github.com/open-vsx/publish-extensions/pull/352 and https://github.com/swellaby/vscode-rust-test-adapter/issues/94) and we'd love to get that sorted as soon as feasible.

Please let me know if you need any more information

**Comment by brianking** [comment]
@calebcartwright In order for me to grant you namespace ownership, you will need to log in at open-vsx.org first.

If you would like open-vsx to stop publishing the extension(s), please file an issue here:
https://github.com/open-vsx/publish-extensions/issues

**Comment by calebcartwright** [comment]
> you will need to log in at open-vsx.org first.

@brianking I have logged in, though I haven't authorized the GitHub app yet. Are you saying I need to both login and grant the app access (which would require me giving the app access to my private profile information)?

**Comment by brianking** [comment]
> @brianking I have logged in, though I haven't authorized the GitHub app yet. Are you saying I need to both login and grant the app access (which would require me giving the app access to my private profile information)?
> 
> (edit - I guess app authorization and logging in are synonymous, so maybe I haven't logged in?)

The only information we use from GH is the username, which is public. We use GitHub OAuth only for authentication, not to access private profile information.

**Comment by calebcartwright** [comment]
> The only information we use from GH is the username, which is public.

I'm fully aware the username is public :wink: My point is that it's using the `read:user` OAuth scope which does grant your app full access to all profile info, public and private, even if you aren't taking advantage of that access today.

To be honest, I find it troublesome that I'd need to both create an Eclipse account, sign a CLA, and grant access to all my GitHub profile data, all just to be able to get to our own extension that's broken here.

I truly appreciate the goals of the Open VSX project, but the process is a little frustrating, especially because of the challenges the broken publishing process has caused for us and our users.

I actually want to take a little time to think through whether it makes more sense for us to go through this for our extensions, or if it'd just be easier to stop the auto-publishing and direct VSCodium users to download the vsix packages from our respective repos (as non-ideal as that may be).

Thanks for your assistance, if we decide to proceed with trying to publish to this registry then I'll post a comment once we have all the relevant accounts and logins completed, otherwise will just close this and follow your guidance to get the publishing stopped.

**Comment by brianking** [comment]
Understood @calebcartwright 

If you have not already, I would encourage you to read our FAQ which might help answer some of your questions:
https://www.eclipse.org/legal/open-vsx-registry-faq/

**Comment by brianking** [comment]
Closing for now.

@calebcartwright feel free to reopen if you wish to pursue this further.

**Comment by calebcartwright** [comment]
Thanks @brianking and understood. I think may know the root cause of the issue with the auto-publishing process, so going to try to get that path working again before reconsidering alternatives

**Comment by calebcartwright** [comment]
https://github.com/open-vsx/publish-extensions/pull/352#issuecomment-958599484
