### ISSUE TITLE
Claiming namespace hideoo

### ISSUE THREAD

**Issue by HiDeoo** [EclipseFdn/open-vsx.org#652]
Hello,

I just [published an extension on the Open VSX Registry](https://open-vsx.org/extension/hideoo/toggler) and would like to remove the verification warning by claiming the `hideoo` namespace ownership.

The Marketplace version can be found [here](https://marketplace.visualstudio.com/items?itemName=hideoo.toggler).

Thank you for your time

**Comment by brianking** [comment]
Granted, thanks for your contributions.
