### ISSUE TITLE
Claiming namespace xlab

### ISSUE THREAD

**Issue by anzoman** [EclipseFdn/open-vsx.org#656]
I am a software developer at [XLAB](https://www.xlab.si/) and I want to claim our `xlab` namespace.
We have already published our [first extension](https://github.com/xlab-si/radon-xopera-saas-plugin) on VS Marketplace [here](https://marketplace.visualstudio.com/items?itemName=xlab.xopera-saas).

My coworkers @cankarm, @sstanovnik can also be added to the namespace.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
