### ISSUE TITLE
Claiming namespace redwan-hossain

### ISSUE THREAD

**Issue by redwan-hossain** [EclipseFdn/open-vsx.org#663]
I recently published SkillAvid Pure Black extension on VS Marketplace under this namespace. I want to make it available for the vscodium store running under open-vsx too.

Link of vscode extentension- https://marketplace.visualstudio.com/items?itemName=redwan-hossain.skillavid-pure-black

**Comment by brianking** [comment]
Granted, thanks for your contributions.
