### ISSUE TITLE
Claiming namespace One Dark Pro

### ISSUE THREAD

**Issue by Binaryify** [EclipseFdn/open-vsx.org#665]
I am the author and publisher of the One Dark Pro extension.

**Comment by brianking** [comment]
@Binaryify The extension is published under the namespace _zhuangtongfa_

https://open-vsx.org/extension/zhuangtongfa/material-theme

Is that the namespace you would like ownership of?

**Comment by Binaryify** [comment]
@brianking 
yes, or maybe you can change it to binaryify if you can, that might be better

**Comment by brianking** [comment]
@Binaryify Are you the original author?

We can't move extensions or rename namespaces. I suggest you create the new namespace, and then open a separate issue to remove the extension from the old namespace.

**Comment by brianking** [comment]
@Binaryify Is there any further action needed in this issue?

**Comment by Binaryify** [comment]
https://open-vsx.org/extension/zhuangtongfa/material-theme 
is fine

**Comment by brianking** [comment]
Ok. If you want to take ownership of the _zhuangtongfa_ namespace and start publishing yourself, please file a new issue for that.
