### ISSUE TITLE
align CORS blob storage settings with production

### ISSUE THREAD

**Issue by akosyakov** [EclipseFdn/open-vsx.org#667]
I'm trying to test latest VS Code against latest Open VSX on staging, but getting CORS errors from blog storage:
<img width="937" alt="Screenshot 2021-09-13 at 11 32 37" src="https://user-images.githubusercontent.com/3082655/133060692-38edf558-fc5f-446d-a5e2-7a6f76aa9549.png">

**Comment by mbarbero** [comment]
Done.

**Comment by akosyakov** [comment]
Unfortunately, i still see same errors.

**Comment by mbarbero** [comment]
CORS for staging were synched on our LB, but Azure configurations were not. It should be all good now. Please try again.

**Comment by akosyakov** [comment]
It works now!
