### ISSUE TITLE
Claiming namespace felipecrs

### ISSUE THREAD

**Issue by felipecrs** [EclipseFdn/open-vsx.org#668]
Because of https://marketplace.visualstudio.com/items?itemName=felipecrs.vscode-gerrit

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by felipecrs** [comment]
Thank you, @brianking. If you could please take a look at https://github.com/EclipseFdn/open-vsx.org/issues/415, it's the only thing pending us from publishing to OpenVSX automatically.

**Comment by brianking** [comment]
> Thank you, @brianking. If you could please take a look at #415, it's the only thing pending us from publishing to OpenVSX automatically.

Done.
