### ISSUE TITLE
Claiming namespace html-validate

### ISSUE THREAD

**Issue by ext** [EclipseFdn/open-vsx.org#675]
I am the primary maintainer of the [html-validate](https://html-validate.org/) ([repo](https://gitlab.com/html-validate/html-validate)) and its [vscode extension](https://gitlab.com/html-validate/vscode-html-validate).

I wish to claim the namespace to publish the extension to Open VSX.

**Comment by ext** [comment]
Relevant links:

https://gitlab.com/html-validate/vscode-html-validate/-/issues/8
https://gitlab.com/html-validate/vscode-html-validate/-/merge_requests/154

**Comment by brianking** [comment]
Granted, thanks for your contributions.
