### ISSUE TITLE
Please delete broken published version James-Yu.latex-workshop 8.20.2

### ISSUE THREAD

**Issue by jankeromnes** [EclipseFdn/open-vsx.org#676]
Now that `vsce` has been upgraded, we should re-publish `James-Yu.latex-workshop@8.20.2`: https://github.com/open-vsx/publish-extensions/issues/414#issuecomment-922539630

Please un-publish/delete https://open-vsx.org/extension/James-Yu/latex-workshop/8.20.2

**Comment by brianking** [comment]
v8.20.2 has been removed.
