### ISSUE TITLE
Please delete broken published version 

### ISSUE THREAD

**Issue by jankeromnes** [EclipseFdn/open-vsx.org#677]
We've tried re-publishing `alefragnani.project-manager` with https://github.com/open-vsx/publish-extensions/pull/306, but it currently fails with this error:

```
Error: Extension alefragnani.project-manager version 12.0.1 is already published, but is currently inactive and therefore not visible.
```

Could you please delete the inactive extension `alefragnani.project-manager` so that it can be republished?

**Comment by brianking** [comment]
@spoenemann Under what circumstances does an extension become inactive? I was not aware of this case.

**Comment by brianking** [comment]
I have removed version 12.0.1.

**Comment by spoenemann** [comment]
> Under what circumstances does an extension become inactive? I was not aware of this case.

 * When it was published before the Publisher Agreement became effective and the publisher has not signed it afterwards, or
 * when a publisher revokes the Publisher Agreement (currently done only by an admin after receiving such a request).

**Comment by Siddhant-K-code** [comment]
`v12.7` is released now. Can we bring it back?

[Older version](https://open-vsx.org/extension/alefragnani/project-manager) seems broken: 
![image](https://user-images.githubusercontent.com/55068936/212819511-dc31c07e-4e67-4f7c-ad59-eb773118e17e.png)
