### ISSUE TITLE
Claiming namespace muhammadelashri

### ISSUE THREAD

**Issue by MohamedElashri** [EclipseFdn/open-vsx.org#678]
Hello, I published my extension which is adding syntax support for Fhicl language (used in Fermilab) which is available now on [open-vsx](https://open-vsx.org/extension/muhammadelashri/FHiCL). I would like to claim the ownership of this namespace to be able to manage and update the extension. As you can see the extension GitHub source is on my account and namespace is my name.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
