### ISSUE TITLE
Claiming namespace illumincrotty

### ISSUE THREAD

**Issue by illumincrotty** [EclipseFdn/open-vsx.org#687]
The namespace is the same as my GitHub profile name, and I have published an extension (a theme named living twilight) under that namespace. 

The theme is from my repository: https://github.com/illumincrotty/VSCode-Themes/tree/main/living-twilight

and the theme on open-vsx: https://open-vsx.org/extension/illumincrotty/living-twilight

**Comment by brianking** [comment]
Granted, thanks for your contributions.
