### ISSUE TITLE
Unpublish (actually remove) `felipecrs.test` and `felipecrs.tsl-problem-matcher`

### ISSUE THREAD

**Issue by felipecrs** [EclipseFdn/open-vsx.org#697]
`felipecrs.test` I just created for test purposes. And `felipecrs.tsl-problem-matcher` was a fork which lived 1 day only. No one downloaded it, as it seems.

**Comment by brianking** [comment]
felipecrs.test has been removed.

felipecrs.tsl-problem-matcher might have downloads, but they are not showing because of #283.

I notice the original extension is live also at https://open-vsx.org/extension/eamodio/tsl-problem-matcher.

@felipecrs Remove or leave your version?

**Comment by felipecrs** [comment]
@brianking remove please. Btw, the original extension was renamed from `eamodio.tsl-problem-matcher` to `amodio.tsl-problem-matcher` on VS Marketplace, I don't know if it matters...

**Comment by felipecrs** [comment]
Thanks a bunch!
