### ISSUE TITLE
Claiming namespace shivaprasanth

### ISSUE THREAD

**Issue by cedric05** [EclipseFdn/open-vsx.org#708]
The namespace should be associated to me as it is all of the following

Its my full name
Has all the packages on the equivalent VSCode namespace
Associated with my token
Was made by me

ref
- https://open-vsx.org/extension/shivaprasanth/dothttp-code
- https://marketplace.visualstudio.com/items?itemName=ShivaPrasanth.dothttp-code

**Comment by brianking** [comment]
Granted, thanks for your contributions.
