### ISSUE TITLE
Autosync 1.0.20 (2110211) log file

### ISSUE THREAD

**Issue by antonyggvzvmnxxcx** [EclipseFdn/open-vsx.org#714]
(Please write in English)

Autosync
1.0.20 (2110211)
Samsung Galaxy A12 (SM-A125F)
Android 11 (RP1A.200720.012.A125FXXU1BUI3)

**Comment by brianking** [comment]
@antonyggvzvmnxxcx Please provide a description of what this issue is about.

**Comment by brianking** [comment]
Closing due to lack of information. If further action is needed, please reopen with specific information.
