### ISSUE TITLE
Claiming namespace PascalReitermann93

### ISSUE THREAD

**Issue by pascalre** [EclipseFdn/open-vsx.org#718]
The namespace should be associated to me as it is all of the following

* Its my full name
* Has all the packages on the equivalent VSCode namespace
* Associated with my token
* Was made by me

ref
* https://open-vsx.org/extension/PascalReitermann93/vscode-yaml-sort
* https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort

**Comment by brianking** [comment]
Granted, thanks for your contributions.
