### ISSUE TITLE
Claiming namespace meronz

### ISSUE THREAD

**Issue by meronz** [EclipseFdn/open-vsx.org#728]
Hello. I'm claiming the namespace meronz, which is currently used by an older version of one extension (https://open-vsx.org/extension/meronz/manpages) published on my behalf by someone else. 

I'm the original developer of the extension, and i want to publish the updated version. I've setup new repositories on github which you can find on profile page. 

Thank you!

**Comment by GitMensch** [comment]
I'm CCing the request and as a "prove" we have the old repository with the merge note at https://gitlab.com/meronz/vscode.manpages/-/issues/7, too.
Looking forward for the new version :-)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
