### ISSUE TITLE
Claiming namespace mercedes-benz

### ISSUE THREAD

**Issue by company-jcup** [EclipseFdn/open-vsx.org#741]
Daimler will seperate into two different legal entities: "Daimler Trucks" and "Mercedes-Benz", see https://www.daimler.com/company/business-units/210730-project-focus.html :

> The remaining Daimler AG – to be renamed as Mercedes-Benz Group AG – with a global workforce of around 170,000 people will concentrate on the business with cars and vans. 

I am maintainer of https://github.com/daimler/sechub-plugin-vscode (which will move in future to https://github.com/mercedes-benz/sechub-plugin-vscode) and we currently provide the sechub plugin to OpenVSX marketplace via the already claimed namespace "daimler".

Because of the company renaming, we need to claim the namespace "mercedes-benz" as well.

**Comment by brianking** [comment]
Granted, thanks.

If you need an extension removed from a legacy namespace, please file a separate issue.
