### ISSUE TITLE
Claiming namespace mercedesbenz

### ISSUE THREAD

**Issue by company-jcup** [EclipseFdn/open-vsx.org#742]
Daimler will seperate into two different legal entities: "Daimler Trucks" and "Mercedes-Benz", see https://www.daimler.com/company/business-units/210730-project-focus.html :

> The remaining Daimler AG – to be renamed as Mercedes-Benz Group AG – with a global workforce of around 170,000 people will concentrate on the business with cars and vans. 

I am maintainer of https://github.com/daimler/sechub-plugin-vscode (which will move in future to https://github.com/mercedesbenz/sechub-plugin-vscode) and we currently provide the sechub plugin to OpenVSX marketplace via the already claimed namespace "daimler".

Because of the company renaming, we need to claim the namespace "mercedesbenz" as well.

**Comment by company-jcup** [comment]
Remark - I added already https://github.com/EclipseFdn/open-vsx.org/issues/741 for "mercedes-benz" com. This is no failure - I want to claim both namespaces.

**Comment by brianking** [comment]
Done.
