### ISSUE TITLE
Claiming namespace adarshpandeyin

### ISSUE THREAD

**Issue by aadarshp31** [EclipseFdn/open-vsx.org#743]
## I own the namespace "adarshpandeyin" in Microsoft's Marketplace & the website https://www.adarshpandey.in
<br />
I already have this extension published on Microsoft's Marketplace 

[here](https://marketplace.visualstudio.com/items?itemName=adarshpandeyin.search-github-users-extension) with the same namespace "adarshpandeyin". I also own the website https://www.adarshpandey.in/ <br />
I want to have uniformity across different marketplace so my users can find my products easily in all marketplaces.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
