### ISSUE TITLE
Claiming namespace MarcosGutirrezAlonso

### ISSUE THREAD

**Issue by margual56** [EclipseFdn/open-vsx.org#746]
> Briefly explain what makes you a legitimate owner of the namespace mentioned in the issue title.

I created the namespace and uploaded the extension in there.

The extension repository is [https://github.com/margual56/vscode-turing-machine](https://github.com/margual56/vscode-turing-machine).<br/>
Feel free to ask for any other information you might need, thank you 😄

**Comment by brianking** [comment]
Granted, thanks for your contributions.
