### ISSUE TITLE
Claiming namespace DaltonMenezes

### ISSUE THREAD

**Issue by daltonmenezes** [EclipseFdn/open-vsx.org#751]
Hi, I'm the [Aura Theme](https://github.com/daltonmenezes/aura-theme) creator and a user ask me to publish it also on open-vsx so I did it. I'm trying to claim the namespace ownership of `DaltonMenezes` of the [published Aura Theme on open-vsx](https://open-vsx.org/extension/DaltonMenezes/aura-theme). Thanks

**Comment by brianking** [comment]
Granted, thanks for your contributions.
