### ISSUE TITLE
unpublish Angular.ng-template 13.0.0

### ISSUE THREAD

**Issue by akosyakov** [EclipseFdn/open-vsx.org#752]
in order to resolve https://github.com/open-vsx/publish-extensions/issues/506

**Comment by brianking** [comment]
@mbarbero I am getting 'Internal server error' when trying to remove this. Can you check the logs to see what might be happening?

Note removal was broken before but it was fixed at: https://github.com/eclipse/openvsx/pull/333

**Comment by mbarbero** [comment]
I see 

```
2021-11-19 11:15:07.513 ERROR 1 --- [.0-8080-exec-31] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: update or delete on table "file_resource" violates foreign key constraint "download_file_resource_fkey" on table "download"
2021-11-19 11:15:07.774 ERROR 1 --- [.0-8080-exec-31] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [download_file_resource_fkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause
org.postgresql.util.PSQLException: ERROR: update or delete on table "file_resource" violates foreign key constraint "download_file_resource_fkey" on table "download"
```

**Comment by brianking** [comment]
@amvanbaren Given you touched this code recently, any ideas what might be happening?

**Comment by amvanbaren** [comment]
The `file_resource` table doesn't have an `active` column like the `extension_version` or `extension` tables. When an extension version is unpublished, then all file resources are deleted instead of updated to `active = false`

**Comment by akosyakov** [comment]
Latest vscode-java-debug is bogus, we need to unpublish it as well.

**Comment by brianking** [comment]
Let's break out each extension into it's own issue.

**Comment by hm2075** [comment]
getting  

Request failed: GET https://openvsxorg.blob.core.windows.net/resources/Angular/ng-template/13.0.0/README.md (The specified blob does not exist.)


broke gitpod workspace which relies on re-downloading extensions each time

**Comment by hm2075** [comment]
not good that this has been down for so many days without resolution

![image](https://user-images.githubusercontent.com/53794682/143616260-49a47554-9955-442c-90f8-648c37a766a4.png)

**Comment by hm2075** [comment]
12 days of a popular extension being down imo isn't good enough.

This is very poor and does nothing for people having trust in the system to make the switch from ms tools.

**Comment by brianking** [comment]
Version 13.0.0 has been removed. I see there is a 13.1.0 published in the meantime, so if anything else needs to be done please reopen or open a new issue.

**Comment by filiptronicek** [comment]
Because of the original issue (and it persisting), it would be good to unpublish the extension again, so that we can sort it out. I fixed the build on our side in https://github.com/open-vsx/publish-extensions/commit/42e34f2468d3c429650f23db4576d01a0e563cb1, so I hope we can publish from there until Angular fixes it on their end.

**Comment by brianking** [comment]
@filiptronicek What do you mean by "unpublish the extension again"? Do you mean remove the latest version, 13.1.0, or remove all versions which will result in delisting?

**Comment by filiptronicek** [comment]
@brianking sorry for not being more specific here: I mean to unpublish the latest release (13.1.0). I have also raised https://github.com/angular/vscode-ng-language-service/issues/1586 to let the authors know that this is an issue and that we would like them to publish it themselves.

**Comment by brianking** [comment]
13.1.0 has been removed.
