### ISSUE TITLE
Claiming namespace cup-lang

### ISSUE THREAD

**Issue by jgrajewsky** [EclipseFdn/open-vsx.org#753]
I'm the creator of [Cup Language](https://github.com/cup-lang/cup) and it's [VSCode extension](https://github.com/cup-lang/vscode-cup). I also publish the extension on the VSCode Marketplace [here](https://marketplace.visualstudio.com/items?itemName=cup-lang.cup).

**Comment by brianking** [comment]
Granted, thanks for your contributions.
