### ISSUE TITLE
Claiming namespace Iamlxm123

### ISSUE THREAD

**Issue by Iamlxm123** [EclipseFdn/open-vsx.org#754]
I created it,now i want to publish my extension
![1637632211(1)](https://user-images.githubusercontent.com/39472896/142960291-74150fb3-48fc-4a48-b566-a2fc7453ebc2.jpg)

**Comment by Iamlxm123** [comment]
![image](https://user-images.githubusercontent.com/39472896/142979033-67e842b9-0d5f-41cd-8d63-1381104ce2a1.png)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
