### ISSUE TITLE
OpenVSX is slow

### ISSUE THREAD

**Issue by akosyakov** [EclipseFdn/open-vsx.org#757]
Looks like https://open-vsx.org is slow at the time of this issue. @mbarbero @eclipsewebmaster Could you check please and update https://www.eclipsestatus.io/ accordingly? Thank you!

**Comment by akosyakov** [comment]
it looks better now.

**Comment by mbarbero** [comment]
Is it better now?

I see load spike at 10am CET (4am EST) and 11am CET (5am EST). It seems to match with our "uncapped bandwidth" timeframe.  @eclipsewebmaster, @agafgfafa WDYT?

**Comment by eclipsewebmaster** [comment]
Yes I'll tweak things on our side.

**Comment by brianking** [comment]
Any improvements today @akosyakov @mbarbero ?

**Comment by mbarbero** [comment]
Tweak is not deployed yet.

**Comment by eclipsewebmaster** [comment]
New bandwidth control is now in place.

**Comment by akosyakov** [comment]
<img width="871" alt="Screenshot 2021-11-29 at 08 56 54" src="https://user-images.githubusercontent.com/3082655/143829146-73c2fd34-d791-4baa-90b7-a675a99630cb.png">

It seems to be alright now. Last spike was on 24th Nov.

**Comment by eclipsewebmaster** [comment]
Just curious, what is that graph?

**Comment by akosyakov** [comment]
We are running OpenVSX caching proxy in Gitpod as a buffer it also monitors performance of OpenVSX from Gitpod perspective.

It would be better to have something like that in OpenVSX instead: https://github.com/EclipseFdn/open-vsx.org/issues/713

**Comment by brianking** [comment]
Closing as the issue as reported is fixed.
