### ISSUE TITLE
Claiming namespace Hamza-Aziane

### ISSUE THREAD

**Issue by Hamza-Aziane** [EclipseFdn/open-vsx.org#762]
I want to claim my namespace at https://open-vsx.org/extension/Hamza-Aziane/obsidian-dark.

I have a github repo for this vscode theme (extension) at https://github.com/Hamza-Aziane/obsidian-dark.

This is the link of the extension at visual studio marketplace https://marketplace.visualstudio.com/items?itemName=Hamza-Aziane.obsidian-dark

Thanks.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
