### ISSUE TITLE
Claiming namespace johnbillion

### ISSUE THREAD

**Issue by johnbillion** [EclipseFdn/open-vsx.org#763]
I would like to claim the `johnbillion` namespace on Open VSX.

* The namespace matches my GitHub username and Open VSX username
* I've published an extension on Open VSX at https://open-vsx.org/extension/johnbillion/vscode-wordpress-hooks
* I've published the same extension on VSC Marketplace at https://marketplace.visualstudio.com/items?itemName=johnbillion.vscode-wordpress-hooks
* The extension source is at https://github.com/johnbillion/vscode-wordpress-hooks

Thanks in advance

**Comment by brianking** [comment]
Granted, thanks for your contributions.
