### ISSUE TITLE
improve website SEO

### ISSUE THREAD

**Issue by akosyakov** [EclipseFdn/open-vsx.org#764]
It does not look like Google can index open-vsx.org:
<img width="701" alt="Screenshot 2021-11-29 at 09 31 26" src="https://user-images.githubusercontent.com/3082655/143837194-f324d88a-f78e-49f9-b963-f2435127ff31.png">

If someone looks for VS Code (extensions) marketplace then OpenVSX should be at least on second position.

**Comment by brianking** [comment]
@chrisguindon Any ideas about this one?

/cc @croundy

**Comment by mbarbero** [comment]
The edge load balancer serves a [robots.txt file](https://open-vsx.org/robots.txt). @agafgfafa, you added this 8 months ago when the site was having a hard time coping with incoming traffic. 

Should it be removed now?

/cc @eclipsewebmaster

**Comment by eclipsewebmaster** [comment]
Googlebot is allowed to crawl.  I'll use the Google webmaster tools to see why it's not indexing.

**Comment by eclipsewebmaster** [comment]
Actually, it is indexing:  
![image](https://user-images.githubusercontent.com/4520186/146243029-610e2aa6-3acf-43de-bc94-6bbe67e08845.png)

**Comment by eclipsewebmaster** [comment]
"ruby for vs code" leads to open-vsx.org on page 4. Indeed, we need SEO.

**Comment by brianking** [comment]
Ok thanks @eclipsewebmaster. I'll ask @croundy for assistance with SEO.

**Comment by kineticsquid** [comment]
Dup of #1240
