### ISSUE TITLE
Claiming namespace SonarSource

### ISSUE THREAD

**Issue by julien-carsique-sonarsource** [EclipseFdn/open-vsx.org#765]
Claiming the namespace ownership on behalf of the SonarLint team at SonarSource company that edits the sonarlint-vscode extension.
https://open-vsx.org/extension/SonarSource/sonarlint-vscode
See committers at https://github.com/SonarSource/sonarlint-vscode

**Comment by brianking** [comment]
Granted, thanks for your contributions. 

If you will be publishing this yourself moving forward, please open an issue at https://github.com/open-vsx/publish-extensions/issues to remove it from the open-vsx publishing script.
