### ISSUE TITLE
Claiming namespace christian-kohler

### ISSUE THREAD

**Issue by ChristianKohler** [EclipseFdn/open-vsx.org#766]
I am the creator of both extensions. Here are both repos:

- https://github.com/ChristianKohler/NpmIntellisense
- https://github.com/ChristianKohler/PathIntellisense

**Comment by brianking** [comment]
@ChristianKohler Looking at the listings on the MS marketplace, shouldn't the namespace be christian-kohler or ChristianKohler and then both extensions could be listed under that?

**Comment by ChristianKohler** [comment]
Ah got it. Thank you @brianking 

So I just wanted to create the namespace but it already exists. I have not created it but would like to claim it so I can add my extensions to open vsx. What do I need to do?

<img width="333" alt="image" src="https://user-images.githubusercontent.com/4374178/144134788-c1a702ad-d017-4047-9c31-53267dfdec43.png">

**Comment by brianking** [comment]
I have now made you owner of the namespace christian-kohler. The open-vsx user already published your extension as part of seeding the registry. 

https://open-vsx.org/extension/christian-kohler/path-intellisense
https://open-vsx.org/extension/christian-kohler/npm-intellisense

If you are going to take over publishing yourself, please open an issue or PR at https://github.com/open-vsx/publish-extensions to remove it from the publish script.
