### ISSUE TITLE
Claiming namespace anwar

### ISSUE THREAD

**Issue by anwar3606** [EclipseFdn/open-vsx.org#770]
Hi, 

I have these two extensions published in vscode marketplace. 

https://marketplace.visualstudio.com/items?itemName=anwar.papyrus-language-support
https://marketplace.visualstudio.com/items?itemName=anwar.papyrus-pdf

I want to also publish them in open vsx too. 
So Can I have "anwar" namespace? 

Thanks,
Anwar

**Comment by brianking** [comment]
Granted, thanks for your contributions.
