### ISSUE TITLE
Claiming namespace flutter-riverpod-snippets

### ISSUE THREAD

**Issue by RobertBrunhage** [EclipseFdn/open-vsx.org#771]
I am the owner of [vscode extension](https://marketplace.visualstudio.com/items?itemName=robert-brunhage.flutter-riverpod-snippets#:~:text=Flutter%20Riverpod%20snippets%20is%20a,different%20snippets%20such%20as%20provider%20.)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
