### ISSUE TITLE
Claiming namespace shufo

### ISSUE THREAD

**Issue by shufo** [EclipseFdn/open-vsx.org#772]
Hi.
I would like to take namespace `shufo`.
I'm the author of https://marketplace.visualstudio.com/items?itemName=shufo.vscode-blade-formatter
open-vsx account name is also `shufo`

Thanks.

**Comment by brianking** [comment]
Granted, thanks for your contributions. 

We encourage you to continue to publish new versions on open-vsx.org. As your extension has already been published by user open-vsx, we recommend you open an issue or PR at https://github.com/open-vsx/publish-extensions to remove it from their publish script.
