### ISSUE TITLE
Claiming namespace egomobile

### ISSUE THREAD

**Issue by mkloubertego** [EclipseFdn/open-vsx.org#775]
I am maintainer of [vscode-powertools](https://github.com/egomobile/vscode-powertools), currently published on https://open-vsx.org/extension/egomobile/vscode-powertools, in [egomobile](https://github.com/egomobile/) organization, where I am also one of the administrators.

I already created the namespace from CLI with my access token.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
