### ISSUE TITLE
Unpublish tabnine-vscode@9999.9999.9999

### ISSUE THREAD

**Issue by bilucodota** [EclipseFdn/open-vsx.org#776]
Hi guys,

My name is Amir, the owner of Tabnine organization.
We accidentally published tabnine-vscode extension with version 9999.9999.9999.

As a result, we're unable to release higher versions.
Would it be possible to unbpublish this version? as far as I understand there's no API for this process.

Thanks!

**Comment by akosyakov** [comment]
@spoenemann @brianking Could you try to unpublish it please? 🙏

**Comment by spoenemann** [comment]
Deleted. It might take a while until all caches are updated.

**Comment by bilucodota** [comment]
Appreciate it!
