### ISSUE TITLE
Claiming namespace CodeSee

### ISSUE THREAD

**Issue by shaneakr** [EclipseFdn/open-vsx.org#777]
I'm Shanea Leven co-founder of CodeSee and my team members created this CodeSee IDE extension in the codesee namespace.

**Comment by brianking** [comment]
Hi @shaneakr , where is the repository for CodeSee Review Maps? The link from the extension listing is 404.

**Comment by brianking** [comment]
@shaneakr A reminder ... see previous comment. Thanks!

**Comment by brianking** [comment]
@shaneakr I found more information at https://www.codesee.io/about, namespace granted, Thanks for your contributions.

However, there are 2 issues that need to be resolved. 

1. The repository url is incorrect for your extension.
2. Your extension is unlicensed. In order for it to stay on Open VSX, it needs to have a license (LICENSE.txt in the package). I'm not sure how that evaded our checks during uploading, I will investigate.
