### ISSUE TITLE
Claiming namespace slbtty

### ISSUE THREAD

**Issue by shenlebantongying** [EclipseFdn/open-vsx.org#778]
Hi, I recently published a syntax highligher to open-vsx.org for lisp family of languages, and I would like to claim the namespace for the extension to eliminate the warning.

The extension on open vsx:
https://open-vsx.org/extension/slbtty/Lisp-Syntax

The repo used
https://github.com/shenlebantongying/vscode-lisp-syntax

The `slbtty` is an abbreviation of my name **S**hen **L**e **B**an **T**ong **Y**ing with extra **T** for rhythm.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
