### ISSUE TITLE
Claiming namespace FelixIcaza

### ISSUE THREAD

**Issue by Felix-Icaza** [EclipseFdn/open-vsx.org#779]
I would like to reclaim the namespace in Open VSX Registry.

I recently published a fork of the Andromeda theme for VS Code.

The extension in VSX:
https://open-vsx.org/extension/FelixIcaza/andromeda

Repo:
https://github.com/Felix-Icaza/Andromeda

**Comment by brianking** [comment]
Granted, thanks for your contributions.
