### ISSUE TITLE
Claiming namespace MattiasBaake

### ISSUE THREAD

**Issue by bammab** [EclipseFdn/open-vsx.org#781]
Hi,

I have an extensions published in vscode marketplace.

https://marketplace.visualstudio.com/items?itemName=MattiasBaake.vscode-snippets-for-ansible

I want to also publish them in open-vsx, because of an open issue (https://github.com/bammab/vscode-snippets-for-ansible/issues/1).

Best regards

**Comment by brianking** [comment]
Granted, thanks for your contributions.
