### ISSUE TITLE
Claiming namespace karolis2011

### ISSUE THREAD

**Issue by Karolis2011** [EclipseFdn/open-vsx.org#782]
This namespace name references my username, there are no other contestants to this namespace, as I am sole contributor of it..
Currently I have published my fork of `platymuus.dm-langclient` found on MS VS Code marketplace. It is open sourced and licensed under GPL3 - https://github.com/SpaceManiac/vscode-dm-langclient
Why I have not asked SpaceManiac/platymuus to publish it? I got news that said author may be unreachable. So I published it under namespace that I would have full ownership.

If said author publishes `dm-langclient` to open-vsx I will unpublish / deprecate / remove my version.

Also I may in future develop extensions for various other reasons.

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by brianking** [comment]
@Karolis2011 , see #784. If you would like your version removed, please file a new issue for that.
