### ISSUE TITLE
Claiming namespace krvajalm

### ISSUE THREAD

**Issue by gnikit** [EclipseFdn/open-vsx.org#788]
I am one of the two devs and the maintainer for the Modern Fortran extension in VSCode https://github.com/krvajal/vscode-fortran-support.

Not sure if @krvajal has an activated open-vsx account but if he does could you add him as owner of the publisher too.

**Comment by brianking** [comment]
@kravjal does not have an activated account, so for now @gnikit I have made you the namespace owner.
