### ISSUE TITLE
Please unpublish the open-build-service-connector

### ISSUE THREAD

**Issue by dcermak** [EclipseFdn/open-vsx.org#789]
The [Open Build Service Connector](https://open-vsx.org/extension/SUSE/open-build-service-connector) extension is no longer maintained and should be removed from the open-vsx registry. However, I do not appear to be able to do that as the namespace owner. Could you perform this instead please?

**Comment by brianking** [comment]
All versions have been removed.

**Comment by dcermak** [comment]
Thanks!
