### ISSUE TITLE
Claiming namespace MarkMcCulloh

### ISSUE THREAD

**Issue by MarkMcCulloh** [EclipseFdn/open-vsx.org#791]
My github username is MarkMcCulloh

Currently published extension for vscode as a publisher with the same name, as well as on open VSX.
https://open-vsx.org/extension/MarkMcCulloh/vscode-projen
https://marketplace.visualstudio.com/items?itemName=MarkMcCulloh.vscode-projen

Here's the repo for that extension
https://github.com/MarkMcCulloh/vscode-projen

**Comment by brianking** [comment]
Granted, thanks for your contributions.
