### ISSUE TITLE
Service outtage - 2021-12-19 14:58 UTC

### ISSUE THREAD

**Issue by MrSimonEmms** [EclipseFdn/open-vsx.org#792]
There have been an alert raised that open-vsx.org went down. It came back up around 15:10 UTC.

It seems that neither http://open-vsx.org nor https://open-vsx.org were responding to requests. The IP address doesn't appear to have changed 198.41.30.195.

Issue tracked in [Gitpod Status](https://www.gitpodstatus.com/incidents/bhv99dsg3pj0)

![image](https://user-images.githubusercontent.com/275848/146680239-aec7ab19-0a06-4913-a55f-85ece8ea9d68.png)

**Comment by mbarbero** [comment]
There was a planned maintenance yesterday (https://www.eclipsestatus.io/incidents/4v4w8hn78h4q) that took longer than expected (https://www.eclipsestatus.io/incidents/r8vcdwb2xgpl). There is another one planned for next Sunday (https://www.eclipsestatus.io/incidents/98cpzg3vwrwn).
