### ISSUE TITLE
Claiming namespace saas-tool

### ISSUE THREAD

**Issue by ruistime** [EclipseFdn/open-vsx.org#796]
I would like to reclaim the namespace in Open VSX Registry.
Thanks！
The extension in VSX:
https://open-vsx.org/extension/saas-tool/saas-tool

The extension in Vscode market:
https://marketplace.visualstudio.com/items?itemName=saas-tool.saas-tool

**Comment by ruistime** [comment]
I would like to reclaim the namespace in Open VSX Registry.
Thanks！
The extension in VSX:
https://open-vsx.org/extension/saas-tool/saas-tool

The extension in Vscode market:
https://marketplace.visualstudio.com/items?itemName=saas-tool.saas-tool

**Comment by brianking** [comment]
@ruistime The repo http://dev.sankuai.com/code/repo-detail/sjst/fe.saas-tool/file/list is unreachable right now. Can you give more details on your relationship to the extension? Thanks.

**Comment by ruistime** [comment]
hi，briankin~

this vscode-extension belongs to https://github.com/ruistim and I provides a description in https://marketplace.visualstudio.com/items?itemName=saas-tool.saas-tool&ssr=false#overview 

![image](https://user-images.githubusercontent.com/12500291/146867142-315d569f-1338-44e8-8f76-6ad9e047eb42.png)


The repo http://dev.sankuai.com/code/repo-detail/sjst/fe.saas-tool/file/list is in my private gitlab right now；some code is private....  If necessary, I will upload to github。

What else do i need to do  for reclaiming the namespace in Open VSX Registry ?  thanks~

**Comment by ruistime** [comment]
hi，briankin~

this vscode-extension belongs to&nbsp;https://github.com/ruistim&nbsp;and I provides a description in&nbsp;https://marketplace.visualstudio.com/items?itemName=saas-tool.saas-tool&amp;ssr=false#overview



The repo&nbsp;http://dev.sankuai.com/code/repo-detail/sjst/fe.saas-tool/file/list&nbsp;is in my private gitlab right now；some code is private.... If necessary, I will upload to github。

we want reclaim the namespace , What else do i need to do ? thanks~







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EclipseFdn/open-vsx.org"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EclipseFdn/open-vsx.org] Claiming namespace saas-tool (Issue #796)





 
@ruistime The repo http://dev.sankuai.com/code/repo-detail/sjst/fe.saas-tool/file/list is unreachable right now. Can you give more details on your relationship to the extension? Thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brianking** [comment]
Granted, thanks for your contributions.

You can remove the explanation text in the README now!

Also if your extension is MIT license, please include it as a LICENSE.txt file similar to this file so that it is picked up correctly:
https://openvsxorg.blob.core.windows.net/resources/julialang/language-julia/1.5.9/LICENSE.txt
