### ISSUE TITLE
Remove entepe85.gitlens

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/open-vsx.org#799]
Per agreement with @entepe85, [entepe85.gitlens](https://open-vsx.org/extension/entepe85/gitlens) will be removed as it is superseded by the original extension [eamodio.gitlens](https://open-vsx.org/extension/eamodio/gitlens) which is now more up-to-date.

**Comment by entepe85** [comment]
Yes, please go ahead and remove [entepe85.gitlens](https://open-vsx.org/extension/entepe85/gitlens).

**Comment by brianking** [comment]
This is done.
