### ISSUE TITLE
Remove snowqm-extension

### ISSUE THREAD

**Issue by orellabac** [EclipseFdn/open-vsx.org#801]
Hi sometime ago, I published this extension:

https://open-vsx.org/extension/orellabacCR/snowqm-extension

It has become obsolete, and it is very buggy I would like to remove it as it is causing issues.

I also would like to remove https://open-vsx.org/extension/orellabacCR/snowconvert-extension-pack

**Comment by brianking** [comment]
orellabacCR.snowqm-extension and orellabacCR.snowconvert-extension-pack have been removed.
