### ISSUE TITLE
Claiming namespace vscode-wakatime-gitpods

### ISSUE THREAD

**Issue by alanhamlett** [EclipseFdn/open-vsx.org#802]
[vscode-wakatime-gitpods](https://open-vsx.org/extension/gengjiawen/vscode-wakatime-gitpods) is a duplicate of the [official extension](https://open-vsx.org/extension/WakaTime/vscode-wakatime).

**Comment by brianking** [comment]
@alanhamlett Is your intention to maintain both with releases, kill one of them off, or something else?

**Comment by alanhamlett** [comment]
It's confusing to have two versions, so I'll kill off one and keep the other maintained and up-to-date.

**Comment by gengjiawen** [comment]
> @gengjiawen Are you ok with us taking down https://open-vsx.org/extension/gengjiawen/vscode-wakatime-gitpods as the original extension is now published and maintained at a later version?

Sure

**Comment by brianking** [comment]
Issue #824 opened to remove gengjiawen.vscode-wakatime-gitpods

**Comment by brianking** [comment]
No further action needed here.
