### ISSUE TITLE
Claiming namespace mintlify

### ISSUE THREAD

**Issue by hanywang2** [EclipseFdn/open-vsx.org#805]
- My name (Han) is on the landing page of [mintlify.com](https://mintlify.com/)
- You can find my profile as one of the two contributors of the Mintlify [github repo](https://github.com/mintlify)
- I am the co-founder of Mintlify on [Crunchbase](https://www.crunchbase.com/person/han-wang-5fa2)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
