### ISSUE TITLE
Claiming namespace - LeonardSSH

### ISSUE THREAD

**Issue by LeonardSSH** [EclipseFdn/open-vsx.org#808]
https://github.com/LeonardSSH/vscord

I've already claimed a namespace https://github.com/EclipseFdn/open-vsx.org/issues/732, but I need another one to be able to use the same publisher name for vscode marketplace and OpenVSX

Can the extension be moved to the new namespace? 😊

**Comment by brianking** [comment]
Hi @LeonardSSH, thanks for your contributions.

We can't move extensions or rename namespaces. I suggest you create the new namespace and start publishing to that, and then open a separate issue to remove the extension from the old namespace.

**Comment by LeonardSSH** [comment]
The extension is already automatically published in the LeonardSSH namespace, I'll create a separate issue to delete the vscord-extension namespace and its attached extension.

**Comment by brianking** [comment]
Namespace ownership granted, thanks for your contributions.
