### ISSUE TITLE
Claiming namespace yuyichao

### ISSUE THREAD

**Issue by yuyichao** [EclipseFdn/open-vsx.org#811]
I am yuyichao and I just created this namespace to publish the digitaljs extension.

**Comment by yuyichao** [comment]
I had some issues publishing to open-vsx (time out though the publication apparently went through anyway....) but now everything is up and here are the links,

1. Github repo: https://github.com/yuyichao/digitaljs_code
2. MS market place: https://marketplace.visualstudio.com/items?itemName=yuyichao.digitaljs
3. Open-vsx: https://open-vsx.org/extension/yuyichao/digitaljs

**Comment by brianking** [comment]
Granted, thanks for your contributions.
