### ISSUE TITLE
Remove Extension from namespace - vscord-extension

### ISSUE THREAD

**Issue by LeonardSSH** [EclipseFdn/open-vsx.org#812]
I want the extension [`vscord`](https://open-vsx.org/extension/vscord-extension/vscord) to be deleted from the `vscord-extension` namespace. 
Also, if the namespace can be deleted as well, it will not be used after the extension is migrated to the new namespace.

Related issue: https://github.com/EclipseFdn/open-vsx.org/issues/808

**Comment by brianking** [comment]
vscord-extension.vscord has been removed.
