### ISSUE TITLE
Claiming namespace halcyontechltd

### ISSUE THREAD

**Issue by worksofliam** [EclipseFdn/open-vsx.org#813]
Want to publish to openvsx and my business, Halcyon Tech, uses halcyontechltd as the publisher.

https://github.com/halcyon-tech/vscode-ibmi/blob/master/package.json#L19

**Comment by worksofliam** [comment]
Bump

**Comment by brianking** [comment]
Granted, thanks for your contributions. 

I notice your extensions have already been published by user @open-vsx. If you intend to publish moving forward, please open an issue or PR at https://github.com/open-vsx/publish-extensions to remove it from their publishing script.
