### ISSUE TITLE
Remove `matklad.rust-analyzer` until 0.2.853

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#814]
The [rust-analyzer](https://open-vsx.org/extension/matklad/rust-analyzer) extension is having some troubles because of [#336](https://github.com/eclipse/openvsx/issues/336) - the build and packaging step succeed, but the extension doesn’t work in practice. Can we please unpublish all version until [0.2.853](https://open-vsx.org/extension/matklad/rust-analyzer/0.2.853) (this is the last version that works)? [I removed it](https://github.com/open-vsx/publish-extensions/commit/3413138234d47cc63f49aa561fae3ccba84938ca) from the [publish-extensions](https://github.com/open-vsx/publish-extensions) repository so it won’t automatically publish the non-working versions. They seem to be willing to publish the extension directly after the aforementioned issue is addressed.

**Comment by lnicola** [comment]
Note that we've also started submitting pre-release versions (see #386). I don't expect `publish-extensions` to work very well with those (even the Code Marketplace has issues), so we do want to set up an Open VSX account and take care of publishing ourselves.

**Comment by brianking** [comment]
To clarify, do you want all versions removed that were published **before** 0.2.853 or **after**?

**Comment by filiptronicek** [comment]
> To clarify, do you want all versions removed that were published before 0.2.853 or after?

@brianking after: all versions worked until `0.2.867`, which broke on OpenVSX. This means we want to remove `0.2.890`, `0.2.880` and `0.2.867`.

**Comment by brianking** [comment]
This is done, kind of. It seems to have caused another issue, see #816. Please don't upload a new version until we figure out what is going on.

**Comment by brianking** [comment]
The error has been fixed and this is now done and ready.
