### ISSUE TITLE
Claiming namespace JFrog

### ISSUE THREAD

**Issue by jfrog-ecosystem** [EclipseFdn/open-vsx.org#825]
We'd like to claim the JFrog namespace to allow publishing the [JFrog VS-Code extension](https://github.com/jfrog/jfrog-vscode-extension) to the open VSX registry.

Thanks in advance.

**Comment by brianking** [comment]
@jfrog-ecosystem It looks like you are a service account! We don't grant namespace ownership to service or bot accounts. Would you like to nominate an individual?

/cc @RobiNino

**Comment by eyalbe4** [comment]
Hey @brianking - 
I can be the nominated individual. I belong to the JFrog GotHub organization (the same organization of the @jfrog-ecosystem account).
Thanks!

**Comment by jfrog-ecosystem** [comment]
@brianking please grant ownership to @eyalbe4.
Thanks!

**Comment by brianking** [comment]
@eyalbe4 In order for me to grant this to you, you will need to log into open-vsx.org for the first time.

**Comment by eyalbe4** [comment]
Thanks @brianking. Done.
Please let me know if anything else is needed.

**Comment by brianking** [comment]
@eyalbe4 You are now namespace owner.
