### ISSUE TITLE
Claiming namespace RoweWilsonFrederiskHolme

### ISSUE THREAD

**Issue by Frederisk** [EclipseFdn/open-vsx.org#828]
To publish my [VSMarket Extension: Wikitext](https://marketplace.visualstudio.com/items?itemName=RoweWilsonFrederiskHolme.wikitext). Its repository is [here](https://github.com/Frederisk/Wikitext-VSCode-Extension).

**Comment by brianking** [comment]
Granted, thanks for your contributions.
