### ISSUE TITLE
Claiming namespace Trelent

### ISSUE THREAD

**Issue by calum-bird** [EclipseFdn/open-vsx.org#830]
- I am a co-founder and the CEO at Trelent Inc. as listed on our [LinkedIn Page](https://linkedin.com/company/trelent), and our [Crunchbase profile](https://www.crunchbase.com/organization/trelent).
- I am a public member of the [Trelent Github Organization](https://github.com/trelent)
- The email tied to my GitHub account is on our primary domain, calum@trelent.net
- My name is listed as a director of Trelent Inc.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
