### ISSUE TITLE
Claiming namespace Autodesk

### ISSUE THREAD

**Issue by EngOpsNeumann** [EclipseFdn/open-vsx.org#834]
We will be publishing more extensions for Autodesk hence this request to reserve the namespace - Autodesk.

**Comment by brianking** [comment]
@EngOpsNeumann I see your GitHub account is pretty new. Can you say, what is your relationship with Autodesk and with this extensions? Thanks.

**Comment by EngOpsNeumann** [comment]
I am the Build Engineer working in Autodesk, Inc. This extension is developed by us.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
