### ISSUE TITLE
Claiming namespace IBMBlockchain

### ISSUE THREAD

**Issue by jt-nti** [EclipseFdn/open-vsx.org#838]
Investigating publishing to Open VSX along with @mbwhite
It would also be useful to add @ibmblockchaindev as an owner

See IBM-Blockchain/blockchain-vscode-extension#3085

**Comment by brianking** [comment]
@jt-nti I can add you or @mbwhite as the owner, as bot or service accounts can't be used for that purpose (they can be added as contributors by the owner after).

Let me know.

**Comment by brianking** [comment]
@jt-nti You are now the namespace owner. Thanks for your contributions.
