### ISSUE TITLE
Claiming namespace espressif

### ISSUE THREAD

**Issue by kolipakakondal** [EclipseFdn/open-vsx.org#841]
I am the engineering manager for Espressif IDEs and manage esp-idf VSCode extension development. We would like to publish our esp-idf VSCode extension to the open-vsx.org also

Here is our repo https://github.com/espressif/vscode-esp-idf-extension

We have already published this in the VSCode marketplace. Please check this here https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension

Let us know if you need more details on this.

Thank you

**Comment by brianking** [comment]
Granted, looking forward to your contributions.

**Comment by kolipakakondal** [comment]
Thanks @brianking
