### ISSUE TITLE
Claiming namespace itspngu

### ISSUE THREAD

**Issue by itspngu** [EclipseFdn/open-vsx.org#843]
It's my Github username and I published an extension on Open VSX as well as the VScode Marketplace:

- https://open-vsx.org/extension/itspngu/jsonnet-format
- https://marketplace.visualstudio.com/items?itemName=itspngu.jsonnet-format

I had some trouble figuring out the setup so I'd also like to ask for (instructions for) the removal of https://open-vsx.org/extension/itspngu/jsonnet-formatter, can't find a delete/unpublish option on the website and in the `ovsx` cli tool. I had to rename the extension because MS'es marketplace wouldn't let me re-publish it under the same name after removing it in an effort to get things working.

**Comment by brianking** [comment]
Namespace ownership has been granted, thanks for your contributions.

To have extensions removed, please file separate issues and specify which versions should be removed.
