### ISSUE TITLE
Claiming namespace isg-cnc

### ISSUE THREAD

**Issue by isg-stuttgart-github** [EclipseFdn/open-vsx.org#844]
change from my personal open-vsx to the oranization open-vsx account.
We have now more than me for developing extensions for isg-cnc.

**Comment by brianking** [comment]
@isg-stuttgart-github @andreashafner-isg Per policy, namespace ownership can only be granted to personal accounts. Service and bot accounts can be added as contributors.

**Comment by isg-stuttgart-github** [comment]
> @isg-stuttgart-github @andreashafner-isg Per policy, namespace ownership can only be granted to personal accounts. Service and bot accounts can be added as contributors.

thank you.
