### ISSUE TITLE
Claiming namespace nwolverson

### ISSUE THREAD

**Issue by nwolverson** [EclipseFdn/open-vsx.org#845]
Namespace corresponding with my username @nwolverson & matching the namespace used on vscode marketplace to publish my extensions https://marketplace.visualstudio.com/items?itemName=nwolverson.ide-purescript

Failed to create the namespace showing as already created, not sure if this was imported from the other registry or how this happened

**Comment by brianking** [comment]
Granted, looking forward to your contributions.

We used to seed the registry with extensions (license permitting), depending on demand, so perhaps your namespace was added with that intention. However, no extension has been published yet under the namespace.

See:
https://github.com/open-vsx/publish-extensions/search?q=nwolverson
