### ISSUE TITLE
Claiming namespace openscript

### ISSUE THREAD

**Issue by openscript** [EclipseFdn/open-vsx.org#848]
Recently I forked the extension [i18n-ally](https://open-vsx.org/extension/lokalise/i18n-ally), because development of this great plugin slowed down and has stopped completely for a few months now.

At my company `openscript Ltd.` we depend on this extension in numerous of projects. The [fork is already pushed to Microsofts Marketplace](https://marketplace.visualstudio.com/items?itemName=openscript.i18n-ally-fork). To publish it at open-vsx.org I would like to claim the namespace `openscript`. We would be happy to do so, because open-vsx.org and openscript have a similar name and share many values, especially about developing free and open software.

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
