### ISSUE TITLE
Claiming namespace silofy

### ISSUE THREAD

**Issue by silofy** [EclipseFdn/open-vsx.org#849]
I own the same in Microsoft visual studio to publish my theme.
https://open-vsx.org/extension/silofy/hackthebox
https://marketplace.visualstudio.com/items?itemName=silofy.hackthebox

cheers

**Comment by brianking** [comment]
@silofy Is this a personal Github account or a service / company account?

**Comment by silofy** [comment]
Hi Brian, this is a personal Github account. The theme was created for the company Hack The Box. I currently work there.

Cheers.

**Comment by brianking** [comment]
Granted, thanks for your contributions.
