### ISSUE TITLE
Delete all versions of obsolete extension itspngu/jsonnet-formatter

### ISSUE THREAD

**Issue by itspngu** [EclipseFdn/open-vsx.org#852]
I had trouble setting up a combined workflow for publishing to both Open VSX as well as the VScode Marketplace, and in an unfortunate chain of events ended up having to rename the package from "jsonnet-formatter" to "jsonnet-format":

- https://open-vsx.org/extension/itspngu/jsonnet-formatter
- https://open-vsx.org/extension/itspngu/jsonnet-format

To avoid confusion and clutter, I'd like to ask for removal of jsonnet-formatter, keeping jsonnet-format, following the advice given in https://github.com/EclipseFdn/open-vsx.org/issues/843#issuecomment-1021100422. Thank you.

**Comment by brianking** [comment]
This is done.
