### ISSUE TITLE
Claiming namespace lockular

### ISSUE THREAD

**Issue by gmawdo** [EclipseFdn/open-vsx.org#853]
Re: Authority to claim this namespace:
My Name is Gary Mawdsley - see lockular.com team
I am CEO of Lockular Ltd in the UK
Lockular Ltd has trademarked the word lockular in the US and EU
Lockular Ltd owns the domains lockular.com, lockular.io and lockular.ai

Thanks

**Comment by brianking** [comment]
Granted, looking forward to your contributions.
