### ISSUE TITLE
Publisher agreement question 

### ISSUE THREAD

**Issue by rangav** [EclipseFdn/open-vsx.org#856]
```
**No Compensation**. You expressly acknowledge that neither Eclipse nor any licensee or
end-user of any of your Offerings published on the Registry shall be required to provide
you with any compensation for the distribution or use of your Offering as made available
on the Registry"
```

Should we only publish free extensions? not any paid extensions where users are required to pay to use the extension?

Also can we publish non open-source extensions?

can you please clarify above

**Comment by brianking** [comment]
Hi!

> Should we only publish free extensions? not any paid extensions where users are required to pay to use the extension?

I will refer you to:
https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-13

Commercial extensions are not excluded, however we do not facilitate any transactions on the site. 
 
> Also can we publish non open-source extensions?

Yes. See:
https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-10

If you have any further questions, you can followup via email as outlined in the last question in the FAQ.

**Comment by rangav** [comment]
Thanks for the help.
