### ISSUE TITLE
Claiming namespace rangav

### ISSUE THREAD

**Issue by thunderclient** [EclipseFdn/open-vsx.org#859]
Hi I am owner of Thunder Client extension. Can you please accept this namespace

My extension support page
https://github.com/rangav/thunder-client-support

**Comment by brianking** [comment]
As @thunderclient looks like a service account, can I grant namespace ownership to @rangav (an individual account). We do not grant ownership to service or bot accounts, but they can still be a contributor and publish.

**Comment by thunderclient** [comment]
I dont want to login with my personal github account rangav, so i created new account @thunderclient to publish to open-vsx.

I never login with my personal account for privacy and security

**Comment by rangav** [comment]
Hi i am commenting from personal account to prove i am owner of both accounts., Please grant `rangav` namespace

**Comment by rangav** [comment]
Hi any update on this?, how long will it take to namespace?

**Comment by brianking** [comment]
@rangav In order for us to grant you namespace ownership, you will need to log into open-vsx.org for the first time.

**Comment by rangav** [comment]
I already logged with @thunderclient github account, that is the account I want to use for publishing

**Comment by rangav** [comment]
Hi @brianking not sure when you will approve the namespace.

Can you at least publish this extension using `open-vsx` account

https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

**Comment by brianking** [comment]
The thunderclient/README.md has reassured me that it is not a service account, but linked to an individual. So namespace ownership has been granted. I'm looking forward to your contributions.

**Comment by rangav** [comment]
Thanks @brianking
