### ISSUE TITLE
Claiming namespace wicked-labs

### ISSUE THREAD

**Issue by michael-andreuzza** [EclipseFdn/open-vsx.org#860]
Hey, I would like to claim the ownership of this namespace https://open-vsx.org/extension/wicked-labs/wvsc-serendipity.

I am the developer and designer of it to prove it you can navigate to our main site https://apesoflondon.design/ or look me up on twitter. @mike_andreuzza o simply google my name it will be associated with Serendipity. Also, feel free to checkout the launch on producthunt https://www.producthunt.com/posts/serendipity-3

thank you for your help.
/Mike

**Comment by brianking** [comment]
Granted, thanks for your contributions.

**Comment by michael-andreuzza** [comment]
> Granted, thanks for your contributions.

Thank you so much, Brian. 

Have a great day.

/Mike
