### ISSUE TITLE
Claiming namespace DamienHubleur

### ISSUE THREAD

**Issue by dams333** [EclipseFdn/open-vsx.org#876]
I created this space with my own name to upload my extension Cpp Class Generator (42 C++ Orthodox Canonical Form Class Generator) as requested by someone on the repository of my extension (https://github.com/dams333/CPP_Class_Generator/issues/1)

My namespace: DamienHubleur
My github name: dams333
My account on open-vsx: dams333 (linked with GitHub)

**Comment by brianking** [comment]
Granted, thanks for your contributions.
