### ISSUE TITLE
Claiming namespace stateful

### ISSUE THREAD

**Issue by christian-bromann** [EclipseFdn/open-vsx.org#877]
Hey,

I would like to claim `stateful` as namespace and at the same time transition our current extension `marquee` to this namespace. `marquee` is currently part of the `activecove` namespace. It would be great if it would be possible to transition this extension without any issues for current end users.

@sourishkrout has claimed the `activecove` namespace in #399. He will approve this operation once this issue is posted.

**Comment by christian-bromann** [comment]
It seems that Stateful was claimed in #827. However would it be possible to do the transition from `activecove.marquee` to `stateful.marquee`?

**Comment by kineticsquid** [comment]
@christian-bromann I have transitioned `activecove.marquee` to `stateful.marquee`.

**Comment by christian-bromann** [comment]
Awesome, thank you!

**Comment by christian-bromann** [comment]
@kineticsquid it seems like this has broken some urls, e.g.: here: https://open-vsx.org/extension/stateful/marquee

**Comment by kineticsquid** [comment]
Shoot. Tracking this new issue in https://github.com/eclipse/openvsx/issues/690.

**Comment by kineticsquid** [comment]
Decided to re-open this because we may need to take action here once we update the namespace code

**Comment by kineticsquid** [comment]
@amvanbaren Do we need some DB surgery here?

**Comment by amvanbaren** [comment]
@kineticsquid I can't help you with DB data related issues. You should ask the Eclipse helpdesk.

**Comment by kineticsquid** [comment]
@amvanbaren Yes, they'll need to take the action, but we'll need to tell them what to do. Do we have the information we need to instruct them. Or will they need to run some queries to determine the state of the tables?

**Comment by amvanbaren** [comment]
> Or will they need to run some queries to determine the state of the tables? 

Yes.

**Comment by degrammer** [comment]
Hello @kineticsquid , it seems after applying these changes, we are now seeing two duplicated namespaces. This is breaking our publishing to ovsx, can you please help us?  cc @christian-bromann 

![image (1)](https://github.com/EclipseFdn/open-vsx.org/assets/4001529/9c46b8af-150e-4277-8115-176d4d1f1498)

**Comment by kineticsquid** [comment]
@amvanbaren We'll need your help with this one. Did we attempt some DB surgery that resulted in the duplicate namespaces?

**Comment by amvanbaren** [comment]
@kineticsquid No, not that I'm aware of. Furthermore there's a case-insensitive unique constraint on the namespace name, so this isn't possible on the database level.

**Comment by sourishkrout** [comment]
> @kineticsquid No, not that I'm aware of. Furthermore there's a case-insensitive unique constraint on the namespace name, so this isn't possible on the database level.

Thanks for checking into it @kineticsquid & @amvanbaren. Any idea why https://open-vsx.org/extension/stateful/marquee is no longer working and we can no longer publish `stateful.runme`? On the surface, it did suggest there maybe be a collision.

**Comment by sourishkrout** [comment]
Based on the finding that our trouble is likely a namespace collision (please see https://github.com/eclipse/openvsx/issues/731#issuecomment-1554727546), @kineticsquid & @amvanbaren, what's the best/most straightforward way to resolve this? We'd be comfortable republishing to a clean `stateful` namespace at this point if that's easier. However, in one way or another, the `stateful` namespace needs unclobbering.

**Comment by amvanbaren** [comment]
When I go to https://open-vsx.org/namespace/stateful it works instead of getting an error as mentioned in https://github.com/eclipse/openvsx/issues/731#issuecomment-1554727546. When I query for stateful https://open-vsx.org/api/-/query?namespaceName=stateful, I don't get any duplicates (please note that runme has multiple entries, one for each target platform). So, I still don't know what's going on here.

**Comment by kineticsquid** [comment]
@amvanbaren Assuming it's OK with @sourishkrout any reason not to un-publish one of more of these extensions (losing the history and ratings of course) and then have them re-published?

**Comment by sourishkrout** [comment]
At this point, I'm ok with un-publishing/deletion or anything it would take to get the unique handles `stateful.runme`, `stateful.*` back working. Even if that means starting over on "history".

Is unpublishing something you would do, @kineticsquid?

**Comment by amvanbaren** [comment]
@kineticsquid No, go ahead. Just keep in mind that delete operations run async, so you can't re-publish right away.

**Comment by kineticsquid** [comment]
@sourishkrout Commencing. I'll let you know when we're ready for you to re-publish.

**Comment by sourishkrout** [comment]
> @sourishkrout @christian-bromann I've unpublished all extensions on this namespace. I've attempted both rename the workspace and remove you two as owners. In both cases those requests failed because the namespace appears corrupted. We're going to have to employ a bit of DB surgery. Sorry this is taking so long.

Thanks for the update. We appreciate it. 🤞 DB surgery will be successful.

**Comment by sourishkrout** [comment]
> > @sourishkrout @christian-bromann I've unpublished all extensions on this namespace. I've attempted both rename the workspace and remove you two as owners. In both cases those requests failed because the namespace appears corrupted. We're going to have to employ a bit of DB surgery. Sorry this is taking so long.
> 
> Thanks for the update. We appreciate it. 🤞 DB surgery will be successful.

Hi @kineticsquid, do you have any updates on this? I do see two namespaces in my account, assuming db surgery hasn't happened yet. Thank you!

**Comment by sourishkrout** [comment]
> > > @sourishkrout @christian-bromann I've unpublished all extensions on this namespace. I've attempted both rename the workspace and remove you two as owners. In both cases those requests failed because the namespace appears corrupted. We're going to have to employ a bit of DB surgery. Sorry this is taking so long.
> > 
> > 
> > Thanks for the update. We appreciate it. 🤞 DB surgery will be successful.
> 
> Hi @kineticsquid, do you have any updates on this? I do see two namespaces in my account, assuming db surgery hasn't happened yet. Thank you!

Hey @kineticsquid. Any news on this item? Thank you!

**Comment by kineticsquid** [comment]
@sourishkrout Sorry for the delay in getting back to this.

@amvanbaren Adding your SQL here:
```
SELECT nm.*
FROM namespace_membership nm
JOIN namespace n ON n.id = nm.namespace
WHERE n.name = 'stateful';

SELECT e.*
FROM extension e
JOIN namespace n ON n.id = e.namespace_id
WHERE n.name = 'stateful';
```

It also occurred to me that namespaces show up in `admin_statistics_top_namespace_extension_versions` and  `admin_statistics_top_namespace_extensions` tables. But those are the names of the namespaces and not the IDs, so deleting a namespace that happens to appear in on of these stats tables shouldn't corrupt the statistics. Agree?

Can you wrap these two `SELECT` statements in `DELETE` statements; my SQL is insufficient. Then we can hand off to IT.

**Comment by sourishkrout** [comment]
> @sourishkrout Sorry for the delay in getting back to this.

Thanks for getting back. I'm looking forward to getting this resolved.

**Comment by amvanbaren** [comment]
@sourishkrout The @eclipsewebmaster ran the select queries against the production database and everything looks fine. It looks like [V1_39__Fix_Unique_Constraints.sql](https://github.com/eclipse/openvsx/blob/master/server/src/main/resources/db/migration/V1_39__Fix_Unique_Constraints.sql) cleaned it up.
Can you try to publish an extension to the stateful namespace?

**Comment by kineticsquid** [comment]
@amvanbaren Based on your experience, given a namespace, how common is the problem this SQL resolves (or how broad a solution is it)? I'm asking because does it make sense to add this to the admin panel in some form so admins like me can administer it.

**Comment by sourishkrout** [comment]
> @sourishkrout The @eclipsewebmaster ran the select queries against the production database and everything looks fine. It looks like [V1_39__Fix_Unique_Constraints.sql](https://github.com/eclipse/openvsx/blob/master/server/src/main/resources/db/migration/V1_39__Fix_Unique_Constraints.sql) cleaned it up. Can you try to publish an extension to the stateful namespace?

It looks like it's working @kineticsquid & @amvanbaren. I just published https://open-vsx.org/extension/stateful/runme and verified I can install & use it inside the IDE. Thank you!!

**Comment by amvanbaren** [comment]
@kineticsquid I think this was caused by the namespace change, which is new functionality. The [V1_39__Fix_Unique_Constraints.sql](https://github.com/eclipse/openvsx/blob/master/server/src/main/resources/db/migration/V1_39__Fix_Unique_Constraints.sql) script should prevent corrupting the database going forward.

**Comment by kineticsquid** [comment]
@amvanbaren Understood. So I think the answer to my question in https://github.com/EclipseFdn/open-vsx.org/issues/877#issuecomment-1642203044 is 'No'.
