### ISSUE TITLE
Claiming namespace AquaSecurityOfficial

### ISSUE THREAD

**Issue by owenrumney** [EclipseFdn/open-vsx.org#881]
I am an employee of AquaSecurity (owen.rumney@aquasec.com), as evidenced [here](https://github.com/orgs/aquasecurity/people?query=owen) and a contributor of this extension as evidenced [here](https://github.com/aquasecurity/trivy-vscode-extension/graphs/contributors)

**Comment by kineticsquid** [comment]
Thanks @owenrumney, you're good to go!
