### ISSUE TITLE
Claiming namespace JustBrenny

### ISSUE THREAD

**Issue by TheBrenny** [EclipseFdn/open-vsx.org#886]
I own the domain name justbrenny.me, and the code for the hosted application is found in one of my repos. I can create a route for you to hit if necessary.

I also own the [Hero Heroku](https://marketplace.visualstudio.com/items?itemName=JustBrenny.hero-heroku) extension on the VSCode Extension Marketplace under the JustBrenny namespace.

**Comment by kineticsquid** [comment]
@TheBrenny ownership granted, thanks!
