### ISSUE TITLE
Claiming namespace keesschollaart

### ISSUE THREAD

**Issue by keesschollaart81** [EclipseFdn/open-vsx.org#887]
As one of the maintainers of the VS Code Extension for Home Assistant, I would like to be able publish our (verified) extension much like we do for the MS Marketplace

Preferred namespace: keesschollaart

Traceback: https://github.com/keesschollaart81/vscode-home-assistant/pull/1918

**Comment by kineticsquid** [comment]
@keesschollaart81 Thanks, you're good to go!
