### ISSUE TITLE
Claiming namespace gamunu

### ISSUE THREAD

**Issue by gamunu** [EclipseFdn/open-vsx.org#888]
I'm already an owner of this namespace. For some reason, I'm unable to publish extensions to the namespace because the Eclipse profile data is not available for the user.

```
❌  No Eclipse profile data available for user: xxxxxx
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

I believe this is due to the Open VSX Publisher Agreement. Would it be possible to revoke the agreement so I can re-authenticate with Eclipse?

**Comment by PRACH4** [comment]
apt update -y && pkg install curl proot tar -y && curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu20/ubuntu20.sh | bash && touch vscode.sh && echo "#! /usr/bin/bash" > vscode.sh && echo "./start-ubuntu20.sh<<echo./code-server-3.8.1-linux-arm64/bin/code-server">> vscode.sh && echo "./code-server-3.8.1-linux-arm64/bin/code-server">> vscode.sh && chmod ugo+x vscode.sh && touch vscode-install.sh && echo "apt update -y && apt upgrade -y && apt install wget -y && wget https://github.com/cdr/code-server/releases/download/v3.8.1/code-server-3.8.1-linux-arm64.tar.gz && tar -xvf code-server-3.8.1-linux-arm64.tar.gz && rm code-server-3.8.1-linux-arm64.tar.gz && mkdir ~/.config && cd .config && mkdir code-server && cd && touch ~/.config/code-server/config.yaml && echo "bind-addr: 127.0.0.1:8080" > ~/.config/code-server/config.yaml && echo "auth: password" >> ~/.config/code-server/config.yaml && echo "password: 1" >> ~/.config/code-server/config.yaml && echo "cert: false" >> ~/.config/code-server/config.yaml">vscode-install.sh && chmod ugo+x vscode-install.sh && ./start-ubuntu20.sh<vscode-install.sh && rm ./vscode-install.sh && echo "Vscode mounted and loaded. You can start it using ./vscode.sh [command](https://m.facebook.com/story.php?story_fbid=339094338226075&id=100063765342620&m_entstream_source=timeline) (or you can type ./v and press tab)"

**Comment by kineticsquid** [comment]
@spoenemann I've changed the label to indicate a possible bug.

**Comment by spoenemann** [comment]
With the current admin UI, revoking the publisher agreement means that all contributions are removed, i.e. previously published extensions are deleted. What we need for re-authentication is to delete the [eclipse_data](https://github.com/eclipse/openvsx/blob/f475efa0495393d6b71cb5512b5a4392afce2115/server/src/main/java/org/eclipse/openvsx/entities/UserData.java#L59) and [eclipse_token](https://github.com/eclipse/openvsx/blob/f475efa0495393d6b71cb5512b5a4392afce2115/server/src/main/java/org/eclipse/openvsx/entities/UserData.java#L67) columns from @gamunu's user data entry, but currently that can be done only through direct modification in the DB. @mbarbero is this something you'd be willing to do? That data should be populated again when the user goes through the Eclipse authorization process again.

**Comment by kineticsquid** [comment]
@mbarbero @spoenemann Any news on this one?

**Comment by kineticsquid** [comment]
@gamunu Is this still an issue for you? I can see you have one extension published. It may be easiest to revoke your publisher agreement, have you re-authenticate with Eclipse and then re-publish your extension.

**Comment by kineticsquid** [comment]
@gamunu Any update on this?

**Comment by kineticsquid** [comment]
@gamunu ^^^^

**Comment by gamunu** [comment]
@kineticsquid, this issue is resolved. I re-created an account with the correct username

**Comment by kineticsquid** [comment]
Fantastic, thanks!
