### ISSUE TITLE
Claiming namespace kodetech

### ISSUE THREAD

**Issue by RobDangerous** [EclipseFdn/open-vsx.org#895]
I created and maintain all extensions published for vscode using the publisher-name "kodetech", it's everything you can find in github.com/Kode that starts with "vscode-". You can see me in the people-list at https://github.com/Kode - and nobody else. Some of those extensions are already auto-published to open-vsx by the open-vsx-user.

**Comment by RobDangerous** [comment]
The auto-publishing came in via https://github.com/open-vsx/publish-extensions/pull/133

**Comment by kineticsquid** [comment]
@RobDangerous Can you create an issue at https://github.com/open-vsx/publish-extensions to remove your extensions in this namespace from auto publishing. Post that issue here. Once that's complete, we can grant the name space.

**Comment by RobDangerous** [comment]
All right, I created a PR to hopefully make this as easy as possible: https://github.com/open-vsx/publish-extensions/pull/563

**Comment by RobDangerous** [comment]
And it's merged.

**Comment by kineticsquid** [comment]
Thanks for PR, you're good to go!
