### ISSUE TITLE
Claiming namespace toroxx

### ISSUE THREAD

**Issue by toroxx** [EclipseFdn/open-vsx.org#897]
Since I planned to publish my theme (tx-neon) to open-vsx.
I'd like to claim the namespace "toroxx". I also owned the same namespace in Microsoft Azure publisher.

vs marketplace: https://marketplace.visualstudio.com/items?itemName=toroxx.tx-neon
Github: https://github.com/toroxx/tx-neon

**Comment by kineticsquid** [comment]
@toroxx Granted!
