### ISSUE TITLE
Claiming namespace tremorproject

### ISSUE THREAD

**Issue by darach** [EclipseFdn/open-vsx.org#900]
Fine folk of open-vsx and the eclipse foundation,

The [tremor](https://www.tremor.rs) is an early stage sandbox CNCF project that originated
at Wayfair. We maintain vscode extensions that adds syntax highlighting and language server
protocol support for the embedded DSLs in the tremor runtime.

The [language server](https://github.com/tremor-rs/tremor-language-server) and the vscode [extension](https://github.com/tremor-rs/tremor-vscode) are also open source as is the tremor [runtime](https://github.com/tremor-rs/tremor-runtime).

We would like to publish these extensions into Open VSX so that they are available in Open VSX
compatible environments such as gitpod.

We would like to claim ownership of the `tremorproject` namespace which we also use in the
vscode extension registry so that tremor maintainers and contributors can publish updates and
new extensions into this namespace looking forward.

Thank you in advance!

On behalf of the tremor project maintainers,

Darach.

**Comment by kineticsquid** [comment]
@darach Good to have you!
