### ISSUE TITLE
Claiming namespace astro-build

### ISSUE THREAD

**Issue by matthewp** [EclipseFdn/open-vsx.org#901]
I'm part of the Astro core team: https://github.com/orgs/withastro/teams/maintainers-core/members, and publish the VSCode extension: https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode .

**Comment by kineticsquid** [comment]
@matthewp That first link doesn't resolve. Regardless, I found you in the commits. You're good to go.

**Comment by matthewp** [comment]
Thank you. I don't see this namespace showing up at https://open-vsx.org/user-settings/namespaces, is there something else I should do?

**Comment by kineticsquid** [comment]
@matthewp This was my mistake. After researching this, I granted ownership but missed that the ownership was pending to `boehs` and not you. I'll fix this, but first and in an effort to minimize churn, are you familiar with this ID?

**Comment by matthewp** [comment]
I believe that is @boehs who is a member of the Astro community. Evan, is it ok if this is transfer to me so that we can start auto-publishing the extension to OpenVSX?

**Comment by boehs** [comment]
Yes, I'm super sorry, I must have accidentally done it when messing around with CI, I will transfer it right away

**Comment by boehs** [comment]
@matthewp, please check again, I have made you an owner (I can't figure out how to make you *the* owner, just one of them

**Comment by boehs** [comment]
All is well, sorry for the trouble. Feel free to ping if there are future issues. Thanks
