### ISSUE TITLE
Claiming namespace gmpl-fork

### ISSUE THREAD

**Issue by adri326** [EclipseFdn/open-vsx.org#902]
I'd like to publish a fork of [klotztech/vscode-gmpl](https://github.com/klotztech/vscode-gmpl), [adri326/vscode-gmpl](https://github.com/adri326/vscode-gmpl). The original repository was only published to the marketplace and hasn't been maintained in over three years. I'm going with `gmpl-fork` instead of `gmpl` so that the original maintainer can claim `gmpl` should they wish to in the future.

**Comment by kineticsquid** [comment]
@adri326 Thanks for the thoughtful choice of namespace. You're good to go!
