### ISSUE TITLE
Claiming namespace vscodevim

### ISSUE THREAD

**Issue by J-Fields** [EclipseFdn/open-vsx.org#905]
I'm the primary maintainer of VSCodeVim; see https://github.com/orgs/VSCodeVim/people and https://github.com/VSCodeVim/Vim/graphs/contributors. I'm claiming this namespace as suggested by https://github.com/VSCodeVim/Vim/pull/7527.

**Comment by kineticsquid** [comment]
@J-Fields Granted, thanks!

**Comment by J-Fields** [comment]
Thanks, created https://github.com/open-vsx/publish-extensions/issues/561

**Comment by J-Fields** [comment]
@kineticsquid auto-publish has been disabled (https://github.com/open-vsx/publish-extensions/commit/d3162dc3ad369617587fb50fca0cdde7eece59ab)

**Comment by kineticsquid** [comment]
@J-Fields You're good to go, thanks!
