### ISSUE TITLE
remove or unpublish obsolete and not supported version

### ISSUE THREAD

**Issue by zimlu02** [EclipseFdn/open-vsx.org#912]
Hello, as an owner of BroadcomMFD namespace I would like to remove (or at least unpublish) an obsolete and no longer supported [data-set-viewer](https://open-vsx.org/extension/BroadcomMFD/data-set-viewer) extension.
Thank you

**Comment by zimlu02** [comment]
Hello, any update on this ,please?

**Comment by kineticsquid** [comment]
@zimlu02 Do you want all versions removed or just the most recent, `0.2.4`?

**Comment by zimlu02** [comment]
all of them please. Thank you

**Comment by kineticsquid** [comment]
Done!
