### ISSUE TITLE
Claiming namespace WyattL

### ISSUE THREAD

**Issue by WyattSL** [EclipseFdn/open-vsx.org#916]
This is a namespace associated with my Github account (https://github.com/WyattSL) and Visual Studio Marketplace publisher (https://marketplace.visualstudio.com/publishers/WyattL).

It currently has my extension https://open-vsx.org/extension/WyattL/greyscript (from https://marketplace.visualstudio.com/items?itemName=WyattL.greyscript) published on it.

**Comment by kineticsquid** [comment]
Thanks @WyattSL!
