### ISSUE TITLE
Claiming namespace joaopalmeiro

### ISSUE THREAD

**Issue by joaopalmeiro** [EclipseFdn/open-vsx.org#917]
Hi! 😄 

I would like to claim the namespace `joaopalmeiro`. It's the same name as my [GitHub handle](https://github.com/joaopalmeiro) as well as my [publisher profile](https://marketplace.visualstudio.com/publishers/joaopalmeiro) on the Visual Studio Code Marketplace.

Thanks!

**Comment by kineticsquid** [comment]
Thanks @joaopalmeiro, granted!
