### ISSUE TITLE
Claiming namespace RedVanWorkshop

### ISSUE THREAD

**Issue by manifestinteractive** [EclipseFdn/open-vsx.org#918]
I am the author of https://open-vsx.org/extension/RedVanWorkshop/sfcc-cartridge-overrides which is a new extension that was just released on your wonderful platform.  I can verify that I have logged in to https://open-vsx.org more than once, and have connected it to my GitHub account per your instructions.  I am now just following the remaining instruction to submit a ticket to claim ownership of my code for RedVanWorkshop.

You can also see that I am the author on the Extensions GitHub repository: https://github.com/redvanworkshop/sfcc-cartridge-overrides-vscode-extension ( under the GitHub `RedVanWorkshop` org, where I am the GitHub admin )

**Comment by kineticsquid** [comment]
You're good @manifestinteractive !

**Comment by manifestinteractive** [comment]
Woo, thanks !!!
