### ISSUE TITLE
Claiming namespace twilsoft

### ISSUE THREAD

**Issue by JakeHL** [EclipseFdn/open-vsx.org#922]
Hi,

I would like to claim the namespace twilsoft. It is the name of my Ltd company in the UK and I am hoping to publish more open source extensions under the name.

I have recently forked the Visual Studio keymaps from the original VSCode extension and have published it under a new name (with attribution, MIT license) so it can live on outside of the microsoft ecosystem.

https://open-vsx.org/extension/twilsoft/old-friend-vs-keybindings

I don't want to dox myself, so please feel free to ask me directly if I need to provide any evidence of owning the company.

Thanks for taking the time to review!

**Comment by kineticsquid** [comment]
Thanks @JakeHL, great to have you!

**Comment by JakeHL** [comment]
Thanks! Great to be here!
