### ISSUE TITLE
nezaboodka

### ISSUE THREAD

**Issue by dmitry-surkov** [EclipseFdn/open-vsx.org#923]
As an owner of the "nezaboodka" namespace on GitHub (https://github.com/nezaboodka) I would like to create the "nezaboodka" namespace on open-vsx.org and use it to publish the VSCode extension for our Nevod open-source technology (https://nevod.io).

**Comment by kineticsquid** [comment]
Namespace created with you as owner. Thanks for your contributions, @dmitry-surkov
