### ISSUE TITLE
Claiming namespace alexkrechik

### ISSUE THREAD

**Issue by alexkrechik** [EclipseFdn/open-vsx.org#924]
Guys asked me to upload my extension to the OpenVSX, so I would like to create a namespace for this.
https://github.com/alexkrechik/VSCucumberAutoComplete/issues/353

**Comment by kineticsquid** [comment]
Hi @alexkrechik , it looks like your cucumber extension is auto-published. Would you create an issue [here](https://github.com/open-vsx/publish-extensions/issues/new) to disable this. When that is complete, I can grant the namespace ownership.

**Comment by kineticsquid** [comment]
Thanks @alexkrechik!
