### ISSUE TITLE
Claiming namespace pshershov

### ISSUE THREAD

**Issue by PeterShershov** [EclipseFdn/open-vsx.org#928]
Hey,
I have created this namespace under my name (peter shershov) and currently, I am the only member of this namespace.
This namespace includes one extension which is [blueberry-banana](https://github.com/PeterShershov/blueberry-banana-vscode-theme) (theme). 
The extension and the repository were created by me originally and I am their author.

**Comment by kineticsquid** [comment]
@PeterShershov you're good to go!
