### ISSUE TITLE
Claiming namespace reageyao

### ISSUE THREAD

**Issue by liyao001** [EclipseFdn/open-vsx.org#931]
Hi,
This namespace was used in Visual Studio Marketplace for the same extension ([bioSyntax](https://marketplace.visualstudio.com/items?itemName=reageyao.biosyntax)), and I want to use the same namespace here to make everything consistent.

Attached is a screenshot from VS marketplace:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/17058337/160268032-6d4a4724-6e00-49ad-86e0-5ca05eb67665.png">

Thanks!

**Comment by kineticsquid** [comment]
@liyao001 Thanks for your contribution, you're good to go!
