### ISSUE TITLE
Claiming namespace reachsh

### ISSUE THREAD

**Issue by hamirmahal** [EclipseFdn/open-vsx.org#933]
Hello! I work on [reachsh's extension for VSCode](https://marketplace.visualstudio.com/items?itemName=reachsh.reach-ide).

I would like to claim ownership of this namespace to mark [our extension on open-vsx](https://open-vsx.org/extension/reachsh/reach-ide) as verified.

**Comment by kineticsquid** [comment]
Thanks for your contribution @hamirmahal, glad to have you!
