### ISSUE TITLE
Claiming namespace revng

### ISSUE THREAD

**Issue by aleclearmind** [EclipseFdn/open-vsx.org#934]
Hi, I'm the founder of rev.ng Labs S.r.l.
We own the website [rev.ng](https://rev.ng) and the [github.com/revng](https://github.com/revng) namespace.
We'd like the `revng` namespace.

Thanks!

**Comment by kineticsquid** [comment]
You're good to go, thanks!

**Comment by kineticsquid** [comment]
@aleclearmind Hmm, maybe refresh? I'm not seeing the warning here: https://open-vsx.org/extension/revng/llvm-ir.

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/681707/160872871-1399f039-d012-44e3-a9b6-4bd2c9b10b65.png">

**Comment by aleclearmind** [comment]
Ah nice, thanks!
