### ISSUE TITLE
Claiming namespace lf-lang

### ISSUE THREAD

**Issue by lhstrh** [EclipseFdn/open-vsx.org#939]
I'm maintaining the Lingua Franca compiler and it's accompanying VS Code extension that is already published on the Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=lf-lang.vscode-lingua-franca
Our team is are already in possession of the `lf-lang` namespace there, as well as on [GitHub](https://github.com/lf-lang). It would be great if we could claim ownership of this namespace in the Open VSX Registry as well, so we can have our extension listed as verified.
Thank you for considering my request!

**Comment by lhstrh** [comment]
On a related note, I've created a separate account for release automation purposes (see @francabot), which is currently unable to publish in the lf-lang organization (I guess because @lhstrh already claimed it). Could you please give @francabot (Eclipse account `linguafranca`) permission to publish in `lf-lang`? Thank you!

**Comment by kineticsquid** [comment]
@lhstrh You and team are good to go, thanks for your contribution!

**Comment by kineticsquid** [comment]
@lhstrh Sorry, I think I missed that. Just added. Let me know if that's not OK. Thanks

**Comment by lhstrh** [comment]
That worked; thanks for fixing! I noticed that OpenVSX somehow caches the name of the GitHub account it gets linked to. I changed the full name of the account from "Lingua Franca Bot" to "Lingua Franca", but OpenVSX still shows the old name. Is there any way to change this?

**Comment by kineticsquid** [comment]
@spoenemann Thoughts?

**Comment by spoenemann** [comment]
First about the bot account, @lhstrh you can add additional members to the namespace yourself using the settings UI. Bots should generally be added as contributors, not owners. See https://github.com/EclipseFdn/open-vsx.org/wiki/Guidelines-on-Namespaces

I'm not sure about the account name, could be that we copy the full name initially but do not update it. Please create an issue at https://github.com/eclipse/openvsx about this.

**Comment by lhstrh** [comment]
Got it. Made the bot a contributor as suggested. I guess it's not too bad to have the original name show -- the account is a bot, after all -- so I'll just leave things as is. Thanks for your help, @spoenemann and @kineticsquid.
