### ISSUE TITLE
Claiming namespace No Theme

### ISSUE THREAD

**Issue by Beenyaa** [EclipseFdn/open-vsx.org#941]
Hey,

I created this little theme called ![No Theme](https://github.com/Beenyaa/no-theme), it is already available on the ![VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=BenceGadanyi.no-theme&ssr=false#overview), now looking to publish it to Open VSX too. :)

**Comment by Beenyaa** [comment]
@kineticsquid yes, `no-theme`

**Comment by kineticsquid** [comment]
@Beenyaa Done, you're good to go now!
