### ISSUE TITLE
Claiming namespace ikappas

### ISSUE THREAD

**Issue by ikappas** [EclipseFdn/open-vsx.org#942]
Hi all,

I am the owner of these projects:
https://github.com/ikappas/vscode-composer
https://github.com/ikappas/vscode-phpcs

**Comment by kineticsquid** [comment]
@ikappas Can you create and issue or PR [here](https://github.com/open-vsx/publish-extensions/issues/new) to remove this from auto-publishing. When that's complete, I'll grant ownership. Thanks

**Comment by ikappas** [comment]
@kineticsquid complete

**Comment by kineticsquid** [comment]
@ikappas Granted. Thanks for your contribution!
