### ISSUE TITLE
Claiming namespace wintercms

### ISSUE THREAD

**Issue by bennothommo** [EclipseFdn/open-vsx.org#944]
I am one of the original founders and maintainers of [Winter CMS](https://github.com/wintercms/winter), and the primary developer of the [Winter CMS VSCode extension](https://github.com/wintercms/vscode-extension) which we intend to publish to the OpenVSX marketplace. I am authorised by the maintainer team of Winter CMS to claim ownership of this namespace.

**Comment by LukeTowers** [comment]
👍
