### ISSUE TITLE
open-vsx published an unverified version of my extension before I had chance to publish it from my verified account

### ISSUE THREAD

**Issue by DanTup** [EclipseFdn/open-vsx.org#945]
I'm the owner of the Dart/Flutter extensions on open-vsx. I'm actively maintaining the extensions and published v3.38. of the Flutter extension yesterday, which shows as verified and published by me:

https://open-vsx.org/extension/Dart-Code/flutter/3.38.0

Today I published a bugfix 3.38.1 to the VS Code marketplace, but I didn't immediately publish to open-vsx. When I tried (a few hours later), I got this:

```
Extension Dart-Code.flutter version 3.38.1 is already published.
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

I can see that open-vsx published it 18 minutes ago:

https://open-vsx.org/extension/Dart-Code/flutter/3.38.1

Now the extension shows a warning as not being published by me.

Is there a way I can fix this (without increasing the version number, which I'd prefer to keep synced with VS Code + release notes), and in future, avoid open-vsx publishing extensions so quickly? I can understand doing it if I didn't publish for a few days, but a couple of hours seems like quite a small window.

**Comment by kineticsquid** [comment]
@DanTup I can see your code is included in the data for auto-publishing here: https://github.com/open-vsx/publish-extensions/blob/master/extensions.json. Probably the simplest solution would be to remove from auto-publishing all together. You can do that with an issue or PR in that repo. Though, if you didn't set this up, not sure how it got there. 

@spoenemann Thoughts on the extension version number?

**Comment by DanTup** [comment]
> Though, if you didn't set this up, not sure how it got there.

Looks like it was added here:

https://github.com/open-vsx/publish-extensions/commit/e194768209a82438dc37a1d5a95c134156c77494

Possibly was done before I was publishing here myself. I guess I've always published quick enough lately that I didn't realise this was set up. I can send a PR to remove it from there, although it's probably not a terrible thing to be there (in case I did stop publishing) if it could wait a bit longer before assuming I wasn't publishing (given the warning that appears when it publishes).

It's not critical to fix this version up, but it'd be useful to know if there are easy options (either for now, or if it happens again in future).

Thanks!

**Comment by DanTup** [comment]
I've opened https://github.com/open-vsx/publish-extensions/pull/575 to remove these extensions for now. I'll close this as there's probably nothing left to do here - although if there's a simple way for me to replace/verify the version published by the script, let me know. If not, it can remain as-is until the next release.

Thanks!

**Comment by spoenemann** [comment]
@kineticsquid I think it makes sense to remove the version published by @open-vsx so @DanTup can publish it again?

**Comment by kineticsquid** [comment]
@DanTup You currently have Dart 3.38.0 and Flutter 3.38.1 published. Do you want me to remove those so you can re-publish?

**Comment by DanTup** [comment]
@kineticsquid Dart 3.38.0 was published by me, so appears as verified. It's only Flutter 3.38.1 that was published by your script. If you can easily remove that one (Flutter 3.38.1), I'll re-publish so it shows as verified.

Thanks!

**Comment by kineticsquid** [comment]
@DanTup I just removed flutter 3.38.1. Let me know if that works for you.

**Comment by DanTup** [comment]
@kineticsquid Perfect - I've re-published it and it now shows up with my name and as verified.

Thanks for your help!
