### ISSUE TITLE
Claiming namespace tym-inc

### ISSUE THREAD

**Issue by angel-pan** [EclipseFdn/open-vsx.org#951]
I'm a member of tym-inc org on [Github](https://github.com/orgs/tym-inc/people) and I have published our open-source extension on Open VSX. The corresponding Github repo is [here](https://github.com/tym-inc/tym-extension) and the corresponding VS Code Marketplace and Open VSX Marketplace links can be found [here](https://marketplace.visualstudio.com/items?itemName=tym-inc.tym) and [here](https://open-vsx.org/extension/tym-inc/tym) respectively.

**Comment by kineticsquid** [comment]
@angel-pan Thanks for your contributions, you're good to go!
