### ISSUE TITLE
Claiming namespace `matklad`

### ISSUE THREAD

**Issue by lnicola** [EclipseFdn/open-vsx.org#952]
Hello! I'm one of the maintainers of the [matklad.rust-analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) VS Code extension and would like to claim its namespace.

Proof:

- I'm a member of the RA GitHub org:

![image](https://user-images.githubusercontent.com/308347/162560242-b8b1cf21-ed68-4a3a-996c-51e8f8722c0e.png)

 - I've committed to the extension `package.json` in the past: https://github.com/rust-analyzer/rust-analyzer/commits/master/editors/code/package.json
 - I still have commit rights on the repo (well, that was awkward :sweat_smile:): https://github.com/rust-analyzer/rust-analyzer/pull/11935#issuecomment-1093752052=
 - I've wrote on the topic of OpenVSX here: https://github.com/rust-analyzer/rust-analyzer/issues/11080

Admittedly, the extension owner is @matklad, but he would probably [rather not](https://github.com/rust-analyzer/rust-analyzer/issues/4936#issuecomment-655466582=) get involved at this moment, but is [not completely](https://github.com/rust-analyzer/rust-analyzer/issues/7284#issuecomment-883427746=) against it. At that time, OpenVSX users could still install our extension, but the auto-publishing broke in December since we started using the platform-specific VSIX functionality, so publishing it ourselves is more important now.

So my request is to give me ownership to the namespace so I can set up auto-publishing. If matklad makes an account, we can transfer the ownership to him, or I can add him as a co-owner (which IIRC should be possible).

We could also not claim the namespace, but that seems to make it pretty easy to publish malware, so I'd rather avoid that.

**Comment by matklad** [comment]
👍 from me!

**Comment by kineticsquid** [comment]
@matklad Thanks for detail on your request. Granted and thanks for your contribution!

**Comment by kineticsquid** [comment]
@spoenemann This extension is set for auto-publishing. Is that going to create a conflict?

**Comment by kineticsquid** [comment]
@lnicola Thanks, yes I see that now. Thanks!
