### ISSUE TITLE
Claiming namespace qufiwefefwoyn

### ISSUE THREAD

**Issue by barklan** [EclipseFdn/open-vsx.org#953]
Would like to claim the same namespace as in VS Marketplace to verify Inline SQL extension. ([VS Marketplace link](https://marketplace.visualstudio.com/items?itemName=qufiwefefwoyn.inline-sql-syntax), [OVSX link](https://open-vsx.org/extension/qufiwefefwoyn/inline-sql-syntax)). Thanks.

**Comment by kineticsquid** [comment]
@barklan Granted. Our marketing folk are going to need a pronunciation guide :).
