### ISSUE TITLE
Claiming namespace dsteenman

### ISSUE THREAD

**Issue by dannysteenman** [EclipseFdn/open-vsx.org#958]
https://open-vsx.org/extension/dsteenman/cloudformation-yaml-snippets
https://github.com/dannysteenman/vscode-cloudformation-snippets/issues/14
https://github.com/dannysteenman/vscode-cloudformation-snippets/graphs/contributors

edit: is it possible to change the namespace from dsteenman to dannysteenman? The reason why I ask is that I'm also planning to move my extensions from the vs code marketplace from dsteenman to dannysteenman

**Comment by kineticsquid** [comment]
@dannysteenman Granted your namespace request for `dsteenman`. Currently, we have an open request for the ability to change a namespace: https://github.com/eclipse/openvsx/issues/427. @spoenemann FYI.

**Comment by dannysteenman** [comment]
Hi @kineticsquid I've been wanting to push some updates for my extensions on open-vsx. I noticed the feature with the ability to change namespace name was merged sometime ago: https://github.com/eclipse/openvsx/pull/469

However I don't see this in the browser when I visit my namespace: https://open-vsx.org/user-settings/namespaces

Is this something only admins can do? If that's the case can you help me to update my namespace name?
