### ISSUE TITLE
Claiming namespace DontShaveTheYak

### ISSUE THREAD

**Issue by shadycuz** [EclipseFdn/open-vsx.org#960]
DontShaveTheYak is a Github org for my side projects. I am the sole member of it https://github.com/DontShaveTheYak

**Comment by kineticsquid** [comment]
@shadycuz Granted (and nominee for most off beat namespace)!

**Comment by shadycuz** [comment]
@kineticsquid It's a dirty job, but someone has to do it. https://seths.blog/2005/03/dont_shave_that/ 😉

**Comment by kineticsquid** [comment]
@shadycuz Thanks, I didn't know. I am enlightened!
