### ISSUE TITLE
Claiming namespace butchland

### ISSUE THREAD

**Issue by butchland** [EclipseFdn/open-vsx.org#965]
I'm maintaining the VS Code extension that is already published on the Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=butchland.vscode-dbt-bigquery-power-user

I am already in possession of the `butchland` namespace there, as well as on [GitHub](https://github.com/butchland). It would be great if I could claim ownership of this namespace in the Open VSX Registry as well, so I can have my extension listed as verified.

Thank you for considering my request!

**Comment by kineticsquid** [comment]
Thanks @butchland, glad to have your contribution!
