### ISSUE TITLE
Outdated 'Debugger for Firefox' extension v2.9.1 (shows current - v2.9.6 - README.md)

### ISSUE THREAD

**Issue by sxc731** [EclipseFdn/open-vsx.org#966]
I'm running VSCodium and spent a fair bit of time scratching my head as to why the [Debugger for Firefox](https://open-vsx.org/extension/firefox-devtools/vscode-firefox-debug) extension wasn't working (I'm a noob at VSCodium and the whole ecosystem).

Turns out I was running **v2.9.1** of the extension, from the OpenVSX repo, which is woefully out of date; doesn't work at all with current versions of Firefox.  What made it quite confusing is that the README - ostensibly sourced from the extension's main Github page, shows **v2.9.6** front and center, misleading me into believing that I was running an up-to-date extension.  The same thing can be observed on the extension's [OpenVSX repo page](https://open-vsx.org/extension/firefox-devtools/vscode-firefox-debug).

So I guess this issue really addresses two aspects:
1. How do we get the Open VSX version of the Firefox Debugger extension to update?  Is the auto-update procedure broken because the user account is not a "verified publisher"?
2. Is there a way to prevent this kind of confusion for OpenVSX/VSCodium users (misleading version label shown on the README page).

Apologies in advance if I'm not raising this issue in the appropriate project.  If so, kindly guide me to the right place.

**Comment by kineticsquid** [comment]
@sxc731 This is really an issue for the authors of the extension. The publisher @hbenl is active at https://github.com/firefox-devtools/vscode-firefox-debug. Suggest you open an issue there.
