### ISSUE TITLE
Claiming namespace jaspergeer

### ISSUE THREAD

**Issue by jaspergeer** [EclipseFdn/open-vsx.org#968]
I wrote an extension called [DocMachine](https://github.com/jaspergeer/DocMachine) which is published to the [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=JasperGeer.docmachine) and recently published it to the Open VSX Registry. I have this namespace here on GitHub and it would be great if I could claim it so my extension can be listed as verified.

Thank You!

**Comment by kineticsquid** [comment]
@jaspergeer Thanks, granted!
