### ISSUE TITLE
biao1010

### ISSUE THREAD

**Issue by biao-1010** [EclipseFdn/open-vsx.org#969]
I logged in to https://open-vsx.org/ using Github bio-1010, created Eclipse and created the namespace biao1010

**Comment by kineticsquid** [comment]
@biao-1010 Is this related to https://github.com/EclipseFdn/open-vsx.org/issues/956?

**Comment by biao-1010** [comment]
yes

**Comment by kineticsquid** [comment]
OK, granted ownership of namespace `biao1010`.
