### ISSUE TITLE
Claiming namespace [SASjs]

### ISSUE THREAD

**Issue by allanbowe** [EclipseFdn/open-vsx.org#971]
I am the founder and owner of this project, as you can see from my commit history.  Our github org is here:  https://github.com/sasjs

Our vs code extension is here:  https://marketplace.visualstudio.com/items?itemName=SASjs.sasjs-for-vscode

Our main site:   https://sasjs.io

**Comment by kineticsquid** [comment]
@allanbowe It looks like you are already owner of this namespace.
