### ISSUE TITLE
Claiming namespace `ultram4rine`

### ISSUE THREAD

**Issue by ultram4rine** [EclipseFdn/open-vsx.org#972]
Hi, I'm recently published my extensions ([[1]](https://open-vsx.org/extension/ultram4rine/vscode-choosealicense), [[2]](https://open-vsx.org/extension/ultram4rine/sqltools-clickhouse-driver)) to Open VSX, can you verify me as publisher of the mentioned namespace? They are published to Visual Studio Marketplace too ([[1]](https://marketplace.visualstudio.com/items?itemName=ultram4rine.vscode-choosealicense), [[2]](https://marketplace.visualstudio.com/items?itemName=ultram4rine.sqltools-clickhouse-driver)).

Thanks!

**Comment by kineticsquid** [comment]
Thanks @ultram4rine, granted!

**Comment by ultram4rine** [comment]
@kineticsquid thanks :)
