### ISSUE TITLE
Claiming namespace ibijon.duckyscript

### ISSUE THREAD

**Issue by Its-ibijon** [EclipseFdn/open-vsx.org#976]
Hey I made a duckyscript extension for VS Codium

**Comment by kineticsquid** [comment]
@ibrahimpervaze Are you looking to claim namespace `ibijon.duckyscript` or `duckyscript`? I ask because it looks like you're currently a contributor to namespace `duckyscript`.

**Comment by kineticsquid** [comment]
See #981 and #975.
