### ISSUE TITLE
Claiming namespace pickoba

### ISSUE THREAD

**Issue by pickoba** [EclipseFdn/open-vsx.org#977]
Hi, I'm maintaining the following extension published on Visual Studio Marketplace ([repo](https://github.com/pickoba/satysfi-workshop)):
https://marketplace.visualstudio.com/items?itemName=pickoba.satysfi-workshop

I also own this namespace on [GitHub](https://github.com/pickoba). I would like to claim the ownership of this namespace in the Open VSX Registry as well to mark my extension verified.

Regards

**Comment by kineticsquid** [comment]
Thanks @pickoba, glad to have you!
