### ISSUE TITLE
hey can you delete all of the extensions with the namespace ibijon 

### ISSUE THREAD

**Issue by Its-ibijon** [EclipseFdn/open-vsx.org#981]
i accidentally uploaded an extension multiple times and would like to just restart is there anyway for me to delete extensions i've uploaded , also what is the command to update  an extension 

thanks

**Comment by kineticsquid** [comment]
@spoenemann Can you take a look? I deleted one of the extensions leaving one. But I can't seem to delete the second because it doesn't show up when I search for it under 'Extensions' on the Admin panel.

**Comment by spoenemann** [comment]
@ibrahimpervaze @kineticsquid do you mean these two?
https://open-vsx.org/extension/ibijon/dd
https://open-vsx.org/extension/ibijon4/duckyscript

**Comment by kineticsquid** [comment]
@Its-ibijon Can you confirm?

**Comment by Its-ibijon** [comment]
hey, sorry for the delayed reply but that's perfect

**Comment by kineticsquid** [comment]
Done
