### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by rbbl-dev** [EclipseFdn/open-vsx.org#982]
Hey There,

https://open-vsx.org/ is currently down.
I didn't see any notice or status so i wanted to ask whats going on.

**Comment by mbarbero** [comment]
Thanks for the heads up. Follow up will be made via status page https://www.eclipsestatus.io/incidents/1f0yhbygjwhq.

**Comment by mbarbero** [comment]
(open-vsx.org is back online)
