### ISSUE TITLE
Claiming namespace kurtisstakley

### ISSUE THREAD

**Issue by kazh1235** [EclipseFdn/open-vsx.org#983]
I'm the btian I'm the no sleep no stop the 39 cups of coffee I'm the only one

**Comment by kineticsquid** [comment]
@kazh1235 Confirming the namespace you're interested in is `kurtisstakley`. I don't see anything yet published to it.

**Comment by kineticsquid** [comment]
@kazh1235 Following up...

**Comment by kineticsquid** [comment]
Closing for lack of response
