### ISSUE TITLE
Unpublish request for `justusadam.language-haskell` v3.6.0

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#984]
Because the latest version, [v3.6.0](https://open-vsx.org/extension/justusadam/language-haskell/3.6.0), is broken [[1](https://github.com/JustusAdam/language-haskell/issues/171#issuecomment-1110426104)]. A fix to the build process so that v3.6.0 will be published correctly next time is in https://github.com/open-vsx/publish-extensions/pull/583.

**Comment by kineticsquid** [comment]
@filiptronicek Confirming you want me to remove `language-haskell` 3.6.0?

**Comment by filiptronicek** [comment]
@kineticsquid exactly.

**Comment by kineticsquid** [comment]
Done

**Comment by filiptronicek** [comment]
@kineticsquid could you please unpublish this exact version once again 🙏? Looks like there was a CI error at publish-extensions and should not happen again after https://github.com/open-vsx/publish-extensions/pull/589.

**Comment by kineticsquid** [comment]
@filiptronicek No worries, done!
