### ISSUE TITLE
`ms-vscode.mock-debug` and `xdebug.php-debug` fail to publish due to an `Internal Server Error`

### ISSUE THREAD

**Issue by filiptronicek** [EclipseFdn/open-vsx.org#990]
When https://github.com/open-vsx/publish-extensions tries to publish them, an Internal Server Error gets returned. This has been happening for a couple of days in a row.

User-facing logs: 
- https://github.com/open-vsx/publish-extensions/runs/6244319645?check_suite_focus=true#step:8:3148
- https://github.com/open-vsx/publish-extensions/runs/6244319645?check_suite_focus=true#step:8:2442

**Comment by kineticsquid** [comment]
@spoenemann @mbarbero

**Comment by kineticsquid** [comment]
@filiptronicek Checking in, is this still an issue?

**Comment by pixelkind** [comment]
I have the same issue. When I try to publish an extension I get the error "Internal Server Error".

```
webpack 5.74.0 compiled successfully in 967 ms
 DONE  Packaged: /var/folders/_m/wsh575rn09l3_tzrx6jjwvtc0000gp/T/tmp-70545-urZAIx9dlWTM-.vsix (10 files, 21.19KB)

❌  Internal Server Error
See the documentation for more information:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
```

**Comment by kineticsquid** [comment]
@pixelkind We need take a look at the logs. Can you try again and post the time you saw the error?

**Comment by kineticsquid** [comment]
@filiptronicek Thanks. @amvanbaren @fredg02 @mbarbero Can you take a look at the logs?

**Comment by kineticsquid** [comment]
@filiptronicek Working for you?

**Comment by kineticsquid** [comment]
@filiptronicek ^^^^

**Comment by filiptronicek** [comment]
Thanks for the ping, @kineticsquid 🧡! Seems the issue is no longer present for the extensions I could find. There are some new issues with `ms-vscode.mock-debug`, which I'll report in a new issue 🙂.
